### ISSUE TITLE
[Platform] Security test: Check for an externally exposed K8s dashboard

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1000]
## Workload test: exposed dashboard

**Describe the solution you'd like**
Create a test using kubescape for the control name test `Exposed dashboard`

Ref: #963 

**Description**
If Kubernetes dashboard is exposed externally in Dashboard versions before 2.01, it will allow unauthenticated remote management of the cluster.

**Remediation**
Update dashboard version to v2.0.1 or above.

**Comment by HashNuke** [comment]
@agentpoyo No worries. I'll rename the test and move it to the right group.

**Comment by agentpoyo** [comment]
Having issues pulling older v2.0.0 image to test:

```
Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Normal   Scheduled  40s   default-scheduler  Successfully assigned kubernetes-dashboard/kubernetes-dashboard-57c9bfc8c8-4s945 to node-control-plane
  Normal   Pulling    39s   kubelet            Pulling image "kubernetesui/dashboard:v2.0.0"
  Warning  Failed     9s    kubelet            Failed to pull image "kubernetesui/dashboard:v2.0.0": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/kubernetesui/dashboard:v2.0.0": failed to resolve reference "docker.io/kubernetesui/dashboard:v2.0.0": failed to do request: Head "https://registry-1.docker.io/v2/kubernetesui/dashboard/manifests/v2.0.0": dial tcp 52.55.168.20:443: i/o timeout
  Warning  Failed     9s    kubelet            Error: ErrImagePull
  Normal   BackOff    9s    kubelet            Back-off pulling image "kubernetesui/dashboard:v2.0.0"
  Warning  Failed     9s    kubelet            Error: ImagePullBackOff
```

Seems to be getting AUTHORIZED errors pulling the manifests/v2.0.0.

**Comment by HashNuke** [comment]
Just in-case you need it for reference, here is my dashboard install
command for v2.0.

kubectl apply -f
https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml

**Comment by agentpoyo** [comment]
Yeah, that's the same YAML I was attempting. I got v2.0.1 installed and
running (could hit the dashboard in a browser) but realized it needed to be
older than 2.0.1. After I kubectl delete to reinstall, it's getting Image
Pull Errors. I've given up tonight, will look tomorrow. I could manually do
a docker pull on the images though..

**Comment by agentpoyo** [comment]
Seems like ARMO kubescape is passing the exposed dashboard when it should fail, based on their tests claiming they raise a warning or flag if v2.0.0 is found.

I've opened an issue to see if there's anything else that should be done to test the exposed dashboard:
https://github.com/armosec/kubescape/issues/236

This is reviewer approved at this point, since failure depends on their upstream tool to report accurate pass/fails.

**Comment by agentpoyo** [comment]
Updating the config from the default ClusterIP type to NodePort got their scans to detect the version and it failed as it should:
![exposed_dashboard_error](https://user-images.githubusercontent.com/14348948/142454280-9274d52c-a137-4583-a24e-5436829db21e.png)
