### ISSUE TITLE
[BUG] GitHub Runners not picking up jobs

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1032]
## Describe the bug
GitHub runners are not picking up jobs. Only the chaos test runners seem to be working fine.

### Steps to resolve

* [x] Update `conformance/github-runner` image to use the latest base image from `myoung34/github-runner/` (2.283.3)
* [x] Updated the `create_runners.sh` script to use the new gitHub-runner image.
* [ ] Remove `RUNNER_GROUP` env var from `create_runners.sh` script
* [x] Update `GH_USER` and `GH_TOKEN` secrets on the cnf-testsuite repo (token had expired). This was causing failures for the `release` tag tests in the recent builds on branches.
* [ ] Update git version on the GitHub-runner image from 2.17 to latest.

**Comment by agentpoyo** [comment]
This was addressed and fixed already.
