### ISSUE TITLE
[BUG] kubescape download framework retry

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#1034]
**Describe the bug**
kubescape intermittently fails:

error: failed to download file, status code: 403 Forbidden
Error: failed to download file, status code: 403 Forbidden
Usage:
  kubescape download framework <framework-name> [flags]

Flags:
  -h, --help                                        help for download
  -o, --output ~/.kubescape/<framework name>.json   Output file. If specified, will store save to ~/.kubescape/<framework name>.json

**To Reproduce**

Retry GitHub actions multiple times
**Expected behavior**
Kubescape install downloads should have a retry with backoff built in

**Comment by lixuna** [comment]
good catch, @wavell and @denverwilliams 

what was the level of effort in points to resolve this bug (0,1,2,3,5,8,13,21)?

**Comment by HashNuke** [comment]
One more fix that was required: Changed the kubescape framework download step to use the github url directly.

**Comment by agentpoyo** [comment]
Acceptable Criteria: 

- [ ] When I view the kubescape_setup.cr, I see that the uninstall_kubescape is removed from uninstalling after every single test, which was causing the rate limits on each kubescape test to install and then uninstall.

The bug is fixed by installing kubescape once and not uninstalling repeatedly.

**Comment by agentpoyo** [comment]
![uninstall_kubescape](https://user-images.githubusercontent.com/14348948/140200048-68415df9-2d14-477e-823b-77fb8d2d68fe.png)

**Comment by lixuna** [comment]
what was the level of effort in points to resolve this bug (0,1,2,3,5,8,13,21)?

@agentpoyo @HashNuke @denverwilliams @wavell
