### ISSUE TITLE
[Workload] Extend checks for non-root and privilege escalation flags for pods + containers using kubescape

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1038]
### Workload: Security test: Non-root containers + privilege esclation flags

**Short description of platform test:**

- Potential attackers may gain access to a container and leverage its privileges to conduct an attack. Hence it is not recommended to deploy containers with root privileges unless it is absolutely necessary.

**Remediation Details**

- If your application does not need root privileges, make sure to define the runAsUser and runAsGroup under the PodSecurityContext to use user ID 1000 or higher, do not turn on allowPrivlegeEscalation bit and runAsNonRoot is true.

**Test Category**

- Security (e.g. State, Security, etc from [README](https://github.com/cncf/cnf-testsuite/blob/main/README.md#cnf-testsuite))

Reference:
- https://hub.armo.cloud/docs/c-0013
- kubescape epic #963 

---

### Implementation Tasks: TBD

**Environment set up tasks:**

- [ ]

**Upstream tool set up tasks: (test suite + upstream tools)**

- [ ] kubescape

**CNF setup Tasks**

- [ ] `./cnf-testsuite non-root-containers`

**Sample CNF tasks:**

- [ ]

**Code implementation tasks:**

- [ ]

**Documentation tasks:**

- [ ] Update [Test Categories md](https://github.com/cncf/cnf-testsuite/blob/main/TEST-CATEGORIES.md) if needed
- [ ] Update [Pseudo Code md](https://github.com/cncf/cnf-testsuite/blob/main/PSEUDO-CODE.md) if needed
- [ ] Update [USAGE md](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) if needed
  - [ ] Add description details in USAGE md
  - [ ] Add remediation details or URL links in USAGE md
- [ ] Update [installation instructions](https://github.com/cncf/cnf-testsuite/install.md) if needed

### QA tasks

Dev Review:

- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes,
  - [ ] move to `Needs Peer Review` column
  - [ ] create Pull Request and follow check list
  - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:

- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes,
  - [ ] move to `Reviewer Approved` column
  - [ ] Approve pull request
- [ ] if no,
  - [ ] document what did not go as expected, including error messages and screenshots (if possible)
  - [ ] Add comment to pull request
  - [ ] request changes to pull request

**Comment by taylor** [comment]
Future, consider deprecating existing non-root user test since this covers it

**Comment by agentpoyo** [comment]
###  Acceptance Criteria 
---
### Documentation is updated:
- [ ] USAGE.md documentation updated
   - [ ] how to run
   - [ ] Description, remediation and details 
       - [ ] what the best practice is
       - [ ] why are we testing this
- [ ] CATEGORIES updated

###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-testsuite/blob/main/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]   As a peer reviewer, Pull down latest version of CNF conformance test code from `main` branch
- [ ]  Run `shards install`

### Update Prerequisite checker
- [ ] NA

### Added to overall points:
- [ ]  I see the test in the embedded points.yml as valid test score

### When I run `` I should see test PASS or FAILED results:
- [ ] Run `./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample_coredns/cnf-testsuite.yml`
- [ ] Run `./cnf-testsuite `
- [ ] I can see PASSED/FAILED result output.

### Screenshots of output:
- [ ] I can see a screenshots of output

**Comment by agentpoyo** [comment]
![non_root_kubescape](https://user-images.githubusercontent.com/14348948/140245518-867dd119-b398-48e2-93ae-22361684848b.png)
