### ISSUE TITLE
[BUG] kubescape is installed before every test in the spec group causing 403s when downloading kubescape framework

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1048]
**Describe the bug**

kubescape is installed before every spec test in the specs. Due to this, some of the situations when `kubescape download framework` is run results in 403s - possibly due to rate-limits by the server that the file is being downloaded from.

* [This is an example workflow run](https://github.com/cncf/cnf-testsuite/actions/runs/1385827343) with the failure (screenshot below).
* To get to the failures directly, find instances of `403` and `error: open ./tools/kubescape/nsa.json` on the workflow output page linked above.
* [This line](https://github.com/cncf/cnf-testsuite/blob/7ef4850716f6d54c1d48513db6d5987c1e32be61/spec/utils/kubescape_spec.cr#L5) in kubescape_spec.cr should be `before_all`.

**To Reproduce**

Run multiple builds/github-actions to notice the failures.

**Expected behavior**

There should not be errors downloading the framework if the file has already been downloaded when the spec group started running..

**Screenshots**

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/84005/138910310-337691b5-afe0-4e5b-9ec0-f4b53e32fd69.png">

**Comment by lixuna** [comment]
good catch @HashNuke 

what was the level of effort in points to resolve this issue (0,1,2,3,5,8,13,21)?

**Comment by agentpoyo** [comment]
See https://github.com/cncf/cnf-testsuite/issues/1034 for acceptance criteria test results.
