### ISSUE TITLE
[BUG] No usage documentation for insecure_capabilities test

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testsuite#1052]
**Describe the bug**
The security test `insecure_capabilities` is not listed in the [USAGE](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#security-tests) document.

**To Reproduce**

1. Go to 'https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#security-tests'
2. Scroll through the list of test
3. The test is not found

**Expected behavior**
The test `insecure_capabilities` is found in the USAGE docs under the security category. The drop-down details explain why the test is important, what it does, and the remediation for how to fix it. Links to additional documentation if relevant.

**Screenshots**
![image](https://user-images.githubusercontent.com/26697/138933872-9ae185e2-9350-46ec-8cb4-51ab0cbcf64a.png)

**Comment by agentpoyo** [comment]
#### :heavy_check_mark: To check for insecure capabilities
<details> <summary>Details for Insecure Capabilities</summary>

<p><b>Insecure Capabilities:</b> Giving insecure and unnecessary capabilities for a container can increase the impact of a container compromise.

This test checks against a [blacklist of insecure capabilities](https://github.com/FairwindsOps/polaris/blob/master/checks/insecureCapabilities.yaml).

<b>Remediation:</b> Remove all insecure capabilities which aren’t necessary for the container.

See more at [ARMO-C0046](https://bit.ly/C0046_Insecure_Capabilities)

</p>
</details>

```
./cnf-testsuite insecure_capabilities
```

**Comment by agentpoyo** [comment]
Acceptance Criteria

- [ ] When I browse to USAGE.md, I see the details dropdown that provides a description and remediation steps for `insecure_capabilities`
