### ISSUE TITLE
[BUG] No usage documentation for dangerous_capabilities test

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testsuite#1053]
**Describe the bug**
The security test `dangerous_capabilities` is not listed in the [USAGE](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#security-tests) document.

**To Reproduce**

1. Go to 'https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#security-tests'
2. Scroll through the list of test
3. The test is not found

**Expected behavior**
The test `dangerous_capabilities` is found in the USAGE docs under the security category. The drop-down details explain why the test is important, what it does, and the remediation for how to fix it. Links to additional documentation if relevant.

**Screenshots**
![image](https://user-images.githubusercontent.com/26697/138933872-9ae185e2-9350-46ec-8cb4-51ab0cbcf64a.png)

**Comment by agentpoyo** [comment]
#### :heavy_check_mark: To check for dangerous capabilities
<details> <summary>Details for Dangerous Capabilities</summary>

<p><b>Dangerous Capabilities:</b> Giving dangerous and unnecessary capabilities for a container can increase the impact of a container compromise.

This test checks against a [blacklist of dangerous capabilities](https://github.com/FairwindsOps/polaris/blob/master/checks/dangerousCapabilities.yaml).

<b>Remediation:</b> Check and remove all unnecessary capabilities from the POD security context of the containers and use the exception mechanism to remove warnings where these capabilities are necessary.

See more at [ARMO-C0028](https://bit.ly/C0028_Dangerous_Capabilities)

</p>
</details>

```
./cnf-testsuite dangerous_capabilities
```

**Comment by agentpoyo** [comment]
Acceptance Criteria

- [ ] When I browse to USAGE.md, I see the details dropdown that provides a description and remediation steps for `dangerous_capabilities`
