### ISSUE TITLE
[BUG] Delete all unnecessary links to NSA K8s hardening PDF from usage.md

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testsuite#1054]
**Describe the bug**
There are tests that link to the NSA K8s hardening PDF that have no mention in the PDF. For example, the exposed dashboard test. 

It's confusing to link to a 59-page PDF w/o any context. Especially when the test does not seem to be directly covered in the PDF at all.

**To Reproduce**

1. Go to 'https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md'
2. Click on 'Platform Tests'
3. Scroll down to 'dashboard is exposed'
4. Click link to [PDF](https://media.defense.gov/2021/Aug/03/2002820425/-1/-1/1/CTR_KUBERNETES%20HARDENING%20GUIDANCE.PDF)
5. Search / read 59 pages of PDF and dashboard is not mentioned

**Expected behavior**
NSA PDF will only be linked from test docs that are directly relevant to the content in the PDF.

**Comment by agentpoyo** [comment]
All links to NSA PDF have been removed. The only mention is in the exposed dashboard that was worded as a guide and not direct link to specific page in document.

**Comment by agentpoyo** [comment]
AC not needed, all links were removed when updated tests details and remediation steps were updated for each.
