### ISSUE TITLE
[BUG] No desc/remediation details for `service_account_mapping` test in USAGE md

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1062]
**Describe the bug**
The security test `service_account_mapping` is not listed in the [USAGE](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-there-are-service-accounts-that-are-automatically-mapped) document.

**To Reproduce**

1. Go to 'https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-there-are-service-accounts-that-are-automatically-mapped'
2. No dropdown description is found
3. No links are found to remediation steps

**Expected behavior**
The test `service_account_mapping` is found in the USAGE docs under the security category. The drop-down details explain why the test is important, what it does, and the remediation for how to fix it. Links to additional documentation if relevant.

**Details**
Potential attacker may gain access to a POD and steal its service account token. Therefore, it is recommended to disable automatic mapping of the service account tokens in service account configuration and enable it only for PODs that need to use them. https://hub.armo.cloud/docs/c-0034

**Remediation**
Only map token to PODs that are really using them. We suggest disabling the automatic mounting of service account tokens to PODs at the service account level, by specifying the securityContext.readOnlyRootFilesystem field to true, and explicitly enabling the map for the PODs which are using it at the POD spec level.

**Comment by anonymousr007** [comment]
Hi @agentpoyo, I am Rishabh, computer engineering student from India and also an open source contributor. Can you please little bit more elaborate about this issue ? I want to make a pull request for this

**Comment by agentpoyo** [comment]
> Hi @agentpoyo, I am Rishabh, computer engineering student from India and also an open source contributor. Can you please little bit more elaborate about this issue ? I want to make a pull request for this

Hello @anonymousr007 ,

I actually just added this issue to https://github.com/cncf/cnf-testsuite/pull/1105 already but forgot to tag it. But if you see any others like this, you can certainly use PR #1105 I have open already as a guide on these documentation update issues.

Cheers,

agentpoyo

**Comment by agentpoyo** [comment]
Acceptance Criteria

- [ ] When I browse to USAGE.md, I see the details dropdown that provides a description and remediation steps for `service_account_mapping`
