### ISSUE TITLE
[Feature] Airgap mode for CNI_compatibility test

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#1064]
**Is your feature request related to a problem? Please describe.**
Airgap mode for CNI_compatibility test

**Describe the solution you'd like**
Airgap mode for CNI_compatibility test

**Comment by agentpoyo** [comment]
###  Acceptance Criteria 
---
### Documentation is updated:
- [ ] USAGE.md documentation updated
   - [ ] how to run
   - [ ] Description, remediation and details 
       - [ ] what the best practice is
       - [ ] why are we testing this
- [ ] CATEGORIES updated

###  Common steps
- [ ] Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-testsuite/blob/main/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]  As a peer reviewer, Pull down latest version of CNF conformance test code from `main` branch
- [ ]  Run `shards install`

### Update Prerequisite checker
- [ ] NA

### Added to overall points:
- [ ]  I see the test in the embedded points.yml as valid test score

### When I run `cni_compatible` in offline mode, I should see cni_compatible PASS:
- [ ] Create a new airgapped tarball following the AIRGAP instructions
- [ ] Run `./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample_coredns/cnf-testsuite.yml input-file=/tmp/airgapped.tar.gz`
- [ ] Run `./cnf-testsuite prometheus_traffic offline=true`
- [ ] I can see PASS result output when prometheus traffic is found in offline mode.

**Comment by agentpoyo** [comment]
![prometheus_traffic_offline](https://user-images.githubusercontent.com/14348948/142688051-595705f0-39e1-4c84-860e-a9c814ae691d.png)

**Comment by agentpoyo** [comment]
Ran into some environment issues getting this to pass; will investigate further before approving the peer review.

**Comment by agentpoyo** [comment]
![1064_passed](https://user-images.githubusercontent.com/14348948/144138339-1752201c-ede9-4af8-bf0e-fa6bb53688e0.png)
