### ISSUE TITLE
[Feature] Use GITHUB_TOKEN secret provided by GitHub Actions for ReleaseManager and other workflows

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1077]
### Description

The GitHub Actions workflow in the repo depends on two secrets `GH_USER` and `GH_TOKEN`.
This token expires and requires a team member to replace the token at regular intervals.

### Possible resolution

Use the `GITHUB_TOKEN` secret that GitHub Actions provides by default. This will not require team members to update the `GH_TOKEN` and `GH_USER` secrets at regular intervals.

**Comment by HashNuke** [comment]
Pushed the branch `github-actions-token` with some changes required for this. Will update here with a PR once the build passes.

**Comment by agentpoyo** [comment]
No acceptance criteria available. Github action workflows are running to verify the update.

**Comment by lixuna** [comment]
Thank you for working on this, @HashNuke and @agentpoyo 

What is your estimate in points (0,1,2,3,5,8,13,21)?
