### ISSUE TITLE
[Feature] cleanup should remove all samples in the cnfs as well as all tools

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#1079]
**Is your feature request related to a problem? Please describe.**
cleanup should remove all samples in the cnfs as well as all tools

**Describe the solution you'd like**
cleanup should loop through the cnfs directory and remove all samples in the cnfs as well as all tools

**Comment by agentpoyo** [comment]
Todo: Write AC steps for Peer Review

**Comment by agentpoyo** [comment]
###  Acceptance Criteria 
---
###  Common steps
- [x] Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-testsuite/blob/main/KIND-INSTALL.md) will work as well
- [x]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [x]  As a peer reviewer, check that PR passes in GitHub Actions
     - [x] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [x]  As a peer reviewer, Pull down latest version of CNF conformance test code from `main` branch
- [x]  Run `shards install`

### Update Prerequisite checker
- [ ] NA

### Added to overall points:
- [ ]  I see the test in the embedded points.yml as valid test score

### When I run `samples_cleanup`, I should see all the samples in cnfs/ directory removed and deleted:
- [x] Run `./cnf-testsuite samples_cleanup` after any oher normal CNF setup
- [x] I can see any and all CNFs cleaned up from k8s pods cluster and none in cnfs/ directory.

**Comment by agentpoyo** [comment]
![1079_results](https://user-images.githubusercontent.com/14348948/152706757-46f44812-f4f8-455a-bd6b-3333095e05f1.png)
