### ISSUE TITLE
[Workload] Observability test: OpenMetrics compliance

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#1080]
## Title: [Workload] Open Metrics compliance

**Is your workload test idea related to a problem? Please describe.**
- CNF should send metrics that are open metrics compliant

**Describe the solution you'd like**
- Send a query to the open metrics endpoint of the cnf and check if it is open metrics compatible

**Test Category Name**
- Observability 

**Type of test (static or runtime)**
- runtime

---

### Documentation tasks:
- [ ] Update [installation instructions](https://github.com/cncf/cnf-testsuite/blob/main/install.md) if needed
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-testsuite/blob/main/TEST-CATEGORIES.md) if needed
- [ ] Update [USAGE md](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) if needed
  - [ ] How to run
  - [ ] Description and details
    - [ ] What the best practice is
    - [ ] Why are we testing this
  - [ ] Remediation steps if test does not pass

### QA tasks

Dev Review:

- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes,
  - [ ] move to `Needs Peer Review` column
  - [ ] create Pull Request and follow check list
  - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:

- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes,
  - [ ] move to `Reviewer Approved` column
  - [ ] Approve pull request
- [ ] if no,
  - [ ] document what did not go as expected, including error messages and screenshots (if possible)
  - [ ] Add comment to pull request
  - [ ] request changes to pull request

**Comment by agentpoyo** [comment]
###  Acceptance Criteria 
---
###  Common steps
- [ ] Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-testsuite/blob/main/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]  As a peer reviewer, Pull down latest version of CNF conformance test code from `main` branch
- [ ]  Run `shards install`

### Update Prerequisite checker
- [ ] NA

### Added to overall points:
- [ ]  I see the test in the embedded points.yml as valid test score

### When I run `open_metrics`, I should see open_metrics PASS:
- [ ] Run `./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample_coredns/cnf-testsuite.yml`
- [ ] Run `./cnf-testsuite open_metrics`
- [ ] I can see PASS result output for open_metrics.

### When I run `workload, I should see open_metrics PASS:
- [ ] Run `./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample_coredns/cnf-testsuite.yml`
- [ ] Run `./cnf-testsuite workload`
- [ ] I can see that open_metrics is run during workload tests.

**Comment by agentpoyo** [comment]
![open_metrics_fail](https://user-images.githubusercontent.com/14348948/144167586-badd4170-5dde-4d0f-a55e-43b4278e0d4a.png)


![open_metrics_pass](https://user-images.githubusercontent.com/14348948/144167572-dd2071ab-9e79-4586-b2ca-18463980886b.png)

**Comment by agentpoyo** [comment]
![open_metrics_workload](https://user-images.githubusercontent.com/14348948/144168526-23ec217c-893b-4489-aab8-d1e220a54b07.png)

**Comment by lixuna** [comment]
Thanks for adding this Observability test, @wavell @denverwilliams @agentpoyo @HashNuke 

What was the level of effort in points? (0,1,2,3,5,8,13,21)

**Comment by agentpoyo** [comment]
I would have said 8pts @lixuna
