### ISSUE TITLE
[Workload] Observability test: Open Tracing (Jaeger)

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#1081]
## Title: [Workload] Tracing

**Is your workload test idea related to a problem? Please describe.**
- Tracing should be configured for a CNF

**Describe the solution you'd like**
- Query Jaeger API to see if a CNF target is configured for it

**Test Category Name**
-  Observability

**Type of test (static or runtime)**
- runtime

---

### Documentation tasks:
- [ ] Update [installation instructions](https://github.com/cncf/cnf-testsuite/blob/main/install.md) if needed
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-testsuite/blob/main/TEST-CATEGORIES.md) if needed
- [ ] Update [USAGE md](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) if needed
  - [ ] How to run
  - [ ] Description and details
    - [ ] What the best practice is
    - [ ] Why are we testing this
  - [ ] Remediation steps if test does not pass

### QA tasks

Dev Review:

- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes,
  - [ ] move to `Needs Peer Review` column
  - [ ] create Pull Request and follow check list
  - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:

- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes,
  - [ ] move to `Reviewer Approved` column
  - [ ] Approve pull request
- [ ] if no,
  - [ ] document what did not go as expected, including error messages and screenshots (if possible)
  - [ ] Add comment to pull request
  - [ ] request changes to pull request

**Comment by wavell** [comment]
https://www.jaegertracing.io/docs/1.29/operator/

**Comment by wavell** [comment]
https://www.jaegertracing.io/docs/1.29/getting-started/

**Comment by wavell** [comment]
https://github.com/jaegertracing/helm-charts/tree/main/charts/jaeger
use hotrod as a cnf
https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/values.yaml#L680

**Comment by agentpoyo** [comment]
###  Acceptance Criteria 
---
###  Common steps
- [ ] Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-testsuite/blob/main/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]  As a peer reviewer, Pull down latest version of CNF conformance test code from `main` branch
- [ ]  Run `shards install`

### Update Prerequisite checker
- [ ] NA

### Added to overall points:
- [ ]  I see the test in the embedded points.yml as valid test score

### When I run `install_jaeger`, I should see jaeger installed when running helm list and kubectl get pods:
- [ ] Run `./cnf-testsuite install_jaeger`
- [ ] Run `helm list` or `kubectl get pods` and I should see jaeger listed and installed on my cluster.
- [ ] Run `./cnf-testsuite uninstall_jaeger`
- [ ] I can see jaeger is no longer installed.

### When I run `tracing`, I should see test run with FAIL results when using a CNF not configured for tracing with jaeger installed:
- [ ] Run `./cnf-testsuite install_jaeger`
- [ ] Run `./cnf-testsuite cnf_setup cnf-config=sample-cnfs/sample-coredns-cnf/cnf-testsuite.yml`
- [ ] Run `./cnf-testsuite tracing`
- [ ] I can see FAIL results for `tracing`.
- [ ] Run `./cnf-testsuite cnf_cleanup cnf-config=sample-cnfs/sample-coredns-cnf/cnf-testsuite.yml`

### When I run `tracing`, I should see test run with PASS results when using a CNF configured for tracing with jaeger installed:
- [ ] Run `./cnf-testsuite install_jaeger` if not already installed or was previously uninstalled from last step.
- [ ] Run `./cnf-testsuite cnf_setup cnf-config=sample-cnfs/sample-tracing/cnf-testsuite.yml`
- [ ] Run `./cnf-testsuite tracing`
- [ ] I can see FAIL results for `tracing`.

### When I run `workload`, I should see `tracing` test run with results:
- [ ] Run `./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample-tracing/cnf-testsuite.yml`
- [ ] Run `./cnf-testsuite workload`
- [ ] I can see that tracing is run during workload tests with pass or fail results.

**Comment by agentpoyo** [comment]
![1081_tracing_install_jaeger](https://user-images.githubusercontent.com/14348948/146809194-67fc0534-ed78-4032-812e-7f52a45dfc12.png)

**Comment by agentpoyo** [comment]
![1081_tracing_fail](https://user-images.githubusercontent.com/14348948/146809302-8512cd46-87e2-46f5-bc8c-e3f7d6996f6a.png)

**Comment by agentpoyo** [comment]
![jaeger_tracing_output](https://user-images.githubusercontent.com/14348948/146809378-608b2c6d-2c8b-47ce-9cc1-fabe3e3ebb43.png)

**Comment by agentpoyo** [comment]
![1081_tracing_workload](https://user-images.githubusercontent.com/14348948/146810280-44dcaf45-4947-401c-a590-67491338b505.png)

**Comment by lixuna** [comment]
@agentpoyo @wavell @denverwilliams what points estimate would you give this workload test? (0,1,2,3,5,8,13,21)

**Comment by agentpoyo** [comment]
8pts @lixuna

**Comment by agentpoyo** [comment]
> @agentpoyo Does this test have documentation in USAGE, or an issue to add documentation?

I'll create an issue to get USAGE doc added.
