### ISSUE TITLE
[BUG] `rolling_version_change` is missing from USAGE doc

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1085]
**Describe the bug**
The `rolling_version_change` is missing from the USAGE documentation.

**Expected behavior**
When I browse to the USAGE doc in our`main` repository, I should see `rolling_version_change` as a valid test with details about the test along with remediation details.

Ref: #1016

**Comment by agentpoyo** [comment]
### Acceptance Criteria

- [ ] When I browse to https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md, I can see `rolling_version_change` test as a individual test that be run or invoked using the `cnf-testsuite` binary executable.

**Comment by lixuna** [comment]
@agentpoyo I see https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-a-cnf-version-can-be-downgraded-through-a-rolling_version_change

Do we also want to add details and remediation to this test?

**Comment by agentpoyo** [comment]
> @agentpoyo I see https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-a-cnf-version-can-be-downgraded-through-a-rolling_version_change
> 
> Do we also want to add details and remediation to this test?

Probably not yet. The whole rollback, rolling_update, rolling_downgrade are all tied together in a sense. Probably need to come up with a good way to document them all. @lixuna
