### ISSUE TITLE
[BUG] Workload test fails and exits after `pod_network_latency` test completes

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1090]
**Describe the bug**
When running a `workload` test, the suite exits after it states the `chaos_cpu_hog` task is not found. 

**To Reproduce**

1. Setup a CNF, eg. `./cnf-testsuite cnf_setup cnf-config=sample-cnfs/sample_coredns/cnf-testsuite.yml`
2. Run `./cnf-testsuite workload`
3. It should fail after `pod_network_latency` test completes.

**Expected behavior**
This should continue running the resilience tests as the chaos_cpu_hog test is no longer valid test and has been disabled.

**Screenshots**
![bug_workload_exits](https://user-images.githubusercontent.com/14348948/140415565-a9f98fac-a222-401e-b689-ef97a850981f.png)

**Comment by agentpoyo** [comment]
Acceptance Criteria:

- [ ] Setup an CNF, `./cnf-testsuite cnf_setup cnf-config=sample-cnfs/sample_coredns/cnf-testsuite.yml`
- [ ] Run `./cnf-testsuite workload`
- [ ] I should not see cnt-testsuite exit after the `pod_network_latency` resilience test.
- [ ] I can see screenshots of the successful output of all the resilience tests during the `workload` run.

**Comment by wavell** [comment]
![image](https://user-images.githubusercontent.com/29548/142510038-334c39cb-0169-49d5-8417-3f4b421bfbc2.png)
