### ISSUE TITLE
[Feature] Use ECR instead of a third-party templating library

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1093]
**Describe the bug**
The third-party templating library that the cnf-testsuite project uses has to be maintained/upgraded for us to upgrade to a newer version of Crystal. The library currently throws an error when using with Crystal 1.2.1.

* Based on our usage of the third-party templating library, it would be easier to use ECR instead.
* ECR also ships with Crystal - so wouldn't need to be separately updated.
* Migrating to use ECR will help with #867 

**To Reproduce**
* Install Crystal 1.2.1 and compile the `main` branch.
* The error displayed in the screenshot would occur.

![image](https://user-images.githubusercontent.com/84005/140479392-99a8123e-7aa0-474a-b004-925786ee5bab.png)

**Comment by agentpoyo** [comment]
#### Acceptance Criteria:

- [ ] Pull down latest `main` after this was merged (passing GH action)
- [ ] Run `crystal build src/cnf-testsuite.cr` and verify no errors on compiling and building the binary using crystal v1.0.0
- [ ] Now upgrade or switch to crystal version 1.2.1 and run the same command to build: `crystal build src/cnf-testsuite.cr` and verify no errors when building occur.
- [ ] I can see screenshots of successful binary builds without errors.

**Comment by agentpoyo** [comment]
**Crystal v1.0:**
![ECR_crystal_v1 0](https://user-images.githubusercontent.com/14348948/142274527-1a7b30ce-0642-4b23-9958-6a6201bffa9d.png)

**Crystal v1.2:**
![ECR_crystal_v1 2](https://user-images.githubusercontent.com/14348948/142274558-55d43fe1-1f8b-4490-a7a1-adf69349e21e.png)
