### ISSUE TITLE
[BUG] cni_compatible fails to delete the temporary kind clusters used to test CNF with CNIs

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1106]
**Describe the bug**
When running the `cni_compatible` test; it setups temporary kind clusters to test the calico and cilium CNIs. If a system does not have kind locally installed, it fails to cleanup and or delete the clusters after running the tests.

**To Reproduce**

1. Setup cnf-testsuite and CNF on a host that does not have kind locally installed.
2. Run `./cnf-testsuite cni_compatible`
3. You should see results for the tests but kind not found errors during the last steps and output.

**Expected behavior**
kind should clear the created clusters

**Screenshots**
![kind_not_locally_installed](https://user-images.githubusercontent.com/14348948/142054931-4879ed43-f1ea-4374-a488-f29264528946.png)

**Comment by agentpoyo** [comment]
###  Acceptance Criteria 
---
### Documentation is updated:
- [ ] USAGE.md documentation updated
   - [ ] how to run
   - [ ] Description, remediation and details 
       - [ ] what the best practice is
       - [ ] why are we testing this
- [ ] CATEGORIES updated

###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-testsuite/blob/main/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]   As a peer reviewer, Pull down latest version of CNF conformance test code from `main` branch
- [ ]  Run `shards install`

### Update Prerequisite checker
- [ ] NA

### Added to overall points:
- [ ]  I see the test in the embedded points.yml as valid test score

### When I run `cni_compatible` I should see the temporary kind clusters created deleted cleanly without errors:
- [ ] Run `./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample_coredns/cnf-testsuite.yml`
- [ ] Run `./cnf-testsuite cni_compatible`
- [ ] I can see PASS result output for calico and cilium CNI
- [ ] I should see the kind clusters being cleared/deleted as they're not longer needed.

### Screenshots of output:
- [ ] I can see a screenshots of the test and the kind clusters deleted

**Comment by wavell** [comment]
![image](https://user-images.githubusercontent.com/29548/142501566-45d19228-aa2c-4b08-8807-5330c7a92242.png)
