### ISSUE TITLE
[BUG] cni_compatible needs description and remediation steps in USAGE doc

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1108]
**Describe the bug**
The `cni_compatible` test is missing more detailed description and remedation steps in the USAGE doc.

**Expected behavior**
When I browse to https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-the-cnf-is-compatible-with-different-cnis, I should see a dropdown with description and remediation details for CNI Compatible Best practices.

Refs: #1024 https://github.com/cncf/cnf-testsuite/issues/1024

**Comment by lixuna** [comment]
@agentpoyo can this issue be prioritized for the Dec 16th release?

**Comment by agentpoyo** [comment]
@lixuna yes, I've started on these so it shouldn't be a problem getting it into the next release.

**Comment by agentpoyo** [comment]
### Acceptance Criteria

- [ ] When I browse to https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-the-cnf-is-compatible-with-different-cnis, I can see a details drop down that has details about the `cni_comparible` test along with remediation steps.

**Comment by lixuna** [comment]
LGTM, thank you @agentpoyo
