### ISSUE TITLE
[Workload] Use Kyverno to add the latest_tag configuration lifecycle test

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1109]
## Description

* Working session to install kyverno
* Add the `latest_tag` test with a sample CNF to reproduce the bad scenario.
* Push changes to `kyverno-demo` branch as an example.

**Comment by agentpoyo** [comment]
No AC required, this was a placeholder issue for working with Sagar to get Kyverno setup within the testsuite.
