### ISSUE TITLE
[BUG] Latest releases are not appearing on https://github.com/cncf/cnf-testsuite/releases as expected

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1111]
**Describe the bug**
I would expect to see the most recent, tagged releases listed on Page 1 of the release page (https://github.com/cncf/cnf-testsuite/releases) 

Instead, the top of Page 1 of the release page shows a drafted, untagged doc update from Aug 11, 2021 called "documentation/#912_crystal_v1.0.0-2021-08-11-184020-ac3ce5c5 August 11, 2021 Draft UPDATES" 

**To Reproduce**

1. Go to Page 1 of the releases page https://github.com/cncf/cnf-testsuite/releases?page=1
2. Click on "Page 2" button at the bottom of the page
3. Scroll down halfway down Page 2
4. Then most recent releases appear (after "untagged draft releases")

**Expected behavior**
I would expect to see the most recent, tagged releases listed on Page 1 of the release page (https://github.com/cncf/cnf-testsuite/releases) 

**Screenshots**

<img width="915" alt="Screen Shot 2021-11-18 at 3 12 15 PM" src="https://user-images.githubusercontent.com/11701267/142497633-e5ac6ecc-4cc5-4364-a825-426cab1981f3.png">

**Comment by agentpoyo** [comment]
In incognito mode and or another browser like firefox, logged out of github, the releases show up normal in alpha numeric order based on date after we removed unnecessary drafts that started with crystal* in the name format.

![1111_releases_cnf-testsuite](https://user-images.githubusercontent.com/14348948/142507356-629f9052-28c4-4099-829e-2cb0c85eea91.png)

**Comment by lixuna** [comment]
Thank you @agentpoyo - much better! 

What was the level of effort in pts for this improvement? (01,2,3,5)

**Comment by agentpoyo** [comment]
1pt @lixuna
