### ISSUE TITLE
[Feature] config map cleanup

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#1115]
**Is your feature request related to a problem? Please describe.**
Config maps should be cleaned up when the cnf is cleaned up

**Describe the solution you'd like**
Config map templates that are used to create new config maps should be placed in a config_maps directory under the CNF release name directory: i.e. cnfs/<release_name>/config_maps
Upon cnf cleanup, all of the config map template files in the cnfs/<release_name>/config_maps directory should be deleted

**Comment by agentpoyo** [comment]
###  Acceptance Criteria 
---
###  Common steps
- [ ] Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-testsuite/blob/main/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]  As a peer reviewer, Pull down latest version of CNF conformance test code from `main` branch
- [ ]  Run `shards install`

### Update Prerequisite checker
- [ ] NA

### Added to overall points:
- [ ]  I see the test in the embedded points.yml as valid test score

### When I install a CNF with configmaps, I should find a config_maps directory under cnfs/
- [ ] Run `./cnf-testsuite cnf_setup cnf-config=`
- [ ] `ls -al cnfs/` should list the installed cnf and it's directories.
- [ ] When I run `./cnf-testsuite cnf_cleanup`, I should now see all the directories cleaned up.

**Comment by agentpoyo** [comment]
![1115_output](https://user-images.githubusercontent.com/14348948/146250634-e834dd31-fdc7-495b-b141-f523885c89c4.png)
