### ISSUE TITLE
[BUG] Add `open_metrics` USAGE with Description and Remediation Details

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1117]
**Describe the bug**
Need to add the open_metrics description, remediation and command usage to the USAGE doc.

Ref: #1080

**Comment by lixuna** [comment]
@agentpoyo can this be completed for the next release, ETA Dec 16th?

**Comment by agentpoyo** [comment]
> @agentpoyo can this be completed for the next release, ETA Dec 16th?

I mean to grab this one when doing the other USAGE docs. I'll have this completed before next release.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] When I goto https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md , I can see `open_metrics` listed as valid test along with a drop down details with remediation steps documented.

**Comment by lixuna** [comment]
QA blocked:
- to do: review and merge https://github.com/cncf/cnf-testsuite/pull/1140/files

**Comment by lixuna** [comment]
![Screen Shot 2021-12-15 at 10 34 30 AM](https://user-images.githubusercontent.com/11701267/146226552-f9737710-1cb0-41f1-821e-46ecd5a28ccf.png)
