### ISSUE TITLE
[BUG] Running workload should not result in a crash if Falco is already installed

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1119]
**Describe the bug**
* If Falco has already been installed with helm previously, then Helm throws a cannot re-use name error.
* The Helm helper module within the test suite throws a `Helm::CannotReuseReleaseNameError`

**To Reproduce**
Run workload against a CNF in a new kind cluster and repeat the step again to see the error (as in the screenshot).

**Expected behavior**
The workload tests should run as expected instead of crashing.

**Screenshots**
![AF4D10F1-0AC0-4779-8636-8D8399CF3AB2](https://user-images.githubusercontent.com/84005/144180681-89df4cf1-4c4b-41a6-831d-e9281068e0d0.png)

**Comment by agentpoyo** [comment]
Duplicate of https://github.com/cncf/cnf-testsuite/issues/1091

**Comment by agentpoyo** [comment]
![falco_bug](https://user-images.githubusercontent.com/14348948/146245548-235ed7bf-eb05-45e1-bc08-ee87e6da5470.png)
