### ISSUE TITLE
[BUG] cnf_setup outputs helm pull error even if cnf_setup was successful

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1120]
**Describe the bug**
In cnf_setup, should not output Helm pull error if helm-pull status was successful.

<img width="1640" alt="image" src="https://user-images.githubusercontent.com/84005/144189160-90fe751c-5d68-49aa-a774-2285c06182e6.png">

**To Reproduce**

In the main branch, run this command to reproduce the issue in the screenshot above:

```
crystal run src/cnf-testsuite.cr -- cnf_setup cnf-config=./sample-cnfs/sample-coredns-cnf/cnf-testsuite.yml
```

**Comment by agentpoyo** [comment]
###  Acceptance Criteria 
---
###  Common steps
- [ ] Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-testsuite/blob/main/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]  As a peer reviewer, Pull down latest version of CNF conformance test code from `main` branch
- [ ]  Run `shards install`

### Update Prerequisite checker
- [ ] NA

### Added to overall points:
- [ ]  I see the test in the embedded points.yml as valid test score

### When I setup a CNF`, I should not see helm errors
- [ ] Run `./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample-coredns-cnf/cnf-testsuite.yml`
- [ ] I do not see `Helm pull error` in the output.
- [ ] I can see screenshot of the output.

**Comment by agentpoyo** [comment]
![1120_output](https://user-images.githubusercontent.com/14348948/146249272-c2ddd184-2e3d-41fc-a9b3-df157a916820.png)
