### ISSUE TITLE
[Feature] Update points with refactored test categories

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1136]
**Is your feature request related to a problem? Please describe.**
- task for #1088 

**Describe the solution you'd like**
- Reduce the number of test categories from 10 to 7 in the Points
- Move tests into new categories, where appropriate
- Notes on reorganizing tests in new categories in https://hackmd.io/NY5jSQp0Q7mM2klg3OFm6w?view

**How will this be tested? aka Acceptance Criteria (optional) **

<img width="578" alt="Screen Shot 2021-11-11 at 12 02 30 PM" src="https://user-images.githubusercontent.com/11701267/141347025-3f205308-2186-45bb-a003-91de84192306.png">

<img width="571" alt="Screen Shot 2021-11-11 at 12 02 40 PM" src="https://user-images.githubusercontent.com/11701267/141347031-b03f26ca-ec44-46e2-9258-1c271e0deee5.png">

**Comment by agentpoyo** [comment]
This work was done in #1135 so the AC steps will be added and reviewed there.

**Comment by lixuna** [comment]
Thank you, @agentpoyo What was the level of effort to refactor the points (0,1,2,3,5,8,13,21)?

**Comment by agentpoyo** [comment]
See https://github.com/cncf/cnf-testsuite/issues/1135#issuecomment-1023465540 for AC for peer review.

**Comment by agentpoyo** [comment]
https://github.com/cncf/cnf-testsuite/issues/1135 Reviewer approved.
