### ISSUE TITLE
[BUG] Delete unused file for Pseudo code 

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1138]
**Describe the bug**
Pseudo code is not used 

**Expected behavior**
Delete unused file [for Pseudo code ](https://github.com/cncf/cnf-testsuite/blob/main/PSEUDO-CODE.md)

**Comment by agentpoyo** [comment]
I added this removal in my current PR: https://github.com/cncf/cnf-testsuite/pull/1140

**Comment by lixuna** [comment]
![Screen Shot 2021-12-15 at 10 37 34 AM](https://user-images.githubusercontent.com/11701267/146227086-e3d1ab95-dc21-4ad9-aad0-dd020f15322f.png)
