### ISSUE TITLE
[BUG] The new fluentd `routed_logs` test is missing from USAGE doc

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1141]
**Describe the bug**
There is no mention of `routed_logs` for fluentd logging in the USAGE doc. Need missing command, details and remediation.

**Comment by lixuna** [comment]
![Screen Shot 2021-12-15 at 4 03 11 PM](https://user-images.githubusercontent.com/11701267/146272058-ac56a40d-f2f5-4a56-8471-5f2810cfb529.png)

https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-logs-and-data-are-being-routed-through-fluentd
