### ISSUE TITLE
[Research] Run CNF Test Suite workload test with an example CNF on Cox Edge Platform

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1143]
**Is your feature request related to a problem? Please describe.**
A new login has been created for the Cox Edge Platform

**Describe the solution you'd like**
- Please login to the platform and try to run the CNF Test Suite using the install guide
- Is the test suite compatible with the platform?
- Note what does and does not work as expected

The goal is to see if the workload tests can run against a CNF running in this environment.  No platform tests. 
 
As this is a research issue, if there are problems in the tasks to run the test suite then document them (ideally in this ticket).  If there is a blocker add a comment with details.  We will decide on resolving the blocker or halting this work.

Tasks:
- [x] Create login creds for team
  - [x] validate @agentpoyo can login
  - [ ] validate @denverwilliams can login
- [ ] Add links or document how to create a K8s cluster in Cox Edge
- [ ] Create K8s cluster on Cox Edge
- [ ] Deploy example CNF
- [ ] Run test suite against CNF on Cox Edge

**Comment by taylor** [comment]
If needed we can create a new ticket for platform tests.

**Comment by agentpoyo** [comment]
@taylor @lixuna 

I was able to login with the provided creds.
