### ISSUE TITLE
[BUG] Missing USAGE doc for Observability Test: Open Tracing (Jaeger)

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1149]
**Describe the bug**
Need to add `tracing` test to USAGE doc along with description details and remediation steps.

Ref #: https://github.com/cncf/cnf-testsuite/issues/1081

**Comment by agentpoyo** [comment]
Acceptance Criteria:

- [ ] When I goto [tracing](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-tracing-is-being-used-with-jaeger) in the USAGE doc, I can see a drop down that provides more details and remediation steps.

**Comment by lixuna** [comment]
I see the details, I have added PR #1155 to fix a typo

![Screen Shot 2022-01-10 at 4 11 35 PM](https://user-images.githubusercontent.com/11701267/148847909-fa40d38f-64a4-4ec9-89c3-cdd4e758ea77.png)
