### ISSUE TITLE
[BUG] Missing USAGE doc for State Test: elastic persistent volumes

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1150]
**Describe the bug**
Need to add the test `elastic_volume` test in USAGE doc with description details and remediation steps.

Ref #: https://github.com/cncf/cnf-testsuite/issues/1025

**Comment by agentpoyo** [comment]
Acceptance Criteria:

- [ ] When I goto [Elastic_Volume](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-test-if-the-cnf-uses-elastic-volumes) in the USAGE doc, I can see a drop down that provides more details and remediation steps.

**Comment by lixuna** [comment]
LGTM 

![Screen Shot 2022-01-10 at 4 13 31 PM](https://user-images.githubusercontent.com/11701267/148847392-3584a113-0590-4514-a20c-da44ff2cd749.png)
