### ISSUE TITLE
[BUG] KindManager.wait_for_cluster/2 should consider clusters where pods can have more than one instance

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1151]
**Describe the bug**
`KindManager.wait_for_cluster/2` in kind_setup.cr should accommodate clusters where a pod can have more than one instance.

To determine if a the cluster is ready, the function gets the pod count and compares it against the ready count.

### Total pod count

The [total pod count](https://github.com/cncf/cnf-testsuite/blob/df2c674555a05e4b72e44da818e89c542b7f5262/src/tasks/kind_setup.cr#L93) command gets the count from the readable kubectl output. But this output is grouped by pod name and lists pod count for each pod. In the screenshot below, the apisnoop pod would be counted as one (but there are two instances).

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/84005/148755672-5d60d177-93e7-4b51-8be9-c1810011b9cc.png">

### Ready pod count
The command output for [ready count](https://github.com/cncf/cnf-testsuite/blob/df2c674555a05e4b72e44da818e89c542b7f5262/src/tasks/kind_setup.cr#L99) is formatted by a go template. This counts the ready pods accurately.

<img width="1816" alt="image" src="https://user-images.githubusercontent.com/84005/148756098-d9ed49c3-481e-403e-a40c-5b4dae57a641.png">

### Detecting cluster readiness

The cluster will never be marked as ready if there is more than one instance of the pod, because the ready pod count will be more than actual pod count and the readiness check uses the equal operator to compare the two numbers.

## Solution
Use a go template to get list of pods too. Will fix this as a part of #41.

**Comment by agentpoyo** [comment]
No AC required, this ties into https://github.com/cncf/cnf-testsuite/issues/41 where AC will be performed.
