### ISSUE TITLE
[BUG] KindManager.wait_for_cluster/2 checks only the kube-system namespace for cluster readiness

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1152]
**Describe the bug**

* [KindManager.wait_for_cluster/2](https://github.com/cncf/cnf-testsuite/blob/df2c674555a05e4b72e44da818e89c542b7f5262/src/tasks/kind_setup.cr#L93-L100) checks only the `kube-system` namespace for cluster readiness.
* With apisnoop in #41, the cluster has apisnoop pre-deployed by kind on cluster creation that is a part of the default namespace.

For #41, in order to accommodate the apisnoop resources in the default namespace, the cluster readiness should also check for ready state of pods in the default namespace.

**Comment by agentpoyo** [comment]
No AC required, this ties into https://github.com/cncf/cnf-testsuite/issues/41 where AC will be performed.
