### ISSUE TITLE
[BUG] KubectlClient.server_version should fetch the right patch version

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1156]
**Describe the bug**
* The current version of the KubectlClient.server_version helper method parses the output of `kubectl version` using regex to get the server version.
* The patch version is hard-coded to `0`

**Expected behavior**
As a part of (#41), the testsuite will require that we create a kind cluster using the same Kubernetes version as the original cluster that cnf-testsuite is being run on. We therefore need the patch version of the Kubernetes server too.

In order to accommodate the requirement, it would be good to fetch the Kubernetes server version using the JSON output of the `kubectl version` command.

**Comment by agentpoyo** [comment]
No AC required, this ties into https://github.com/cncf/cnf-testsuite/issues/41 where AC will be performed.

**Comment by lixuna** [comment]
@HashNuke @agentpoyo what was the level of effort involved with these updates? (0,1,2,3,5,8,13,21)
