### ISSUE TITLE
[Feature] Improvements to KindManager to support requirements for apisnoop integration

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1157]
This ticket is to document improvements required to KindManager to support the apisnoop integration (#41)

## Requirement-1: Maintain correct paths to support running commands from different directories

The `KindManager` currently has the following limitations
* The current working directory is assumed to be the root of the project.
* The helm and kind binary paths are fetched on the fly based on the root of the project

But these would not work with apisnoop since it requires that we change the working directory to within the apisnoop repo
* In order to use the kind config provided
* And the kind config yaml has a relative path reference to manifest files within the same directory

**Solution:** Update the KindManager class interface to require instantiating objects that maintain state information about the paths to project root, kind and helm.

## Requirement-2: Add helper for waiting for nodes to be ready in a multi-node cluster

* The apisnoop kind config has two notes defined (control plane and a worker node)
* Based on observations on GitHub Action builds, kind cluster create command succeeds when the control plane is started. it takes a while for the second node to be up and running.

**Solution:** A helper would be useful to wait for all nodes to be up and running.

**Comment by agentpoyo** [comment]
No AC required, this ties into https://github.com/cncf/cnf-testsuite/issues/41 where AC will be performed.
