### ISSUE TITLE
[Workload] Microservices test: Shared Database Instance

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#1165]
## Title: [Workload] Microservices test: Shared Database Instance

**Is your workload test idea related to a problem? Please describe.**
- Microservices should not share data (no integrated database)

**Describe the solution you'd like**
- Two microservices (containers that have an api exposed, as evidenced by having a corresponding K8s Service) that open a connection (verified by something like netstat) to the same database (a verified official database container) should be flagged as an integration database (https://martinfowler.com/bliki/IntegrationDatabase.html)

**Test Category Name**
- Microservices

**Type of test (static or runtime)**
- runtime

---

### Documentation tasks:
- [ ] Update [installation instructions](https://github.com/cncf/cnf-testsuite/blob/main/install.md) if needed
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-testsuite/blob/main/TEST-CATEGORIES.md) if needed
- [ ] Update [USAGE md](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) if needed
  - [ ] How to run
  - [ ] Description and details
    - [ ] What the best practice is
    - [ ] Why are we testing this
  - [ ] Remediation steps if test does not pass

### QA tasks

Dev Review:

- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes,
  - [ ] move to `Needs Peer Review` column
  - [ ] create Pull Request and follow check list
  - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:

- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes,
  - [ ] move to `Reviewer Approved` column
  - [ ] Approve pull request
- [ ] if no,
  - [ ] document what did not go as expected, including error messages and screenshots (if possible)
  - [ ] Add comment to pull request
  - [ ] request changes to pull request

**Comment by wavell** [comment]
1) single schema per microservice
-- a microservice's database schema should not be directly accessible by another microservice
2) multiple schemas per process (container)
-- a microservice schema's process (container) can not be shared with another schema
-- single point of failure (database) for two microservices

**Comment by agentpoyo** [comment]
###  Acceptance Criteria 
---
###  Common steps
- [x] Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-testsuite/blob/main/KIND-INSTALL.md) will work as well
- [x]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [x]  As a peer reviewer, check that PR passes in GitHub Actions
     - [x] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [x]  As a peer reviewer, Pull down latest version of CNF conformance test code from `main` branch
- [x]  Run `shards install`

### Update Prerequisite checker
- [ ] NA

### Added to overall points:
- [ ]  I see the test in the embedded points.yml as valid test score

### When I run `shared_database`, I should see elastic_volumes test run with PASS results:
- [ ] Run `./cnf-testsuite cnf_setup cnf-path=sample-cnfs/sample-statefulset-cnf/cnf-testsuite.yml`
- [ ] Run `./cnf-testsuite shared_database`
- [ ] I can see results for database persistence.

### When I run `shared_database`, I should see a sample test run with FAIL results designed to fail:
- [ ] Run `./cnf-testsuite cnf_setup cnf-path=sample-cnfs/sample-multi-db-connections-fail/cnf-testsuite.yml`
- [ ] Run `./cnf-testsuite shared_database`
- [ ] I can see results for database persistence.

### When I run `workload`, I should see shared_database test run during workloads with points assigned on either FAIL or PASS:
- [ ] Run `./cnf-testsuite cnf_setup cnf-path=sample-cnfs/sample-statefulset-cnf/cnf-testsuite.yml`
- [ ] Run `./cnf-testsuite workload`
- [ ] I can see results for database persistence.

**Comment by agentpoyo** [comment]
![1165_pass](https://user-images.githubusercontent.com/14348948/152703829-76ddbd4b-51c8-474b-8a18-f0e26fdef852.png)

**Comment by agentpoyo** [comment]
@wavell @denverwilliams 

Seeing PASS and then FAIL for the failed sample CNF:

![1165_fail](https://user-images.githubusercontent.com/14348948/152704915-1e5cc845-3973-420b-9859-992688c8e6eb.png)

**Comment by agentpoyo** [comment]
@wavell @denverwilliams 

`shared_database` missing from points and does not show when running `workload` or `microservice` specific tests.

Opened bug: https://github.com/cncf/cnf-testsuite/issues/1204

**Comment by agentpoyo** [comment]
![1168_microservice_pass](https://user-images.githubusercontent.com/14348948/152989499-09e8c72e-b887-43da-ac98-9cf6d7e6b35a.png)

**Comment by agentpoyo** [comment]
I would say 8pts for myself. @lixuna
