### ISSUE TITLE
[BUG] Docker connection timeout error when connecting to Docker Hub API endpoints

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1184]
## Describe the bug

> *Identified this issue when fixing #1180. The issue described in 1180 was caused by the code. But this issue describes an error that occurs due to docker itself.*

Docker sometimes cannot connect to the DockerHub registry and endpoints. This happens when running GitHub Actions builds.
The failures begin with "docker login".

**The docker login error**
```
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
command terminated with exit code 1
```

**Where to find the error?**
* The screenshot below shows the error
* The build shown in the screenshot can be viewed [here](https://github.com/cncf/cnf-testsuite/runs/4970038451?check_suite_focus=true#step:9:383).

<img width="1539" alt="image" src="https://user-images.githubusercontent.com/84005/151413462-78397413-afa8-434a-a356-37e145e2b8a2.png">

## Possible solutions
Setup a docker mirror or a pass-through registry.

**Comment by taylor** [comment]
@HashNuke update and close

**Comment by agentpoyo** [comment]
No AC required.

**Comment by HashNuke** [comment]
Looks like there is a delay in the networking working for the container.
I added a curl command making a request to example.com before making the dockerhub request. That resolved the issue. Removing this would again bring back the issue (I had verified this).
