### ISSUE TITLE
[Documentation] documentation needed for nodeport_not_used configuration test

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1191]
**Describe the bug**
Documentation needed for https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-test-if-there-are-node-ports-used-in-the-service-configuration

**Comment by agentpoyo** [comment]
This has been addressed from other doc updates for USAGE.

**Comment by agentpoyo** [comment]
There is now documentation for nodePort: https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#nodeport-not-used
