### ISSUE TITLE
[BUG] documentation needed for 'immutable_configmap' test

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1195]
**Describe the bug**
Documentation needed for 'immutable_configmap' https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-a-cnf-version-uses-immutable-configmaps

**Comment by agentpoyo** [comment]
This has been addressed in other documentation tickets.

#### Acceptance Criteria

- [ ] You can see that there is documentation for immutable configmaps in the USAGE doc found at: https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#immutable-configmaps
