### ISSUE TITLE
[BUG] cluster-tools in default namespace interferes with test results

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1199]
## Describe the bug
The presence of cluster-tools in the default namespace interferes with certain tests. This is causing certain tests to fail (false-negatives).

> Going by the screenshot below, similar could be said of Falco or any tools that are installed. But for tools, this is yet to be verified and maybe a residue of a previous test run.

### Found evidence of this in two scenarios

1. When pairing with @nsagark for the `require_labels` test, we found that the Kyverno policy reports checks default namespace and cluster-tools being present and not adhering to the the required policy would fail the test.
2. When looking into #687, I found the `hostpath_mounts` and `immutable_file_systems` tests failing and they have messages about cluster-tools being one of the failures. Both tests use Kubescape. Screenshot below.

![image](https://user-images.githubusercontent.com/84005/152310406-d7ce3c86-d379-4cc3-8cbc-f55aeb5cb28d.png)

## To reproduce

Run the `workload` tests.

```
crystal run src/cnf-testsuite.cr -- workload
```

## Expected behaviour

Tests should not fail due to cluster-tools adhering to test requirements.

## Possible solution

Moving clustertools to another namespace might resolve this issue.

**Comment by HashNuke** [comment]
> Notes to self

These are my notes for making the changes

#### Add required support in required helpers without breaking build

1. Identify `KubectlClient` helpers that are used along with cluster-tools.
2. Add namespace option to the select `KubectlClient` helpers.
3. Ensure that the build is green.

#### Ensure that cluster-tools is installed and used within stipulated namespace

1. Define `cnf-testsuite` namespace for tools installed by testsuite.
2. Ensure cluster-tools is installed in the testsuite namespace.
3. Make appropriate changes to areas where cluster-tools is used by scoping it to namespace.

#### Ensure that other third-party tools are installed by testsuite within stipulated namespace.

1. Identify other tools that are installed in the default namespace.
2. Create ticket for other tools that are also in the default namespace.
3. Make changes for the ticket created in previous step [2]

**Comment by HashNuke** [comment]
### Update: 11 Feb 2022

Tracked down impact areas in ClusterTools module and the KubectlClient module and updated the code appropriately. Notes below.

**Next TODOs:** Look into each task and spec test that uses cluster-tools and cluster-tools-k8s. To find impact areas
* Look for the direct manifest install
* Look for ClusterTools.install

#### Notes about helper functions updated
```
[DONE] KubectlClient::Apply.file
[DONE] KubectlClient::Delete.file

[DONE] KubectlClient::Get.resource_wait_for_uninstall
* [N/A] KubectlClient::Get.pods_by_nodes
* [N/A] KubectlClient::Get.pods_by_label
* [DONE] KubectlClient::Get.resource

[DONE] KubectlClient::Get.wait_for_install
[DONE] KubectlClient::Get.resource_wait_for_install
[DONE] KubectlClient::Get.resource
[DONE] KubectlClient.exec

[DONE] ClusterTools.install
* [DONE] KubectlClient::Get.resource_wait_for_install

[DONE] ClusterTools.uninstall
* [DONE] KubectlClient::Get.resource_wait_for_uninstall

[DONE] ClusterTools.exec
* [DONE] KubectlClient.exec

[DONE] ClusterTools.exec_k8s
* [DONE] KubectlClient.exec

[DONE] ClusterTools.wait_for_cluster_tools
* [DONE] KubectlClient::Get.resource_wait_for_install
* [DONE] KubectlClient::Get.resource_wait_for_install

[N/A] ClusterTools.official_content_digest_by_image_name

[DONE] ClusterTools.local_match_by_image_name
* [N/A] KubectlClient::Get.container_tag_from_image_by_nodes
* [N/A] KubectlClient::Get.pods_by_nodes

[DONE] ClusterTools.pod_name
* [DONE] KubectlClient::Get.pod_status

[DONE] ClusterTools.pod_by_node
* [DONE] KubectlClient::Get.resource
* [DONE] KubectlClient::Get.pods_by_resource
```

**Comment by HashNuke** [comment]
#### Update 12 Feb 2022

* Changes for cluster-tools moving cluster tools to another namespace.
* Line of interest: `spec/utils/utils_spec.cr:197`. Should check if this test fails due to cluster-tools being moved to another namespace.
```
(task_response).should eq("✖️  FAILED: Found privileged containers: [\"cluster-tools\", \"coredns\", \"kube-proxy\"]".colorize(:red))
```

**Next steps:**
* Fix any build failures
* Check status by running workload tests and comparing failures against main branch.
* Identify areas where third-party tools are being installed and move them to another namespace. Create a separate ticket for this

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Setup test CNF: `./cnf-testsuite cnf_setup cnf-config=sample-cnfs/sample-coredns-cnf/cnf-testsuite.yml`
- [ ] Run `./cnf-testsuite hostpath_mounts` and I should not see any FAIL with errors pointing to pods using our tools for the tests as problematic installs that affect the test outcome, a PASS result is satisfactory as well.
- [ ] Run `./cnf-testsuite immutable_file_systems` and like before, if FAILS, should not see any of the tools used for the testsuite causing the CNF to fail in output or see a PASSED.
- [ ] I can see a screenshot of the output.

**Comment by agentpoyo** [comment]
![1199_test_results](https://user-images.githubusercontent.com/14348948/154143084-d58d24fd-6320-4544-b4ea-5c6b30ba205a.png)
