### ISSUE TITLE
[BUG] `shared_database` missing from points and USAGE doc

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1204]
**Describe the bug**
The new `shared_database` test is missing from the embedded points and USAGE doc while also not running or displaying it's running during `microservice` or `workload` tests.

Ref #1165 

Also the Failed Sample test is producing both PASS and FAILED results which they should be FAIL.

**To Reproduce**

1. Setup `./cnf-testsuite cnf_setup cnf-path=sample-cnfs/sample-statefulset-cnf/cnf-testsuite.yml`
2. Then run `cnf-testsuite` followed by `workload` and or `microservice` arguments.

**Expected behavior**
I should find the description on the `shared_database` in the USAGE doc and should also see it PASS or FAIL with points awarded or removed when running `workload` or `microservice` tests.

**Screenshots**
![microservice_bug_output](https://user-images.githubusercontent.com/14348948/152705726-bddbe715-ad7f-48f6-ad14-d3d2fcb16ec4.png)

Here is the output from `workload`:
![microservice_bug_output2](https://user-images.githubusercontent.com/14348948/152705757-c908c987-df19-434b-be58-65da306ca761.png)

**Comment by agentpoyo** [comment]
https://github.com/cncf/cnf-testsuite/issues/1165 covers the AC steps; USAGE and points now have been fixed.

**Comment by lixuna** [comment]
@agentpoyo what is the points estimate for this bug (01,2,3,5,8,13,21)?

**Comment by agentpoyo** [comment]
2pts, added. @lixuna
