### ISSUE TITLE
[Feature]. Base reasonable startup time on readiness and startup probe

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#1205]
**Is your feature request related to a problem? Please describe.**
The reasonable startup time suffers from intermittent failures because it actually tests the startup time of the CNF

**Describe the solution you'd like**
Base reasonable startup time on readiness and startup probe's failurethreshhold and periodseconds fields:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

**Comment by agentpoyo** [comment]
No AC required as this mainly fixes the intermittent issues we are seeing in the CI actions, which has not reappeared after the fix has been implemented.
