### ISSUE TITLE
[BUG] reasonable_image_size test fails when cnf-testsuite is used in a cleanroom environment/dir

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1209]
## Describe the bug

* The dockerd install task `install_dockerd` uses a manifest file path to install dockerd.
* This manifest path refers to dockerd manifest in the `tools` directory.
* This file/path is not created by the testsuite binary and is only present in the project git repository.

Due to this reason, when the testsuite binary is used in a clean environment outside of the git repository, then the dockerd install fails. This results in the reasonable_image_size test failing.

> Notice the dockerd install failure in the screenshot below.

<img width="958" alt="image" src="https://user-images.githubusercontent.com/84005/153341987-32e718cc-bd2d-4ccf-afb2-28a035167ac3.png">

## To Reproduce

```shell
# Build the binary
crystal build src/cnf-testsuite.cr

# Create a cleanroom to test the binary and copy the binary into the cleanroom
mkdir ../cleanroom
cp cnf-testsuite ../cleanroom/cnf-testsuite
cd ../cleanroom

# Create a kind cluster for the cleanroom tests
export KIND_CLUSTER_NAME="1202"
export KUBECONFIG="${PWD}/${KIND_CLUSTER_NAME}.kubeconfig"
kind create cluster --name $KIND_CLUSTER_NAME --kubeconfig $KUBECONFIG

# Setup the testsuite and the sample CNF
./cnf-testsuite setup
./cnf-testsuite cnf_setup cnf-path=../cnf-testsuite/sample-cnfs/sample_coredns

# Run the test
LOG_LEVEL=info ./cnf-testsuite reasonable_image_size
```

## Expected behavior
dockerd install in `reasonable_image_size` test should not fail when the testsuite binary is used in a cleanroom.

**Comment by agentpoyo** [comment]
### Acceptance Criteria

# When I build and run `cnf-testsuite` in a cleanroom setup, I should not see reasonable_image_size fail:
- [ ] Build the binary `crystal build src/cnf-testsuite.cr` based on the dev branch or `main` if merged already
- [ ] Create a cleanroom to test the binary and copy the binary into the cleanroom
  - [ ] `mkdir ../cleanroom; cp cnf-testsuite ../cleanroom/cnf-testsuite; cd ../cleanroom`
- [ ] Create a kind cluster for the cleanroom tests
  - [ ] `export KIND_CLUSTER_NAME="cleanroom"; export KUBECONFIG="${PWD}/${KIND_CLUSTER_NAME}.kubeconfig"; kind create cluster --name $KIND_CLUSTER_NAME --kubeconfig $KUBECONFIG`
- [ ] Setup the testsuite and the sample CNF: `./cnf-testsuite setup; ./cnf-testsuite cnf_setup cnf-path=../cnf-testsuite/sample-cnfs/sample_coredns`
- [ ] Run the test: `LOG_LEVEL=info ./cnf-testsuite reasonable_image_size`
- [ ] I should not see failure for reasonable_image_size
- [ ] I can see the results here.

**Comment by agentpoyo** [comment]
![1209_passed_results](https://user-images.githubusercontent.com/14348948/153477653-411bdb4f-e0e9-479b-b5e3-218f36efb7d1.png)
