### ISSUE TITLE
[Maintenance] Update version of Crystal lang in Q4 2022 

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1211]
### [Q2 2022 Maintenance] Update version of Crystal lang 

**Describe the maintenance item**
- in Q2 2022 (April 1-June 30), check for latest release of Crystal
- check compatibility with dependencies
- update CNF Test Suite with one minor release behind the latest

**Expected behavior**
- the CNF Test Suite will function as expected after updating Crystal

**How will this be tested? aka Acceptance Criteria (optional)**

- [ ] All documentation is updated to mention the updated software version
- [ ] Install works as expected
- [ ] Running `workload` works as expected
- [ ] Running `cert` works as expected
- [ ] Running individual test categories works as expected
- [ ] Running individual tests works as expected
- [ ] tbd, add more expectations as needed

**Additional context**
- in #867 the test suite was updated for crystal v1.1.1 
- in #771 the test suite was updated for crystal v1.0.0

**Comment by lixuna** [comment]
Request to wait until June 2022 to start on this

As of April 22, https://github.com/crystal-lang/crystal/releases/tag/1.4.1 is released.

**Comment by denverwilliams** [comment]
```

**Comment by lixuna** [comment]
As of Aug 24, https://github.com/crystal-lang/crystal/releases/tag/1.5.0 is the latest (released on July 6)

**Comment by lixuna** [comment]
Crystal version will be updated after Nov 1, 2022

**Comment by lixuna** [comment]
FYI - https://github.com/crystal-lang/crystal/releases/tag/1.6.0

**Comment by lixuna** [comment]
FYI - https://github.com/crystal-lang/crystal/releases/tag/1.6.2

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Find or build k8s cluster
- [ ] Checkout latest main or dev branch changes are made for crystal upgrade
- [ ] Make sure you are using crystal v1.6.x through v1.6.2 on your OS
- [ ] Run `shards install` to install any required modules.
- [ ] Run `crystal build src/cnf-testsuite.cr` to make sure a binary is built without issues
- [ ] Setup a sample or example CNF with `cnf_config` after running `setup`
- [ ] Now run `cert` tests
- [ ] Run `workload` tests
- [ ] Test individual tests or category based tests
- [ ] I should see no exit or errors (outside of test fails that are valid fails)
- [ ] I can see screenshot of outputs above.

**Comment by agentpoyo** [comment]
![1211_output](https://user-images.githubusercontent.com/14348948/209223197-414f5b3f-a9c9-46ec-bc1b-17d9085af51a.jpg)

**Comment by lixuna** [comment]
@williscool @denverwilliams @agentpoyo what was the level of effort in pts for this (0,1,2,3,5,8,13)?
