### ISSUE TITLE
[BUG] Third-party tools installed by testsuite are causing test failures

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1219]
## Describe the bug

> This issue is an off-shoot from #1199. Some base work has already been done in #1199.

Third-party tools like falco, dockerd, etc installed by testsuite are causing test failures. Screenshots below show the test results for specific tests.

The tools that cause test failures are:
* falco
* dockerd
* chaos_operator
* local-path-provisioner
* Litmus Chaos
* pod-io-stress

### Test: `privilege_escalation`

<img width="958" alt="image" src="https://user-images.githubusercontent.com/84005/154049751-dfcce668-aaa8-4211-8d73-29cdaebca5d4.png">

### Test: `resource_policies`

<img width="956" alt="image" src="https://user-images.githubusercontent.com/84005/154049536-66bf8768-fbb5-4568-8860-9d2f9ef91f8d.png">

### Test: `linux_hardening`

<img width="957" alt="image" src="https://user-images.githubusercontent.com/84005/154049459-a8bd5598-ce9e-4717-a584-e5b4ace5f2c5.png">

### Test: `ingress_egress_blocked`

<img width="957" alt="image" src="https://user-images.githubusercontent.com/84005/154049381-27cabab5-f236-4b69-badd-e883db593a16.png">

### Test: `privileged_containers`

<img width="954" alt="image" src="https://user-images.githubusercontent.com/84005/154049331-400fa837-9e15-4a2a-8165-fdf744b580c2.png">

### Test: `network_policies`

<img width="954" alt="image" src="https://user-images.githubusercontent.com/84005/154049257-b1ceed5b-9a49-4ee7-96df-2d10c8cbaf9b.png">

### Test: `immutable_file_systems`

<img width="958" alt="image" src="https://user-images.githubusercontent.com/84005/154049157-6e2541eb-0c8c-4b1e-bfa7-ddd3a36c9df3.png">

### Test: `hostpath_mounts`

<img width="949" alt="image" src="https://user-images.githubusercontent.com/84005/154049003-80690137-62c0-4097-9001-07464ee9d441.png">

## To reproduce

> To reproduce, run the workload tests twice.

The bug is not reproduce-able running individual tests. This is why our CI is less likely to catch these issues.

1. Run the workload tests using the below command to reproduce the same issues as the screenshots above.
2. The first run will not throw failures about dockerd and pod-stress-io. For this to show up as failures, run the workload tests for the second time.

```
crystal run src/cnf-testsuite.cr -- workload
```

## Expected behaviour

Tools installed by the testsuite should not cause test failures

## Proposed solution

* Third-party tools can be moved into a different namespace to avoid causing the issue described in this ticket.
* cluster-tools is already being moved to a `cnf-testsuite` namespace as a part of #1199.

**Comment by agentpoyo** [comment]
@HashNuke 

As we are merging the new Kyverno PRs, we need to ensure Kyverno is also ignoring our cnf-testsuite tools and pods that will cause failures during tests. The new `require_labels` is failing the test based on our own cri-tools, dockerd, etc pods, See Screenshot:

![kyverno_skip_testsuite_tools_pods](https://user-images.githubusercontent.com/14348948/154508135-d6d5920c-f377-40e0-88bd-76db675f5150.png)

**Comment by HashNuke** [comment]
@agentpoyo Sagar asked for some pairing help next week to resolve this and one more thing for the Kyverno tests. I’ll work with him.

**Comment by agentpoyo** [comment]
###  Acceptance Criteria 
---
### Documentation is updated:
- [x] USAGE.md documentation updated
   - [x] how to run
   - [x] Description, remediation and details 
       - [x] what the best practice is
       - [x] why are we testing this
- [ ] CATEGORIES updated

###  Common steps
- [x]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-testsuite/blob/main/KIND-INSTALL.md) will work as well
- [x]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [x]  As a peer reviewer, check that PR passes in GitHub Actions
     - [x] if yes, merge PR to master
     - [x]  if no, make a comment and request that developer make changes to pass tests 
- [x]   As a peer reviewer, Pull down latest version of CNF conformance test code from `main` branch
- [ ]  Run `shards install`

### Update Prerequisite checker
- [ ] NA

### Added to overall points:
- [ ]  I see the test in the embedded points.yml as valid test score

### When I run `workload` I should not see our tools cause FAILURES during test runs and only the CNF results:
- [ ] Run `./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample_coredns/cnf-testsuite.yml`
- [ ] Run `./cnf-testsuite workload`
- [ ] I can see PASS result output for only CoreDNS CNF that is installed, not our other tools.

### Screenshots of output:
- [ ] I can see a screenshots of the test and the kind clusters deleted

**Comment by agentpoyo** [comment]
![1219_output](https://user-images.githubusercontent.com/14348948/160014256-3644afed-44a7-491f-a24c-daa9257a1baf.png)

**Comment by lixuna** [comment]
@HashNuke @agentpoyo  what is the points estimate for this issue (0,1,2,3,5,8,13,21)?

**Comment by HashNuke** [comment]
@lixuna 8pts. I've now added the points to the labels.
