### ISSUE TITLE
[BUG] ClusterTools.local_match_by_image_name should not assume default value for nodes during compile time

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1220]
## Describe the bug

> Found this issue when looking into #1199.

`ClusterTools.local_match_by_image_name` ([link](https://github.com/cncf/cnf-testsuite/blob/c0ad4464f6194fa1105b0fd6546f9ef562d23d3e/src/tasks/utils/cluster_utils.cr#L85)) function is currently assigned the default argument for nodes as the list of nodes available during compile time.

We distribute the testsuite as a binary as a part of the releases and the default value will always be based on the environment where the binary is compiled.

<img width="783" alt="image" src="https://user-images.githubusercontent.com/84005/154080125-7bd9a1dd-fe2e-4629-a41d-9d3a9f41d798.png">

## Expected behaviour

* The nodes in the user's current cluster can be the default value if no nodes are passed in the function argument.
* For the above mentioned behaviour, the default value of the arg can be nil, while the body of the function checks for the nil value and fetches the list of nodes on the current cluster.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

No real way to test specifically, this is passing github actions.
