### ISSUE TITLE
[BUG] Spec test for database_persistence is failing in main branch build

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1221]
## Describe the bug

The below mentioned test is failing in the main branch.

```
'database_persistence' should pass if the cnf uses a database that uses an elastic volume with a stateful set
```

* [Link to failing build](https://github.com/cncf/cnf-testsuite/runs/5191105763?check_suite_focus=true)
* Failing test reference: `spec/workload/state_spec.cr:28`

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/84005/154092058-ed2da2e5-c0a9-4342-9b24-4d2bdb59aae8.png">

## Expected behaviour

Test should pass // Build should be green.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] When I run `LOG_LEVEL=debug crystal spec spec/workload/state_spec.cr:28` I should see the spec test PASS instead of SKIP or FAIL when there is a mysql db present.
- [ ] I can see a screenshot of the output.

**Comment by agentpoyo** [comment]
![1221_pass_db_persistence](https://user-images.githubusercontent.com/14348948/154137301-ad6238a3-b4c1-4dae-9d0d-5181bb9cfaa0.png)

**Comment by agentpoyo** [comment]
@HashNuke points?
