### ISSUE TITLE
[BUG] immutable_configmap --- Does not account for containers that do not have "configMapRef" under "ENV"

### ISSUE THREAD

**Issue by EricLo-417** [cncf/cnf-testsuite#1230]
**Describe the bug**
When checking if all used config maps are immutables, the testsuite looks at volumes and containers.
When checking if a container's config map is immutable it checks for "ENV". If found it will look for "configMapRef" and then use that to find its associated config map. However, in our test case one of our containers have "ENV" but no "configMapRef". This causes the testsuite to check if "null" has the field "immutable", which it does not and this causes the test to fail

**To Reproduce**

1. Run test `immutable_configmap`
2. Make sure you have a container that has an "ENV" but does not have a "configMapRef"

**Expected behavior**
This container should be skipped as it does not have a configMap associated to it

**Comment by wavell** [comment]
@EricLo-417 we will need to you test this one.  We weren't able to make a spec test that replicated your error case

**Comment by EricLo-417** [comment]
I have tested against latest main, and it looks like it is now passing

**Comment by lixuna** [comment]
Thanks, @EricLo-417!
