### ISSUE TITLE
[BUG] elastic_volumes --- False negative is reported when no volumes are found

### ISSUE THREAD

**Issue by EricLo-417** [cncf/cnf-testsuite#1231]
**Describe the bug**
When looking for elastic volumes, if no volumes are found cnf-testsuite reports there are no elastic volumes and fails the test.

**To Reproduce**

1. There should be no volumes in the cnf
2. Run test `elastic_volumes `
3. See error

**Expected behavior**
If no volumes are found this should be skipped or passed.

**Comment by taylor** [comment]
@EricLo-417 you can test with main or the upcoming release

**Comment by taylor** [comment]
https://github.com/cncf/cnf-testsuite/issues/1213

**Comment by taylor** [comment]
https://github.com/cncf/cnf-testsuite/pull/1223
