### ISSUE TITLE
[Documentation] Document current test list with points for pass/fail

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1237]
## Document current test list with points for pass/fail

- [x]  list tests under each category (points file should have this)
    - with point value (if different than default)
        - default= +5, -1
- [x] list which tests are "carrot tests"
- [x] list which tests are marked as "hard required" tests, if any

**Comment by agentpoyo** [comment]
https://hackmd.io/94IKwahBQMOWKcqLoa7Zzw

**Comment by agentpoyo** [comment]
@lixuna @taylor Let me know if the hackmd doc works. I stripped out the rationale quotes and created legend of:  

:heavy_check_mark: = Defended
:carrot: = Carrot Test
:star: = Required Test
