### ISSUE TITLE
[Feature] Running a category test should provide info about the results.yml log on the console output

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1241]
**Is your feature request related to a problem? Please describe.**
When running category tests, eg. `./cnf-testsuite compatibility`, when the tests are complete and the points are provided, the console output should also provide the results yml file location and name ( this happens if you run `workload` or `all`, etc currently ).

**Describe the solution you'd like**
Should see console output of the results file for category tests that are run for easy identification.

**Screenshot that shows no results file location**
<img width="811" alt="compatibility_output" src="https://user-images.githubusercontent.com/14348948/156376575-d16e52ff-b652-457e-8a9c-4c9a3b7a7386.png">

**Comment by wavell** [comment]
Example of results file message
<img width="946" alt="image" src="https://user-images.githubusercontent.com/29548/159553625-94d8c5f1-06bb-4f68-bc5f-5fb69edaec12.png">

**Comment by wavell** [comment]
This is useful when troubleshooting a specific category or test

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] When I run a category test, I should see the console provide information about the results file name and location in the stdout
- [ ] I can see screenshot of the output here

**Comment by agentpoyo** [comment]
![1241_results_output](https://user-images.githubusercontent.com/14348948/174314133-3128815d-9686-462e-9c3e-443d2c3e397c.png)
