### ISSUE TITLE
[Documentation BUG]: Link for rolling-update-replication-controller is broken

### ISSUE THREAD

**Issue by CsatariGergely** [cncf/cnf-testsuite#1243]
**Describe the bug**
In the description of [To test if the CNF can perform a rolling update](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-test-if-the-cnf-can-perform-a-rolling-update) the link to [rolling-update-replication-controller](
https://kubernetes.io/docs/tasks/run-application/rolling-update-replication-controller/) is broken.

**To Reproduce**

1. Go to https://kubernetes.io/docs/tasks/run-application/rolling-update-replication-controller/

**Expected behavior**
Remove the link or add the correct one.

**Screenshots**
N/A

**Device (please complete the following information):**
All

**How will this be tested? aka Acceptance Criteria (optional)**
N/A

**Comment by agentpoyo** [comment]
Looks like they removed the old page. Suitable replacement found at https://kubernetes.io/docs/tutorials/kubernetes-basics/update/update-intro/

**Comment by agentpoyo** [comment]
Acceptance Criteria:

- [ ] When I view [Rolling Update](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-test-if-the-cnf-can-perform-a-rolling-update) test in the USAGE doc, the link takes me to a valid k8s doc detailing rolling updates.

**Comment by taylor** [comment]
@CsatariGergely
