### ISSUE TITLE
[Documentation BUG]: Bugs in "To check if the CNF is compatible with different CNIs"

### ISSUE THREAD

**Issue by CsatariGergely** [cncf/cnf-testsuite#1244]
**Describe the bug**
There are two bugs in the description of "To check if the CNF is compatible with different CNIs"
- CNI is explained as "Cloud Container Interface" however it is "Container Network Interface"
- Link for "https://bit.ly/cni-compatible-k8s-doc" is misformulated

**To Reproduce**

1. Go to https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-the-cnf-is-compatible-with-different-cnis

**Expected behavior**
Fix the typos.

**Screenshots**
N/A

**Device (please complete the following information):**
All

**Comment by agentpoyo** [comment]
> Thanks for reporting these, @CsatariGergely.
> 
> Can you please explain what you mean by "misformulated"
> 
> > Link for "https://bit.ly/cni-compatible-k8s-doc" is misformulated

This was fixed. The markdown was not rendering the link properly.

**Comment by CsatariGergely** [comment]
> Thanks for reporting these, @CsatariGergely.
> 
> Can you please explain what you mean by "misformulated"
> 
> > Link for "https://bit.ly/cni-compatible-k8s-doc" is misformulated

Haha, sorry I just invented a new world for not correctly formulated :)

**Comment by agentpoyo** [comment]
Acceptance Criteria:

- [x] When I view [cni_compatibilty](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-the-cnf-is-compatible-with-different-cnis) test in the USAGE doc, CNI should be described as "Container Network Interface" and the link should not display markdown language for the link.

**Comment by taylor** [comment]
@CsatariGergely
