### ISSUE TITLE
[Feature] Install kyverno/policies repo as one of the tools

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1246]
> This is regarding the new Kyverno tests being integrated as a part of #1182

* Each of the 24 Kyverno tests use a different policy file that is downloaded using the raw GitHub CDN content url.
* The policy files are in the [kyverno/policies](https://github.com/kyverno/policies) repo.
* The testsuite does not require users to provide GitHub credentials for making authenticated calls to GitHub.
* GitHub rate limits are at 60/hr for unauthenticated requests.

Using direct policy urls would impact any user attempting to run full workload tests more than twice within the hour.

## Solution

As a part of the Kyverno install, clone the `kyverno/policies` repo within the tools directory.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Setup or find a k8s cluster (kind, etc)
- [ ] Setup cnf-testsuite
- [ ] Run `./cnf-testsuite install_kyverno`
- [ ] I should see a kyverno directory in the tools/ directory so it's not downloading this every time a test is run that requires kyverno policy and files.

**Comment by agentpoyo** [comment]
![1246_kyverno_tools](https://user-images.githubusercontent.com/14348948/159994973-267f0f16-752e-4b15-99fa-36c833093a48.png)
