### ISSUE TITLE
[Feature] Check for PolicyReport availability instead of sleep

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1247]
> This is regarding the new Kyverno tests being integrated as a part of #1182 and the ones that are already in `main` branch.

Example: The `require_labels` test in `main` branch.

After installing the Kyverno policy (`ClusterPolicy` resource), the current implementation of the test uses `sleep` to wait for 3 seconds before checking for the `PolicyReport` resource.

Instead of using `sleep`, it would be more reliable to wait for resource readiness or check for availability of policy reports.

**Comment by HashNuke** [comment]
Will have to confirm without someone aware of Kyverno about when the ClusterPolicy's state gets marked as ready.
If this happens after generating the policy reports, then this ready state can be used as a reliable way to detect availability of policy reports.

**Comment by agentpoyo** [comment]
No AC required, this is passing and the `sleep 3` has been replaced with a check instead.
