### ISSUE TITLE
[Feature] Add command to run tests that will be included in CNF Certification v1.0.0

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1251]
### Short description: 
- Currently, the test suite supports several commands to run tests, like `workload`, `all`, by category and individually
- For the CNF Certification program, please create a command to run the tests that will be included in the v1.0.0 launch
- This is part of "Instructions on how to run the CNF Test Suite" for CNF Certification program

### To do: 

- [x] Decide on which command will be run for the CNF Certification program, ie. `Certification`, `cert`, `cnf-certification`
- [x] Decide how selected tests will be linked to the CNF Certification command
- [x] Create command
- [x] Assign label/tag/flag/etc to selected tests for CNF Certification

**Comment by taylor** [comment]
Estimate of effort:
- @wavell 5
- @denverwilliams 5 
- @HashNuke 5
- @agentpoyo 5

**Comment by taylor** [comment]
TODO: Add Acceptance Criteria

@wavell @lixuna @agentpoyo

**Comment by wavell** [comment]
## Acceptance criteria
- [ ] `./cnf-testsuite cert`
- [ ] `./cnf-testsuite cnf_setup cnf-config=./example-cnfs/coredns/cnf-testsuite.yml`

**Comment by lixuna** [comment]
@agentpoyo when going through the A/C please check the list of tests that run with `cert` against the cert planning spreadsheet https://docs.google.com/spreadsheets/d/1xOxrXzexUaV-hLnPCT7NgcF6pWVWuVUrsDMXFIc8XXc/edit#gid=972880459. 

Note if any workload tests need to be removed from `cert`
