### ISSUE TITLE
[BUG] GitHub Runners not picking up jobs

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1261]
## Describe the bug
GitHub Actions Runners are not working anymore. Jobs not being picked up by GitHub Actions.

## Solution

The GitHub Runners base image has to be updated.

1. Update the base image in the Dockerfile to `myoung34/github-runner:2.288.1-ubuntu-bionic`
2. Build and push new docker image got github actions runner
3. Update the `create_runners.sh` script to create workers with the new image version
4. Cleanup runners on the worker machines
5. Recreate runners on the worker machines

**Comment by HashNuke** [comment]
Pushed new runner image to DockerHub with the following commands.

```
export IMAGE_NAME="conformance/github-runner:2.288.1"
docker build -t $IMAGE_NAME tools -f tools/github-runner/Dockerfile
docker push $IMAGE_NAME
```

**Comment by agentpoyo** [comment]
No AC required, github runners running now with new image to support updated API.
