### ISSUE TITLE
[Feature] Write script to delete GitHub Actions Runners using GitHub API

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1262]
## Description

The GitHub Runners sometimes require updates when they are stuck and part of the resolution is to delete the GitHub Actions Runners from the repository settings page. This is tedious and requires opening each of the runners page and clicking remove button for the runner.

## Solution

Provide a script to the team to be able to use to easily clean up runners when required.

#### Expected usage for the script

```
GH_USER=TODO \
GH_TOKEN=TODO \
bash tools/github-runner/delete-runners-on-github.sh
```

**Comment by lixuna** [comment]
@HashNuke @agentpoyo @wavell @denverwilliams what is the points estimate for this issue (0,1,2,3,5,8,13,21)?

**Comment by agentpoyo** [comment]
2pts

**Comment by agentpoyo** [comment]
No AC required, this is manually run as script from command line.
