### ISSUE TITLE
[BUG] Container name clashes when creating GitHub Actions Runners

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1263]
## Describe the bug

When creating runners using the `create_runners.sh` script, some runners are not created due to container name clashes. Docker prints an error about this too.

<img width="1790" alt="image" src="https://user-images.githubusercontent.com/84005/157515758-24f20d2b-300c-4c5c-9344-d27f33a42f46.png">

## Solution

When runners are being stopped and cleaned up, also force-delete the docker container to ensure no residue. This update is to be made to the `cleanup_runners.sh` script.

**Comment by agentpoyo** [comment]
No AC required, this is a script run manually from command line.
