### ISSUE TITLE
[Paper] State

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#1269]
We should write a blog on cloud native statefulness (as well as storage methods)

**Comment by lixuna** [comment]
Update: 
- Scope changed from blog post to a white paper

Action items:
- Could be shared with tech writers to create smaller listicles or blog posts
- Could be announced as a product, like "CNCF published a Cloud Native State White Paper"

**Comment by taylor** [comment]
Estimate of effort:  13
- taylor 13
- @wavell 13

**Comment by lixuna** [comment]
https://vmblog.com/archive/2022/05/16/stateful-cnfs.aspx#.Y5JL4ezMJqs
