### ISSUE TITLE
[Workload] Security test: `default_network_policy` using Kyverno

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1271]
## [Workload] Security test: To check for default network policy for each namespace

> Ref: #1182, #1176

#### Details
By default, Kubernetes allows communications across all Pods within a cluster. The NetworkPolicy resource and a CNI plug-in that supports NetworkPolicy must be used to restrict communications.

#### Remediation steps
A default NetworkPolicy should be configured for each Namespace to default deny all ingress and egress traffic to the Pods in the Namespace. Application teams can then configure additional NetworkPolicy resources to allow desired traffic to application Pods from select sources. This policy will create a new NetworkPolicy resource named `default-deny` which will deny all traffic anytime a new Namespace is created.

**Test Category Name**
- Security

**Type of test (static or runtime)**
- runtime

---

### Documentation tasks:
- [ ] Update [installation instructions](https://github.com/cncf/cnf-testsuite/blob/main/install.md) if needed
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-testsuite/blob/main/TEST-CATEGORIES.md) if needed
- [ ] Update [USAGE md](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) if needed
  - [ ] How to run
  - [ ] Description and details
    - [ ] What the best practice is
    - [ ] Why are we testing this
  - [ ] Remediation steps if test does not pass

### QA tasks

Dev Review:

- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes,
  - [ ] move to `Needs Peer Review` column
  - [ ] create Pull Request and follow check list
  - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:

- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes,
  - [ ] move to `Reviewer Approved` column
  - [ ] Approve pull request
- [ ] if no,
  - [ ] document what did not go as expected, including error messages and screenshots (if possible)
  - [ ] Add comment to pull request
  - [ ] request changes to pull request

**Comment by HashNuke** [comment]
The [kyverno policy file](https://github.com/kyverno/policies/blob/main/best-practices/add_network_policy.yaml) isn't a test. It defines and adds a network policy. I don't think we should perform any activity that isn't a test/check.

Will revisit this ticket after discussion with team.

**Comment by HashNuke** [comment]
The Kyverno policy file adds a default network policy to resources in the namespace. It does not check for anything.
Closing this after discussion with the team. There is another Kubescape test that tests similar stuff.

**Comment by agentpoyo** [comment]
### Acceptance Criteria

- [ ] Setup k8s and CNF on a cluster; pulling down latest main (if merged) or branch that supports this new `default_network_policy` test.
- [ ] When I run `workload`, I should see `default_network_policy` test run.
- [ ] When I run `cnf-testsuite default_network_policy`, the test should run with PASS results.
- [ ] I should see results that FAIL when running `default_network_policy` using a bad CNF sample.
- [ ] I can see output or screenshots of the results here.

**Comment by agentpoyo** [comment]
This was removed. No AC.
