### ISSUE TITLE
[Workload] Configuration test `default_namespace` using Kyverno

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1272]
## [Workload] Configuration test: To check if resources of the CNF are not in the default namespace

> Ref: #1182, #1176

#### Details
Kubernetes Namespaces provide a way to segment and isolate cluster resources across multiple applications and users. As a best practice, workloads should be isolated with Namespaces.

#### Remediation steps
Namespaces should be required and the default (empty) Namespace should not be used. This policy validates that Pods specify a Namespace name other than `default`.

**Test Category Name**
- Configuration

**Type of test (static or runtime)**
- runtime

---

### Documentation tasks:
- [ ] Update [installation instructions](https://github.com/cncf/cnf-testsuite/blob/main/install.md) if needed
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-testsuite/blob/main/TEST-CATEGORIES.md) if needed
- [ ] Update [USAGE md](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) if needed
  - [ ] How to run
  - [ ] Description and details
    - [ ] What the best practice is
    - [ ] Why are we testing this
  - [ ] Remediation steps if test does not pass

### QA tasks

Dev Review:

- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes,
  - [ ] move to `Needs Peer Review` column
  - [ ] create Pull Request and follow check list
  - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:

- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes,
  - [ ] move to `Reviewer Approved` column
  - [ ] Approve pull request
- [ ] if no,
  - [ ] document what did not go as expected, including error messages and screenshots (if possible)
  - [ ] Add comment to pull request
  - [ ] request changes to pull request

**Comment by agentpoyo** [comment]
### Acceptance Criteria

- [ ] Setup k8s and CNF on a cluster; pulling down latest main (if merged) or branch that supports this new `default_namespace` test.
- [ ] When I run `workload`, I should see `default_namespace` test run.
- [ ] When I run `cnf-testsuite default_namespace`, the test should run with PASS results.
- [ ] I should see results that FAIL when running `default_namespace` using a bad CNF sample.
- [ ] I can see output or screenshots of the results here.

**Comment by agentpoyo** [comment]
FAILED output:
![1272_default_namespace_FAIL](https://user-images.githubusercontent.com/14348948/162464447-ef8b1a21-659f-4b78-be30-f4531c8c9e73.png)

**Comment by agentpoyo** [comment]
PASS output:
![1272_default_namespace_PASS](https://user-images.githubusercontent.com/14348948/162465859-0a8326a6-6882-4697-99d3-da970b962994.png)

**Comment by agentpoyo** [comment]
Workload output:
![1272_default_namespace_workload](https://user-images.githubusercontent.com/14348948/162466857-aa6bb54f-d8a5-4412-8b10-b9d43e6a70f1.png)
