### ISSUE TITLE
[Workload] Configuration test `latest_tag` using Kyverno

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1273]
## [Workload] Configuration test: To check if Pods in the CNF use images with the latest tag

> Ref: #1182, #1176

#### Details
The `:latest` tag is mutable and can lead to unexpected errors if the image changes. Even when a tag is not specified, the `:latest` tag is used by default.

#### Remediation steps
When specifying container images, always specify a tag and ensure to use an immutable tag that maps to a specific version of an application Pod. Avoid using the `latest` tag, as it is not guaranteed to be always point to the same version of the image.

**Test Category Name**
- Configuration

**Type of test (static or runtime)**
- runtime

---

### Documentation tasks:
- [ ] Update [installation instructions](https://github.com/cncf/cnf-testsuite/blob/main/install.md) if needed
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-testsuite/blob/main/TEST-CATEGORIES.md) if needed
- [ ] Update [USAGE md](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) if needed
  - [ ] How to run
  - [ ] Description and details
    - [ ] What the best practice is
    - [ ] Why are we testing this
  - [ ] Remediation steps if test does not pass

### QA tasks

Dev Review:

- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes,
  - [ ] move to `Needs Peer Review` column
  - [ ] create Pull Request and follow check list
  - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:

- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes,
  - [ ] move to `Reviewer Approved` column
  - [ ] Approve pull request
- [ ] if no,
  - [ ] document what did not go as expected, including error messages and screenshots (if possible)
  - [ ] Add comment to pull request
  - [ ] request changes to pull request

**Comment by agentpoyo** [comment]
### Acceptance Criteria

- [ ] Setup k8s and CNF on a cluster; pulling down latest main (if merged) or branch that supports this new `latest_tag` test.
- [ ] When I run `workload`, I should see `latest_tag` test run.
- [ ] When I run `cnf-testsuite latest_tag`, the test should run with PASS results.
- [ ] I should see results that FAIL when running `latest_tag` using a bad CNF sample.
- [ ] I can see output or screenshots of the results here.

**Comment by agentpoyo** [comment]
FAILED output using bad CNF:
![1273_failed_latesttag](https://user-images.githubusercontent.com/14348948/162456831-f0847002-9edd-4fa9-a645-129d60e18356.png)

**Comment by agentpoyo** [comment]
![1273_workload_latesttag](https://user-images.githubusercontent.com/14348948/162458146-554b3afe-3be3-4b5a-a7a6-cb76825ceda0.png)

**Comment by agentpoyo** [comment]
![1273_PASS_latesttag](https://user-images.githubusercontent.com/14348948/162459882-cc6df267-ceeb-40c1-b883-f54d87e5b2f0.png)
