### ISSUE TITLE
[Workload] Security test `selinux_options` using Kyverno

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1274]
## [Workload] Security test: To check if CNF resources use custom SELinux options that allow privilege escalation

> Ref: #1182, #1176

#### Details
SELinux options can be used to escalate privileges and should not be allowed.

#### Remediation steps
SELinux options can be used to escalate privileges and should not be allowed.
* If the SELinux option `type` is set, it should only be one of the allowed values: `container_t`, `container_init_t`, or `container_kvm_t`.
* SELinux options `user` or `role` should not be set.

**Test Category Name**
- Security

**Type of test (static or runtime)**
- runtime

---

### Documentation tasks:
- [ ] Update [installation instructions](https://github.com/cncf/cnf-testsuite/blob/main/install.md) if needed
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-testsuite/blob/main/TEST-CATEGORIES.md) if needed
- [ ] Update [USAGE md](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) if needed
  - [ ] How to run
  - [ ] Description and details
    - [ ] What the best practice is
    - [ ] Why are we testing this
  - [ ] Remediation steps if test does not pass

### QA tasks

Dev Review:

- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes,
  - [ ] move to `Needs Peer Review` column
  - [ ] create Pull Request and follow check list
  - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:

- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes,
  - [ ] move to `Reviewer Approved` column
  - [ ] Approve pull request
- [ ] if no,
  - [ ] document what did not go as expected, including error messages and screenshots (if possible)
  - [ ] Add comment to pull request
  - [ ] request changes to pull request

**Comment by agentpoyo** [comment]
### Acceptance Criteria

- [ ] Setup k8s and CNF on a cluster; pulling down latest main (if merged) or branch that supports this new `selinux_options` test.
- [ ] When I run `workload`, I should see `selinux_options` test run.
- [ ] When I run `cnf-testsuite selinux_options`, the test should run with PASS results.
- [ ] I should see results that FAIL when running `selinux_options` using a bad CNF sample.
- [ ] I can see output or screenshots of the results here.

**Comment by agentpoyo** [comment]
![1274_pass_selinux](https://user-images.githubusercontent.com/14348948/162454123-0a40962c-debf-43e0-a8d5-e5af7463252b.png)

**Comment by agentpoyo** [comment]
Workload output:
![1274_pass_workload_selinux](https://user-images.githubusercontent.com/14348948/162454433-a070ec39-e138-42f1-8c59-088f94d91e17.png)

**Comment by agentpoyo** [comment]
![1274_failed_selinux](https://user-images.githubusercontent.com/14348948/162456403-57aa8911-eaf9-435b-81e5-02f9ab1a0587.png)
