### ISSUE TITLE
[BUG] list of mandatory PaaS components is not clarified and justified

### ISSUE THREAD

**Issue by CsatariGergely** [cncf/cnf-testsuite#1281]
**Describe the bug**
There are several tests testing for different PaaS components, like
- [To](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-prometheus-is-installed-and-configured-for-the-cnf) check if prometheus is installed and configured for the cnf
- [To](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-logs-and-data-are-being-routed-through-fluentd) check if logs and data are being routed through fluentd
- [To](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-open-metrics-is-being-used-and-or-compatible) check if Open Metrics is being used and or compatible.
- [To](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-tracing-is-being-used-with-jaeger) check if tracing is being used with Jaeger

It is not explained anywhere why these particular tools are tested and why they are mandatory. 

**To Reproduce**

1. Go to https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md
2. Read descriptions
3. See error

**Expected behavior**
Clear explanation why specific PaaS tools are mandated. 

**Screenshots**
N/A

**Device (please complete the following information):**

- All

**Comment by taylor** [comment]
@CsatariGergely These components are not mandatory. The tests are considered indicators of good behaviour, but it is known there are other options. Each of these are bonus tests tests, so if they are not "passed", their is no negative effect.

**Comment by CsatariGergely** [comment]
If I understood correctly bonus test means, that not having these means no extra points, what is a drawback.
