### ISSUE TITLE
[Feature] Create CI Infrastructure for Testing the CNF-Testsuite Against Multiple Platforms.

### ISSUE THREAD

**Issue by denverwilliams** [cncf/cnf-testsuite#1283]
The testsuite currently only runs tests against KIND clusters. We should add support for regularly testing the cnf-testsuite against different platforms, i.e Kubespary, in order to catch bugs and compatibility issues that only affect different platforms.

**Describe the solution you'd like**
Create a separate repo & CI configuration that will create K8s Clusters using Kubespary [k8s-infra](https://github.com/crosscloudci/k8s-infra), then all of cnf-testsuite spec tests aginst it.

**Describe alternatives you've considered**

**How will this be tested? aka Acceptance Criteria (optional) **

(optional: unnecessary for things like some version bumps etc.)

Once this issue is addressed how will the fix be verified?

**Additional context**

**Comment by denverwilliams** [comment]
Repo & CI Configuration created here: https://github.com/cncf/testsuite-infra/blob/master/.github/workflows/actions.yml

**Comment by denverwilliams** [comment]
Working Automated Job Here: https://github.com/cncf/testsuite-infra/actions/runs/1989447704

**Comment by agentpoyo** [comment]
No AC required, CI setup and running now under the testsuite-infra repo:

![1283_ci_infra_setup](https://user-images.githubusercontent.com/14348948/159995318-84d80fd1-3dd2-439c-b9af-332f8a3d41b7.png)

**Comment by lixuna** [comment]
[@agentpoyo](https://github.com/agentpoyo) [@wavell](https://github.com/wavell) [@denverwilliams](https://github.com/denverwilliams) what is the points estimate for this issue (0,1,2,3,5,8,13,21)?

**Comment by agentpoyo** [comment]
8pts
