### ISSUE TITLE
[BUG] typo: 2 tests have the same description: application_credentials and service_account_mapping

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1287]
**Describe the bug**
`application_credentials` and `service_account_mapping` tests both have the same description of "✔️ To check if there are [service accounts that are automatically mapped](https://bit.ly/C0034_service_account_mapping)"

**To Reproduce**

1. [Go to '...'](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-there-are-service-accounts-that-are-automatically-mapped) (application_credentials)
2.  Scroll down to `service_account_mapping`
4. See error - both tests have the same description

**Expected behavior**
- update description for Details for Service Application Credentials
(application_credentials)

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] `application_credentials` and `service_account_mapping` tests should not have the same description in the USAGE doc.

**Comment by lixuna** [comment]
LGTM:

https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-there-are-application-credentials-stored-in-configuration-or-environment-variables

is different than

https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-there-are-service-accounts-that-are-automatically-mapped
