### ISSUE TITLE
[BUG] To keep consistency, all SKIPPED tests should use the ⏭️ emoji in the console output

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1291]
**Describe the bug**
Not all SKIPPED tests should use the ⏭️ emoji in the console output.

**To Reproduce**
Run workload, see results.

**Expected behavior**
SKIPPED test should use the  ⏭️ emoji in the console output. Some still use :x: or have no emoji.

**Screenshots**
![skipped-tests_emoji](https://user-images.githubusercontent.com/14348948/160016364-0c9dee82-36fe-4eb7-ab6f-d95d8be4190e.png)

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] When I run a workload test, all SKIPPED tests should display the ⏭️  emoji to keep the output consistent.

**Comment by agentpoyo** [comment]
✖️  SKIPPED: pod_dns_error docker runtime not found 🗡️💀♻️ 

Still has an X instead of the track forward emoji!

**Comment by agentpoyo** [comment]
✔️ SKIPPED: Pods are not using SELinux options 🔓🔑

Is using a check mark instead of track forward emoji.

**Comment by lixuna** [comment]
Acceptance Criteria

- [x]  When I run a workload test, all SKIPPED tests should display the ⏭️ emoji to keep the output consistent.

or
- [ ]  When I run grep -r SKIPPED * in the cnf-testsuite root source directory, I should see that all references for console output use the 'next track" emoji.

Using the output from MicroK8s in https://github.com/cncf/cnf-testsuite/issues/1403#issuecomment-1111049415, I used Find command and found 12 skipped tests, all 12 skipped tests had the  ⏭️ emoji 

Including the tests listed above: 
- ⏭️  SKIPPED: pod_dns_error docker runtime not found 🗡️💀♻️
- ⏭️  SKIPPED: Pods are not using SELinux options 🔓🔑 
- ⏭️  SKIPPED: Jaeger not configured ⎈🚀

**Comment by taylor** [comment]
@agentpoyo please provide a current run of the tests and the output can be reviewed.

**Comment by taylor** [comment]
nvm.  @lixuna looked at the kind results from #1403.  

The only other thing we could do is look at every test individually to see if they have the skip emoji.
