### ISSUE TITLE
[Feature] Helper to wait for all resources of the CNF to be fully deleted

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1292]
> Noticing random [build failures](https://github.com/cncf/cnf-testsuite/runs/5687307372?check_suite_focus=true#logs) the the WIP kyverno test `default_namespace` (part of #1272)

A pod for the CNF installed for a previous spec test is still in terminating state, and causes the kyverno test to fail in the current spec test. Resources still in terminating state are not detected by Kyverno, and result in failures of the subsequent spec test for the default_namespace test.

#### kubectl & helm wait options

Helm uninstall wait option and kubectl delete wait options, do not wait for child resources (example: pods under a deployment) to be fully deleted.

####  sleep(3)

Tried adding `sleep(3)` and it looks like the resources take more than 3 seconds to 

## Possible solution: Write a custom helper to wait for deletion

* The output from kubectl JSON does not clearly indicate when a resource is in a terminating state. (`.state.phase` still says running when the human readable output says terminating.)
* On the other hand, the human-readable output from `kubectl get` can be used to check for terminating resources.

**Here are possiblies for the helper:**
1. Use the output from `kubectl get all -A` to check if any resources are still in terminating state.
2. Use the `app.kubernetes.io/name` and `app.kubernetes.io/instance` labels to lookup if any resources of the CNF still exist.

[1] seems to be the easiest approach given that this helper is only required for a spec tests and is not likely to be used in the testsuite itself.

**Comment by agentpoyo** [comment]
No AC necessary, no real way to test this directly.
