### ISSUE TITLE
[BUG] GitHub Actions runners are not working

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1296]
## Describe the bug
The runners are idle and there are jobs pending for about 2 days now.
Most likely that the runner image has to be updated.

## Solution
1. Update runner image to `myoung34/github-runner:2.289.1-ubuntu-bionic`
2. Cleanup runners
3. Remove runners from GitHub Actions
4. Recreate runners

**Comment by agentpoyo** [comment]
No AC required, you can see the runners working on the actions page.
