### ISSUE TITLE
[BUG] Incorrect description for `shared_database` test in code

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1298]
**Describe the bug**
In https://github.com/cncf/cnf-testsuite/blob/v0.27.0/src/tasks/workload/microservice.cr#L19, Description for shared_database test currently says 
> desc "Does the CNF have a reasonable startup time (< 30 seconds)?"
> task "shared_database","

This is a duplicate (copy/paste) description from another test, called reasonable_startup_time, in https://github.com/cncf/cnf-testsuite/blob/v0.27.0/src/tasks/workload/microservice.cr#L183

**Expected behavior**
- update the description in [line 19](https://github.com/cncf/cnf-testsuite/blob/v0.27.0/src/tasks/workload/microservice.cr#L19) to be specific to the "shared_database" test
- ex. Does the CNF share a database with another CNF?

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] When I view src/tasks/workload/microservice.cr for the shared_database description, it should be unique and not use the same description for the "reasonable_startup_time" test description.

**Comment by lixuna** [comment]
LGTM 

https://github.com/cncf/cnf-testsuite/blob/main/src/tasks/workload/microservice.cr#L19

![Screen Shot 2022-05-05 at 3 55 59 PM](https://user-images.githubusercontent.com/11701267/167024108-fb1fec4b-04c4-4da4-a61b-c626da7d1c69.png)
