### ISSUE TITLE
[BUG] `platform:helm_tiller` test should be moved to the platform category in the USAGE.md

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1299]
**Describe the bug**
- The `platform:helm_tiller` test is currently listed in the workload tests, under Security Category
- see https://github.com/cncf/cnf-testsuite/blob/v0.27.0/USAGE.md#heavy_check_mark-to-check-if-containers-are-using-any-tiller-images

**Expected behavior**
- Move this test to https://github.com/cncf/cnf-testsuite/blob/v0.27.0/USAGE.md#platform-tests

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] When I view the USAGE doc, I should find that platform:helm_tiller is under the Platform section of the documentation and not workload.
