### ISSUE TITLE
[Feature] Document cnf-testsuite.yml fields and possible values

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1305]
The keys and values for `cnf-testsuite.yml` config file should be documented for reference. This would help any user explore options available to configure for their CNF to be tested.

For example: `white_list_container_names` option is being read in the `privileged` test, but I did not find any mention of it in the usage docs or elsewhere in the repo.

**Comment by agentpoyo** [comment]
@HashNuke it was updated to AllowList for the config. The code likely needs to be updated but perhaps kept for white_list for backwards compatibility?

@wavell @denverwilliams any ideas?

**Comment by taylor** [comment]
@HashNuke

**Comment by HashNuke** [comment]
Closing this in favour of #680.
