### ISSUE TITLE
[Documentation] Create List of Tests Document for Releases

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1306]
**Is your feature request related to a problem? Please describe.**
Create a new document that lists all tests for each release (when it was added) and other information.

**Describe the solution you'd like**
New document.

**Comment by lixuna** [comment]
A/C:

- [x] https://github.com/cncf/cnf-testsuite/blob/main/docs/LIST_OF_TESTS.md
- [x] check that links to code are added to each test, add if needed
- [ ] check that expectation and what's tested is added to each test

**Comment by lixuna** [comment]
To do: replace TBDs with content, make sure 0.28 tests are listed

**Comment by lixuna** [comment]
I created a follow up ticket to fill in the missing content https://github.com/cncf/cnf-testsuite/issues/1370
