### ISSUE TITLE
[BUG] Difference between test results when running compiled version of a tag vs GitHub release

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1309]
## Describe the bug
> Found this when debugging #1308

Running workload tests does seem to have a difference between GitHub release and a build compiled for the specific version tag. Happens for both 0.26 and 0.27.

Used the `sample-cnfs/sample_coredns` sample cnf for the below tests.

**v0.27.0**
* Compiled from source: `179 / 286`
  * 1st repeat run: `189 / 281`
  * 2nd repeat run: `189 / 281`
* GitHub release: `189 / 281`
  * 1st repeat run: `189 / 281`
  * Total tests: 55

**v0.26.0**
* Compiled from source: `134 / 271`
  * 1st repeat run (new cluster): `156 / 266`
  * 2nd repeat run: `150 / 266`
* GitHub release: `156 / 266`
  * 1st repeat run: `156 / 266`
  * 2nd repeat run: `150 / 266`
  * 3nd repeat run: `150 / 266`
  * 4th repeat run (new kind cluster):  `150 / 266`
  * Total tests: 52

## Expected behaviour

The maximum points and test score should be the same for a version of the testsuite. Whether the testsuite binary is the github release or downloaded from source should not matter.

## Steps to reproduce

Run the cnf-testsuite for the `sample_coredns` sample cnf for 0.27 and 0.26 tags of the cnf.

#### v0.27.0 compiled from source
```
git checkout v0.27.0
crystal build src/cnf-testsuite.cr
./cnf-testsuite setup

./cnf-testsuite cnf_setup cnf-config=../cnf-testsuite/sample-cnfs/sample_coredns
./cnf-testsuite workload
```

<img width="1023" alt="CleanShot 2022-04-05 at 11 09 14@2x" src="https://user-images.githubusercontent.com/84005/161733198-1d44cc0a-c676-442a-8104-2e9a85e360b1.png">

#### v0.27.0 GitHub release
```
mkdir v27 && cd v27
wget https://github.com/cncf/cnf-testsuite/releases/download/v0.27.0/cnf-testsuite-v0.27.0.tar.gz
tar zxvf cnf-testsuite-v0.27.0.tar.gz
export OLDPATH=$PATH; export PATH=$PATH:$(pwd)

./cnf-testsuite setup
./cnf-testsuite cnf_setup cnf-config=../cnf-testsuite/sample-cnfs/sample_coredns
./cnf-testsuite workload
```

<img width="1036" alt="CleanShot 2022-04-05 at 15 30 10@2x" src="https://user-images.githubusercontent.com/84005/161733243-0facc35b-dd0b-458a-87cb-a6a1d7263cf8.png">

#### v0.26.0 compiled from source
```
git checkout v0.27.0
crystal build src/cnf-testsuite.cr
./cnf-testsuite setup

./cnf-testsuite cnf_setup cnf-config=../cnf-testsuite/sample-cnfs/sample_coredns
./cnf-testsuite workload
```

<img width="1048" alt="CleanShot 2022-04-05 at 12 47 21@2x" src="https://user-images.githubusercontent.com/84005/161733279-65659101-9aaf-4a3c-9710-61c77c510569.png">

#### v0.26.0 GitHub release
```
mkdir v26 && cd v26
wget https://github.com/cncf/cnf-testsuite/releases/download/v0.26.0/cnf-testsuite-v0.26.0.tar.gz
tar zxvf cnf-testsuite-v0.26.0.tar.gz
export OLDPATH=$PATH; export PATH=$PATH:$(pwd)

./cnf-testsuite setup
./cnf-testsuite cnf_setup cnf-config=../cnf-testsuite/sample-cnfs/sample_coredns
./cnf-testsuite workload
```

<img width="1011" alt="CleanShot 2022-04-05 at 15 03 30@2x" src="https://user-images.githubusercontent.com/84005/161733331-6be4b835-a9e7-4e7f-b4d5-a9f2664ff4ea.png">

**Comment by HashNuke** [comment]
Updating the ticket description with outputs of repeat runs to confirm the issue.

**Comment by HashNuke** [comment]
Ruby snippet to help with parsing test results file and comparing two results files. Run this in the `irb` console.

```ruby
require "yaml"
def parse_results(file)
  YAML.load_file(file)["items"].map {|t| t["name"]}.sort
end

x = parse_results("results1.yml")
y = parse_results("results2.yml")

puts(x - y)
```

**Comment by HashNuke** [comment]
Multiple issues resolved in separate tickets. Moving to peer review to close.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Setup the latest release v0.28.1 source:
```
git checkout v0.28.0
crystal build src/cnf-testsuite.cr
./cnf-testsuite setup

./cnf-testsuite cnf_setup cnf-config=../cnf-testsuite/sample-cnfs/sample_coredns
./cnf-testsuite workload
```
And compare the workload output the binary download:
```
mkdir v28.1 && cd v28.1
wget https://github.com/cncf/cnf-testsuite/releases/download/v0.28.1/cnf-testsuite-v0.28.1.tar.gz
tar zxvf cnf-testsuite-v0.28.1.tar.gz
export OLDPATH=$PATH; export PATH=$PATH:$(pwd)

./cnf-testsuite setup
./cnf-testsuite cnf_setup cnf-config=../cnf-testsuite/sample-cnfs/sample_coredns
./cnf-testsuite workload
```

- [ ] I should see that both have the same number of tests and total scores tallied.

**Comment by agentpoyo** [comment]
v0.28.1 source workload results:
![v0 28 1 workload_source](https://user-images.githubusercontent.com/14348948/164565126-d1b71406-128c-402f-b560-489b786fd43d.png)

**Comment by agentpoyo** [comment]
![v0 28 1 workload_binary](https://user-images.githubusercontent.com/14348948/164568335-4eaee67f-5e7c-46d4-9634-de782622a76b.png)

Both source and binary resulted in same total points available. The binary failed the CNI compatible which the admin.yml used could not be pulled down, likely since this is using a newer helm version and the file did not exist already from a previous run using helm v3.1.1, will open a bug on more findings to reproduce.
