### ISSUE TITLE
[BUG] Workload tests writes two results files

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1310]
## Describe the bug
Running workload tests results in two results files. One of them is barebones and looks like below:

<img width="1067" alt="CleanShot 2022-04-05 at 20 51 48@2x" src="https://user-images.githubusercontent.com/84005/161788533-206df12b-8a11-496f-a199-04df93c218ea.png">

Only verified the behaviour for workload tests. Have not verified if this same behaviour exists when running platform tests or all tests.

## To Reproduce
Install a CNF and run workload tests.

```
./cnf-testsuite workload
```

## Expected behaviour

Anytime workload tests are run, there should only be one results file per test run.

**Comment by agentpoyo** [comment]
> @HashNuke @agentpoyo what is the status of this issue please?

Still needs verification and peer review.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Setup k8s cluster or use existing one.
- [ ] Setup a sample or other CNF with cnf_setup and then cnf-config
- [ ] I should not see any empty results file created in results/ directory.
- [ ] When I run `workload` against my CNF, I should only see a single results file generated and appended during the workload run.

**Comment by agentpoyo** [comment]
```
pair@cnfdev4:~/workspace/drew/cnf-testsuite$ ls -al results/
total 16
drwxrwxr-x  2 pair pair 12288 Oct 26 15:40 .
drwxrwxr-x 17 pair pair  4096 Oct 26 15:45 ..
```
Now run workload:
```
pair@cnfdev4:~/workspace/drew/cnf-testsuite$ ./cnf-testsuite workload                                                       │total 20
Successfully created directories for cnf-testsuite                                                                          │drwxrwxr-x  2 pair pair 12288 Oct 26 15:45 .
✔️  PASSED: Helm Chart exported_chart Lint Passed ⎈📝☑️                                                                       │drwxrwxr-x 17 pair pair  4096 Oct 26 15:45 ..
✔️  PASSED: Published Helm Chart Found ⎈📦🌐                                                                                 │-rw-r--r--  1 pair pair   391 Oct 26 15:46 cnf-testsuite-results-20231026-154558-61
✔️  PASSED: Helm deploy successful ⎈🚀 
...
```
Now you only see one results file generated:
```
pair@cnfdev4:~/workspace/drew/cnf-testsuite$ ls -al results/
total 20
drwxrwxr-x  2 pair pair 12288 Oct 26 15:45 .
drwxrwxr-x 17 pair pair  4096 Oct 26 15:45 ..
-rw-r--r--  1 pair pair   391 Oct 26 15:46 cnf-testsuite-results-20231026-154558-617.yml
```
