### ISSUE TITLE
[Feature] combine cert scoring for (increase_decrease_capacity) test 

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1314]
**Is your feature request related to a problem? Please describe.**
- for cert, increase_decrease_capacity will be considered as one test
- increase_decrease_capacity will be test type: essential

**Describe the solution you'd like**
- if a CNF passes the entire process, it gets the Essential score
- if a CNF fails any part of the process, it gets the Essential penalty

**Comment by lixuna** [comment]
level of effort: 

@wavell 3 pts
@taylor 3 pts
@agentpoyo 3 pts
@denverwilliams 3 pts

**Comment by lixuna** [comment]
A/C needs work:

Preliminary results, using https://github.com/cncf/cnf-testsuite/issues/1365#issuecomment-1119006922 

It appears that increase and decrease are running as one test, test results show as: 
✔️  PASSED: Replicas increased to 3 and decreased to 1 📦📉                                                                                                                                                                        


I cannot tell if they are "counted" as separate tests, given the calculation error for the test category: 
"Compatibility, installability, and upgradeability results: 115 of 11 tests passed"

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] When I run `cert`, I see that both increase and decrease capacity are combined and their points are combined.
- [ ] I can see results here (screenshot and results file output)

**Comment by agentpoyo** [comment]
```
- name: increase_decrease_capacity                   
  status: passed                                                                                                                
  points: 100 
```
![1314_increase_decrease](https://user-images.githubusercontent.com/14348948/167214779-82dcf314-864c-4264-9f80-d73795ffa8ab.png)
