### ISSUE TITLE
[BUG] `shared_database` should be run when microservice category is run

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1323]
## Describe the bug
* `shared_database` is currently not a dependency of the `microservice` category test. As a result the test is not run when the microservice category is run.
* The possible pass score for the test is already included in the total for the microservice category. But since the test is not run, it would not be possible to score points for this test.

## To Reproduce
Run workload tests with `./cnf-testsuite workload`. Screenshot below shows the results of the tests in the microservice category. Does not include `shared_database`.

<img width="691" alt="CleanShot 2022-04-07 at 19 42 48@2x" src="https://user-images.githubusercontent.com/84005/162219532-622bd062-dfe3-4a1a-a158-a9b1ce7014eb.png">

## Expected behavior
When the workload tests are run, shared_database test should be run in the microservice category.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Setup CNF using sample-coredns
- [ ] When I run `./cnf-testsuite microservice`, I should see that the `shared_database` test runs within this category.
- [ ] When I run `./cnf-testsuite workload`, I should see that the `shared_database` test runs during `workload` test.
- [ ] I can see screenshot output of each in this issue.

**Comment by agentpoyo** [comment]
![1323_shared_db_microservice_workload](https://user-images.githubusercontent.com/14348948/164326950-08a3c402-9562-44d4-a001-c97da14a3c8f.png)

**Comment by agentpoyo** [comment]
![1323_shared_db_microservice](https://user-images.githubusercontent.com/14348948/164327099-85efca7b-6157-41c9-86f0-903065632f4a.png)
