### ISSUE TITLE
[BUG] `versioned_tag` should be run when the configuration category test is run

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1324]
## Describe the bug
* `versioned_tag` is not a dependency of `configuration` category test and as a result the test is not run.
* The possible pass score for the test is already included in the total for the configuration category. But since the test is not run, it would not be possible to score points for this test.

## To Reproduce
Run the workload tests with the command `./cnf-testsuite workload`. Screenshot below shows the results of the configuration tests that are run as a part of workload.
<img width="1291" alt="CleanShot 2022-04-07 at 19 54 17@2x" src="https://user-images.githubusercontent.com/84005/162221986-43f117a5-6653-4288-b6e6-5e19f22c1150.png">

## Expected behavior
`versioned_tag` test should be run when the `workload` task or the `configuration` tasks are run.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Setup CNF using sample-coredns
- [ ] When I run `./cnf-testsuite configuration`, I should see that the `versioned_tag` test runs within this category.
- [ ] When I run `./cnf-testsuite workload`, I should see that the `versioned_tag` test runs during `workload` test under the configuration category.
- [ ] I can see screenshot output of each in this issue.

**Comment by agentpoyo** [comment]
![versioned_tag_workload_output](https://user-images.githubusercontent.com/14348948/164325588-02f30018-158a-4b79-a11f-a6b0278c55f6.png)

**Comment by agentpoyo** [comment]
![versioned_tag_config_output](https://user-images.githubusercontent.com/14348948/164325695-d041425f-03e6-4636-acc3-01e8916a50f6.png)
