### ISSUE TITLE
[BUG] `host_network` test should be run when security workload tests are run

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1325]
## Describe the bug
When the `security` category is run or `workload` tests are run, the `host_network` test is not run. This is due to the `host_network` test not being a dependency of the security task.

## To Reproduce
Run the workload tests with the ./cnf-testsuite workload` command.

## Expected behavior
The `host_network` test should be run when the workload security tests are run.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Setup CNF using sample-coredns
- [ ] When I run `./cnf-testsuite security`, I should see that the `host_network` test runs within this category.
- [ ] When I run `./cnf-testsuite workload`, I should see that the `host_network` test runs during `workload` test under the security category.
- [ ] I can see screenshot output of each in this issue.

**Comment by agentpoyo** [comment]
![host_network_workload](https://user-images.githubusercontent.com/14348948/164318656-3c4d779b-8c78-48e0-bd0d-aa25decd5043.png)

**Comment by agentpoyo** [comment]
![host_network_1325](https://user-images.githubusercontent.com/14348948/164325442-390c99b2-b394-4378-82f1-e489f50e3b4c.png)
