### ISSUE TITLE
[BUG] `service_account_mapping` should be run when workload security test category is run

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1326]
## Describe the bug
When the `security` category is run or `workload` tests are run, the `service_account_mapping` test is not run. This is due to the `service_account_mapping` test not being a dependency of the security task.

## To Reproduce
Run the workload tests with the `./cnf-testsuite workload` command.

## Expected behavior
The `service_account_mapping` test should be run when the workload security tests are run.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [x] Setup CNF using sample-coredns
- [x] When I run `./cnf-testsuite security`, I should see that the `service_account_mapping` test runs within this category.
- [x] When I run `./cnf-testsuite workload`, I should see that the `service_account_mapping` test runs during `workload` test under the configuration category.
- [x] I can see screenshot output of each in this issue.

**Comment by agentpoyo** [comment]
![srevice_accounts_mapped](https://user-images.githubusercontent.com/14348948/164333172-abcdca03-fb79-4e8c-9891-e7a475ef1a16.png)

**Comment by agentpoyo** [comment]
![srevice_accounts_mapped_workload](https://user-images.githubusercontent.com/14348948/164333293-2c956fe9-7917-4847-8e27-2792b92d22fd.png)
