### ISSUE TITLE
[BUG] `application_credentials` should be run when workload security test category is run

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1329]
## Describe the bug
When the `security` category is run or `workload` tests are run, the `application_credentials` test is not run. This is due to the `application_credentials` test not being a dependency of the security task.

## To Reproduce
Run the workload tests with the `./cnf-testsuite workload` command.

## Expected behavior
The `application_credentials` test should be run when the workload security tests are run.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Setup CNF using sample-coredns
- [ ] When I run `./cnf-testsuite security`, I should see that the `application_credentials` test runs within the security category.
- [ ] When I run `./cnf-testsuite workload`, I should see that the `application_credentials` test runs during `workload` test under the resilience category.
- [ ] I can see screenshot output of each in this issue.

**Comment by agentpoyo** [comment]
![application_creds](https://user-images.githubusercontent.com/14348948/164560682-6fc6b4ef-718b-46fd-bb59-8efb7a879bae.png)

**Comment by agentpoyo** [comment]
![application_creds_workload](https://user-images.githubusercontent.com/14348948/164560798-45f874fe-1b77-4bdb-8155-78c8d1a4c105.png)
