### ISSUE TITLE
[BUG] `pod_network_duplication` should be run when workload resilience test category is run

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1330]
## Describe the bug
When the `resilience` category is run or `workload` tests are run, the `pod_network_duplication ` test is not run. This is due to the `pod_network_duplication ` test not being a dependency of the resilience task.

## To Reproduce
Run the workload tests with the `./cnf-testsuite workload` command.

## Expected behavior
The `pod_network_duplication` test should be run when the workload security tests are run.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Setup CNF using sample-coredns
- [ ] When I run `./cnf-testsuite resilience`, I should see that the `pod_network_duplication` test runs within this category.
- [ ] When I run `./cnf-testsuite workload`, I should see that the `shared_database` test runs during `workload` test under the resilience category.
- [ ] I can see screenshot output of each in this issue.

**Comment by agentpoyo** [comment]
![1331_liveness_readiness](https://user-images.githubusercontent.com/14348948/164318320-f0af51b7-6bca-4af4-b820-b6da1e6a6a10.png)

**Comment by agentpoyo** [comment]
![1331_liveness_readiness_workload](https://user-images.githubusercontent.com/14348948/164318361-ec62d8ac-8589-4282-936d-220fa4dccd7d.png)
