### ISSUE TITLE
[BUG] `liveness` and `readiness` tests are not run when the workload resilience tests are run

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1331]
## Describe the bug
* When the `resilience` category is run or `workload` tests are run, the `liveness` and `readiness` tests are not run.
* This is due to the `liveness` and `readiness` tests not being a dependency of the `resilience` task.

## To Reproduce
Run the workload tests with the `./cnf-testsuite workload` command.

## Expected behavior
The `liveness` and `readiness` tests should be run when the workload security tests are run.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Setup CNF using sample-coredns
- [ ] When I run `./cnf-testsuite resilience`, I should see that the `liveness` test runs within this category.
- [ ] When I run `./cnf-testsuite resilience`, I should see that the `readiness` test runs within this category.
- [ ] When I run `./cnf-testsuite workload`, I should see that the both `readiness` and `liveness` test runs during `workload` test under the resilience category.
- [ ] I can see screenshot output of each in this issue.

**Comment by agentpoyo** [comment]
![1331_liveness_readiness](https://user-images.githubusercontent.com/14348948/164309895-d1067da8-bb15-427e-8712-b5ee3630ad41.png)

**Comment by agentpoyo** [comment]
![1331_liveness_readiness_workload](https://user-images.githubusercontent.com/14348948/164318223-c5d5de2a-2f2d-4d29-be0f-850a73e57c6d.png)
