### ISSUE TITLE
[BUG] remove the word `destructive` from `reasonable_startup_time destructive`

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1332]
**Describe the bug**
- reasonable_startup_time test is not destructive
- remove the word destructive from [USAGE](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-the-cnf-have-a-reasonable-startup-time)

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] When I view reasonable startup time in USAGE.md, I do not find the word `destructive` next to the test command.

**Comment by lixuna** [comment]
LGTM, the word `destructive` has been removed from this test command

https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-the-cnf-have-a-reasonable-startup-time

![Screen Shot 2022-05-05 at 4 42 02 PM](https://user-images.githubusercontent.com/11701267/167030412-80e7d5b2-4f49-497d-9449-f93eba1ec930.png)
