### ISSUE TITLE
[Feature] `selinux_options` test should only be applicable when selinux is enabled

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1333]
## Description

`selinux_options` test should only be run when selinux is enabled.

## Expected behaviour

If SELinux is not enabled, then the `selinux_options` test should be skipped.

**Comment by HashNuke** [comment]
I think the points.cr has to be updated to consider N/A tasks in the `total_max_points` function. It does not consider any N/A status.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Setup CNF with k8s cluster along with cnf-testsuite.
- [ ] Setup CNF `./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample_nonroot`
- [ ] When I run `./cnf-testsuite selinux_options`, I should see SKIPPED when using a CNF that does not have selinux enabled.
- [ ] I can see screenshots below of SKIPPED results.
- [ ] Setup CNF `./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample_valid_selinux_options`
- [ ] When I run `./cnf-testsuite selinux_options`, I should see PASS results when using a CNF with selinux enabled but not options that enable privilege escalations.
- [ ] I can see a screenshot of the PASS results.
- [ ] Setup CNF `./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample_latest_tag`
- [ ] When I run `./cnf-testsuite selinux_options`, I should see FAILED results when using a CNF with selinux enabled and options that allow privilege escalations.
- [ ] I can see screenshot of FAILED results.

**Comment by agentpoyo** [comment]
![1333_skipped](https://user-images.githubusercontent.com/14348948/164546085-e30efad0-03be-4b8b-94fa-60eb9bd44b4f.png)

**Comment by agentpoyo** [comment]
![1333_passed](https://user-images.githubusercontent.com/14348948/164546405-7eca83b0-78d9-4616-b21a-dc5f57db21a9.png)
