### ISSUE TITLE
[BUG] shared_database test causes failure of "Test binary without source (all)" test in the CI

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1342]
## Describe the bug

> Related to #1323

After `shared_database` test was added as a dependency of the workload tests to resolve Issue-1323, the [*"Test binary without source (all)"* test in the CI build](https://github.com/cncf/cnf-testsuite/runs/5872181630?check_suite_focus=true) is failing (screenshot below).

<img width="1161" alt="CleanShot 2022-04-08 at 14 42 42@2x" src="https://user-images.githubusercontent.com/84005/162404987-4aed60ce-8599-4ccd-a465-6a3f229200f5.png">

## To Reproduce

Check [build link](https://github.com/cncf/cnf-testsuite/runs/5872181630?check_suite_focus=true).

**Comment by HashNuke** [comment]
#### What was happening

The `shared_database` test was attempting to run the test even when there were no MariaDB images being used by any of the containers.

#### Changes made in the `bug/1308` branch to resolve this

* I've added a code snippet to detect this scenario and skip the test.
* Also added a spec test for this scenario.

**Comment by agentpoyo** [comment]
No AC required, this was a fix for CI spec tests that are now running.
