### ISSUE TITLE
[Feature] Rationale is needed for new tests in the Security category

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1345]
**Is your feature request related to a problem? Please describe.**
- Rationale is needed for new tests in the Security category

**Describe the solution you'd like**
Add rationale details to https://github.com/cncf/cnf-testsuite/blob/main/RATIONALE.md and link to/from USAGE.md for:
- [x] https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-a-cnf-is-using-container-socket-mounts
- [x] https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-any-pods-in-the-cnf-use-sysctls-with-restricted-values
- [x] https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-a-cnf-is-running-services-with-external-ips
- [x] https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-there-are-service-accounts-that-are-automatically-mapped
- [x] https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-cnf-resources-use-custom-selinux-options-that-allow-privilege-escalation

**Comment by agentpoyo** [comment]
Verifying this now as these should have been addressed in other documentation issues.

**Comment by agentpoyo** [comment]
Verified that all these are now in RATIONALE with descriptions.
