### ISSUE TITLE
[Feature] Rationale is needed for new tests in the Configuration category 

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1346]
**Is your feature request related to a problem? Please describe.**
- Rationale is needed for new tests in the Configuration category

**Describe the solution you'd like**
Add rationale details to https://github.com/cncf/cnf-testsuite/blob/main/RATIONALE.md and link to/from USAGE.md for:
- [x] https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-resources-of-the-cnf-are-not-in-the-default-namespace
- [x] https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-pods-are-using-the-appkubernetesioname-label
- [x] https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-test-if-there-are-versioned-tags-on-all-images-using-opa-gatekeeper should go to https://github.com/cncf/cnf-testsuite/blob/main/RATIONALE.md#to-test-if-there-are-versioned-tags-on-all-images-using-opa-gatekeeper
- [x] https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-test-if-there-are-any-non-declarative-hardcoded-ip-addresses-or-subnet-masks
- [x] https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-test-if-the-cnf-crashes-when-pod-dns-error-occurs

**Comment by agentpoyo** [comment]
Verifying, likely addressed in other documentation issues that have been worked and reviewed already.

**Comment by agentpoyo** [comment]
Verified that all these are now in RATIONALE with descriptions.
