### ISSUE TITLE
[BUG] Category for `pod_dns_error` should be `resilience` in points.yml

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1353]
**Describe the bug**
Category for `pod_dns_error` is marked as `pod_dns_error` in the `points.yml`. It should be `resilience` according to the source code.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] I can view the embedded points.yml and see that `pod_dns_error` is marked as resilience in the file.

**Comment by agentpoyo** [comment]
https://github.com/cncf/cnf-testsuite/blob/6b83f9d0506f5390d83891ff8e903ba6273d39f4/embedded_files/points.yml#L85
