### ISSUE TITLE
[Documentation]Add a list of supported runtimes to prereqs in INSTALL

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1366]
**Is your feature request related to a problem? Please describe.**
https://github.com/cncf/cnf-testsuite/blob/main/INSTALL.md#pre-requisites does not list runtimes that are supported by the CNF Test Suite

**Describe the solution you'd like**
- Add supported runtimes to https://github.com/cncf/cnf-testsuite/blob/main/INSTALL.md#pre-requisites

**Comment by taylor** [comment]
@wavell Is dockerd the only runtime supported?  That is all that is listed

dockerd support has been removed from K8s as of v1.24.0

**Comment by agentpoyo** [comment]
> @wavell Is dockerd the only runtime supported? That is all that is listed
> 
> dockerd support has been removed from K8s as of v1.24.0

We only support containerd for the cnf-testsuite.

**Comment by taylor** [comment]
@agentpoyo @wavell that should be added to the prereqs.  Docker is for a single test that runs on the workstation. This ticket is about documenting the supported runtimes for testing. As far as I knew, and what you say, that is only containerd.  The runtime containerd is not in the prereq.

**Comment by taylor** [comment]
@wavell @denverwilliams I see it is there but not as visible. PR #1444 makes it more visible
