### ISSUE TITLE
[Documentation] Document cert instructions: how to run test suite for cert

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1369]
### Instructions for CNF Certification 

**Describe the solution you'd like**
- How to run the test suite for cert
- How to submit results see #1378
- How to review results

DRAFT: for landing page
- TBD: https://www.cncf.io/certification/cnf-conformance/

Draft for GitHub repo > https://github.com/cncf/cnf-conformance/blob/main/instructions.md)
- based on https://github.com/cncf/k8s-conformance/blob/master/instructions.md#how-to-submit-conformance-results

**Comment by lixuna** [comment]
DRAFTs started in https://hackmd.io/Xt_FW9u0QPmtgR1z5YF08g?both

**Comment by taylor** [comment]
Estimate of effort: 
- taylor 5
- @lixuna 5
- @denverwilliams 5
- @wavell 5
- @HashNuke 5 
- @agentpoyo 5

**Comment by lixuna** [comment]
https://github.com/cncf/cnf-conformance/blob/main/instructions.md

**Comment by lixuna** [comment]
@denverwilliams ready for peer review 

Content at https://github.com/cncf/cnf-conformance/blob/main/instructions.md

**Comment by denverwilliams** [comment]
QA'ed steps & commands:

```
kind create cluster --name testk8s --kubeconfig ./admin.conf
export KUBECONFIG=$(pwd)/admin.conf
wget https://github.com/cncf/cnf-testsuite/releases/download/v0.29.0/cnf-testsuite-v0.29.0.tar.gz
./cnf-testsuite setup
./cnf-testsuite cnf_setup cnf-config=./cnf-testsuite.yml
./cnf-testsuite cert
```

Results:
```

**Comment by lixuna** [comment]
@denverwilliams I noticed that Configuration Tests says 5 of 11 tests passed, but only 8 tests seem to be displayed:

✔️  PASSED: NodePort is not used
✔️  🏆 PASSED: HostPort is not used
✔️  🏆 PASSED: No hard-coded IP addresses found in the runtime K8s configuration
No Secret Volumes or Container secretKeyRefs found for resource: {kind: "Deployment", name: "coredns-coredns", namespace: "default"}
⏭  SKIPPED: Secrets not used 🧫
✖️  FAILED: Found mutable configmap(s) ⚖️
✔️  PASSED: Pods have the app.kubernetes.io/name label 🏷️✔️
✔️  🏆 PASSED: Container images are not using the latest tag 🏷️✔️
✖️  FAILED: Resources are created in the default namespace 🏷️❌

Configuration results: 5 of 11 tests passed

**Comment by lixuna** [comment]
@denverwilliams do you know why this test below has `
^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[A^[[A^[[A^[[A^[[A^[[A^[[A`?

`^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[A^[[A^[[A^[[A^[[A^[[A^[[A✔️  PASSED: disk_fill chaos test passed 🗡️💀♻️`

Reliability, Resilience, and Availability Tests
✔️  PASSED: pod_network_latency chaos test passed 🗡️💀♻️
✔️  PASSED: pod_network_corruption chaos test passed 🗡️💀♻️
^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[A^[[A^[[A^[[A^[[A^[[A^[[A✔️  PASSED: disk_fill chaos test passed 🗡️💀♻️
✔️  PASSED: pod_delete chaos test passed 🗡️💀♻️
✔️  PASSED: pod_memory_hog chaos test passed 🗡️💀♻️
✔️  PASSED: pod_io_stress chaos test passed 🗡️💀♻️
⏭️  SKIPPED: pod_dns_error docker runtime not found 🗡️💀♻️
✔️  PASSED: pod_network_duplication chaos test passed 🗡️💀♻️
✔️  🏆 PASSED: Helm liveness probe found ⎈🧫
✔️  🏆 PASSED: Helm readiness probe found ⎈🧫
Reliability, resilience, and availability results: 9 of 10 tests passed

**Comment by denverwilliams** [comment]
@lixuna The weird output was from me scrolling my mouse, before the doing the copy and paste. So, it wast't actually in the output.
