### ISSUE TITLE
[Documentation] Missing content for essential tests in List of Tests

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1370]
**Describe the bug**
- There is missing content in https://github.com/cncf/cnf-testsuite/blob/main/docs/LIST_OF_TESTS.md
- Followup of https://github.com/cncf/cnf-testsuite/issues/1306

**Expected behavior**
- Add content for What's expected and What is tested
- Make sure Essential tests have complete documentation (normal will be in a new issue)
- Replace TBD with content

**Essential tests**

1. (latest_tag)
2. (selinux_options)
3. (single_process_type)
4. (node_drain)
5. (liveness)
6. (readiness)
7. (log_output)
8. (container_sock_mounts)
9. (privileged_containers)
10. (non_root_containers)
11. (resource_policies)
12. (hostpath_mounts)
13. (hostport_not_used)
14. (hardcoded_ip_addresses_in_k8s_runtime_configuration)
15. (increase_decrease_capacity)

**Comment by lixuna** [comment]
Level of effort

@lixuna 2 pts
@agentpoyo 3 pts
@denverwilliams 3 pts

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] When I view the LIST OF TESTS doc, I can see that the following tests have documentation for each while also linking to other relevant docs (USAGE, RATIONALE, etc):
- [ ] (latest_tag)
- [ ] (selinux_options)
- [ ] (single_process_type)
- [ ] (node_drain)
- [ ] (liveness)
- [ ] (readiness)
- [ ] (log_output)
- [ ] (container_sock_mounts)
- [ ] (privileged_containers)
- [ ] (non_root_containers)
- [ ] (resource_policies)
- [ ] (hostpath_mounts)
- [ ] (hostport_not_used)
- [ ] (hardcoded_ip_addresses_in_k8s_runtime_configuration)
- [ ] (increase_decrease_capacity)

**Comment by agentpoyo** [comment]
@denverwilliams `selinux_options` is still missing from the LIST OF TESTS.

**Comment by taylor** [comment]
lgtm

**Comment by taylor** [comment]
lgtm @lixuna
