### ISSUE TITLE
[Documentation] Remove duplicate content from USAGE.md

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1371]
**Describe the bug**
- the USAGE.md contains duplicate content that should be in the LIST_OF_TESTS instead

**Expected behavior**
- USAGE = how to run, how to resolve a failed test
- LIST_OF_TEST = what does the test expect, what is tested
- (RATIONALE = why is the test important)

**Comment by taylor** [comment]
level of effort:
- @agentpoyo 3
- @denverwilliams 2
- @taylor 2
- @lixuna 3
- @wavell 3
- @HashNuke 2

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] When I view the USAGE doc, I will see no duplicate entries while seeing each test in the following format:
```
Test Name (with brief sentence if necessary)
Command to run it
Remediation
```
