### ISSUE TITLE
[Feature] Design Command Line output & results files for `setup` `cnf-setup` and `cert` command

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1373]
**Is your feature request related to a problem? Please describe.**
- Design Command Line output & results file for cert command

**Describe the solution you'd like**
- Capture existing command line output #1352 
- Design expected output on command line for cert
- Design expected results file for cert

**Comment by lixuna** [comment]
draft in hackmed https://hackmd.io/VGn25S9ySVmRVg7iQX4-KQ

level of effort for design, need issue for implementation

@taylor 3 pts
@agentpoyo 3 pts
@denverwilliams 3 
@wavell 3

**Comment by taylor** [comment]
See implementation in https://github.com/cncf/cnf-testsuite/issues/1408
