### ISSUE TITLE
[Documentation] Document cert instructions: how to submit results for cert

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1378]
### Instructions for CNF Certification 

**Describe the solution you'd like**
- How to run the test suite for cert see #1369 
- How to submit results 
- How to review results see #1379 

DRAFT: for landing page
- TBD: https://www.cncf.io/certification/cnf-conformance/

Draft for GitHub repo > https://github.com/cncf/cnf-conformance/blob/main/instructions.md)
- based on https://github.com/cncf/k8s-conformance/blob/master/instructions.md#how-to-submit-conformance-results

**Comment by lixuna** [comment]
level of effort 

@taylor if based off K8s conformance, 2 pts
@agentpoyo 3 pts
@lixuna 3 pts

**Comment by lixuna** [comment]
This is partly done, submitting via PR is ready in https://github.com/cncf/cnf-conformance/blob/main/instructions.md#uploading

To do: 

- [ ] how to submit a private review via email

**Comment by lixuna** [comment]
update: not including email review at this time, can add into the process in a later iteration, if needed

**Comment by lixuna** [comment]
Ready for peer review: 
https://github.com/cncf/cnf-conformance/blob/main/instructions.md#uploading

**Comment by taylor** [comment]
lgtm.
