### ISSUE TITLE
[BUG] opa should be uninstalled when `cleanup_all` is run

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1386]
**Describe the bug**

* When the `cleanup_all` task is run, opa should be uninstalled too.
* Without removing opa on `cleanup_all`, the cluster still has opa running on the default namespace.

**To Reproduce**

1. Install a CNF
2. Run the `versioned_tag` test. This would install opa.
4. Run `kubectl get all` to verify that opa is installed
5. Run the `cleanup_all` task.
6. Run `kubeclt get all` to verify that opa is still installed.

**Expected behavior**

opa should be uninstalled when `samples_cleanup` is run.

**Comment by taylor** [comment]
@HashNuke I'm confused because the PRs are about namespace

**Comment by HashNuke** [comment]
@taylor The `versioned_tag` test was installing OPA and not removing it after the test was run. Made it harder to run workload tests on the same cluster more than once and expect the same result The OPA rule may prevent even the subsequent `cnf_setup` from succeeding if the new cnf is using the latest tag.

**Example scenario to reproduce:**
1. Run `versioned_tag` test on any CNF.
2. Cleanup and install another CNF that might fail the versioned_tag CNF - blocked at `cnf_setup`.

### Related issue: OPA blocking test runs on GitHub Actions

There is also another issue related to OPA causing random GitHub Actions failures on the PR:
1. Failing `versioned_tag` tests in GitHub Actions if the build was running in a specific order.
2. Example: Bad scenario test running after the good scenario test would fail at `cnf_setup` because the opa rule would block the install of a CNF using latest tag.

I cannot find the ticket, but I found [the commit](https://github.com/cncf/cnf-testsuite/commit/b4fff0def887c49eeb02bf968b6ab5cc971fda88) that resolves this.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] When I run `cleanup_all` after I've run a `workload` or `cert` test load, I should see that gatekeeper pods are terminated on my k8s cluster after running `kubectl get pods`
- [ ] I can see a screenshot or pasted output

**Comment by agentpoyo** [comment]
@HashNuke 

`cleanup_all` did not uninstall opa (gatekeeper) pods. Moving back to Ready for Dev.

![opa_uninstall_screenshot](https://user-images.githubusercontent.com/14348948/167212037-6ead4b0a-2e52-4021-ac1d-6984168b9aa4.png)

**Comment by HashNuke** [comment]
@agentpoyo Just tried this ticket to verify if it's still pending. Seems to work as expected. Can you give this another at peer review? I used the `main` branch.

### `opa_install`

> Requires about 5min to install

![CleanShot 2022-07-25 at 06 20 13](https://user-images.githubusercontent.com/84005/180673673-2c1a1e04-ac8c-4a2e-8689-03326b4f561e.png)

### `cleanup_all`

The tool is uninstalled as expected when `cleanup_all` is run.

![CleanShot 2022-07-25 at 06 19 44](https://user-images.githubusercontent.com/84005/180673647-3cf98d12-d9ed-4e44-b6ab-6264d148ecb5.png)

**Comment by agentpoyo** [comment]
I'll test again @HashNuke as you can see, my previous attempt did not clean them up but perhaps it was some sort of hiccup then.

**Comment by agentpoyo** [comment]
It's working now. But found another issue, we should probably have OPA install to the cnf-testsuite namespace and it appears running `install_opa` puts it in the default namespace. Opening a BUG.

AC Peer Review Approved.

**Comment by agentpoyo** [comment]
![install_opa_default_namespace](https://user-images.githubusercontent.com/14348948/180857168-cd0078a0-79de-4d7b-af15-dd2b01b7da55.jpg)
