### ISSUE TITLE
[Maintenance] Update version of helm in Q2 2022 (June 1-June 30) 

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1391]
### [Q2 2022 Maintenance] Update version of helm in CNF Test Suite

**Describe the maintenance item**
- in Q2 2022 (April 1-June 30), check for latest release of helm
- check compatibility with dependencies
- update CNF Test Suite with one minor release behind the latest

**Expected behavior**
- the CNF Test Suite will function as expected after updating helm

**How will this be tested? aka Acceptance Criteria (optional)**

- [ ] All documentation is updated to mention the updated software version
- [ ] Install works as expected
- [ ] Running `all` tests works as expected
- [ ] Running `workload` works as expected
- [ ] Running `platform` works as expected
- [ ] Running `cert` works as expected
- [ ] Running individual test categories works as expected
- [ ] Running individual tests works as expected
- [ ] tbd, add more expectations as needed

**Comment by agentpoyo** [comment]
`setup` output when helm v3.8.2 is locally on the client:
![helm_update_1](https://user-images.githubusercontent.com/14348948/181074481-736e5986-03be-40f8-b60f-22c505fc7e06.png)

**Comment by agentpoyo** [comment]
`setup` output when no OS or global helm found, forcing the tool to download helm:
![helm_update_2](https://user-images.githubusercontent.com/14348948/181075386-8f09b35a-708e-4283-957c-c3a0814a7c97.png)

**Comment by agentpoyo** [comment]
Workload runs without any helm issues:
![hardcodedIP_output_workload](https://user-images.githubusercontent.com/14348948/181086446-9220c86f-d97f-4347-a32d-5689cf57cccb.png)

**Comment by agentpoyo** [comment]
`cert` is clean without any issues for latest helm v3.8.2:
![1391_helm_update_cert](https://user-images.githubusercontent.com/14348948/181093260-1fc817ed-3833-4f06-9ba4-571334d4c6d7.png)

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] When I run setup without helm locally installed, I should see v3.8.2 install into the tools/helm directory
- [ ] When I run setup with helm locally installed (global), I should see that helm is not downloaded into tools/helm directory
- [ ] When I run `workload`, I should not see helm errors on any of the tests
- [ ] When I run `cert`, I should not see any helm errors on any of the tests.

##### Notes
https://github.com/cncf/cnf-testsuite/issues/1376 is now invalid as cni_compatible attempts to use the tools/helm that is installed if not found globally.
https://github.com/cncf/cnf-testsuite/issues/1374 is still valid and was found prior to this upgrade, only cni_compatible is affected so still pushing this through as approved; this bug will get addressed.
