### ISSUE TITLE
[Feature] Add support for normal and essential state tests for testing CNFs using non-default namespaces

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1397]
> *This issue is part of #1286 and #1363*

* Add support for testing CNFs that use non-default namespaces for tests under the category.
* Update relevant spec tests for failure scenarios to use CNFs that use non-default namepaces.
* Manually run the tests with failure CNFs to validate the outputs

Tests:
- [ ] ~no_local_volume_configuration~
- [x] node_drain (Litmus)
- [x] elastic_volumes
- [ ] ~database_persistence~

**Comment by taylor** [comment]
level of effort
- @denverwilliams 3
- @wavell 3
- @HashNuke 5
- @agentpoyo 3️⃣ 
- @taylor 3

**Comment by taylor** [comment]
Related to work in https://github.com/cncf/cnf-testsuite/pull/1438

**Comment by taylor** [comment]
@HashNuke move bonus and non-cert tests to new tickets

**Comment by HashNuke** [comment]
The normal and essentials tests were completed as a part of the PR for #1437.

**Comment by wavell** [comment]
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/29548/167923890-c24ff08a-fe40-4fed-ae7f-bf5bd9b5d94b.png">
<img width="587" alt="image" src="https://user-images.githubusercontent.com/29548/167923964-16138909-1742-4c82-8f93-e2dda11f6586.png">
state tests work in a separate namespace
