### ISSUE TITLE
[Feature] Add support for configuration tests for testing CNFs using non-default namespaces

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1398]
> *This issue is part of #1286 and #1363*

* Add support for testing CNFs that use non-default namespaces for tests under the category.
* Update relevant spec tests for failure scenarios to use CNFs that use non-default namepaces.
* Manually run the tests with failure CNFs to validate the outputs

Tests:

- [x] nodeport_not_used
- [x] hostport_not_used
- [x] secrets_used
- [x] immutable_configmap
- [x] versioned_tag

**Comment by taylor** [comment]
level of effort
- @denverwilliams 5
- @HashNuke 5
- @agentpoyo 5

**Comment by HashNuke** [comment]
### Progress updates

* Added a patch for `helm template` issue (helm/helm#10737)
* Updated `nodeport_not_used` and tested with sample CNF
* Updated `hostport_not_used` and tested with sample CNF
* Updated `versioned_tag` in a previous branch. Yet to test

### Observations for `secrets_used`
* If looking for secrets across all namespaces `secrets_used` test would pass if any third-party tools we install have/use secrets.
* The `secrets_used` test would have to filter out secrets from `EXCLUDE_NAMESPACES`.

**Comment by HashNuke** [comment]
### Progress updates

* Tested `immutable_configmap` test and found some bugs. Created and fixed the following:
  * #1417 
  * #1418
* Rewrote part of `immutable_configmap` test to git rid of the state variables and handle a few scenarios (like #1418).
* Fixing surfaced a bug with `elastic_volumes` test in the Github Actions failures (#1419).

Work on the configuration tests are complete. But not raising a PR for now. Have to fix #1419 before creating the PR.

**Comment by taylor** [comment]
@HashNuke move bonus and non-cert tests to new tickets that are in the todo queue (not ready for dev)

**Comment by lixuna** [comment]
@agentpoyo @denverwilliams has this been peer reviewed or was it closed automatically?

**Comment by wavell** [comment]
[ ]- install a cnf with a non-default namespace
[ ]- run the configuration tests
[ ]- ensure that there are no exceptions

**Comment by wavell** [comment]
<img width="1887" alt="image" src="https://user-images.githubusercontent.com/29548/167486331-cdd45f85-c804-4969-a3e7-69d302899c50.png">

**Comment by taylor** [comment]
@wavell is there a sample that passes version tag?  The one used did not deploy because it did not have a image tag version.

cc: @denverwilliams

**Comment by wavell** [comment]
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/29548/167926708-ba818bdb-1159-4f2d-8ddf-7d3e8f1ba45e.png">
<img width="529" alt="image" src="https://user-images.githubusercontent.com/29548/167926750-0704642c-26b5-46ff-ad30-5c5cdc15525c.png">
