### ISSUE TITLE
QA end-user test suite steps with CoreDNS against Microk8s and document results #1365

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testsuite#1403]
https://github.com/cncf/cnf-testsuite/issues/1365

**Comment by agentpoyo** [comment]
```
root@cnfqa1:~/v0.28.1# ./cnf-testsuite setup
Successfully created directories for cnf-testsuite
Global helm found. Version: v3.1.1
Local helm found. Version: v3.1.1
Global kubectl found. Version: 1.23
No Local kubectl version found
Global git found. Version: 2.25.1
No Local git version found
All prerequisites found.
Created cnf-testsuite namespace on the Kubernetes cluster
Setup complete

root@cnfqa1:~/v0.28.1# ./cnf-testsuite cnf_setup cnf-config=./cnf-testsuite.yml
Successfully created directories for cnf-testsuite
cnf-testsuite namespace already exists on the Kubernetes cluster
cnf setup online mode
Successfully setup coredns
cnf setup online mode complete
```

**Comment by agentpoyo** [comment]
[microk8s_info_output.log](https://github.com/cncf/cnf-testsuite/files/8573365/microk8s_info_output.log)

**Comment by wavell** [comment]
KindManager#create_cluster(online) command: /root/v0.28.1/tools/kind/kind create cluster --name calico-test --config /root/v0.28.1/tools/kind/disable_cni.yml --image kindest/node:v1.21.1 --kubeconfig /root/v0.28.1/tools/kind/calico-test_admin.conf
I, [2022-04-27 14:10:51 +00:00 #1454961]  INFO -- cnf-testsuite: KindManager#create_cluster(online) stderr: ERROR: failed to create cluster: failed to get docker info: command "docker info --format '{{json .}}'" failed with error: exec: "docker": executable file not found in $PATH

cni test has a docker prereq

**Comment by agentpoyo** [comment]
Verdict: MicroK8s passed

**Comment by taylor** [comment]
@agentpoyo does this mean that microk8s got the same results as Kind?  If so approved otherwise please list tests that had different results for Microk8s vs Kind.  This can be a list of the test names or showing the result differences like seen in https://github.com/cncf/cnf-testsuite/issues/1405#issuecomment-1119010951.  

Refer to kind results here: https://github.com/cncf/cnf-testsuite/issues/1365#issuecomment-1119009274

**Comment by denverwilliams** [comment]
@agentpoyo These results differ from kind. Can you list a side-by-side comparison, like what was done in the Azure [ticket](https://github.com/cncf/cnf-testsuite/issues/1406#issuecomment-1119114697)

**Comment by agentpoyo** [comment]
![1403_comparison_results](https://user-images.githubusercontent.com/14348948/184154313-2558e3f1-a064-4aa9-b60d-012167d6fbed.png)
![1403_comparison_results2](https://user-images.githubusercontent.com/14348948/184154322-1310991f-e632-4a91-9e77-f7b7043279c1.png)

**Comment by agentpoyo** [comment]
Appears every platform fails for he chaos network tests besides kind clusters. So either there's a bug in the tests or something else is going on in how it's testing other platform clusters that are not kind.

**Comment by agentpoyo** [comment]
This doesn't require AC, we have open tickets on the findings that are not non-kind clusters and Chaos tests that do not appear to run properly.
