### ISSUE TITLE
[BUG] `elastic_volumes` test should not pass if any of the resources in the CNF use volumes that are not elastic

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1424]
## Describe the bug

`elastic_volumes` test should not pass if any of the resources in the CNF use volumes that are not elastic.

* `elastic_volumes` test uses one boolean state variable `elastic` for the test result for all resources being tested.
* This means that even if one of the resources being tested uses elastic volumes, the entire test would pass.

## Example of a CNF that should not pass

Consider a CNF with two resources:
* resource-1 in the CNF uses elastic volumes
* resource-2 in the CNF does not use elastic volumes

The CNF still has resource-2 that does not have elastic volumes and should not pass. But the current implementation of the `elastic_volumes` test would pass this CNF.

## Reason why this happens

* `elastic_volumes` test uses one common boolean state variable `elastic` for the test result for all resources being tested.
* This means that even if one of the resources being tested uses elastic volumes, the entire test for the CNF would pass.

**Comment by HashNuke** [comment]
Failures for this test in GitHub Actions is blocking creating PRs and making further changes to support non-default namespace. So picking this up first.

**Comment by HashNuke** [comment]
Clarified with Watson. This test is to check if the CNF uses ANY elastic volumes. It is alright if there are other volumes too.

Closing this issue.

**Comment by CsatariGergely** [comment]
@HashNuke can you please explain what elastic volumes are in this test? I try to clarify this in #1278
