### ISSUE TITLE
[CNFs] Test VPP-based Pipeline Service Chain Example (3 chains of 2 nodes) with the CNF Conformance Test Suite

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#143]
[Acceptance Criteria](https://github.com/cncf/cnf-conformance/issues/143#issuecomment-614286152)

### [CNFs] Test VPP-based Pipeline Service Chain Example (3 chains of 2 nodes) with the CNF Conformance Test Suite

Planning Tasks:
- [x] Review and update https://github.com/cncf/cnf-conformance/edit/develop/EXAMPLE-CNFS.md
- [x] Select the next one (or two) CNF(s) that will be tested in the CNF Conformance Test Suite => VPP IP Forwarder (See [3c2n-csp](https://github.com/cncf/cnf-testbed/tree/master/examples/use_case/3c2n-csp))

Documentation tasks: TBD
- [x]  create README for VPP IP Forwarder CNF (example: https://github.com/cncf/cnf-conformance/blob/master/sample-cnfs/sample-coredns-cnf/README.md)

Implementation tasks: TBD
- [x]  create a cnf-conformance.yml for VPP IP Forwarder CNF (example: https://github.com/cncf/cnf-conformance/blob/master/sample-cnfs/sample-coredns-cnf/cnf-conformance.yml)
- [ ]  
- [x] Tag 1 or more people to peer review

**QA tasks**

Dev Review: 
- [x] walk through A/C
- [ ] do you get the expected result?
- [x] if yes, 
   - [x] move to `Needs Peer Review` column  
   - [x] create Pull Request and follow check list
   - [x] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by lixuna** [comment]
Acceptance criteria: steps to test during development and peer review
---

- [ ]  I can follow the set up instructions
- [ ]  I should see a VPP IP Forwarder CNF example folder
    - [ ]   Ie. in an example-cnfs folder with each example CNF having it’s own sub-folder with a config
- [ ]  I should see VPP IP Forwarder CNF README with summary and instructions in VPP IP Forwarder directory and in example CNFs
- [ ]  I should see a cnf-conformance.yml configuration in the VPP IP Forwarder example CNF folder
- [ ]  I can run the CNF Conformance Tests w/ the VPP IP Forwarder CNF
- [ ]  I can check the output of the CNF conformance command
   - [ ]  I should see which tests passed or failed for the VPP IP Forwarder CNF
   - [ ]  I should see a final score for the VPP IP Forwarder CNF
- [ ]  Final Score for VPP IP Forwarder =

**Comment by wavell** [comment]
The example ip-forwarder directory is example-cnfs/ip-forwarder/

**Comment by taylor** [comment]
Example testing docs for an example https://hackmd.io/0AagcIE0RdC53lRaIFAn4A?view

**Comment by taylor** [comment]
Example summary and update for README:
----

Upstream: https://github.com/cncf/cnf-testbed/tree/master/examples/network_functions/vpp-ip-forwarder

Description:  Pipeline Service Chain using  3 chains of 2 CNFs (per chain)

This example installs the pipeline service chain example on a kubernetes worker node. All nodes are connected using Memif interfaces, with the chain endpoints connecting to the host vSwitch (VPP) while the intermediate connections are done directly between nodes.

Description:
- Layer 3 packet forwarding
- Based on the fd.io VPP project
- Uses DPDK
- memif interfaces

....

**Comment by taylor** [comment]
TODO:
- add summary and overview to README
- rename example to vpp-3c2n-csp-use-case

**Comment by taylor** [comment]
Does not work as an example using the current cnf_setup and other install examples.  config updated to have default image tag in PR https://github.com/cncf/cnf-conformance/pull/187

**Comment by taylor** [comment]
@denverwilliams @wavell  Errors with helm chart and helm usage for this example

```
pair@cnfdev03:~/workspace/taylor/qa/cnf-conformance$ ./cnf-conformance-v0.5.0-prealpha-amd64 cnf_setup cnf-path=
example-cnfs/vpp-3c2n-csp-use-case                                                              
Successfully created directories for cnf-conformance                                                            
sample_setup_args                                                                                 
release_name: ip-forwarder-csp                                                                                 
deployment_name: ip-forwarder-csp                                                                         
helm_chart:                                                                                   
helm_directory: csp                                                                                             
git_clone_url:                                                                                                  
sample_setup                                                                                              
/home/pair/workspace/taylor/qa/cnf-conformance                                                                  
destination_cnf_dir: /home/pair/workspace/taylor/qa/cnf-conformance/cnfs/vpp-3c2n-csp-use-case  
                                                                                                                
                                                                                                
/home/pair/workspace/taylor/qa/cnf-conformance/tools/helm/linux-amd64/helm                                      
deploying with chart repository                                                                   
Error: must either provide a name or specify --generate-name                                                   
                                                                                                          
Error: "helm pull" requires at least 1 argument                                               
                                                                                                                
Usage:  helm pull [chart URL | repo/chartname] [...] [flags]                                                    
                                                                                                          
mv -*.tgz /home/pair/workspace/taylor/qa/cnf-conformance/cnfs/vpp-3c2n-csp-use-case/csp   

```


Results in many other failures including deployment

cc: @michaelspedersen
