### ISSUE TITLE
[BUG] Update Usage Documentation for the cnf-testsuite.yml Generator

### ISSUE THREAD

**Issue by denverwilliams** [cncf/cnf-testsuite#1431]
**Describe the bug**
Update usage documentation for the cnf-testsuite.yml generator & remove container_names for the generator as it's currently not needed in the cert.

**To Reproduce**

1. Go to [CNF_TESTSUITE_YML_USAGE.md](https://github.com/cncf/cnf-testsuite/blob/main/CNF_TESTSUITE_YML_USAGE.md)
2. Go to "[What is the cnf-testsuite.yml and why is it required?](https://github.com/cncf/cnf-testsuite/blob/main/CNF_TESTSUITE_YML_USAGE.md#what-is-the-cnf-testsuiteyml-and-why-is-it-required)"
4. Read information
5. See container name as part of the details needed.

**Expected behavior**
container names are not required so should not be mentioned

(optional: unnecessary for things like spelling errors and such)

Once this issue is address how will the fix be verified?

**Additional context**

--

**Comment by taylor** [comment]
@denverwilliams documentation still mentions container names here https://github.com/cncf/cnf-testsuite/blob/main/CNF_TESTSUITE_YML_USAGE.md#what-is-the-cnf-testsuiteyml-and-why-is-it-required

**Comment by taylor** [comment]
All good.  This can be closed.

From Denver:

> allowlist_helm_chart_container_names   is used for excluding privileged containers and entirely separate argument from container_names
