### ISSUE TITLE
[Feature] Support CNFs that do not use default namespace in the Essential and Normal tests

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1437]
> *This ticket is a part of #1286. Prioritizing normal and essential tests to allow making a release for users to try this out*.

Support CNFs that do not use default namespace in the Essential and Normal tests.

The pending Essential tests that need this support are below:
* liveness
* readiness
* node_drain
* log_output
* increase_decrease_capacity

The pending Normal tests that need this support are below:
* disk_fill
* pod_delete
* pod_memory_hog
* rollback
* cni_compatible

**Comment by HashNuke** [comment]
Other tests that required updates due to common dependencies or impact areas.

* rolling_version_update
* rolling_downgrade
* rolling_update
* prometheus_traffic
* routed_logs
* database_persistence

**Comment by taylor** [comment]
@HashNuke move bonus and non-cert tests to new tickets that are in the todo queue (not ready for dev)

**Comment by lixuna** [comment]
@agentpoyo @denverwilliams has this been peer reviewed or was it closed automatically?

**Comment by wavell** [comment]
All of these tests (essential tests) are handled in the tickets for the other categories (since essential tests are all handled  within a category)
