### ISSUE TITLE
[BUG] Update GitHub Actions runners to new base image (05-May-2022)

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1439]
**Describe the bug**
GitHub Actions workers are not picking up jobs. Update GitHub Actions runners to new base image `myoung34/github-runner:2.291.1-ubuntu-bionic`.

**Comment by agentpoyo** [comment]
Github action runners picking up jobs again:

![1439_fixed](https://user-images.githubusercontent.com/14348948/166996758-fcc56391-fb51-4f1d-a5e3-ec21f66dfb2d.png)

**Comment by lixuna** [comment]
@HashNuke @agentpoyo what was the level of effort in points for this?
