### ISSUE TITLE
[Feature] EPIC: Ignore existing containers when running tests

### ISSUE THREAD

**Issue by EricLo-417** [cncf/cnf-testsuite#1440]
**Is your feature request related to a problem? Please describe.**
When running tests using my kubernets, I have some pods that already exist (promtail, loki for example), however when running tests some of these pods cause tests to fail which creates false negatives. It would be helpful to have these be ignored in some way from the whole testsuite.

**Describe the solution you'd like**
Base on previous conversations there are two solutions 
 - Add an ignore_list field to the cnf config
 - Look at all pods running before deploying chart and add those to an internal ignore list

The second choice seems to be the better one as it will be no extra config work for the user and is much harder to abuse compared to the first option.

**Comment by taylor** [comment]
@EricLo-417 can you list the tests that checking the containers that should be excluded?

**Comment by taylor** [comment]
cc: @Smitholi67

**Comment by HashNuke** [comment]
These are the final list of tests.

<img width="1026" alt="CleanShot 2022-06-21 at 19 42 57@2x" src="https://user-images.githubusercontent.com/84005/174821228-ae9d332c-8b81-4fff-b651-32da5c2d769e.png">

**Comment by HashNuke** [comment]
Tickets that are to be verified as part of this epic:
* [ ] #1503
* [ ] #1504
* [ ] #1505
* [ ] #1506
* [ ] #1507
* [ ] #1508
* [ ] #1509
* [ ] #1510
* [ ] #1511
* [ ] #1512
* [ ] #1513
* [ ] #1514
* [ ] #1515
* [ ] #1516
* [ ] #1517
* [ ] #1518
* [ ] #1519
* [ ] #1520
* [ ] #1521
* [ ] #1522
* [ ] #1523
* [ ] #1524

**Comment by HashNuke** [comment]
Most of the issues have been fixed. My comment above has some updates (issues that are checked are completed).

For the issues checked above, the updates made to resolve the issue so far are in the `feature/1518` branch. The changes are being validated before making a PR to `main` branch.
