### ISSUE TITLE
[BUG] console output states rolling_update failed before "rollback" failed but rolling updates were removed for the `cert` command

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1446]
**Describe the bug**
Either this is misleading and pertains to rollback test but the output message indicates it's failing on a `rolling update` test that is failing, which these tests were removed for the `cert` command.

**To Reproduce**
Run the `cert` command against a CNF.

**Expected behavior**
Remove or update the description of the message.

**Screenshots**
![rolling_update_failed](https://user-images.githubusercontent.com/14348948/167175972-b852758a-0f93-4753-80dd-fb3276226cdd.png)

**Comment by lixuna** [comment]
Followup of A/C in #1383

**Comment by agentpoyo** [comment]
![1446_rollback_desc_fix](https://user-images.githubusercontent.com/14348948/167209842-81f64ef6-67de-492a-9715-b759a2b6a2d5.png)

**Comment by agentpoyo** [comment]
#### Acceptance Criteria:

- [ ] When I run rollback on a CNF that fails, I should not see a description that states "Rolling update failed" but rather "Rollback failed.."
- [ ] I can see the output or screenshot in this issue.

**Comment by wavell** [comment]
<img width="854" alt="image" src="https://user-images.githubusercontent.com/29548/167511574-7c007bcc-dc5a-44ed-a894-cd4135140e5e.png">

**Comment by lixuna** [comment]
@agentpoyo @wavell add level of effort in points (0,1,2,3,5,8,13)

**Comment by agentpoyo** [comment]
2pts
