### ISSUE TITLE
[Documentation] update README on cnf-conformance repo for CNF Certification

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1458]
**Is your feature request related to a problem? Please describe.**
- README on cnf-conformance repo is out of date, last updated 1 yr ago

**Describe the solution you'd like**
- update README on cnf-conformance repo for CNF Certification

**Comment by taylor** [comment]
WIP https://github.com/cncf/cnf-conformance/pull/4

**Comment by lixuna** [comment]
This has been done
