### ISSUE TITLE
[BUG] service_account_mapping looking at litmus chaos tests

### ISSUE THREAD

**Issue by EricLo-417** [cncf/cnf-testsuite#1471]
**Describe the bug**
Running the test `service_account_mapping` along with the other litmus chaos tests causes it to look at those as well.

**To Reproduce**
I was running all tests in cert individually and noticed that this test was looking at "pod_X_sa", Service account mapping was ran after all the other tests

**Expected Results**
`service_account_mapping` should either ignore these or/and these tests need to be clean up after they are ran.

Ran with version `0.29.1`

attached is `service_account_mapping` and the other pod tests

[service_account_mapping.txt](https://github.com/cncf/cnf-testsuite/files/8763463/service_account_mapping.txt)
[disk_fill.txt](https://github.com/cncf/cnf-testsuite/files/8763464/disk_fill.txt)
[pod_delete.txt](https://github.com/cncf/cnf-testsuite/files/8763465/pod_delete.txt)
[pod_io_stress.txt](https://github.com/cncf/cnf-testsuite/files/8763467/pod_io_stress.txt)
[pod_memory_hog.txt](https://github.com/cncf/cnf-testsuite/files/8763468/pod_memory_hog.txt)
[pod_network_corruption.txt](https://github.com/cncf/cnf-testsuite/files/8763469/pod_network_corruption.txt)
[pod_network_duplication.txt](https://github.com/cncf/cnf-testsuite/files/8763470/pod_network_duplication.txt)
[pod_network_latency.txt](https://github.com/cncf/cnf-testsuite/files/8763471/pod_network_latency.txt)

**Comment by HashNuke** [comment]
With progress made on #1440, this ticket should have been resolved. service_account_mapping test only tests for resources that belong to the CNF now.

Moving this ticket to peer review to be closed.

**Comment by agentpoyo** [comment]
![1471_results](https://user-images.githubusercontent.com/14348948/179067061-a2ea3f42-5aab-4536-9d6b-fb96617659bd.png)
