### ISSUE TITLE
[Feature] The cnf-testsuite should report the version used during `cert` command on console and results.yml 

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1472]
**Is your feature request related to a problem? Please describe.**
No but it's helpful to know the version used to run `cert` submissions for PR's for those getting certified.

**Describe the solution you'd like**
When running `setup`, it should stdout on the console the cnf-testsuite version used.
This should also be reported into the final results.yml file generated that is used for PR submissions.

**Comment by HashNuke** [comment]
Request on a testsuite office hours call by @EricLo-417: Display the testsuite version on the console output for setup command.

**Comment by agentpoyo** [comment]
@HashNuke 

Looks like the version is printed out everytime the binary is ran. We probably only want it to output during setup, not every time. See screenshot when `cert` was run:

![1472_cert_output](https://user-images.githubusercontent.com/14348948/213298480-d33d8697-02a3-4f5d-aa8c-2018dfda7ba5.jpg)

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Checkout the development branch used in the pull request to `main`
- [ ] Build the cnf-testsuite binary (follow the development instructions on installation is needed)
- [ ] Find or build a k8s cluster with kubectl connection to the cluster
- [ ] I should see the version of the cnf-testsuite when `./cnf-testsuite setup` is run.
- [ ] I can see the screenshot of output here from the `setup` argument.
- [ ] I should also see the cnf-testsuite version when I run a tests in the results.yml file that is generated.
- [ ] I can see the screenshot or output of the generated results yml file here.
- [ ] In this case, the version should report the `branch name` followed by a timestamp.

**Comment by agentpoyo** [comment]
![1472_setup_output](https://user-images.githubusercontent.com/14348948/213299103-82d51dcb-7a44-4223-af62-29fbf13d58bb.jpg)

**Comment by agentpoyo** [comment]
![1472_resultsfile_output](https://user-images.githubusercontent.com/14348948/213300742-ba25cd1a-0918-4286-86bc-d7e4f33ce066.jpg)
