### ISSUE TITLE
[Feature] Add support for CNFs that use non-default namespace for `pod_network_latency` test

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1474]
> *This is a part of #1286 and split from #1400*

Add support for running the `pod_network_latency` test against CNFs that use non-default namespaces.

**Comment by agentpoyo** [comment]
![1474_results](https://user-images.githubusercontent.com/14348948/174322677-13061f91-732c-4c61-87cf-4185159cb36c.png)
