### ISSUE TITLE
[Feature] Add support for CNFs that use non-default namespace for `pod_network_corruption` test 

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1476]
> *This is a part of #1286 and split from #1400*

Add support for running the `pod_network_corruption` test against CNFs that use non-default namespaces.

**Comment by agentpoyo** [comment]
Todo: Add AC and peer review.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Install CNF that doesn't use default namespace
- [ ] Run `pod_network_corruption` after setting up cnf-testsuite
- [ ] Make sure there are no exceptions.

**Comment by agentpoyo** [comment]
![1476_network-corruption](https://user-images.githubusercontent.com/14348948/172950429-f830f075-0094-4259-ba95-aa1e6a14cd5b.png)
