### ISSUE TITLE
[Feature] Add support for CNFs that use non-default namespace for `pod_network_duplication` test 

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1477]
> *This is a part of #1286 and split from #1400*

Add support for running the `pod_network_duplication` test against CNFs that use non-default namespaces.

**Comment by agentpoyo** [comment]
Todo: AC and peer review.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Install CNF that doesn't use default namespace
- [ ] Run `pod_network_duplication` after setting up cnf-testsuite
- [ ] Make sure there are no exceptions.
