### ISSUE TITLE
[Feature] Add support for CNFs that use non-default namespace for `pod_dns_error` test 

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1478]
> *This is a part of #1286 and split from #1400*

Add support for running the `pod_dns_error` test against CNFs that use non-default namespaces.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Install CNF that doesn't use default namespace
- [ ] Run `pod_dns_error` after setting up cnf-testsuite
- [ ] Make sure there are no exceptions.
