### ISSUE TITLE
[BUG] kubectl version parsing throws an error on k3s when `cnf_setup`

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1484]
**Describe the bug**

kubectl version parsing throws an error on k3s when `cnf_setup`

<img width="1130" alt="CleanShot 2022-05-31 at 09 23 27@2x" src="https://user-images.githubusercontent.com/84005/171089533-70b88f5d-7ef1-44d8-92e7-2698c2696254.png">

**To Reproduce**

1. Install k3s
2. Run `cnf_setup` with any CNF

**Comment by agentpoyo** [comment]
Todo: AC and Peer Review/Testing

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Setup a k3s cluster
- [ ] When running testsuite against k3s cluster, I should not see a 'semantic version' error during `cnf_setup` 
- [ ] I can see a screenshot of clean console output for cnf_setup.

**Comment by agentpoyo** [comment]
![1484_k3s_bug](https://user-images.githubusercontent.com/14348948/172928783-1ad84ef5-5898-409e-a870-8064fa40cd03.png)
