### ISSUE TITLE
[Feature] Add support for CNFs that use non-default namespace for `pod_io_stress` test

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1492]
> *This is a part of #1286 and split from #1400*

Add support for running the `pod_io_stress` test against CNFs that use non-default namespaces.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Install CNF that doesn't use default namespace
- [ ] Run `pod_io_stress` after setting up cnf-testsuite
- [ ] Make sure there are no exceptions.

**Comment by agentpoyo** [comment]
![1492_pod_io](https://user-images.githubusercontent.com/14348948/172954197-762507a3-f449-4243-9a81-fbdcb5e820dc.png)
