### ISSUE TITLE
[FEATURE] `network_policies` should only consider resources that are part of the CNF

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1504]
* Part of #1440
* `network_policies` should only consider resources that are part of the CNF

**Comment by HashNuke** [comment]
This ticket is outdated since #1539. Moving this to peer review to review close.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Setup or find k8s cluster
- [ ] `helm install corednstag coredns/coredns`
- [ ] `./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample_coredns`
- [ ] `./cnf-testsuite network_policies`
- [ ] I should see no failures as it should not check the manually installed coredns using it's own namespace.
- [ ] I can see screenshots of the output here.

**Comment by lixuna** [comment]
@HashNuke  @agentpoyo What is the level of effort in pts? (0,1,2,3,5,8,13,21)
