### ISSUE TITLE
[Feature] `immutable_file_systems` should only consider resources that are part of the CNF

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1505]
* Part of #1440
* `immutable_file_systems` should only consider resources that are part of the CNF

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [x] Setup or find k8s cluster
- [x] `helm install corednstag coredns/coredns`
- [x] `./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample_coredns`
- [x] `./cnf-testsuite immutable_file_systems`
- [x] I should see results where  it should not check the manually installed coredns using it's own namespace outside of the CNF namespace.
- [x] I can see screenshots of the output here.

**Comment by agentpoyo** [comment]
![1505_results](https://user-images.githubusercontent.com/14348948/176967305-000ac29f-a638-4bde-964c-e2f22f8adc47.png)
