### ISSUE TITLE
[Feature] `immutable_configmap` should only consider resources that are part of the CNF

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1506]
* Part of #1440
* `immutable_configmap` should only consider resources that are part of the CNF

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Update the `sample_nonroot` CNF manifest file to use a mutable configmap (check the reference section below for the code).
- [ ] Apply the manifest file using kubectl: `kubectl apply -f sample-cnfs/sample_nonroot/manifests/pod.yml`
- [ ] Setup a CNF that would pass the test: `./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/ndn-immutable-configmap`
- [ ] Ensure that the test passes. `./cnf-testsuite immutable_configmap`
- [ ] Uninstall the `ndn-immutable-configmap` CNF and install the modified `sample_nonroot` CNF: `./cnf-testsuite cleanup_all` and then `./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample_nonroot`
- [ ] The test should fail: `./cnf-testsuite immutable_configmap`
