### ISSUE TITLE
[Feature] `selinux_options` should only consider resources that are part of the CNF

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1508]
* Part of #1440
* `selinux_options` should only consider resources that are part of the CNF

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Setup or find k8s cluster
- [ ] `helm install corednstag coredns/coredns`
- [ ] `./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample_coredns`
- [ ] `./cnf-testsuite selinux_options`
- [ ] I should see no failures as it should not check the manually installed coredns using it's own namespace.
- [ ] I can see screenshots of the output here.

**Comment by agentpoyo** [comment]
![1508_results](https://user-images.githubusercontent.com/14348948/176720568-2cffc292-1819-4d97-aef1-949bb8947512.png)
