### ISSUE TITLE
[Feature] `privileged_containers` should only consider resources that are part of the CNF

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1509]
* Part of #1440
* `privileged_containers` should only consider resources that are part of the CNF

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [x] Setup or find k8s cluster
- [x] `helm install corednstag coredns/coredns`
- [x] `./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample_coredns`
- [x] `./cnf-testsuite privileged_containers`
- [x] I should see results where  it should not check the manually installed coredns using it's own namespace outside of the CNF namespace.
- [x] I can see screenshots of the output here.

**Comment by agentpoyo** [comment]
![1509_results](https://user-images.githubusercontent.com/14348948/176967049-b780827e-5762-4aed-ab4e-a39b0de6b75f.png)
