### ISSUE TITLE
[Feature] `non_root_containers` should only consider resources that are part of the CNF

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1510]
* Part of #1440 
* `non_root_containers` should only consider resources that are part of the CNF

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [x] Setup or find k8s cluster
- [x] `helm install corednstag coredns/coredns`
- [x] `./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample_coredns`
- [x] `./cnf-testsuite non_root_containers`
- [x] I should see results where  it should not check the manually installed coredns using it's own namespace outside of the CNF namespace.
- [x] I can see screenshots of the output here.

**Comment by agentpoyo** [comment]
![1510_results](https://user-images.githubusercontent.com/14348948/176966867-8da495c9-f996-4041-8a4c-4c9acbea9846.png)
