### ISSUE TITLE
[Feature] `sysctls` should only consider resources that are part of the CNF

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1514]
* Part of #1440
* `sysctls` should only consider resources that are part of the CNF

**Comment by denverwilliams** [comment]
@HashNuke  I think `CNFManager::Task.task_runner(args) ` is looping for each CNF. Meaning https://github.com/cncf/cnf-testsuite/blob/main/src/tasks/workload/security.cr#L48 is running multiple times when it doesn't need to. We could move it out of the task_runner and it should still work as expected.

**Comment by HashNuke** [comment]
@denverwilliams Thank you for taking a look at this. I updated a branch with the change. Will send a PR soon.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Setup or find k8s cluster
- [ ] `helm install corednstag coredns/coredns`
- [ ] `./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample_coredns`
- [ ] `./cnf-testsuite sysctls`
- [ ] I should see no failures as it should not check the manually installed coredns using it's own namespace.
- [ ] I can see screenshots of the output here.

**Comment by HashNuke** [comment]
Marking this as 5pts since this ticket included the initial work for parsing Kyverno test results.

**Comment by agentpoyo** [comment]
![1514_results](https://user-images.githubusercontent.com/14348948/176719882-7394eb7d-1303-47c9-8c58-18e0ce0ccb61.png)
