### ISSUE TITLE
[Feature] `privilege_escalation` should only consider resources that are part of the CNF

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1517]
* Part of #1440
* `privilege_escalation` should only consider resources that are part of the CNF

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [x] Setup or find k8s cluster
- [x] `helm install corednstag coredns/coredns`
- [x] `./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample_coredns`
- [x] `./cnf-testsuite privilege_escalation`
- [x] I should see no failures as it should not check the manually installed coredns using it's own namespace.
- [x] I can see screenshots of the output here.

**Comment by agentpoyo** [comment]
![1517_results](https://user-images.githubusercontent.com/14348948/176961500-99ccaa10-146a-4f87-904e-1374ae53f3ed.png)
