### ISSUE TITLE
[Feature] `application_credentials` should only consider resources that are part of the CNF

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1518]
* Part of #1440
* `application_credentials` should only consider resources that are part of the CNF

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [x] Setup or find k8s cluster
- [x] `helm install corednstag coredns/coredns`
- [x] `./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample_coredns`
- [x] `./cnf-testsuite application_credentials`
- [x] I should see results where  it should not check the manually installed coredns using it's own namespace outside of the CNF namespace.
- [x] I can see screenshots of the output here.

**Comment by agentpoyo** [comment]
![1518_results](https://user-images.githubusercontent.com/14348948/176963187-8272d54e-d0a8-404c-9564-34fcebb41c5f.png)
