### ISSUE TITLE
[Feature] `host_network` should only consider resources that are part of the CNF

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1519]
* Part of #1440
* `host_network` should only consider resources that are part of the CNF

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [x] Setup or find k8s cluster
- [x] `helm install corednstag coredns/coredns`
- [x] `./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample_coredns`
- [x] `./cnf-testsuite host_network`
- [x] I should see results where  it should not check the manually installed coredns using it's own namespace outside of the CNF namespace.
- [x] I can see screenshots of the output here.

**Comment by agentpoyo** [comment]
![1519_results](https://user-images.githubusercontent.com/14348948/176964158-9d0b59e8-c5d1-4beb-bae8-5284ae25cfe0.png)
