### ISSUE TITLE
[Feature] `dangerous_capabilities` should only consider resources that are part of the CNF

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1522]
* `dangerous_capabilities` should only consider resources that are part of the CNF
* Part of #1440

**Comment by HashNuke** [comment]
This ticket is outdated since #1539. Moving this to peer review to review close.

**Comment by agentpoyo** [comment]
Approved as this test was removed. See previous comment and #1539

**Comment by lixuna** [comment]
@HashNuke  @agentpoyo What is the level of effort in pts? (0,1,2,3,5,8,13,21)
