### ISSUE TITLE
[Maintenance] Remove dangerous_capabilities test

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1539]
> *Part of #1551*

The latest Kubescape framework has removed the "Dangerous policies"  definitions.
We will have to remove the test that depends on this definition.

### Info about affected tests

`dangerous_capabilities` - subset of `insecure_capabilities`. So it seems alright to remove this.

### Kubescape & NSA framework versions

```
KUBESCAPE_VERSION = "2.0.158"
KUBESCAPE_FRAMEWORK_VERSION = "1.0.179"
```

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] When I run `./cnf-testsuite network_policies`, I should see that the command is no longer valid.
- [ ] When I run `./cnf-testsuite dangerous_capabilities`, I should see that the command is no longer valid
- [ ] When I run `./cnf-testsuite security`, I should not see these tests run in the category assigned after removal.

**Comment by lixuna** [comment]
https://github.com/cncf/cnf-certification/issues/24
