### ISSUE TITLE
[Feature] Update Kubescape-based `platform:security` tests to use new Kubescape test parser

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1541]
In order to resolve #1518,
1. The Kubescape version had to be updated.
2. [1] required an update of Kiubescape framework too.
3. [2] resulted in platform:security tests breaking - [Build link](https://github.com/cncf/cnf-testsuite/runs/7071558786)

## Test details

* `control_plane_hardening`
* `cluster_admin`
* `exposed_dashboard`

These tests would have to use the new Kubescape test parser instead of depending on the existing `test_passed?` helper.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Setup k8s cluster
- [ ] Setup cnf-testsuite `setup` and then `cnf_setup` sample CNF like coredns.
- [ ] Now run `./cnf-testsuite platform:control_plane_hardening`
- [ ] You should not see any exceptions using the new parser and kubescape updates.
- [ ] Now run `./cnf-testsuite platform:cluster_admin`
- [ ] You should not see any exceptions using the new parser and kubescape updates.
- [ ] Now run `./cnf-testsuite platform:exposed_dashboard`
- [ ] You should not see any exceptions using the new parser and kubescape updates.
- [ ] You can see a screenshot of the output results here.

**Comment by agentpoyo** [comment]
![1541_results](https://user-images.githubusercontent.com/14348948/176959180-7a8f26c1-dc28-44e0-bc57-b89e2c6c27bd.png)
