### ISSUE TITLE
[Feature]  Cluster network inspection tool 

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#1543]
**Is your feature request related to a problem? Please describe.**
The shared_database test is hard to understand

**Describe the solution you'd like**
Refactor the logic of the shared_database test into a tool for inspecting the network of a cluster

**Comment by williscool** [comment]
fixed by #1655 and #1698

**Comment by agentpoyo** [comment]
No AC required, done in https://github.com/cncf/cnf-testsuite/issues/1655
