### ISSUE TITLE
[Maintenance/2022-Q2] Upgrade Kubescape tool and Kubescape NSA framework to the latest version

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1551]
> *Part of #1532. Required for #1440*

## Description

* The tool version should be updated.
* The NSA framework version should be updated.
* The existing tests should be verified for any impact (already being verified as a part of tickets under #1440).

**Comment by HashNuke** [comment]
As a part of this epic:
* Removed `dangerous_capabilities` test and `network_policies` test to reflect the removal in the Kubescape NSA framework. (#1539)
* The `host_network` test should be updated to use the new name ("hostNetwork" is now "HostNetwork" in the control definitions). This has been updated as a part of #1519.
* Verify `symlink_file_system` #1547

The other Kubescape tests were updated and verified as a part of tickets already created for individual tests linked on the #1440 epic.

**Comment by agentpoyo** [comment]
These Kubescape tests have all been individually AC and verified, no AC required for this issue for the upgrade.
