### ISSUE TITLE
[Feature] Support for Fluent Bit for the `routed_logs` test

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1552]
> *Request by MATRIXX Software*

The `routed_logs` test only supports/checks for fluentd currently. It would be helpful to add support for Fluent Bit, which is also a popular tool for routing logs.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Setup or find k8s cluster
- [ ] `./cnf-testsuite install_fluentbit`
- [ ] I should see fluentbit installed on the cluster.
- [ ] `./cnf-testsuite cnf_setup cnf-config=./sample-nfs/sample-fluentbit`
- [ ] `./cnf-testsuite routed_logs`
- [ ] I should see PASS for having fluentbit installed on the cluster.
- [ ] I can see screenshots of the output.
