### ISSUE TITLE
[BUG] Running workload tests without installing a CNF should inform the user to install a CNF and should not result in a crash

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1555]
## Describe the bug

When running workload tests, the test crashes if there is no CNF installed. The user should be informed that the test requires a CNF to be installed.

> *Came across this a few times. Sagar@Nirmata also found this issue during our pairing session.*

<img width="1098" alt="CleanShot 2022-07-06 at 19 05 12@2x" src="https://user-images.githubusercontent.com/84005/177563582-bec1abd5-4ab1-4964-b521-16581a1784b0.png">

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] find or create k8s cluster
- [ ] Setup cnf-testsuite and run `setup`
- [ ] Do not install a CNF but rather start a platform test.
- [ ] The testsuite should run the test without the need or error of no CNF installed.

**Comment by agentpoyo** [comment]
![1555_output](https://user-images.githubusercontent.com/14348948/222243108-14ecd0cd-13e3-4cbe-b391-400d408d883f.jpg)

**Comment by lixuna** [comment]
@williscool @agentpoyo what was the level of effort in points for this issue (0,1,2,3,5,8,13)?

**Comment by agentpoyo** [comment]
3pts
