### ISSUE TITLE
[Research] Estimate and test HTTP_PROXY with cnf-testsuite

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1556]
**Describe the solution you'd like**
Implement cnf-testsuite using HTTP PROXY configurations.

```
$ cnf-testsuite setup
Successfully created directories for cnf-testsuite
Global helm found. Version: v3.7.1
No Local helm version found
Global kubectl found. Version: 1.22
No Local kubectl version found
Global git found. Version: 2.31.1
No Local git version found
All prerequisites found.
cnf-testsuite namespace already exists on the Kubernetes cluster
/usr/share/crystal/src/gc/boehm.cr:110:5 in 'io'
/usr/share/crystal/src/http/client.cr:671:19 in 'send_request'
/usr/share/crystal/src/http/client.cr:651:20 in 'perform'
/usr/share/crystal/src/log/main.cr:38:3 in '->'
/workspace/lib/sam/src/sam/task.cr:44:29 in 'call'
/workspace/lib/sam/src/sam/execution.cr:20:7 in '__crystal_main'
/usr/share/crystal/src/crystal/main.cr:110:5 in 'main'
src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
Error connecting to 'github.com:443': Operation timed out
```

**Comment by wavell** [comment]
We confirmed that only the installs of upstream projects is failing.  The test suite can actually run if upstream projects are installed.  We think the work to update just the installs of the upstream projects is worth about 5 points

**Comment by lixuna** [comment]
@denverwilliams @wavell @agentpoyo Please disable the test proxy server ASAP.

**Comment by taylor** [comment]
@denverwilliams @agentpoyo Or limit access / create authentication controls

**Comment by lixuna** [comment]
@wavell Thanks for estimating the effort to update upstream project installs.  I'd suggest creating a new issue for implementing any enhancements related to HTTP PROXY configurations - to be prioritized.

**Comment by denverwilliams** [comment]
@lixuna Proxy is shutdown and this ticket is complete in regards to estimating effort.

**Comment by agentpoyo** [comment]
AC and peer review will occur in https://github.com/cncf/cnf-testsuite/issues/1568
