### ISSUE TITLE
[Feature] Move TarClient in Separate Repo

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#1563]
**Is your feature request related to a problem? Please describe.**
The current libraries in ./util are being maintained solely by Vulk.

**Describe the solution you'd like**
Put tarclient that is currently in the ./utils directory into its own repo
Set up github actions for each tarclient
Library should be searchable in https://crystalshards.org/

**Comment by taylor** [comment]
Move it to https://github.com/organizations/cnf-testsuite/repositories/new

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Checkout `main` branch of the cnf-testsuite repository on a machine that is setup with crystal.
- [ ] Run `shards install` and you should see that the tar client is installed without errors from it's own repo.
- [ ] You can now run `workload` or `cert` commands to verify no tests break using tar

**Comment by agentpoyo** [comment]
![1563_shards_install](https://user-images.githubusercontent.com/14348948/182227263-8f1583db-3375-4261-8c08-6d7f186526d2.png)
