### ISSUE TITLE
[Feature] Move kubectl library to separate repo

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#1564]
Is your feature request related to a problem? Please describe.
The current libraries in ./util are being maintained solely by Vulk.

Describe the solution you'd like
Put kubectl that is currently in the ./utils directory into its own repo
Set up github actions for each kubectl
Library should be searchable in https://crystalshards.org/

related to #943

**Comment by taylor** [comment]
Create new repo under https://github.com/organizations/cnf-testsuite/repositories/new

**Comment by agentpoyo** [comment]
A new duplicate was created at https://github.com/cncf/cnf-testsuite/issues/1642

**Comment by agentpoyo** [comment]
AC will be in https://github.com/cncf/cnf-testsuite/issues/1642
