### ISSUE TITLE
[BUG] Fix typos of "rational" to "rationale" in LIST_OF_TESTS.md

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1565]
**Describe the bug**
In https://github.com/cncf/cnf-testsuite/blob/main/docs/LIST_OF_TESTS.md, the word "rationale" is misspelled as "rational"

**To Reproduce**

1. Go to https://github.com/cncf/cnf-testsuite/blob/main/docs/LIST_OF_TESTS.md
2. Scroll down to every test, starting with https://github.com/cncf/cnf-testsuite/blob/main/docs/LIST_OF_TESTS.md#increase-decrease-capacity
3. See error `Rational & Reasoning`

**Expected behavior**
Replace all instances of `Rational & Reasoning` with `Rationale & Reasoning`

**How will this be tested? aka Acceptance Criteria (optional)**
1. Go to https://github.com/cncf/cnf-testsuite/blob/main/docs/LIST_OF_TESTS.md
2. Scroll down to every test, starting with https://github.com/cncf/cnf-testsuite/blob/main/docs/LIST_OF_TESTS.md#increase-decrease-capacity
3. I can see that all instances of `Rational & Reasoning` are replaced with `Rationale & Reasoning`

**Screenshots**
![Screen Shot 2022-07-14 at 11 28 06 AM](https://user-images.githubusercontent.com/11701267/179031446-ca42f9f8-f3f8-40fc-9497-067a72fc7827.png)

**Comment by agentpoyo** [comment]
@lixuna https://github.com/cncf/cnf-testsuite/pull/1566

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] When I view https://github.com/cncf/cnf-testsuite/blob/main/docs/LIST_OF_TESTS.md I should see that Rationale is not spelled as Rational for each of the tests linking back to the RATIONALE.md documentation.

**Comment by lixuna** [comment]
LGTM, thanks
