### ISSUE TITLE
[Feature] Add support for custom registries for third-party tools like Prometheus

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1571]
## Description

To avoid supply chain disruptions, users may use third-party tools like Prometheus from different/self-hosted registry other than the public registry. Container images of tools are re-tagged and pushed to these self-hosted registries.

1. As demonstrated in #1567, re-tagging an image changes the SHA of an image.
2. Any tests we have that check of third-party tools, fetches image digests from quay or the public registry of the tool. These digests do not match with the container image digest of the containers running on the cluster due to [1] mentioned above.

## Proposed solution

Allow users to override registry urls for certain tools in the `cnf-testsuite.yml` file.

```
image_repositories:
  prometheus: "http://localhost:5000/prometheus"
```

**Comment by HashNuke** [comment]
Checked the API docs for different registries. Looks like they are all different and there is no standard API for container registries. Support for custom registries is going to be difficult to implement (in terms of time/trade-off).

Given this scenario, I would rather add support for setting prometheus service/urls directly in the config. Will attempt that and then Create a new issue.

**Comment by agentpoyo** [comment]
No AC required for this issue.
