### ISSUE TITLE
[Feature] Allow users to configure Prometheus endpoint in testsuite config file

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1572]
## Description

> This ticket is to help close #1567

To avoid supply chain disruptions, users may use third-party tools like Prometheus from different/self-hosted registry other than the public registry. Container images of tools are re-tagged and pushed to these self-hosted registries.

1. As demonstrated in #1567, re-tagging an image changes the SHA of an image.
2. We fetch image digests from quay for Prometheus. These digests do not match with the container image digest of the Prometheus containers running on the cluster due to [1] mentioned above.

## Proposed solution

Allow users to specify prometheus endpoint in the `cnf-testsuite.yml` file.

```
prometheus_endpoint: "http://prometheus.tools.svc.cluster.local"
```

**Comment by denverwilliams** [comment]
@HashNuke We talked about implementing a different solution to fix the SHA issue. We want to avoid adding additional configuration where possible. I'll open a ticket do document what we talked about doing to fix this.

**Comment by denverwilliams** [comment]
Closed in favour of new ticket https://github.com/cncf/cnf-testsuite/issues/1581
