### ISSUE TITLE
[BUG] falco tools not uninstalled when `cleanup_all` invoked with the testsuite

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1579]
**Describe the bug**
If Falco is installed during the `./cnf-testsuite` process, it does not get uninstalled or removed when `cleanup_all` is used to remove all cnf-testsuite tools installed as dependencies for tests.

**To Reproduce**
Install_falco and then run `cleanup_all`, you'll see falco continues to run.

**Expected behavior**
`cleanup_all` should remove all cnf-testsuite tools dependencies.

**Screenshots**
![cleanup_all_falco_not_removed](https://user-images.githubusercontent.com/14348948/180860934-0483d197-21ba-4be8-b190-506fb9846602.png)

**Comment by HashNuke** [comment]
Also found #1586 that needed to be fixed in order to resolve this issue. Changes for both the issues are in the same PR (1587).

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] When all the tools are installed from running `cnf-testsuite`, when I run `cleanup_all`, I should see all the tools installed into the cnf-testsuite namespace terminated and removed.
- [ ] I can see a screenshot of all the tools removed after running `cleanup_all`

**Comment by agentpoyo** [comment]
![1579_falco_cleanup](https://user-images.githubusercontent.com/14348948/182457197-ab601809-13ae-4d6a-8c14-4111658c6028.png)
