### ISSUE TITLE
[BUG] Replace any usage of SHA searches with the new process search module

### ISSUE THREAD

**Issue by denverwilliams** [cncf/cnf-testsuite#1581]
**Describe the bug**

Ticket to complete before starting this: https://github.com/cncf/cnf-testsuite/issues/1580

Replace any usage of SHA searches with the new process search module.

e.g. What needs to be to replaced https://github.com/cncf/cnf-testsuite/blob/8f5de840d0cae0c7e0b871adfca07c471b475edd/src/tasks/workload/observability.cr#L63
```
      prometheus_server_releases = resp.body
      sha_list = named_sha_list(prometheus_server_releases)
      imageids = KubectlClient::Get.all_container_repo_digests
      match = DockerClient::K8s.local_digest_match(sha_list, imageids)
```
**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

- OS [e.g. Linux, iOS, Windows, Android]
- Distro [e.g. Ubuntu]
- Version [e.g. 18.04]
- Architecture [e.g. x86, arm]

**How will this be tested? aka Acceptance Criteria (optional)**

(optional: unnecessary for things like spelling errors and such)

Once this issue is address how will the fix be verified?

**Additional context**

---

NOTE: you can enable higher logging level output via the command line or env var. to help with debugging

```
# cmd line
./cnf-testsuite -l debug test

# make sure to use -- if running from source
crystal src/cnf-testsuite.cr -- -l debug test

# env var
LOGLEVEL=DEBUG ./cnf-testsuite test
```

Also setting the verbose option for many tasks will add extra output to help with debugging

```
crystal src/cnf-testsuite.cr test_name verbose
```

Check [usage documentation](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) for more info about invoking commands and logging

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Setup cnf-testsuite on k8s cluster
- [ ] Install prometheus outside of cnfspace onto the cluster with helm install. `helm install kube-state-metrics prometheus-community/prometheus`
- [ ] Verify prometheus is running after a few minutes with `kubectl get pods`
- [ ] You should see the test `prometheus_traffic` skip if prometheus is not on the cluster.
- [ ] You should see the test `prometheus_traffic` PASS or FAIL if found, FAIL if not traffic is being sent (which is normal on a local kind install where we have tested)
- [ ] I can see screenshot of the output.

**Comment by agentpoyo** [comment]
Prometheus found but not sending traffic.

![1581_prom_failed_sha_pid](https://user-images.githubusercontent.com/14348948/192645277-0ae984b6-13f1-4959-b37d-704272f4d4b0.png)

**Comment by agentpoyo** [comment]
Prometheus uninstalled; skipped:

![1581_prom_removed_skipped](https://user-images.githubusercontent.com/14348948/192646504-bb19dc44-9072-4425-b60a-0cc667c83610.png)

**Comment by lixuna** [comment]
@denverwilliams @wavell @agentpoyo what is the level of effort in points for this issue (0,1,2,3,5,8,13)?

**Comment by agentpoyo** [comment]
5pts
