### ISSUE TITLE
[BUG] OPA Gatekeeper helm install takes 5min to complete (versioned_tag test)

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1582]
**Describe the bug**
* The `versioned_tag` test requires OPA Gatekeeper to be installed. This is installed via the `install_opa` task as a dependency.
* The helm install takes about 5min to complete. Upon using the debug flag for the helm install, it is visible that one of the jobs times out.

Further checks revealed that
* The `gatekeeper-update-namespace-label` job has an error trying to access a service account that does not exist.
* The service account that the job is trying to access is `gatekeeper-update-namespace`.

**To Reproduce**
* Run `versioned_tag` test after installing a CNF.
* OR directly run the helm command used to install gatekeeper: `helm install --set auditInterval=1 opa-gatekeeper gatekeeper/gatekeeper --debug`

**Expected behavior**
The gatekeeper install should be faster.

**Comment by HashNuke** [comment]
Added issue notes to [hackmd doc](https://hackmd.io/M7qWnl5sRKCGBkCCXK190w).

**We have two ways to resolve this:**
1. Pass the flag to helm install to disable the gatekeeper-namespace-label-update job.
2. Send a PR to the gatekeeper helm chart repo to update the order of specs in the `namespace-post-install.yml` file.

More details are on the hackmd doc.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] When installing OPA gatekeeper, it should not take more than 5 minutes to install.
- [ ] Run `install_opa` and time it using the `time` command.
- [ ] I can see that the install takes less than 5 minutes.
- [ ] I can see a screenshot of the results here.

**Comment by agentpoyo** [comment]
![1582_opa_time](https://user-images.githubusercontent.com/14348948/182461521-0226f446-cc53-4a93-9db7-08439ec1d4df.png)
