### ISSUE TITLE
[BUG] When cleaning up tools in `tools_cleanup`, local helm should be uninstalled last

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1586]
> *Found this when looking into #1579*

**Describe the bug**
* When `cleanup_all` is run, the third-party tools installed are also expected to be cleaned up (via the dependency task `tools_cleanup`).
* The `tools_cleanup` task, uninstalls local helm first, before running the uninstall for other tools (for example OPA Gatekeeper). As a result, uninstall for any tool that requires helm would fail.

![CleanShot 2022-08-01 at 13 26 52@2x](https://user-images.githubusercontent.com/84005/182101130-ca1d6668-dd88-458a-bac0-585a33fa5002.png)

**To Reproduce**
* Run the cert command for any CNF.
* Run `LOG_LEVEL=info ./cnf-testsuite cleanup_all`
* The helm command would fail when parts of the code tries to run helm delete to uninstall the third-party tools.

**Expected behavior**

Local helm should be uninstalled last.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Make sure helm is not in your path or on OS (globally installed).
- [ ] Make sure tools/helm exists, run `setup` to install if necessary.
- [ ] Setup and install OPA, `install_opa` and verify it's installed with `kubectl get pods` output
- [ ] Now run `LOG_LEVEL=info ./cnt-testsuite cleanup_all`
- [ ] I should not see any helm errors and OPA should be terminated and removed.
- [ ] I can see screenshots of the output here of successful tools cleanup.

**Comment by agentpoyo** [comment]
![1586_cleanup_helm_last](https://user-images.githubusercontent.com/14348948/182466686-0f7f7e86-7a1a-4db8-8c9e-b4ec11495ba8.png)

![1586_loglevel_cleanupall](https://user-images.githubusercontent.com/14348948/182466707-bef9c97d-32e8-4ef0-b4c5-ffb504388f87.png)

![1586_loglevel_cleanupall_good](https://user-images.githubusercontent.com/14348948/182466723-dbf66d3c-f7e0-46d7-a436-8dd78cc0f941.png)
