### ISSUE TITLE
[BUG] No longer showing "found containers" for FAILED test(s)

### ISSUE THREAD

**Issue by EricLo-417** [cncf/cnf-testsuite#1595]
**Describe the bug**
Instead of showing the found containers that caused the test to fail, it logs nothing.

**To Reproduce**

1. Run test that will fail (this example will use "privilege_escalation")
2. Look at result

**Expected behavior**
It will list the found containers

**Additional context**
This seemed to start with version 0.31 and continues to version 0.32
I believe this affects all tests that find containers, but I ran the "privilege_escalation" test in 0.32.
It also did not log containers in 0.31 for non-root-containers.

![image](https://user-images.githubusercontent.com/99511419/182863339-1851458e-30db-4cbb-8552-48e10ce00695.png)

**Comment by HashNuke** [comment]
**Update**
The root-cause of this issue was affecting a few other tests too. This has been fixed in PR #1606.
The bug reported in this ticket should be resolved once the PR is merged.

**Comment by agentpoyo** [comment]
No AC required as these were done in https://github.com/cncf/cnf-testsuite/issues/1603
