### ISSUE TITLE
[BUG] hash data error when running `cert` or `cni_compatible` tests

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1601]
**Describe the bug**
Seeing crystal `Missing hash key: "data"` errors when running `cert` or `cni_compatible` tests

**To Reproduce**
Run `cert` or `cni_compatible` tests

**Expected behavior**
We should not see any errors.

**Screenshots**
![cni_hash_error](https://user-images.githubusercontent.com/14348948/184713308-de8dd5c2-724a-4a1d-9c32-301e99e79c92.png)

**Comment by macaktom** [comment]
I tried to reproduce it, but couldn't. What setup was used here?

Specs:
Ubuntu 22.04.3
minikube
kubernetes v1.28.3 without Calico CNI
crystal 1.11.1
cnf-testsuite v0.45.0
![cert-coredns](https://github.com/cncf/cnf-testsuite/assets/43893713/a9d07b79-a9fd-44d0-8499-de6283ea8e44)

**Comment by lixuna** [comment]
@agentpoyo has this issue been resolved? See above, [macaktom](https://github.com/macaktom) was not able to recreate the bug. Thanks for your help!

**Comment by agentpoyo** [comment]
> @agentpoyo has this issue been resolved? See above, [macaktom](https://github.com/macaktom) was not able to recreate the bug. Thanks for your help!

I believe it was. Let me track down the issue that this was fixed, etc. @lixuna

**Comment by agentpoyo** [comment]
We can close this. Not sure which BUG fixed it directly as we had several merges to address similiar hash issues. We can reopen if we encounter this "hash" error again.
