### ISSUE TITLE
[BUG] Display failed resources for Kubescape-based tests

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1603]
> *Identified during #1595*

## Describe the bug
* The "alertMessage" in the Kubescape test report is an empty string.
* Previously this was being populated for a few tests, but in the latest test Kubescape reports, the alertMessage is empty for all the Kubescape-based tests that we use in the testsuite.

## To Reproduce

The below test would fail as expected. But the failed resources would not be output. This is because the test is outputting blank strings.

```
./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample-privilege-escalation/cnf-testsuite.yml
./cnf-testsuite privilege_escalation
./cnf-testsuite cnf_cleanup cnf-config=./sample-cnfs/sample-privilege-escalation/cnf-testsuite.yml
```

## Expected behavior
For any Kubescape-based test, the list of failed resources must be output, along with their namespace (namespace if applicable).

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Run `./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample-privilege-escalation/cnf-testsuite.yml`
- [ ] Now run the `privilege_escalation` test
- [ ] The sample should provide output for the FAILED test
- [ ] I can see a screenshot of the FAIL here and output

**Comment by agentpoyo** [comment]
![1603_results](https://user-images.githubusercontent.com/14348948/186752243-c5936838-3755-4232-a189-e4b24887b657.png)
