### ISSUE TITLE
[BUG] `setup` causes SSL_connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed

### ISSUE THREAD

**Issue by geetamakineni** [cncf/cnf-testsuite#1613]
**Describe the bug**
Trying to run cnf-testsuite in our local environment, and we keep getting
zsh: exec format error: cnf-testsuite error causing the set up to fail.
And when running it on the AWS Environment, the below error pops up.
SSL_connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
which causes the set up to fail

**To Reproduce**
It is currently failing on the following command cnf-testsuite setup. We are using VS Code locally and AWS.

**Screenshots**

![Screen Shot 2022-08-29 at 9 37 48 AM](https://user-images.githubusercontent.com/59195740/187295652-bc1c0b1c-930c-40cd-8dfc-845eb9249c3c.png)
![Screen Shot 2022-08-29 at 9 39 29 AM](https://user-images.githubusercontent.com/59195740/187295698-4dcca21f-43e4-43ad-bdb8-19ec69ec84e5.png)

**Device (please complete the following information):**

- OS - Mac OS 
- Distro - mac OS
- Version- 12.5.1 
- Architecture - Arm x64 M1 chip
- Browser - Chrome

**Comment by agentpoyo** [comment]
Hello @geetamakineni ,

We have a similiar issue opened already that is currently in progress about SSL certificate. I believe this is the same issue you are seeing when running setup.

If you are using AWS instance images, I believe they are based on Red Hat and that is why you are seeing this currently. Can you confirm what the OS is that you are attempting to run from?

Related issue #: https://github.com/cncf/cnf-testsuite/issues/1464

**Comment by geetamakineni** [comment]
Hi @agentpoyo 
We are using a Linux Platform for the instance. I attached the screenshot below.
<img width="399" alt="Screen Shot 2022-08-30 at 11 42 53 AM" src="https://user-images.githubusercontent.com/59195740/187506702-40b776e9-3684-4632-8fc0-d28bbb0ce71a.png">

And apart from the AWS setup, we are also trying a local setup of the test suite using VS Code and we see zsh: exec format error: cnf-testsuite error. Can you also please look into this. 
This error also occurs when We are running the cnf-testsuite setup command.
There is a screenshot of this attached baove.

**Comment by agentpoyo** [comment]
Hello @geetamakineni 

> And apart from the AWS setup, we are also trying a local setup of the test suite using VS Code and we see zsh: exec format error: cnf-testsuite error. Can you also please look into this.

If this is using MacOS, unfortunately MacOS is not currently supported.

**Comment by agentpoyo** [comment]
Hello @geetamakineni 

We just created a patch that should address the SSL error on your AWS instance when setting up the cnf-testsuite. I plan to spin up an AWS instance to test and verify today and can provide the binary once vetted that it's working.

Thanks.

**Comment by agentpoyo** [comment]
@geetamakineni 

I've verified AWS instance images and it appears they tag their OS as "amzn". So we'll have to fix this in the code to apply the same patch we did for RHEL based systems.

**Comment by geetamakineni** [comment]
@agentpoyo 

Thanks for looking into the error. Let me know once you have resolved the error so maybe I can try it again.

**Comment by agentpoyo** [comment]
@geetamakineni 

Here is the latest patch binary you can use that should work on your Amazon AWS instances to test the testsuite:

SHA256SUM: 3c338260ada0b9256976163ec84979524ae5007811790eef467c7d7327ec4564  cnf-testsuite-v0.32.3.tar.gz
[cnf-testsuite-v0.32.3.tar.gz](https://github.com/cncf/cnf-testsuite/files/9481259/cnf-testsuite-v0.32.3.tar.gz)

We'll have this likely published soon under our releases.

**Comment by agentpoyo** [comment]
This has been verified with the release of the patch binary v0.32.3 of cnf-testsuite. No AC required. AC steps will be done in https://github.com/cncf/cnf-testsuite/issues/1619

**Comment by geetamakineni** [comment]
I have tried to run with the binary patch you provided. But it still is giving the same error as above. Can we setup some time to have a meet virtually, so we can check it merely.

**Comment by agentpoyo** [comment]
Hello @geetamakineni 

You can use https://calendly.com/cnfcertification/contributing?month=2022-09 to schedule a meetup if that works with you. We also have weekly meetings on Thursdays for the Testsuite starting at 9:15AM Central Time. I can provide the link to the Zoom Meeting if that's an option you like as well.

**Comment by geetamakineni** [comment]
Hey @agentpoyo 
Sure, I have scheduled a meeting tomorrow at 2pm MST.

**Comment by agentpoyo** [comment]
> Hey @agentpoyo Sure, I have scheduled a meeting tomorrow at 2pm MST.

Sounds good! :+1:

**Comment by agentpoyo** [comment]
Hello @geetamakineni 

Out of curiosity, can you paste the /etc/os-release from the machine you're running the cnf-testsuite from here? 

Thanks.

**Comment by agentpoyo** [comment]
This has been verified by the end user that they are not seeing the SSL error any longer, the issue was they didn't have connection to their k8s cluster.
