### ISSUE TITLE
[BUG] single_process_type outputs unnecessary info to stdout

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1622]
**Describe the bug**
`single_process_type` outputs white-lines to stdout. This info that shouldn't be a part of the default test result output for cert.

![CleanShot 2022-09-06 at 06 05 26](https://user-images.githubusercontent.com/84005/188524038-2be1dbcb-2d7e-4896-af89-33a592aedf51.png)

**To Reproduce**
```
./cnf-testsuite cnf_setup cnf-path=sample-cnfs/sample_coredns
./cnf-testsuite cert
```

**Expected behavior**
The white-lines should not be output when running this test.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Setup k8s cluster
- [ ] Setup cnf-testsuite using INSTALL instructions (pull latest main branch from source install that hold these updates)
- [ ] Run `./cnf-testsuite cnf_setup cnf-path=sample-cnfs/sample_coredns` and then `cert`
- [ ] Run `./cnf-testsuite single_process_type` test 
- [ ] I should see no white line stdout on the console, only if the test PASS, FAIL or SKIPS
- [ ] I can see a screenshot of the output without stdout white INFO type text for the processes found.

**Comment by agentpoyo** [comment]
![1622_singleProcesstype](https://user-images.githubusercontent.com/14348948/192373353-05ec3c13-dc9b-4765-ba31-95a29ac63cc4.png)

**Comment by agentpoyo** [comment]
![1622_singleProcesstype_cert_output](https://user-images.githubusercontent.com/14348948/192374985-a85ff69d-4a5f-42af-8462-fb13ec70f997.png)

**Comment by lixuna** [comment]
@HashNuke @denverwilliams @wavell @agentpoyo what is the level of effort in points for this issue (0,1,2,3,5,8,13)?

**Comment by agentpoyo** [comment]
3pts
