### ISSUE TITLE
[BUG] When `cnf-testsuite` namespaces are not found, tools installations fail after a preliminary `setup` has already been ran, etc

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1624]
**Describe the bug**
When the `cnf-testsuite` namespace is removed, deleted or not found for any reason after a successful `setup` and or tests run, the testsuite will fail to install required tools, eg `cluster_tools` when a test requires them with namespace not found errors:

```
I, [2022-09-07 11:40:18 +00:00 #2235622]  INFO -- cnf-testsuite: install_cluster_tools                                                                                                                                            I, [2022-09-07 11:40:18 +00:00 #2235622]  INFO -- cnf-testsuite: ClusterTools install                                                                                                                                             
I, [2022-09-07 11:40:18 +00:00 #2235622]  INFO -- cnf-testsuite: KubectlClient::Apply.file command: kubectl apply -n cnf-testsuite -f cluster_tools.yml                                                                           I, [2022-09-07 11:40:18 +00:00 #2235622]  INFO -- cnf-testsuite: KubectlClient::Apply.file stderr: Error from server (NotFound): error when creating "cluster_tools.yml": namespaces "cnf-testsuite" not found 
```

**To Reproduce**
Setup cnf-testsuite, perform a `setup` and then any tests. Delete the cnf-testsuite namespace and attempt to run a test that requires tools like `cluster_tools` like `routed_logs`, you will see errors of the `cnf-testsuite` namespaces not found.

**Expected behavior**
The testsuite should recreate the required namespaces for our tools without the user needing to run `setup` or other preliminary tasks again.

**Comment by williscool** [comment]
https://github.com/cncf/cnf-testsuite/pull/1746


https://github.com/cnf-testsuite/cluster_tools/pull/12

**Comment by williscool** [comment]
![image](https://user-images.githubusercontent.com/394931/220212379-620048cc-b4ee-4500-b621-5ea947f7cfc5.png)

**Comment by agentpoyo** [comment]
![1624_results](https://user-images.githubusercontent.com/14348948/236464405-5905595f-7bc9-4dd0-bace-8c5b69a95cd5.jpg)
