### ISSUE TITLE
[BUG] host_network test should not uninstall ClusterTools

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1626]
**Describe the bug**
The `host_network` test currently has `uninstall_cluster_tools` as a dependency task. This dependency is a relic and was added to prevent cluster tools from resulting in failure of the test. This is not required anymore since the testsuite now filters the Kubescape test report before deciding on result of the test.

In its current state, whenever `host_network` is run, cluster tools is uninstalled. This causes issues when other tests that require ClusterTools are also run individually after running the `host_network` test.

**To Reproduce**
1. Run the host_network test
2. Run any other test that requires cluster tools (example: `prometheus_traffic`)

**Expected behavior**
Any test that requires cluster tools should run as expected after host_network is run (order of tests should not matter when running them individually).

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Setup k8s cluster
- [ ] Setup cnf-testsuite using INSTALL instructions (pull latest main branch from source install that hold these updates)
- [ ] Run `./cnf-testsuite cnf_setup cnf-path=sample-cnfs/sample_coredns`
- [ ] Run `./cnf-testsuite host_network`
- [ ] Verify that cluster_tools is not uninstalled by doing a `kubectl get pods --all-namespaces`
- [ ] I can see results screenshot here from above command that displays the cluster_tools running.

**Comment by agentpoyo** [comment]
![1626_host_network](https://user-images.githubusercontent.com/14348948/192369487-f1d01085-c00b-4aae-8c9a-e226f7615211.png)
