### ISSUE TITLE
[Feature] Move docker library to separate repo

### ISSUE THREAD

**Issue by williscool** [cncf/cnf-testsuite#1629]
Is your feature request related to a problem? Please describe.
The current libraries in ./util are being maintained solely by Vulk.

Describe the solution you'd like
Put docker that is currently in the ./utils directory into its own repo

Set up github actions for each git

Library should be searchable in https://crystalshards.org/

related to https://github.com/cncf/cnf-testsuite/issues/943

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [x] When installing from source, I should see the docker_client get pull down during the `shards install` step as a separate crystal module
- [x] I can see screenshots of the output here of the shards install.

**Comment by agentpoyo** [comment]
![1642_kubectl_shards](https://user-images.githubusercontent.com/14348948/192367430-e9b9bf22-a6b6-40b8-bd55-f4dad40158c1.png)
