### ISSUE TITLE
[BUG] GitHub Actions Runner image docker build fails with an error

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1630]
## Describe the bug

Docker fails to build the GitHub Actions Runner image with an error (Screenshots below).

```
docker build -t $IMAGE_NAME tools -f tools/github-runner/Dockerfile
```

```
#6 7.608 Reading package lists...
#6 8.705 W: GPG error: https://cli.github.com/packages stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23F3D4EA75716059
#6 8.705 E: The repository 'https://cli.github.com/packages stable InRelease' is not signed.
------
executor failed running [/bin/bash -o pipefail -c apt-get install apt-transport-https --yes &&     curl https://baltocdn.com/helm/signing.asc | apt-key add - &&     echo "deb https://baltocdn.com/helm/stable/debian/ all main" | tee /etc/apt/sources.list.d/helm-stable-debian.list &&     apt-get update &&     apt-get install helm uuid-runtime &&     ln -s /usr/bin/python3 /usr/bin/python]: exit code: 100
```

## Screenshots

![CleanShot 2022-09-08 at 13 22 19](https://user-images.githubusercontent.com/84005/189066548-7b59b670-aa45-40b2-b285-907eb9b607ad.png)

![CleanShot 2022-09-08 at 13 22 31](https://user-images.githubusercontent.com/84005/189066597-808675dd-d0c0-4c1b-917c-8870236e7045.png)

**Comment by HashNuke** [comment]
Resolved this by adding the github gpg key in the runner image. Will combine the change for this issue in the PR along with changes for #1631

**Comment by agentpoyo** [comment]
No AC required, this fix made it possible to get the github runners to pickup jobs to run.
