### ISSUE TITLE
[BUG] `open_metrics` test is being skipped

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1644]
## Describe the bug
> *Issue reported by @iElephant on #1623 in the comments.*
> 
> Another side effect observed is that the open_metrics test case will be always skipped as the prometheus_traffic is a dependency task of open_metrics.

## To reproduce

![CleanShot 2022-09-19 at 17 50 55@2x](https://user-images.githubusercontent.com/84005/191015934-108fd9bf-22f6-4152-b682-ba3607bb9591.png)

**Comment by HashNuke** [comment]
![CleanShot 2022-09-19 at 17 53 57@2x](https://user-images.githubusercontent.com/84005/191016503-df28c242-bed7-4d7b-a9ca-f1a1ae263b30.png)

**Comment by HashNuke** [comment]
The error has something to do with the metric names. openmetricsvalidator does not like metrics which have the same name as another metric without the suffix.

![CleanShot 2022-09-22 at 10 23 10@2x](https://user-images.githubusercontent.com/84005/191661936-4c261d1b-598c-42b2-befc-140605e49e42.png)

**Comment by HashNuke** [comment]
The above issues with the invalid metrics output needs to be fixed in coredns itself.

**Comment by HashNuke** [comment]
Verified with the OpenMetrics standards doc.

<img width="938" alt="CleanShot 2022-09-22 at 10 33 50@2x" src="https://user-images.githubusercontent.com/84005/191662612-a3c9a5d4-edac-48b8-bae6-eb3872b3efcb.png">

**Comment by HashNuke** [comment]
@iElephant as of now, the cnf-testsuite can only run multiple tests if the task names are separated by `@`. This is a limitation of the library we use ([sam.cr](https://github.com/imdrasil/sam.cr)). Found this today.

**Example that works:**
```
./cnf-testsuite prometheus_traffic @ open_metrics
```

Based on a quick check that I ran, we haven't documented this anywhere in the testsuite. I wouldn't recommend documenting the above usage this this isn't make-like and might confuse users.

If there is anything else, please do let us know. Else our team will proceed to close this ticket in a few days.

## Notes on different scenarios

```
./cnf-testsuite prometheus_traffic open_metrics
# Runs only prometheus_traffic test because open_metrics is passed as task args to the prometheus_traffic test (which is ignored).

./cnf-testsuite open_metrics prometheus_traffic
# Runs prometheus_traffic test because open_metrics depends on prometheus_traffic test
# prometheus_traffic is passed as task args to the open_metrics test, which is ignored.
```

<img width="1045" alt="CleanShot 2022-09-22 at 16 36 12@2x" src="https://user-images.githubusercontent.com/84005/191731249-f2520e3a-0389-4f0b-a399-2450a5a114fe.png">

**Comment by HashNuke** [comment]
@agentpoyo @lixuna No code changes to be made for this issue. I would recommending moving to close this after peer review.

**Comment by agentpoyo** [comment]
![1644_metrics](https://user-images.githubusercontent.com/14348948/192372191-f7160844-1fcf-4d82-b3da-35c8f28b26ce.png)
