### ISSUE TITLE
[BUG] Extended relative path in cnf-testuiste.yaml helm_directory doesn't work

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#1645]
**Describe the bug**
 Extended relative path in cnf-testuiste.yaml helm_directory doesn't work see #1636 

**To Reproduce**

1.  Create a source helm directory that descends multiple directories  (e.g. tar/repo/helm)
2.  Create a cnf-testsuite.yml file that has the relative path that descends multiple directories
3.  Install the cnf

**Expected behavior**
Cnf should install

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Setup k8s
- [ ] Install cnf-testsuite using source install with branch changes
- [ ] Create a CNF that has a cnf-testsuite.yml config that is not in the same directory as the helm charts directory
- [ ] When I run `./cnf-testsuite cnf_setup cnf-config=sample/cnf/cnf-testsuite.yml`, I should see the CNF install without errors
- [ ] I can see a screenshot of the successful install here.

**Comment by agentpoyo** [comment]
![1645_path_helm_chart](https://user-images.githubusercontent.com/14348948/192635792-64f3fb8f-5aec-493a-828c-7cb2ff1aefef.png)
