### ISSUE TITLE
[Feature] Extract Cluster tools to its own library

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#1653]
**Is your feature request related to a problem? Please describe.**
Cluster tools is tightly coupled with the code base

**Describe the solution you'd like**
Extract Cluster tools to its own library

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Checkout the `main` branch source and follow the install instructions for cnf-testsuite
- [ ] When you run `shards install`, you should see that `cluster_tools` is now a crystal module that gets pulled down as a shard
- [ ] You can see screenshots of the shards output here that `cluster_tools` is now a shard.
- [ ] Running tests and or `cert`, `workload` should run successfully without helm errors.

**Comment by agentpoyo** [comment]
![shards_install](https://user-images.githubusercontent.com/14348948/195727783-fa5bb6d8-032a-482e-a8cb-e1217925fbe6.png)
