### ISSUE TITLE
[Feature] Extract Kernel Introspection to its own library

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#1654]
** depends on cluster tools **

**Is your feature request related to a problem? Please describe.**
Kernel Introspection is tightly coupled with the code base

**Describe the solution you'd like**
Extract Kernel Introspection to its own library

**Comment by agentpoyo** [comment]
![shards_install_output](https://user-images.githubusercontent.com/14348948/206011700-ae7f2e00-a12f-4082-8522-f1fa04562193.jpg)
