### ISSUE TITLE
[Feature] Extract Netstat to its own library

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#1655]
**depends on kernel introspection **

**Is your feature request related to a problem? Please describe.**
Netstat is tightly coupled with the code base

**Describe the solution you'd like**
Extract Netstat to its own library

**Comment by williscool** [comment]
making new libraries

## k8s_kernel_introspection

uses kernel_introspection to interact with k8s api (move the k8s code out of kernel_introspection)

## k8s_netstat

netstat code lives here

abstracts out

131 to 149 of

src/tasks/workload/microservice.cr

aka passing in a list of pods

get their container statues

and run netstat code on that

note: look at 36 to 50 of src/tasks/workload/microservice.cr for inspiration

**Comment by williscool** [comment]
1. figure out how to install and uninstall the sample cnfs with just the helm library.. once that works
2. port over the code that gets a list of mariadb pods and genelize it
3. take that list of pods get there staueses



the folowing step is next!

1. take those statuts and run netstat
2. test that out put and the other stuff along hte way

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Find a k8s cluster and checkout latest `main` or `branch` code with changes
- [ ] Run `shards install` 
- [ ] You should see the netstat crystal module in the list of shards installing from it's own repo
- [ ] You should see no errors on output and build the cnf-testsuite binary without errors
- [ ] Run `cnf-testsuite setup`
- [ ] You can then proceed with configuring a cnf to then run tests without errors or issues.
- [ ] You can see a screenshot of the shard output and netstat installation from it's own repo.

**Comment by agentpoyo** [comment]
![shards_install_output](https://user-images.githubusercontent.com/14348948/206011742-2d13bb14-773e-4a2d-94df-6179a053dd4d.jpg)
