### ISSUE TITLE
[BUG] should get rid of the ["wget"] tag since there are no specs associated with it

### ISSUE THREAD

**Issue by williscool** [cncf/cnf-testsuite#1662]
**Describe the bug**

![image](https://user-images.githubusercontent.com/394931/193100466-36e93d48-a0ca-48aa-b4ca-237535cf6cdf.png)

i.e. https://github.com/cncf/cnf-testsuite/actions/runs/3148582891/jobs/5119280359

0 specs are run but the build and setup takes 90 seconds unnecessarily 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

- OS [e.g. Linux, iOS, Windows, Android]
- Distro [e.g. Ubuntu]
- Version [e.g. 18.04]
- Architecture [e.g. x86, arm]

**How will this be tested? aka Acceptance Criteria (optional)**

(optional: unnecessary for things like spelling errors and such)

Once this issue is address how will the fix be verified?

**Additional context**

---

NOTE: you can enable higher logging level output via the command line or env var. to help with debugging

```
# cmd line
./cnf-testsuite -l debug test

# make sure to use -- if running from source
crystal src/cnf-testsuite.cr -- -l debug test

# env var
LOGLEVEL=DEBUG ./cnf-testsuite test
```

Also setting the verbose option for many tasks will add extra output to help with debugging

```
crystal src/cnf-testsuite.cr test_name verbose
```

Check [usage documentation](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) for more info about invoking commands and logging

**Comment by agentpoyo** [comment]
No AC required, this no longer runs as a spec test in GH actions.
