### ISSUE TITLE
[BUG] security category stops running after `non_root_user` test on RHEL8

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1666]
**Describe the bug**
`security` category stops running after `non_root_user` falco test on RHEL8

<img width="1299" alt="CleanShot 2022-10-03 at 14 43 22@2x" src="https://user-images.githubusercontent.com/84005/193541895-34aa6f25-6c00-4001-b83d-3b0da7be3bc0.png">

**To Reproduce**
Run `./cnf-testsuite security` on RHEL8 after setting up a CNF.

**Expected behavior**
The command should run all the workload security tests.

**Comment by agentpoyo** [comment]
This is duplicate of https://github.com/cncf/cnf-testsuite/issues/1421

**Comment by agentpoyo** [comment]
@HashNuke Try doing the following if using kind clusters on RHEL 8

```
export FALCO_ENV=CI
```

**Comment by HashNuke** [comment]
@agentpoyo I can confirm that this is a duplicate of #1421.

IMHO, setting that env var shouldn't even be required. It already prints a skip message. So I would think that it would stop and continue to the next test. Will submit a fix in sometime.

**Comment by agentpoyo** [comment]
> IMHO, setting that env var shouldn't even be required. It already prints a skip message. So I would think that it would stop and continue to the next test. Will submit a fix in sometime.

Yes, I agree. Just wanted to confirm if it doesn't exit if using that ENV variable as I have yet to test myself. But yes, since it skips, it should continue on to the next test and not exit the testsuite.

**Comment by HashNuke** [comment]
@agentpoyo Thanks for confirming about the error ~!
Found the issue and fixed it. Submitting PR now. 🕺🕺🕺

I'll try the env var and post an update.

**Comment by agentpoyo** [comment]
AC will be in https://github.com/cncf/cnf-testsuite/issues/1421
