### ISSUE TITLE
[BUG] `prometheus_traffic` test crashes on RHEL-8

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1668]
**Describe the bug**
`prometheus_traffic` test crashes on RHEL8. Screenshot below.

![CleanShot 2022-10-04 at 21 49 28](https://user-images.githubusercontent.com/84005/193872481-cffa535f-c00b-4968-9ff0-da585ed8dd5e.png)

**To Reproduce**
1. Install a CNF
2. `./cnf-testsuite prometheus_traffic`

**Expected behavior**
Test should output pass/fail/skip instead of crashing.

**Comment by HashNuke** [comment]
This seems to be specific to the version of Kubernetes installed on the RHEL-8 machine. Version information below to compare with pair machine.

## RHEL 8 workstation

> *`prometheus_traffic` test crashes on this machine when prometheus is not installed*.

```
[root@akash-rhel8 cnf-testsuite]# kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-09-01T23:30:43Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
```

## Pair machine

```
pair@cnfdev03:~/workspace/akash/projects/cnf-testsuite$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-19T15:39:43Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by lixuna** [comment]
@agentpoyo was this included in 0.35.1?

**Comment by agentpoyo** [comment]
Yes, it should have been included likely on 0.35.0 @lixuna

**Comment by lixuna** [comment]
@agentpoyo has it been peer reviewed?

**Comment by lixuna** [comment]
@agentpoyo what was the level of effort in pts for this bug (0,1,2,3,5,8,13)?

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Setup k8s cluster using RHEL 8 client.
- [ ] Install CNF (ex. coredns) with `cnf_setup` and `cnf-config`
- [ ] Now run `./cnf-testsuite prometheus_traffic`
- [ ] I should not see the testsuite crash but rather skip, pass or fail depending on real tests results.
- [ ] I can see a screenshot of the results without errors here.

**Comment by agentpoyo** [comment]
![1668_results](https://user-images.githubusercontent.com/14348948/200069563-d7274877-a563-4826-8a9e-6a4676b42a3f.png)

**Comment by lixuna** [comment]
@HashNuke  @agentpoyo what was the level of effort in pts for this bug (0,1,2,3,5,8,13)?

**Comment by agentpoyo** [comment]
3pts
