### ISSUE TITLE
[DOC] Review and update the CNF_TESTSUITE_YML_USAGE for additions, updates and corrections

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1672]
**Describe the bug**
The TESTSUITE_YML_USAGE is missing `helm_install_namespace: ` and likely other information that is valuable to end users and operators.

Need to review and add updates to reflect current usage and requirements.

**Comment by lixuna** [comment]
@taylor please peer review

**Comment by taylor** [comment]
lgtm
