### ISSUE TITLE
[Maintenance] Update Litmus Chaos to latest version for cnf-testsuite

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1681]
**Describe the solution you'd like**
Litmus Chaos is still using an older version within the testsuite. We should explore upgrading to their latest version along with the updated yml templates for the tests integrated into the testsuite to stay current.

**Describe alternatives you've considered**
None

**Comment by williscool** [comment]
related to #1532

**Comment by lixuna** [comment]
@agentpoyo has this issue been peer reviewed?

**Comment by agentpoyo** [comment]
@lixuna Not yet. I plan to review and test.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Find or build k8s cluster
- [ ] Setup cnf-testsuite from working branch or `main` as it's been merged after passing github actions
- [ ] Setup the testsuite with `setup` and install a CNF to use for testing
- [ ] Run `cert` or `reliability` to run the litmus chaos tests
- [ ] I should not see errors or failures based on latest version (not normal CNF failures)
- [ ] I can see a screenshot of the results here.

**Comment by agentpoyo** [comment]
![1681_results](https://user-images.githubusercontent.com/14348948/213059721-5392ee1e-82ae-4a27-a672-678e70a8828b.jpg)

**Comment by agentpoyo** [comment]
```
pair@cnfdev4:~/workspace/drew/cnf-testsuite/tools/chaos-experiments$ cat *.yaml | grep 2.14
    app.kubernetes.io/version: 2.14.0
    image: "litmuschaos/go-runner:2.14.0"
      value: 'litmuschaos/go-runner:2.14.0'
      app.kubernetes.io/version: 2.14.0
    app.kubernetes.io/version: 2.14.0
    image: "litmuschaos/go-runner:2.14.0"
      app.kubernetes.io/version: 2.14.0
    app.kubernetes.io/version: 2.14.0
    image: "litmuschaos/go-runner:2.14.0"
        value: 'litmuschaos/go-runner:2.14.0'
      app.kubernetes.io/version: 2.14.0
    app.kubernetes.io/version: 2.14.0
    image: "litmuschaos/go-runner:2.14.0"
        value: 'litmuschaos/go-runner:2.14.0'
      app.kubernetes.io/version: 2.14.0
    app.kubernetes.io/version: 2.14.0
    image: "litmuschaos/go-runner:2.14.0"
      value: 'litmuschaos/go-runner:2.14.0' 
      app.kubernetes.io/version: 2.14.0
    app.kubernetes.io/version: 2.14.0
    image: "litmuschaos/go-runner:2.14.0"
      value: 'litmuschaos/go-runner:2.14.0'
      app.kubernetes.io/version: 2.14.0
    app.kubernetes.io/version: 2.14.0
    image: "litmuschaos/go-runner:2.14.0"
      value: 'litmuschaos/go-runner:2.14.0' 
      app.kubernetes.io/version: 2.14.0
```
