### ISSUE TITLE
[BUG] ClusterTools not Embedding Files Correctly

### ISSUE THREAD

**Issue by denverwilliams** [cncf/cnf-testsuite#1693]
**Describe the bug**
ClusterTools is doing a [File.read](https://github.com/cnf-testsuite/cluster_tools/blob/main/src/utils/embedded_file_manager.cr#L7) at compile time. This means that data in not embedded when compiled and if the test suite binary is run standalone, without access to the yaml file, it will fail. 

This needs to be updated to do a [cat/base64](https://github.com/cncf/cnf-testsuite/blob/main/src/tasks/utils/embedded_file_manager.cr#L8) encode, so the yaml data in embedded in the binary. 

**_Error when running standalone binary:_**
```
root@github-runner2:/shared/346fbb55-0d96-4777-b96a-63874eed5b3d# ./cnf-testsuite setup
Unhandled exception: Error opening file with mode 'r': './lib/cluster_tools/tools/cluster-tools/manifest.yml': No such file or directory (File::NotFoundError)
  from /usr/share/crystal/src/crystal/system/unix/file.cr:11:7 in 'open'
  from /usr/share/crystal/src/file.cr:111:5 in 'new'
  from /usr/share/crystal/src/file.cr:627:5 in 'read'
  from /usr/share/crystal/src/file.cr:641:3 in 'read'
  from /github-runner-cnf-testsuite/cnf-testsuite/cnf-testsuite/lib/cluster_tools/src/constants.cr:6:1 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:110:5 in 'main_user_code'
  from /usr/share/crystal/src/crystal/main.cr:96:7 in 'main'
  from /usr/share/crystal/src/crystal/main.cr:119:3 in 'main'
  from __libc_start_main
  from _start
  from ???
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

- OS [e.g. Linux, iOS, Windows, Android]
- Distro [e.g. Ubuntu]
- Version [e.g. 18.04]
- Architecture [e.g. x86, arm]

**How will this be tested? aka Acceptance Criteria (optional)**

(optional: unnecessary for things like spelling errors and such)

Once this issue is address how will the fix be verified?

**Additional context**

---

NOTE: you can enable higher logging level output via the command line or env var. to help with debugging

```
# cmd line
./cnf-testsuite -l debug test

# make sure to use -- if running from source
crystal src/cnf-testsuite.cr -- -l debug test

# env var
LOGLEVEL=DEBUG ./cnf-testsuite test
```

Also setting the verbose option for many tasks will add extra output to help with debugging

```
crystal src/cnf-testsuite.cr test_name verbose
```

Check [usage documentation](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) for more info about invoking commands and logging

**Comment by HashNuke** [comment]
AFAIK this is complete with changes in the cluster_tools repo

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Setup k8s cluster
- [ ] Setup CNF Testsuite from source and checkout branch or `main` if bug branch already merged
- [ ] Run shards install and you should see that cluster tools is installed via module now from it's own repo
- [ ] Now run `./cnf-testsuite setup`
- [ ] You should not see failures or errors for the cluster tools installation embedded files
- [ ] I can see a screenshot here of the successful setup

**Comment by agentpoyo** [comment]
![1693_results](https://user-images.githubusercontent.com/14348948/200668115-62c593d0-e6c1-4eb2-b89e-180332359c33.png)
