### ISSUE TITLE
[BUG] `shared_database` appears to add to total number of tests running under `cert` when it is SKIPPED

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1697]
**Describe the bug**
The SKIPPED `shared_database` is adding to the total number of tests in the summary when running `cert` under the microservice category.

```
Microservice Tests
✔️  PASSED: Image size is good 🐜 ⚖️👀
✔️  PASSED: CNF had a reasonable startup time 🚀
✔️  🏆 PASSED: Only one process type used 🐜 ⚖️👀
✔️  ✨PASSED: Some containers exposed as a service 🐜 ⚖️👀
⏭️  SKIPPED: [shared_database] No MariaDB containers were found
Microservice results: 4 of 5 tests passed
```

**To Reproduce**
Run `cert` against sample coredns cnf and if `shared_database` is skipped, it still adds to total tests output.

**Expected behavior**
This should not count if skipped, treat it like the other tests like `prometheus_traffic` and others in observability category as not every CNF will use MariaDB databases.

**Screenshots**

![shared_database_skipped_totaltestspassed](https://user-images.githubusercontent.com/14348948/200897430-add88ef8-1fbc-4bff-889d-fe05ff6fc4ba.png)

**Comment by HashNuke** [comment]
@agentpoyo I checked the conditions for including tests for max tests (total tests). Below are the conditions:

1. IF test result is N/A, THEN not included for max tests.
3. IF test is bonus AND result is skipped, THEN not included for max tests.
4. IF test is bonus AND result is failed, THEN not included for max tests.
5. IF test resultt is skipped, THEN included in max tests.
6. ELSE include test in max tests (as long as points is defined for a test).


`shared_database` is a normal test according to points. So it is currently included for total tests.
IMHO if MariaDB is not found on the cluster, `shared_database` result should be `N/A`.

**Comment by agentpoyo** [comment]
> `shared_database` is a normal test according to points. So it is currently included for total tests.
> IMHO if MariaDB is not found on the cluster, `shared_database` result should be `N/A`.

Yes, we should be doing an N/A if not found, not tagging as SKIPPED.  It getting tagged as a "missed test" is not ideal if MariaDB is not even detected or used on the cluster/CNF being tested since it's "Not Available" to test.

Thoughts @wavell @denverwilliams @williscool @HashNuke  ?

**Comment by agentpoyo** [comment]
Reran failed jobs 3 times, this is the lone one that keeps failing that looks legit @HashNuke :

```
Failures:

  1) SampleUtils bonus tests should not decrease the maximum points when a failure occurs
     Failure/Error: (/of 4 tests passed/ =~ response_s).should_not be_nil

       Expected: nil not to be nil

     # spec/utils/cnf_manager_spec.cr:474

Finished in 2:04 minutes
5 examples, 1 failures, 0 errors, 0 pending

Failed examples:

crystal spec spec/utils/cnf_manager_spec.cr:467 # SampleUtils bonus tests should not decrease the maximum points when a failure occurs
Error: Process completed with exit code 1.
```

**Comment by agentpoyo** [comment]
![shared_database_tests_output](https://user-images.githubusercontent.com/14348948/206016583-663135a7-6332-4b3d-a20d-4cce7085e1dc.jpg)
