### ISSUE TITLE
[BUG] Litmus Chaos binary tests are failing in github actions with errors, preventing clean builds

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1703]
**Describe the bug**
```
/usr/bin/ld: D-igest5858M-D-5.o: in function `digest_size':
/usr/share/crystal/src/openssl/digest.cr:75: undefined reference to `EVP_MD_size'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o /home/runner/.cache/crystal/crystal-run-spec.tmp  -rdynamic -L/usr/bin/../lib/crystal/lib -lz `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` -lyaml -lpcre -lm -lgc -lpthread /usr/share/crystal/src/ext/libcrystal.a -levent -lrt -ldl`
Error: Process completed with exit code 1.
```

**To Reproduce**
Any branch push or merge will result in the binary tests for chaos tests to fail.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] When viewing litmus tests in GH actions, you should see no errors or failures.
- [ ] I can see a screenshot of no failing litmus tests using the github runners, not self hosted runners.

**Comment by agentpoyo** [comment]
![1703_litmus_tests](https://user-images.githubusercontent.com/14348948/206010336-4a51d1f9-9b7b-4597-9a4b-9f7e0a3c4e1d.jpg)

**Comment by lixuna** [comment]
@HashNuke  @agentpoyo what was the level of effort in pts for this bug (0,1,2,3,5,8,13)?

**Comment by agentpoyo** [comment]
3pts
