### ISSUE TITLE
[Maintenance] Extract Github Release Manager to its own library 

### ISSUE THREAD

**Issue by williscool** [cncf/cnf-testsuite#1707]
**Is your feature request related to a problem? Please describe.**
Github Release Manager is tightly coupled with the code base

**Describe the solution you'd like**
Extract Github Release Manager to its own library

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Setup or find k8s cluster
- [ ] Setup cnf-testsuite from source
- [ ] Run `shards install`
- [ ] I should see github release manager get pulled down as a module
- [ ] I can successfully run `workload` or `cert` tests without issues or exit failures
- [ ] I can see a screenshot of the output.

**Comment by agentpoyo** [comment]
![1707_output](https://user-images.githubusercontent.com/14348948/209213257-8d4ff579-9fa5-4608-b776-8828758670b9.jpg)

**Comment by lixuna** [comment]
@williscool @denverwilliams @agentpoyo what was the level of effort in pts for this (0,1,2,3,5,8,13)?

**Comment by agentpoyo** [comment]
5pts
