### ISSUE TITLE
[DEV] Need to migrate/rebuild new cnfdev build box in Equinix Metal - Old Hardware being Decommissioned

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1720]
**Describe the issue**
Need to migrate/rebuild new cnfdev build box in Equinix Metal - Old Hardware being Decommissioned

**Comment by agentpoyo** [comment]
Kicked off rsync of pair user from old cnfdev to new cnfdev created.

**Comment by agentpoyo** [comment]
kind, vim, emacs, spacemacs and docker all installed

**Comment by agentpoyo** [comment]
Added more packages required for crystal-lang and building cnf-testsuite along with make and gcc to build required shards.

**Comment by lixuna** [comment]
@agentpoyo @denverwilliams @wavell What is remaining on the rebuild before the old machine can be shut down?

As a reminder:  vulk.coop-cncf and cnfdev03.vulk.coop are affected within the EWR1 region data centers that are being shut down.

**Comment by agentpoyo** [comment]
I have verified that I can perform testing, peer reviews, qa, code updates, etc on the new cnfdev4 instance. @lixuna

**Comment by agentpoyo** [comment]
vim_tlib module has been updated which fixed errors when launching vim to edit files.

**Comment by agentpoyo** [comment]
a full rsync backup of /home being pushed to new cnfdev4 in /backup directory to preserve files in original state.

Once this backup is complete, I will turn off cnfdev3.

**Comment by agentpoyo** [comment]
cnfdev3 has been powered off.

**Comment by agentpoyo** [comment]
cnfdev3 has been terminated. No AC required for this.

**Comment by lixuna** [comment]
Thank you, @agentpoyo 

What was the level of effort in points to migrate/rebuild dev box (0,1,2,3,5,8,13,21)?

**Comment by agentpoyo** [comment]
5pts
