### ISSUE TITLE
[Documentation] Single process per container (microservice) rational paper

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#1721]
**Is your feature request related to a problem? Please describe.**
Single process per container (microservice) rational paper

**Describe the solution you'd like**
Single process per container (microservice) rational paper

https://github.com/cncf/cnf-testsuite/pull/1715

**Comment by agentpoyo** [comment]
Where was the link to the rational paper @wavell ?

**Comment by agentpoyo** [comment]
No AC required for this document.
