### ISSUE TITLE
[Workload] Check if processes use a sig term

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#1722]
## Title: [Workload] Microservices test: sig_term_handled

**Is your workload test idea related to a problem? Please describe.**
- SIGTERM

Problem 1: How the Linux kernel handles signals
The Linux kernel handles signals differently for the process that has PID 1 than it does for other processes. Signal handlers aren't automatically registered for this process, meaning that signals such as SIGTERM or SIGINT will have no effect by default. By default, you must kill processes by using SIGKILL, preventing any graceful shutdown. Depending on your app, using SIGKILL can result in user-facing errors, interrupted writes (for data stores), or unwanted alerts in your monitoring system.
https://cloud.google.com/architecture/best-practices-for-building-containers#problem_1_how_the_linux_kernel_handles_signals

**Describe the solution you'd like**
- Execute a termination and see if SIGTERM signal is passed into the child processes using strace.

**Test Category Name**
- Microservices

**Type of test (static or runtime)**
- runtime

---

### Documentation tasks:
- [ ] Update [installation instructions](https://github.com/cncf/cnf-testsuite/blob/main/install.md) if needed
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-testsuite/blob/main/TEST-CATEGORIES.md) if needed
- [ ] Update [USAGE md](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) if needed
  - [ ] How to run
  - [ ] Description and details
    - [ ] What the best practice is
    - [ ] Why are we testing this
  - [ ] Remediation steps if test does not pass

### QA tasks

Dev Review:

- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes,
  - [ ] move to `Needs Peer Review` column
  - [ ] create Pull Request and follow check list
  - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:

- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes,
  - [ ] move to `Reviewer Approved` column
  - [ ] Approve pull request
- [ ] if no,
  - [ ] document what did not go as expected, including error messages and screenshots (if possible)
  - [ ] Add comment to pull request
  - [ ] request changes to pull request

**Comment by wavell** [comment]
https://github.com/cnf-testsuite/cluster_tools/issues/4

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Find or build k8s cluster
- [ ] Pull `main` branch and build from source the cnf-testsuite, following doc instructions
- [ ] Setup CNF `sample-cnfs/sample_bad_signal_handling/cnf-testsuite.yml` running cnf-config
- [ ] I should see the test fail with screenshot.
- [ ] Cleanup the CNF by runing `cleanup`
- [ ] Setup CNF `sample-cnfs/sample_good_signal_handling/cnf-testsuite.yml` running cnf-config
- [ ] I should see the test pass with screenshot.

**Comment by agentpoyo** [comment]
![1722_failed](https://user-images.githubusercontent.com/14348948/227587657-4b2379ef-648a-4274-821a-0e2fe25390f0.jpg)

**Comment by agentpoyo** [comment]
![1722_passed](https://user-images.githubusercontent.com/14348948/227588446-0ab9bd11-8814-460d-9261-a21b719eb434.jpg)

**Comment by lixuna** [comment]
@denverwilliams @wavell @agentpoyo what was the level of effort in points for this new test (0,1,2,3,5,8,13)?

**Comment by agentpoyo** [comment]
8pts
