### ISSUE TITLE
[BUG] SSL_connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed on Rocky Linux 8.7

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1728]
**Describe the bug**
Trying to run cnf-testsuite on Rocky Linux 8.7 and we see the following error: 

```
# ./cnf-testsuite setup
CNF TestSuite version: v0.39.0
Successfully created directories for cnf-testsuite
/usr/share/crystal/src/openssl/ssl/socket.cr:34:11 in 'io'
/usr/share/crystal/src/http/client.cr:676:19 in 'send_request'
/usr/share/crystal/src/http/client.cr:661:37 in 'perform'
/workspace/src/tasks/helmenv_setup.cr:32:11 in '->'
/workspace/lib/sam/src/sam/execution.cr:20:7 in 'call'
/workspace/lib/sam/src/sam/execution.cr:20:7 in '__crystal_main'
/usr/share/crystal/src/crystal/main.cr:115:5 in 'main'
src/env/__libc_start_main.c:95:2 in 'libc_start_main_stage2'
SSL_connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
```

OS Release Info:
```
# cat /etc/os-release 
NAME="Rocky Linux"
VERSION="8.7 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.7 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.7"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.7"
```

Ref Bug # https://github.com/cncf/cnf-testsuite/issues/1464

**To Reproduce**

It is currently failing on the following command `cnf-testsuite setup`.

**Device (please complete the following information):**

- OS Linux
- Distro RHEL8.5
- Version 8.5
- Architecture x86

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Find or build a new k8s cluster
- [ ] Setup a Rocky Linux v8.7 client for cnf-testsuite
- [ ] Checkout the dev branch or `main` if merged.
- [ ] Build the cnf-testsuite binary (do not build from source on the Rocky Linux instance) from the same process our github actions builds the binary using alpine linux image
- [ ] Copy the binary to the Rocky Linux client
- [ ] Run `./cnf-testsuite setup`
- [ ] I should not see SSL errors on the output and the binary should create a tools/ directory
- [ ] I can now run cnf tests after configuring a CNF 
- [ ] I can see a screenshot of the `setup` output here as being successful without error.

**Comment by HashNuke** [comment]
## ✅ Validation: `setup` and `cnf_setup` commands

<img width="1321" alt="CleanShot 2023-02-14 at 22 47 24@2x" src="https://user-images.githubusercontent.com/84005/218787797-bffc37d4-8f16-4697-9e10-d281ed1e9d3d.png">

**Comment by HashNuke** [comment]
## ✅ Validation: Should be able to run tests

<img width="1345" alt="CleanShot 2023-02-14 at 22 53 47@2x" src="https://user-images.githubusercontent.com/84005/218789297-ea5fa30e-0335-49d0-a688-c10cbe2ec2f9.png">

**Comment by HashNuke** [comment]
## Errors when running some configuration tests

<img width="1359" alt="CleanShot 2023-02-14 at 22 55 56@2x" src="https://user-images.githubusercontent.com/84005/218789878-c03b6747-2a00-48a8-8f7e-212fb45fd05d.png">

## Error when running `cert:security` tests

<img width="1298" alt="CleanShot 2023-02-14 at 22 56 48@2x" src="https://user-images.githubusercontent.com/84005/218790080-3d0f525c-0e4a-40e3-b844-2f9a460c0a3f.png">

**Comment by HashNuke** [comment]
## ✅ Testsuite `cert` command completed running

<img width="1470" alt="CleanShot 2023-02-14 at 23 03 16@2x" src="https://user-images.githubusercontent.com/84005/218791785-76a4dd68-be34-4f26-8076-ec280c7076f4.png">

**Comment by lixuna** [comment]
Thank you for reviewing this @HashNuke 

Were the errors seen during configuration and security tests expected (shared above)? cc @agentpoyo

**Comment by agentpoyo** [comment]
> Thank you for reviewing this @HashNuke
> 
> Were the errors seen during configuration and security tests expected (shared above)? cc @agentpoyo

These errors could be isolated and are not part of the SSL I believe. @HashNuke should open new tickets and we should test the suite on other platforms with binary only to see if they occur elsewhere. But we should mark this as complete, since the bug was SSL related and the new errors are PATH related to another likely issue, could just be environment related. Could be related to podman too, which might be default unless @HashNuke installed the real docker daemon on this machine.
