### ISSUE TITLE
[BUG] cnf-testsuite does not compile after merging main branch

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1738]
**Describe the bug**

The testsuite does not compile after merging the main branch into `bug/1726` branch.
This is a compile issue caused by `kubectl_client`.

<img width="949" alt="CleanShot 2023-02-14 at 14 24 45@2x" src="https://user-images.githubusercontent.com/84005/218667720-f2ad3878-31dc-4ac3-b16d-1909b7619c42.png">

**To Reproduce**

1. Clone testsuite repo
2. `shards install`
3. `crystal build src/cnf-testsuite.cr`

**Expected behavior**
The build should be successful.

**Comment by agentpoyo** [comment]
No Peer Review needed, AC was performed in #1726
