### ISSUE TITLE
[Maintenance] Update GitHub Actions workflow to resolve deprecation notices

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1739]
**Describe the bug**

Update GitHub Actions workflow to resolve deprecation notices.

* https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
* https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

<img width="1114" alt="CleanShot 2023-02-14 at 16 33 47@2x" src="https://user-images.githubusercontent.com/84005/218695931-d017c924-b7cf-46cd-856a-0cbf4b71fce2.png">

**To Reproduce**
Check [this build](https://github.com/cncf/cnf-testsuite/actions/runs/4129467242) to view deprecation notices (scroll below the workflow chart).

**Expected behavior**
Deprecations should be resolved.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] When I view action jobs in github actions, I should not see deprecation warnings in the logs output for each spec test.

**Comment by agentpoyo** [comment]
No deprecation warnings on github action merges and runs:

![1739_no_deprecation_notices](https://user-images.githubusercontent.com/14348948/219080288-c3411e4d-b553-440e-9397-7bb74663b8bb.jpg)
