### ISSUE TITLE
[MAINTENANCE] k8s.gcr.io Image Registry Will Be Frozen From the 3rd of April 2023

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1742]
**Describe the software update**
- update images in cnf-testsuite repo to use registry.k8s.io instead of k8s.gcr.io

**Describe why update is needed**
- On the 3rd of April 2023, the old registry k8s.gcr.io will be frozen and no further images for Kubernetes and related subprojects will be pushed to the old registry.

**What version is in use now?**
- k8s.gcr.io
- 56 code results in [cncf/cnf-testsuite](https://github.com/cncf/cnf-testsuite)
- https://github.com/cncf/cnf-testsuite/search?q=k8s.gcr.io

**What version is the latest version and/or which version you will use for the update?**
- https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/

**Additional context**
- https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/

**Comment by agentpoyo** [comment]
A quick look shows only our sample CNF configs we use are using this repo. Should be a pretty straight forward verify, test and fix.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Find or create a k8s cluster to use
- [ ] Pull down the development branch `maintenance/#1742_registery_k8s` or the `main` branch if already merged.
- [ ] Build the cnf-testsuite binary from source (follow instructions if needed)
- [ ] Run `setup` and other requirements for the testsuite to prepare testing of changed code.
- [ ] Now run cnf_setup for one of the samples that uses the new registry URL for k8s: `./cnf-testsuite cnf_setup cnf-config=sample-cnfs/sample-appliciation-credentials/chart/values.yaml`
- [ ] You should see the CNF setup complete without errors.
- [ ] You can now run spot checks on tests, `cert`, `workload` and or individual tests. They should run (FAIL or PASS) but without actual errors.
- [ ] Run a cleanup to remove that CNF after tests have been performed and verified.
- [ ] Now run another sample test that uses the new registry URL: `./cnf-testsuite cnf_setup cnf-config=sample-cnfs/sample-local-storage/chart/values.yaml`
- [ ] You should see the CNF setup complete without errors.
- [ ] You can now run spot checks on tests, `cert`, `workload` and or individual tests. They should run (FAIL or PASS) but without actual errors.
- [ ] Run a cleanup to remove that CNF after tests have been performed and verified.
- [ ] I can see screenshots of valid results without errors in this issues comments.

**Comment by HashNuke** [comment]
Re-using the checklist above.

[x] Compiled the binary from main branch, setup a cluster and ran the `setup` command.
[x] Setup CNF with updated registry `./cnf-testsuite cnf_setup cnf-config=sample-cnfs/sample-appliciation-credentials`

![CleanShot 2023-03-15 at 20 01 20@2x](https://user-images.githubusercontent.com/84005/225316715-4dcfa8de-9f19-48bb-aecd-a2145796d6e7.png)

**Comment by HashNuke** [comment]
Found two errors. Will create separate tickets for these.

## `cni_compatible` test error

<img width="1470" alt="CleanShot 2023-03-15 at 20 07 29@2x" src="https://user-images.githubusercontent.com/84005/225317853-b90ac081-8f25-4b36-b0df-73adfca0da28.png">

## `reasonable_image_size` test error
<img width="1286" alt="CleanShot 2023-03-15 at 20 06 46@2x" src="https://user-images.githubusercontent.com/84005/225317700-390a51f2-4fb8-4f12-8b86-41d12f66ee66.png">

**Comment by HashNuke** [comment]
Testing with a different sample CNF `sample-cnfs/sample-local-storage`

```
./cnf-testsuite setup
./cnf-testsuite cnf_setup cnf-config=sample-cnfs/sample-local-storage
./cnf-testsuite cert
./cnf-testsuite workload
./cnf-testsuite cnf_cleanup cnf-config=sample-cnfs/sample-local-storage
```

* [ ] `cnf_setup`
* [ ] `cert`
* [ ] `workload`
* [ ] `cnf_cleanup`

**Comment by HashNuke** [comment]
Peer-review compete.
