### ISSUE TITLE
[BUG] CNF Security test cases not working in offline mode

### ISSUE THREAD

**Issue by vinaysha11983741** [cncf/cnf-testsuite#1744]
**Describe the bug**
CNF Security test cases not working in offline mode.

**To Reproduce**
1. Setup airgapped installation using official documentation (https://github.com/cncf/cnf-testsuite/blob/main/AIRGAP.md)
2. Execute whole security test suite using command: `cnf-testsuite security` or a single security test case using command : `cnf-testsuite container_sock_mounts` or `cnf-testsuite container_sock_mounts`.
3. It generates the following error message:
```
E, [2023-02-20 09:38:07 +00:00 #25607] ERROR -- cnf-testsuite: Error resolving real path: 'cnf-testsuite': No such file or directory
E, [2023-02-20 09:38:08 +00:00 #25607] ERROR -- cnf-testsuite: /usr/share/crystal/src/string.cr:5213:13 in 'real_path'
E, [2023-02-20 09:38:08 +00:00 #25607] ERROR -- cnf-testsuite: /workspace/src/tasks/utils/utils.cr:331:18 in 'install'
E, [2023-02-20 09:38:08 +00:00 #25607] ERROR -- cnf-testsuite: /workspace/src/tasks/utils/utils.cr:331:46 in '->'
E, [2023-02-20 09:38:08 +00:00 #25607] ERROR -- cnf-testsuite: /workspace/src/tasks/utils/task.cr:47:11 in 'all_cnfs_task_runner'
E, [2023-02-20 09:38:08 +00:00 #25607] ERROR -- cnf-testsuite: /workspace/src/tasks/utils/task.cr:19:9 in 'task_runner'
E, [2023-02-20 09:38:08 +00:00 #25607] ERROR -- cnf-testsuite: /workspace/lib/sam/src/sam/execution.cr:20:7 in '__crystal_main'
E, [2023-02-20 09:38:08 +00:00 #25607] ERROR -- cnf-testsuite: /usr/share/crystal/src/crystal/main.cr:115:5 in 'main'
E, [2023-02-20 09:38:08 +00:00 #25607] ERROR -- cnf-testsuite: src/env/__libc_start_main.c:95:2 in 'libc_start_main_stage2'
```

**Expected behavior**
The security test cases should work correctly similar to test cases in State, Microservices etc test suites.

**Screenshots**
![cncf security ](https://user-images.githubusercontent.com/85561319/220072067-7af87794-37ff-48e9-8044-ed9cadec19f2.jpg)

**Device (please complete the following information):**

- OS Linux
- Distro Ubuntu
- Version 20.04, 22.04

**Comment by HashNuke** [comment]
@vinaysha11983741 Hello Vinay, Thank you for reporting this issue with details.
I'll look into it and share updates.

**Comment by HashNuke** [comment]
@vinaysha11983741 We've stopped working on airgapped/offline mode for now. We'll add back support for it if there is more interest.
