### ISSUE TITLE
[BUG] Duplicate messages for all commands / tests run

### ISSUE THREAD

**Issue by denverwilliams** [cncf/cnf-testsuite#1749]
**Describe the bug**
When running the test-suite we are getting double-up/duplicate info messages for all logs.

Example, when running tests:
```
✔️  🏆 PASSED: Only one process type used 🐜 ⚖️👀
✔️  🏆 PASSED: Only one process type used 🐜 ⚖️👀
✔️  🏆 PASSED: Only one process type used 🐜 ⚖️👀
✖️  ✨FAILED: No containers exposed as a service 🦖 ⚖️👀
✖️  ✨FAILED: No containers exposed as a service 🦖 ⚖️👀
✖️  ✨FAILED: No containers exposed as a service 🦖 ⚖️👀
⏭️  N/A: [shared_database] No MariaDB containers were found
⏭️  N/A: [shared_database] No MariaDB containers were found
⏭️  N/A: [shared_database] No MariaDB containers were found
Microservice results: 3 of 3 tests passed
```

Example, when compiling:
```
pair@cnfdev03:~/workspace/denver/cnf-testsuite$ crystal build src/cnf-testsuite.cr
current_branch during compile: "fix_exec_loop_bug_1745"
current_tag during compile:
current_branch during compile: "fix_exec_loop_bug_1745"
current_tag during compile:
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

- OS [e.g. Linux, iOS, Windows, Android]
- Distro [e.g. Ubuntu]
- Version [e.g. 18.04]
- Architecture [e.g. x86, arm]

**How will this be tested? aka Acceptance Criteria (optional)**

(optional: unnecessary for things like spelling errors and such)

Once this issue is address how will the fix be verified?

**Additional context**

---

NOTE: you can enable higher logging level output via the command line or env var. to help with debugging

```
# cmd line
./cnf-testsuite -l debug test

# make sure to use -- if running from source
crystal src/cnf-testsuite.cr -- -l debug test

# env var
LOGLEVEL=DEBUG ./cnf-testsuite test
```

Also setting the verbose option for many tasks will add extra output to help with debugging

```
crystal src/cnf-testsuite.cr test_name verbose
```

Check [usage documentation](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) for more info about invoking commands and logging

**Comment by agentpoyo** [comment]
@denverwilliams @wavell 

Did you delete all the duplicate tgz files in your cnf-testsuite directory? I had same issue, which was the issue having multiple tgz of downloads in the root cnf-testsuite directory.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Setup k8s or find k8s cluster
- [ ] Pull latest `main` branch and build cnf-testsuite from source
- [ ] Setup a sample CNF following basic setup instructions
- [ ] When I run `cert` or any other test, I should not see duplicate messages on the console for the same tests.
- [ ] I can see a screenshot of the output here.

**Comment by agentpoyo** [comment]
![no_duplicates](https://user-images.githubusercontent.com/14348948/222258910-e9e6d947-60c8-4bf4-8b6a-6856c09fc7e9.jpg)
