### ISSUE TITLE
[Feature] Version all of the cnf-testsuite dependencies

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#1751]
**Is your feature request related to a problem? Please describe.**
We need all of the cnf-testsuite dependencies to have a semantic version with the tilde e.g. ~> 1.0.1
This will allow us to increment changes on the various libraries and cnf-testsuite without changing every dependency in lock step.  For instance if release_manager depends on kubectl_client, and cnf-testsuite requires a change to kubectl_client, the version change to kubectl_client will force release_manager to have its shard.lock file in its repository to be updated *unless* the shards.yml is set to a versioned kubectl_client e.g. ~> 1.0.1.  

**Describe the solution you'd like**
Set all projects in the https://github.com/cnf-testsuite that point to other projects in https://github.com/cnf-testsuite to be versioned.  This will require a tag of the current main and all of the shard.yml files to be reference tags (versions) of their cnf-testsuite libraries.  Make sure to include a full semantic version (https://semver.org/) in the reference (major, minor, patch) with the tilde so that the patch will be automatically upgraded with a shards upgrade command.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] When I run `shards install` during install of cnf-testsuite, I should see all of our modules labeled with versions rather than their SHA sums
- [ ] I can see an output here in this issue.

**Comment by agentpoyo** [comment]
```
pair@cnfdev4:~/workspace/drew/cnf-testsuite$ shards install
Resolving dependencies
Fetching https://github.com/vulk/sam.cr.git
Fetching https://github.com/icyleaf/totem.git
Fetching https://github.com/icyleaf/halite.git
Fetching https://github.com/mrrooijen/commander.git
Fetching https://github.com/crystal-community/icr.git
Fetching https://github.com/sija/retriable.cr.git
Fetching https://github.com/cnf-testsuite/tar.git
Fetching https://github.com/cnf-testsuite/find.git
Fetching https://github.com/cnf-testsuite/git.git
Fetching https://github.com/cnf-testsuite/docker_client.git
Fetching https://github.com/cnf-testsuite/kubectl_client.git
Fetching https://github.com/cnf-testsuite/kernel_introspection.git
Fetching https://github.com/cnf-testsuite/cluster_tools.git
Fetching https://github.com/cnf-testsuite/k8s_kernel_introspection.git
Fetching https://github.com/cnf-testsuite/k8s_netstat.git
Fetching https://github.com/cnf-testsuite/helm.git
Fetching https://github.com/cnf-testsuite/release_manager.git
Fetching https://github.com/jeromegn/protobuf.cr.git
Fetching https://github.com/crystal-ameba/ameba.git
Fetching https://github.com/icyleaf/popcorn.git
Fetching https://github.com/crystal-lang/crystal-readline.git
Using sam (0.4.0 at 4e3b271)
Using readline (0.1.1 at add6679)
Using icr (0.9.0 at f62bfcd)
Using commander (0.4.0)
Using retriable (0.2.4)
Using popcorn (0.3.0)
Using totem (0.7.0)
Installing git (1.0.0)
Installing kernel_introspection (0.1.0)
Installing docker_client (1.0.0)
Installing kubectl_client (1.0.1)
Installing cluster_tools (1.0.0)
Installing k8s_kernel_introspection (1.0.0)
Using halite (0.12.1)
Using find (0.1.0 at 129096c)
Using tar (0.1.0 at ae9bbea)
Installing helm (1.0.1)
Installing k8s_netstat (1.0.0)
Using release_manager (0.1.0 at a1d7b35)
Using airgap (0.1.0 at utils/airgap)
Using protobuf (2.3.0)
Installing ameba (1.3.1)
Postinstall of ameba: make bin && make run_file
```

**Comment by lixuna** [comment]
@wavell @agentpoyo what was the level of effort in points for this issue (0,1,2,3,5,8,13)?

**Comment by agentpoyo** [comment]
3pts
