### ISSUE TITLE
[BUG] open_metrics specs failing for sample-openmetrics CNF

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1755]
**Describe the bug**

Observability specs fail on GitHub Actions due to open_metrics specs failing for sample_openmetrics CNF

### Screenshot of test failure ([build link](https://github.com/cncf/cnf-testsuite/actions/runs/4363502991/jobs/7650268271))
<img width="1077" alt="CleanShot 2023-03-09 at 17 04 29@2x" src="https://user-images.githubusercontent.com/84005/223988670-22a3f18a-c771-42f6-8326-46ba2c16e96a.png">

### Screenshot of `openmetricsvalidator` error output
![image](https://user-images.githubusercontent.com/84005/223988732-bf87b719-fd49-4a69-bd89-e20135f79f75.png)

**To Reproduce**
Steps to reproduce the behavior, run the commands below to install the sample CNF and run the `open_metrics` test.

```
./cnf-testsuite cnf_setup cnf-config=sample-cnfs/sample-openmetrics/cnf-testsuite.yml

helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm  install \
--set alertmanager.persistentVolume.enabled=false \
--set server.persistentVolume.enabled=false \
--set pushgateway.persistentVolume.enabled=false \
prometheus prometheus-community/prometheus

./cnf-testsuite open_metrics
```

**Expected behavior**
The specs should pass.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] When I view github actions, I should not see `exit 1` failures for the observability spec test.
- [ ] I can see a screenshot of github actions passing here.
