### ISSUE TITLE
[BUG] `reasonable_image_size` test error when using sample CNF

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1759]
**Describe the bug**
*Found this issue when peer-reviewing #1742*.
The `reasonable_image_size` test throws an error when using a sample CNF. Commands to reproduce mentioned in the section below.

![image](https://user-images.githubusercontent.com/84005/225319903-7775813b-e2ea-40ea-9e04-a743b7c40e67.png)

**To Reproduce**

```
./cnf-testsuite cnf_setup cnf-config=sample-cnfs/sample-appliciation-credentials
./cnf-testsuite cert
```

The error occured on Ubuntu. Below is some environment info:
<img width="683" alt="CleanShot 2023-03-15 at 20 17 43@2x" src="https://user-images.githubusercontent.com/84005/225320222-ab9a5dfe-2b7b-42e0-b258-8d751ae4d649.png">

**Expected behavior**
Test should pass or fail. Should not throw an error.

**Comment by agentpoyo** [comment]
This was same issue MATRIXX mentioned in CNF Weekly meeting they were seeing. It's definitely intermittent error seen.

**Comment by HashNuke** [comment]
This is a duplicate of #1597. The issue has been fixed. Moving to review.

**Comment by agentpoyo** [comment]
No AC required; duplicate issue that was already reviewed.
