### ISSUE TITLE
[BUG] Some GitHub Actions jobs are running a different version of Crystal

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1760]
**Describe the bug**

* Some GitHub Actions jobs are running a different version of Crystal (1.0.0)
* The Chaos tests are running 1.6.2 (they use a GitHub Action step by the crystal community).

This causes an issue when upgrading all shards to semver releases for #1751.

Confirmed this by adding a step to display crystal version to some of the tests.

Example build: https://github.com/cncf/cnf-testsuite/actions/runs/4427454683/jobs/7765077886

## Screenshot

<img width="1064" alt="CleanShot 2023-03-15 at 21 34 47@2x" src="https://user-images.githubusercontent.com/84005/225342639-352f9ee3-6482-4a89-be08-dcadbcf21241.png">

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] When I view github actions specs, I should see they're running the recommended version of crystal.
