### ISSUE TITLE
[MAINTENANCE] Update GitHub Runner base image to use `myoung34/github-runner:2.303.0-ubuntu-bionic`

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1761]
**Describe the software update**
Updating GitHub Runner with new version of crystal as a part of #1760.
Checked that the GitHub Runner base image has new versions. The latest version is `2.303.0-ubuntu-bionic`.

**Describe why update is needed**
GitHub Runners will soon stop picking up jobs if the images are too old and are not updated frequently.

**What version is in use now?**
`myoung34/github-runner:2.299.1-ubuntu-bionic`

**Comment by agentpoyo** [comment]
@HashNuke the runners stopped working today so I went ahead and created the new Docker image and pushed up; created new runners based on 2.303.0 image version.

**Comment by HashNuke** [comment]
Build worked fine - https://github.com/cncf/cnf-testsuite/actions/runs/4463694011

No validation required.
