### ISSUE TITLE
[EPIC] Kubecon Amsterdam Demo

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#1762]
**Is your feature request related to a problem? Please describe.**
We should have a joint demo of the cnf-testsuite for Kubecon Amsterdam with Dish Wireless

**Describe the solution you'd like**
We should have a joint demo of the cnf-testsuite for Kubecon Amsterdam with Dish Wireless
Slide deck
https://github.com/cncf/cnf-testsuite/issues/1770
Realistic CNF preparation (5g emulator)
https://github.com/cncf/cnf-testsuite/issues/1771
https://github.com/cncf/cnf-testsuite/issues/1772

**Comment by agentpoyo** [comment]
Approved, no acceptance criteria required.
