### ISSUE TITLE
[BUG] Fix CI issues affecting main branch and PR-1767

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1774]
**Describe the bug**
Build failures on GitHub Actions for main branch. Specs for certain tests and also the airgap specs are failing despite no changes made to them recently.

https://github.com/cncf/cnf-testsuite/actions/runs/4493559328/jobs/7942040917

**Expected behavior**
The specs should pass on the main branch.

**Comment by HashNuke** [comment]
This issue was resolved in this PR - https://github.com/cncf/cnf-testsuite/pull/1775.
Moving this issue to peer review.

**Comment by agentpoyo** [comment]
No AC required, you can see that github actions are passing for PR-1767.
