### ISSUE TITLE
[Workload] Software Defined Radio Driver containerization

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#1788]
## Title: [Workload] Software Defined Radio Driver containerization

**Is your workload test idea related to a problem? Please describe.**
- The packages for the Software Defined Radio (such as the b200) need to be containerized

**Describe the solution you'd like**
- The packages for the Software Defined Radio (such as the b200) need to be containerized

**Comment by agentpoyo** [comment]
No AC required; reviewed and followed README for setup of containerized Radio Driver.
