### ISSUE TITLE
[Workload] SDR-RAN integration

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#1790]
**Is your workload test idea related to a problem? Please describe.**
The software defined radio containerization needs to be integrated with the 5g Core containerization
**Describe the solution you'd like**
The software defined radio containerization needs to be integrated with the 5g Core containerization

**Comment by agentpoyo** [comment]
No AC required. This was part of https://github.com/cncf/cnf-testsuite/issues/1784 and https://github.com/cncf/cnf-testsuite/issues/1788.
