### ISSUE TITLE
[CNFs] Test Linkerd2 as an example CNF with the CNF Conformance Test Suite

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#180]
[Acceptance Criteria](https://github.com/cncf/cnf-conformance/issues/180#issuecomment-620869799)

### [CNFs] Test Linkerd2 as an example CNF with the CNF Conformance Test Suite

Planning Tasks:
- [x] Review and update https://github.com/cncf/cnf-conformance/edit/develop/EXAMPLE-CNFS.md
- [x] Select the next one (or two) CNF(s) that will be tested in the CNF Conformance Test Suite => Linkerd2 CNF

Documentation tasks: TBD
- [ ]  create [README for Linkerd2 CNF], based on [Envoy example](https://github.com/cncf/cnf-conformance/blob/master/example-cnfs/envoy/README.md) (example: https://github.com/cncf/cnf-conformance/blob/master/sample-cnfs/sample-coredns-cnf/README.md)
- [ ]  

Implementation tasks: TBD
- [ ] create [cnf-conformance.yml], based on [Envoy example](https://github.com/cncf/cnf-conformance/blob/master/example-cnfs/envoy/cnf-conformance.yml) 
- [ ] Tag 1 or more people to peer review
- [ ] TBD

CNF Testing task:
- [ ]  Follow the new example CNF's README.md to test the CNF
- [ ]  Add the Final Score in a comment in this ticket
- [ ]  Add the entire test result output in a comment in this ticket

**QA tasks**

Dev Review: 
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by lixuna** [comment]
[DRAFT-copy of #133] Acceptance criteria: steps to test during development and peer review
---

- [ ]  I can follow the set up instructions https://github.com/cncf/cnf-conformance/blob/master/INSTALL.md#cnf-creatorvendor-install-and-usage-guide
- [ ]  I should see a Linkerd2 CNF example folder
    - [ ]   Ie. in an example-cnfs folder with each example CNF having it’s own sub-folder with a config
- [ ]  I should see Linkerd2 CNF README with summary and instructions in Linkerd2 directory and in example CNFs
- [ ]  I should see a cnf-conformance.yml configuration in the Linkerd2 example CNF folder
- [ ]  I can run the CNF Conformance Tests w/ the Linkerd2 CNF
- [ ]  I can check the output of the CNF conformance command
   - [ ]  I should see which tests passed or failed for the Linkerd2 CNF
   - [ ]  I should see a final score for the Linkerd2 CNF
- [ ]  Final Score for Linkerd2 CNF = 


Testing A/C task:
- [ ]  Add the Final Score in a comment in this ticket
- [ ]  Add the entire test result output in a comment in this ticket

**Comment by lixuna** [comment]
Level of effort: 0,1,2,3,5,8,13,21 pts = 
---

**Comment by lixuna** [comment]
@williscool is this in progress

**Comment by williscool** [comment]
```
william@Will-LAPTOP-L47SIB7:/mnt/c/Users/william/unison-with-dropbox-symlinked-to-linux/vulk_stuff/cnf-conformance$ helm install linkerd2 linkerd/linkerd2
Error: execution error at (linkerd2/templates/web.yaml:98:12): Please provide the identity trust anchors
```

**Comment by taylor** [comment]
linkerd2 prerequisite: identity certificates https://linkerd.io/2/tasks/install-helm/#prerequisite-identity-certificates

**Comment by taylor** [comment]
TODO: 
- plan support for pre-req automation for CNF examples
- optional: plan additional support for helm options beyond what is currently supported

**Comment by denverwilliams** [comment]
Closed, new ticket here https://github.com/cncf/cnf-testsuite/issues/1628
