### ISSUE TITLE
[Feature] Add task runtime info to results file to help with debugging long testsuite runtimes

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1807]
## Describe

When debugging the testsuite's long runtimes, it would be useful to have info about how long the testsuite spent on each test.

The best place to add this info would be the results file since the test results are also in the same file.

The following information would be useful per test:
* Start timestamp
* End timestamp
* Task runtime in milliseconds

To begin with, this info could be made available when an environment variable is set.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Find or setup k8s cluster for test
- [ ] Checkout the `tasks_runtime` branch unless it was already merged into `main`
- [ ] Build the cnf-testsuite binary from source build 
- [ ] Setup or install an example CNF (in our case, we'll use the coredns sample)
- [ ] When I run `TASK_TIMESTAMPS=true ./cnf-testsuite cert` or other test, I should see the time stamps of start and finish in the results file.
