### ISSUE TITLE
[BUG] Chaos Tests (zombie) failing

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1820]
> *Created a duplicate issue by mistake. This is a duplicate of #1821. The other ticket has more details in the comments.*

**Describe the bug**

"Chaos Tests (zombie)" is failing on GitHub Actions.

![CleanShot 2023-08-30 at 21 09 40@2x](https://github.com/cncf/cnf-testsuite/assets/84005/cd889e9f-c87d-4ce6-8def-199da99fb7a2)

**Comment by HashNuke** [comment]
Moving this to needs peer review. But none required since this is a duplicate of #1821, which has it's own activity log. Apologies.

**Comment by agentpoyo** [comment]
No AC here, refer to https://github.com/cncf/cnf-testsuite/issues/1821 for Peer Review notes.
