### ISSUE TITLE
[BUG] "Chaos Tests (zombie)" failing on GitHub Actions

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1821]
**Describe the bug**

> *This was a part of fixes for #1798*

"Chaos Tests (zombie)" is failing on GitHub Actions. ([build link](https://github.com/cncf/cnf-testsuite/actions/runs/5958865755/job/16184611204))

![CleanShot 2023-08-30 at 21 09 40@2x](https://github.com/cncf/cnf-testsuite/assets/84005/cd889e9f-c87d-4ce6-8def-199da99fb7a2)

**Comment by HashNuke** [comment]
The root cause was kubectl detection failing. The kubectl version detection needs to be updated to support new versions of kubectl. Reported this issue as #1822

![CleanShot 2023-08-30 at 21 12 55@2x](https://github.com/cncf/cnf-testsuite/assets/84005/58663e46-aab8-496c-8b6b-effb7c96d08c)

**Comment by HashNuke** [comment]
This has been fixed as a part of #1823. Moving this to peer review

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] When I view github actions, I should find the Chaos Tests are passing and not failing with errors.
- [ ] I can see a screenshot here of passing Chaos tests.

**Comment by agentpoyo** [comment]
![1821_chaos_passing](https://github.com/cncf/cnf-testsuite/assets/14348948/c9950e70-73b4-4aa2-9e3f-8ff6ab9435d2)
