### ISSUE TITLE
[Feature] Output failed resources for the `sig_term_handled` test to help resolve the test failures

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1825]
# Describe

When the `sig_term_handled` test fails, the output is a single-line failure message.

```
🏆 FAILED: Sig Term not handled
```

To help improve the CNF, it would be helpful if the test also outputs pods/containers that failed the test.

**Comment by HashNuke** [comment]
Making updates for this as a part of [PR-1825](https://github.com/cncf/cnf-testsuite/pull/1826) which resolves #1817 too.
Will move this ticket to the appropriate state once the PR is ready.

**Comment by lixuna** [comment]
@HashNuke @agentpoyo what is the status of this issue please?

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Setup k8s or use existing cluster
- [ ] Setup cnf-testsuite and run setup, cnf_setup against working CNF
- [ ] When sig_term_handled fails, I should only see a single line output and the pod info when it fails after running `sig_term_handled` test
- [ ] I can see screenshots of the output here.

**Comment by agentpoyo** [comment]
![sig_term_handled](https://github.com/cncf/cnf-testsuite/assets/14348948/37a8067b-b2d0-487c-bbe9-f31770bc9e05)
