### ISSUE TITLE
[Documentation] Link to non-existent file in README.md - CNF WG

### ISSUE THREAD

**Issue by gigachad95** [cncf/cnf-testsuite#1853]
### Description:
There is a hyperlink in README.md that leads nowhere:

`This Test Suite initiative works closely with the [CNF WG](cnf-wg/README.md) which determines requirements for the CNF Test Suite program.`

This is likely an artifact of CNF WG separation from this repository.

### Solution:

Change the link to https://github.com/cncf/cnf-wg .

**Comment by lixuna** [comment]
Thank you for resolving this issue, [gigachad95](https://github.com/gigachad95)!
