### ISSUE TITLE
[Feature] Add flag for all slow tests

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#337]
**Problem**
- some tests are "slow" and take a longer time to run
- it would be nice to flag the tests with longer running times, marked as "slow" (or equivalent)

**Possible solution**
- Add a "slow" flag to all of the slower tests (tests that take much longer to run than the other tests in the CNF Test Suite)

**List of slower tests**
- tbd, needed to be added

**How will this be tested?**
- when I run x test, then it should take under (n) time to run

**Comment by lixuna** [comment]
@agentpoyo when you have run the test suite recently, have you noticed if tests are still running slowly? (I recall some tests have been refactored. Is this ticket still valid?)

**Comment by agentpoyo** [comment]
@lixuna  workload tests if dependencies are already setup or cached seems to run in about 5-6 minutes. Platform tests are still slow but that's expected currently.

**Comment by lixuna** [comment]
Closing this issue as "duplicate." Slow tests have been refactored or handled differently, so that the workload tests take 5-6 minutes now vs the 20+ minutes to run workload tests in the past.
