### ISSUE TITLE
[Feature] CNF Test Suite needs a logo

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#341]
**Problem**
- CNF Test Suite needs a new logo 
- We are currently using an [open source icon](https://commons.wikimedia.org/wiki/File:Checklist_Noun_project_5166.svg) w/ text for the CNF Test Suite [twitter](https://twitter.com/cnfconformance) account and presentations

<img width="122" alt="Screen Shot 2021-04-23 at 10 43 07 AM" src="https://user-images.githubusercontent.com/11701267/117215943-9fbb9c80-adc4-11eb-944c-f1bbc1793df0.png">

**Solution**
- ideas for new logo design are welcome! 

**What is CNF Test Suite?** 
An open source test suite for validating Cloud Native Network Functions (CNFs) and Telecom Platform adherence to cloud native principles with the following goals:

1. Provide test results for CNFs and Telecom platforms to help operators identify solutions which observe the cloud native capabilities and principles important to them
2. Enable CNF Developers to demonstrate conformance to cloud native best practices
3. Provide tools and feedback to help to CNF Developers improve their CNFs and platforms

**Comment by sakshamgurbhele** [comment]
can I work on this?

**Comment by lixuna** [comment]
Thank you, @sakshamgurbhele. We'd appreciate your contributions toward a new icon and logo for the test suite. One potential blocker could be a renaming effort for the "cnf-conformance" test suite in the near future.

**Comment by lixuna** [comment]
Note: the name of the CNF Test Suite may be changed to have more personality/brand identity, in #887
