### ISSUE TITLE
[Documentation] Create a video for installing the CNF test suite

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#378]
**Is your feature request related to a problem? Please describe.**
- Create a video for installing the CNF test suite

**Describe the solution you'd like**
- a video for the install process could be used in the install guide/quick start guide
- a video for install could also be used in presentations at Open Networking Summit or Telecom User Group calls

**Comment by lixuna** [comment]
@williscool what is the level of effort in points to create this video? (ex. 0,1,2,3,5,8,13,21)

**Comment by williscool** [comment]
@lixuna 3 pts

**Comment by williscool** [comment]
Working video of source install

https://asciinema.org/a/pKIE0itd2JlxX0WtZsdZNIY1S

**Comment by lixuna** [comment]
@williscool is this ready for peer review? If so, can you please move it to the Needs Peer Review status column?

**Comment by williscool** [comment]
Working curl install video

https://asciinema.org/a/jEz6eZt8IJMHv5mFxT7NYwU26

**Comment by agentpoyo** [comment]
LGTM

Just things to point out, the latest curl install is now less chatty on output so it might make the output a little cleaner.

Also, we may want to cut out the end where it looks like a ctrl-c is invoked before the setup finishes.

**Comment by williscool** [comment]
https://asciinema.org/a/ltDRq5er7zV9aEaktoWeS5ZF2

@agentpoyo give this one a look its a lot cleaner

**Comment by williscool** [comment]
https://asciinema.org/a/lpuwHLNmIaf2VOFFQwbG7Bzo7

**Comment by agentpoyo** [comment]
> https://asciinema.org/a/ltDRq5er7zV9aEaktoWeS5ZF2
> 
> @agentpoyo give this version of the curl install a look its a lot cleaner

Looks much better. I did update the INSTALL and README to add the `curl -s` to make it more clean but I think it's fine as is. @taylor might pick it apart though.

**Comment by agentpoyo** [comment]
> Source install
> 
> https://asciinema.org/a/lpuwHLNmIaf2VOFFQwbG7Bzo7

Not sure if we wanted to perhaps add  the `--warnings none` during the `crystal build` command. Maybe we add that to our documenation as well to get rid of those normal warnings. @taylor @lixuna What do you all think?
