### ISSUE TITLE
[Documentation]  Create a video for running platform tests against an example platform (eg. CNF Testbed)

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#379]
**Is your feature request related to a problem? Please describe.**
- Create a video for running platform tests against an example platform (eg. CNF Testbed)

**Describe the solution you'd like**
- a video for running platform tests could be used in the install guide
- a video for running platform tests could also be used in presentations at Open Networking Summit or Telecom User Group calls

**Comment by lixuna** [comment]
@williscool what is the level of effort in points to create this video? (ex. 0,1,2,3,5,8,13,21)

**Comment by williscool** [comment]
@lixuna 3pts

**Comment by williscool** [comment]
platform video 

https://asciinema.org/a/NgBCqRqJRiSB27V4vxvBStwmB

**Comment by agentpoyo** [comment]
This would be great if it wasn't 95% of nothing happening in the video. We definitely need to cut out the dead parts in it with no movement or output and just claim that the video is edited to show the output, the actual tests will take much longer to run.

@williscool @lixuna @taylor

**Comment by williscool** [comment]
version with most of the dead air cut out @wavell @agentpoyo 

https://asciinema.org/a/fG660M2ITzZDWoUYDfO9pGoBB
