### ISSUE TITLE
[Documentation] Create a video of running a workload test with an example CNF

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#380]
**Is your feature request related to a problem? Please describe.**
- Create a video of running a workload test with an example CNF

**Describe the solution you'd like**
- a video of running a workload test could be used in the install guide/quick start guide
- a video of running a workload test could also be used in presentations at Open Networking Summit or Telecom User Group calls

**Comment by lixuna** [comment]
@williscool what is the level of effort in points to create this video? (ex. 0,1,2,3,5,8,13,21)

**Comment by williscool** [comment]
@lixuna 3pts

**Comment by williscool** [comment]
Workload tests

https://asciinema.org/a/DUI1XgA45N4OJ8sKZQ2hinCfn

**Comment by agentpoyo** [comment]
Looks good. I think if possible, we should cut out the parts of the video where nothing is happening (at least nothing is scrolling for output). Perhaps just put in the description that the video has been cut to speed up the video playback so we don't mess with peoples expectations as to how long it should actually take. @williscool @lixuna @taylor
