### ISSUE TITLE
[Enhancement] Update ReleaseManager to specify if an items is a Pull Request or an Issue

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testsuite#381]
# [Enhancement] Update ReleaseManager to specify if an items is a Pull Request or an Issue

**Is your feature request related to a problem? Please describe.**

Currently the release docs show a large list of issues for commit created by the ReleaseManager code.

The pre-text before links and issue number is sometimes incorrect in that it says issue rather than Pull Request.

**Describe the solution you'd like**

Update pre-text to have Pull Request (or PR)  when the link and number referenced is a PR rather than an a Github Issue.

![image](https://user-images.githubusercontent.com/26697/91494134-ff4cca00-e87d-11ea-9668-f2898d86c2ce.png)

**Comment by lixuna** [comment]
@taylor I think this has been addressed in another issue. Can we close this as "duplicate"?

**Comment by lixuna** [comment]
Releases no longer include "PR"

Closing as duplicate
