### ISSUE TITLE
[Enhancement] Sonobuoy version should be dynamically updated

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#406]
**Describe the enhancement**
Sonobuoy version should be dynamically updated

**To Reproduce**
1. `crystal spec spec/platform/platform_spec.cr -v '
2.  There should be no warnings about version mismatches

**Expected behavior**

**Screenshots**
Error when there is a mismatch
![image](https://user-images.githubusercontent.com/29548/94052421-8c604180-fd9e-11ea-90f8-200db9b7aba9.png)

Where to change the code
![image](https://user-images.githubusercontent.com/29548/94051924-e4e30f00-fd9d-11ea-9e13-9f6a5f404371.png)

**Comment by lixuna** [comment]
### Note: Alternate approach - needs discussion:

We may want to switch to using K8s e2e tests directly instead of sonobuoy.  Before automating anything with sonobuoy, we should discuss the alternatives first.
