### ISSUE TITLE
Suggestion: make the helm tar file or at least the version a variable which is used throughout the helm_local_install task.

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#409]
Suggestion: make the helm tar file or at least the version a variable which is used throughout the helm_local_install task.

_Originally posted by @taylor in https://github.com/cncf/cnf-conformance/pull/407#r494448159_

**Comment by lixuna** [comment]
@taylor is this still needed? If so, can you please add the problem, suggested solution and "How this will be tested" sections to the description above? If this item has already been handled, I'll close the issue as "duplicate"

**Comment by taylor** [comment]
I'm not sure if this has been addressed yet.

@wavell, @denverwilliams, @williscool, @agentpoyo, @HashNuke is this covered already or still a todo.
