### ISSUE TITLE
Suggestion: use the Crystal lang builtin cd command, Dir.cd.  See https://crystal-lang.org/api/0.21.0/Dir.html#cd%28path%2C%26block%29-class-method

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#410]
Suggestion: use the Crystal lang builtin cd command, Dir.cd.  See https://crystal-lang.org/api/0.21.0/Dir.html#cd%28path%2C%26block%29-class-method

_Originally posted by @taylor in https://github.com/cncf/cnf-conformance/pull/407#r494450040_

**Comment by lixuna** [comment]
@taylor is this still a valid issue? If so, please add the problem that it solves, the suggested solution and how it will be tested.

**Comment by taylor** [comment]
@lixuna not sure I'll check the code. If it was not implemented it would still be a good first issue that makes the code cleaner among other benefits.
