### ISSUE TITLE
[BUG] LOG_LEVEL command line arg doesn't exist

### ISSUE THREAD

**Issue by williscool** [cncf/cnf-testsuite#420]
**Describe the bug**

We should alias `LOGLEVEL` to `LOG_LEVEL` in the code base other wise that typo of no underscore will lead to confusion

NOTE: you can enable higher logging level output via the command line or env var. to help with debugging

```
# cmd line
./cnf-conformance -l debug test

# make sure to use -- if running from source
crystal src/cnf-conformance.cr -- -l debug test 

# env var
LOGLEVEL=DEBUG ./cnf-conformance test
```

Also setting the verbose option for many tasks will add extra output to help with debugging

```
crystal src/cnf-conformance.cr test_name verbose
```

Check [usage documentation](https://github.com/cncf/cnf-conformance/blob/master/USAGE.md) for more info about invoking commands and loggin

**To Reproduce**

**Expected behavior**

**Screenshots**

**Workstation (please complete the following information):**
 - OS [e.g. Linux]
 - Distro [e.g. Ubuntu]
 - Version [e.g. 18.04]
 - Architecture [e.g. x86, arm]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by williscool** [comment]
address in #447

**Comment by williscool** [comment]
refs #400

**Comment by lixuna** [comment]
@williscool has this bug been fixed?

**Comment by williscool** [comment]
@lixuna yes
