### ISSUE TITLE
[BUG] Fix resource conflict issue affecting all tests that need to install the CNF

### ISSUE THREAD

**Issue by denverwilliams** [cncf/cnf-testsuite#552]
**Describe the bug**
Currently not all K8s resources can be put into a namespace. For example, CRDs, RBAC roles, and any other cluster wide resource types aren't able to be deployed into a namespace, instead they are available at a cluster-wide level which causes resource conflicts when we run any tests that involve installing a copy of the entire CNF. 

Tests affected:
- helm_deploy
- reasonable_startup_time

There are three potential fixes for this;

- The affected resources are given names that are based on the Helm Release name, which is unique for each installation. This isn't really a feasible option for CRDs though.
- We update the tests to first uninstall the existing installation of the CNF, then re-install it during the test.
- Update the test suite to execute all the affected tests in a single pass during the original CNF installation, e.g when cnf-setup is run.
   - [Enhancement] Refactor helm_deploy to use data from initial test suite CNF deployment and no longer do a new deployment #564
   - [Enhancement] Refactor reasonable_startup_time to use data from initial test suite CNF deployment and no longer do a new deployment #565
- Quickfix: add destructive flag to two affected tests and skip by default for now. See #562

---

## Scenario 1 - RBAC role clobbering for Dev team with CoreDNS already deployed

1. Team has shared cluster with a default CoreDNS deployed and default RBAC roles applied
2. Dev runs cnf_setup with coredns example
3. New CoreDNS RBAC roles are applied overwriting the original teams RBAC roles
4. New CoreDNS is deployed to cluster in its own namespace

**Result: RBAC role for the teams shared CoreDNS will be overwritten and the original shared CoreDNS will stop functioning**

References:
- https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
- https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#api-server-aggregation
- https://kubernetes.io/docs/reference/access-authn-authz/rbac/
- https://kubernetes.io/docs/tasks/extend-kubernetes/

## Scenario 2 - RBAC role clobbering in new cluster with single dev, no CoreDNS deployed yet

1. Dev has own cluster with no CoreDNS deplolyed
2. Dev runs cnf_setup with coredns example
3. CoreDNS RBAC roles are applied
4. CoreDNS is deployed to cluster
5. The reasonable_startup_time test (or another test which does a deploy) runs
6. New CoreDNS RBAC roles are applied
7. Records of original RBAC roles are destroyed
8. CoreDNS is deployed to cluster
9. Two copies of CoreDNS will be running in their own namespaces

**Result: Any test using original CoreDNS (and RBAC roles) installation will fail**

**Comment by taylor** [comment]
## Scenario 1 - Dev team with CoreDNS already deployed

1. Team has shared cluster with a default CoreDNS deployed and default RBAC roles applied
2. Dev runs cnf_setup with coredns example
3. New CoreDNS RBAC roles are applied overwriting the original teams RBAC roles
4. New CoreDNS is deployed to cluster in its own namespace

Result: RBAC role for the teams shared CoreDNS will be overwritten and the original shared CoreDNS will stop functioning

## Scenario 2 - new cluster with single dev, no CoreDNS deployed yet

1. Dev has own cluster with no CoreDNS deplolyed
2. Dev runs cnf_setup with coredns example
3. CoreDNS RBAC roles are applied
4. CoreDNS is deployed to cluster
5. The reasonable_startup_time test (or another test which does a deploy) runs
6. New CoreDNS RBAC roles are applied
7. Records of original RBAC roles are destroyed
8. CoreDNS is deployed to cluster
9. Two copies of CoreDNS will be running in their own namespaces

**Result: Any test using original CoreDNS (and RBAC roles) installation will fail**

**Comment by taylor** [comment]
More issues with CRDS.

TODO: write-up scenarios

**Comment by taylor** [comment]
https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/

**Comment by taylor** [comment]
Multiple Schedulers - https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/

**Comment by taylor** [comment]
Pod PriorityClasses are non-namespaced and could be an issue with conflicts.  See https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption

**Comment by taylor** [comment]
Kubernetes Policies: define policies cluster-wide
- network
- resource quotas
- security

Also see https://github.com/kubernetes/community/tree/master/wg-policy

**Comment by taylor** [comment]
Potential warnings/communication:
- disabled tests which have conflicts
- test suite could clobber global data.  Don’t run on shared cluster nor production

**Comment by taylor** [comment]
The resource conflicts will be addressed in multiple parts, starting with [[Enhancement] Add existing destructive flag to the `reasonable_startup_time` and `helm_deploy` tests #562
](https://github.com/cncf/cnf-conformance/issues/562)

**Comment by taylor** [comment]
Longer term fix for the two affected tests:
- [Enhancement] Refactor helm_deploy to use data from initial test suite CNF deployment and no longer do a new deployment #564
- [Enhancement] Refactor reasonable_startup_time to use data from initial test suite CNF deployment and no longer do a new deployment #565

**Comment by agentpoyo** [comment]
This is in reference to: https://github.com/cncf/cnf-testsuite/issues/565

**Comment by agentpoyo** [comment]
AC already run: https://github.com/cncf/cnf-testsuite/issues/565#issuecomment-759070387

**Comment by lixuna** [comment]
0 pts, work for this issue completed in #565
