### ISSUE TITLE
[Enhancement] Refactor helm_deploy to use data from initial test suite CNF deployment and no longer do a new deployment

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testsuite#564]
[Acceptance Criteria](https://github.com/cncf/cnf-conformance/issues/564#issuecomment-759082400) 

### [Enhancement] Refactor `helm_deploy` to use data from initial test suite CNF deployment and no longer do a new deployment

**Is your feature request related to a problem? Please describe.**
The helm_deploy test does a new CNF deployment and any global resources will overwrite existing ones causing failures with any following tests as well as cleanup problems.

**Describe the solution you'd like**
Save the data which this test needs during the initial CNF deployment (done by cnf_setup) and access the saved information when this test runs.

**Describe alternatives you've considered**
- disable test completely
- add destructive flag and skip by default. See #562 
- create unique names for the global resources for each new deploy and cleanup after every test

**Additional context**

**Comment by lixuna** [comment]
A/C to be based on updated A/C in #565 
- https://github.com/cncf/cnf-conformance/issues/565#issuecomment-759070387

**Comment by agentpoyo** [comment]
Acceptance Criteria: 
---

### Documentation is updated, as needed:

**Remove the destructive warning from the documentation for reasonable_startup_time**

- [ ]  USAGE is updated
- [ ]  Test Categories md is updated
- [ ]  Installation instructions is updated

Note: CNF configuration may or may not change in this ticket. Update docs accordingly.

###  Common steps
- [x]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [x]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [x]  Set the GITHUB_USER environment variable for running the specs
- [x]  Set the GITHUB_TOKEN environment variable for running the specs
- [x]  Set the DOCKERHUB_USERNAME environment variable for running the specs
- [x]  Set the DOCKERHUB_PASSWORD environment variable for running the specs
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GHA CI
- [ ]  As a peer reviewer, check that PR passes GHA CI tests
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [x]   As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [x]  Run `shards install`


### Spec test should pass
- [x]  Run `crystal spec`
- [x]   I expect to see PASSED for the tests

### Update Prerequistite checker
- TBD

### Update cnf-conformance.yml
- [ ] N/A
- [ ] Update cnf-conformance.yml
- [ ] continue, If there is an update to cnf-conformance.yml
- [ ] for each CNF Example
- [ ] Update the example CNF's cnf-conformance.yml to include the new changes
- [ ] Update the example CNF's README if needed
- [ ] Test the example CNF following it's README

Note: CNF configuration may or may not change in this ticket. Update example CNFs and cnf-conformance.yml example files accordingly. 

### Update yml validator, if needed
- [ ] N/A
- [ ] Update yaml to support any changes in CNF configuration

### Using `crystal spec spec/workload` command should PASS or FAIL as expected reasonable_startup_time without causing resource conflicts:
- [x]  Run `crystal spec spec/workload`
- [x]  I expect to see the output and results from all workload tests in the spec/workload directory
- [x]  I expect to see PASSED for all specs
- [x]  I do not expect to see any stack traces, exceptions, or unexpected application errors

### I would expect the `helm_deploy` test to provide FAIL a bad helm deploy:
- [x]  Follow common steps above
- [x]   Prepare the test suite to use the CNF by running: `./cnf-conformance cnf_setup cnf-path=./sample-cnfs/sample-bad-helm-deploy-repo`
- [x]  Run  `./cnf-conformance helm_deploy destructive`

### I would expect the `helm_deploy` test to provide PASS a good helm deploy:
- [x]  Follow common steps above
- [x]   Prepare the test suite to use the CNF by running: `./cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample-coredns/cnf-conformance.yml`
- [x]  Run  `./cnf-conformance helm_deploy`
- [x]  I do not expect to see any stack traces, exceptions, or unexpected application errors

### Screenshots of tests runs with results in the comments
- [x]  I can see a screenshot of the FAILED deploy
- [x]  I can see a screenshot of the PASSED deploy

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/115813832-8cb6ce80-a3b9-11eb-8cd6-9f33caef2181.png)

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/115814216-40b85980-a3ba-11eb-9d80-678dcb52c4b9.png)

**Comment by lixuna** [comment]
@wavell @agentpoyo @denverwilliams what was the level of effort in pts to make this change? (0,1,2,3,5,8,13,21)

**Comment by agentpoyo** [comment]
5pts
