### ISSUE TITLE
[Feature] Create a tool to help generate cnf-conformance.yaml

### ISSUE THREAD

**Issue by clementnuss** [cncf/cnf-testsuite#588]
**Is your feature request related to a problem? Please describe.**
When using cnf-conformance to test closed-source CNF (a real 5G Core CNF from a vendor :)), it took quite a bit of time creating the `cnf-conformance.yaml` file, as the CNF under test is comprised of more 20 pods, which complicates a bit filling the `container names` section of `cnf-conformance.yaml`.

**Describe the solution you'd like**
Ideally, a small utility could parse a folder containing the CNF/Helm Chart, and generate a `cnf-conformance.yaml` file with all container_names that have been found in the Helm Chart.

**Comment by agentpoyo** [comment]
Todo: Add Acceptance Criteria steps for peer review.

**Comment by agentpoyo** [comment]
### Acceptance Criteria

---
###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]   As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`

### Update documentation 
- [ ] Go to https://github.com/cncf/cnf-testsuite/blob/main/CNF_CONFORMANCE_YML_USAGE.md
- [ ] I expect to see an explanation of generate_config

### Update Prerequisite checker
- [ ] N/A (check for dockerd install)

### When `generate_config` is passed against a helm chart, we should see a cnf-testsuite.yml created as our specified output file:
- [ ] Follow common steps above
- [ ]  Run `cnf-testsuite generate_config config-src=stable/coredns output-file=./cnf-testsuite.yml`
- [ ]  I expect to see the output from the test
- [ ] I would expect a working config file for ./cnf-testsuite.yml by viewing the file, eg. `cat cnf-testsuite.yml`

### When `generate_config` is passed against a helm directory, we should see a cnf-testsuite.yml created as our specified output file:
- [ ] Follow common steps above
- [ ]  Run `cnf-testsuite generate_config config-src=/helm/dir output-file=./cnf-testsuite.yml`
- [ ]  I expect to see the output from the test
- [ ] I would expect a working config file for ./cnf-testsuite.yml by viewing the file, eg. `cat cnf-testsuite.yml`

### When `generate_config` is passed against a manifest directory, we should see a cnf-testsuite.yml created as our specified output file:
- [ ] Follow common steps above
- [ ]  Run `cnf-testsuite generate_config config-src=/manifest/directory output-file=./cnf-testsuite.yml`
- [ ]  I expect to see the output from the test
- [ ] I would expect a working config file for ./cnf-testsuite.yml by viewing the file, eg. `cat cnf-testsuite.yml`


### Screenshots of all command and workload command output
- [ ] I can see a screenshot from the generate_configs above with sample output of the files generated.

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/117348604-04800100-ae70-11eb-9d90-41ecd63a8aa4.png)

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/117349249-c9320200-ae70-11eb-8034-cd55662cccbc.png)

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/117352497-ad305f80-ae74-11eb-9178-b433a4869f2b.png)

**Comment by clementnuss** [comment]
Thanks a lot for the work on this issue 👏 👍
