### ISSUE TITLE
[Feature] Update INSTALL and CNF_TESTSUITE_YML_USAGE with helm chart / k8s manifest requirements

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#609]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Documentation does not detail that CNF Test Suite requires a helm chart or k8s manifest.

**Describe alternatives you've considered**
We need to add to the INSTALL and CNF_TESTSUITE_YML_USAGE about such requirements.

**Additional context**
No

**Comment by taylor** [comment]
@agentpoyo dup?

**Comment by lixuna** [comment]
@agentpoyo is this issue still relevant?
