### ISSUE TITLE
[Feature] ./cnf-conformance cnf_setup should have a more prominent warning if release is already installed

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#633]
**Describe the bug**
./cnf-conformance cnf_setup should have a more prominent warning if deployment is already installed

**To Reproduce**
1. run `./cnf-conformance cnf_setup cnf-path=./sample-cnfs/sample_local_registry/cnf-conformance.yml`
2. run `./cnf-conformance cnf_setup cnf-path=./sample-cnfs/sample_coredns/cnf-conformance.yml`
3. See error:
![image](https://user-images.githubusercontent.com/29548/109874188-659f1480-7c34-11eb-8cd9-21d25df29ad9.png)

**Expected behavior**
The message should be a yellow warning message, informing the user that the cnf was not installed

**Comment by HashNuke** [comment]
The code for the fix is in PR #861. I'll add some tests and then send a PR.

**Comment by lixuna** [comment]
@HashNuke what is the status of this issue?

**Comment by lixuna** [comment]
What is the level of effort in pts for this issue? (ie. 0,1,2,3,5,8,13,21) 

Please add a comment with your estimates, @HashNuke @wavell @denverwilliams @taylor @agentpoyo

**Comment by HashNuke** [comment]
@lixuna 5pts. Some changes in the PR pending post-review.

**Comment by HashNuke** [comment]
I just reviewed this PR and updated it with changes from the main branch.I think this change is reasonable.

**Comment by agentpoyo** [comment]
![633_results_output](https://user-images.githubusercontent.com/14348948/137828607-56d8be56-1393-446f-9770-a3a0b68336fe.png)

**Comment by agentpoyo** [comment]
> @agentpoyo
> 
> It seems like it should exit after "Release name coredns has already been setup" and skip the successful message.
> 
> Alternatively it after that message it should say something like "Use the cnf_cleanup command to remove the existing release for coredns"
> 
> That could be a new enhancement though?

Good point @taylor. Honestly thinking about it, if you've already run cnf_setup on an existing CNF that's a duplicate, could also do away with the first line as well, since it didn't actually create directories in cnfs/ 

@HashNuke 

Thoughts on opening up a new feature issue?

**Comment by agentpoyo** [comment]
@HashNuke @taylor 

Perhaps instead of it saying it 'successfully setup <cnf-name>', if it found it's a duplicate, it should print out something that details  '<cnf-name> currently in running state'. And if we find coredns installed but in a error state, it can state such things as well. Sounds like a feature when I start thinking about it more.

**Comment by lixuna** [comment]
closing as done, please open a new issue for the updates suggested above
