### ISSUE TITLE
[BUG] ./cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample_local_registry should not error

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#634]
**Describe the bug**
'LOG_LEVEL=error ./cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample_local_registry' currently errors if there is no cnf installed, but works in all other cases (during the cleanup, during a reinstall)

**To Reproduce**
1. Make sure there is no cnf installed
2. `LOG_LEVEL=error ./cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample_local_registry`
3. See error
![image](https://user-images.githubusercontent.com/29548/109874377-a4cd6580-7c34-11eb-9413-7e4fe2025962.png)

**Expected behavior**
cnf-config should work as an alias for cnf-path

**Comment by HashNuke** [comment]
Work in progress as a part of `bug/#634` branch.

**Comment by agentpoyo** [comment]
Acceptance Criteria:

#### When running cnf_cleanup, both cnf-config and cnf-path should work the same to cleanup any installed cnfs:
- [ ] Create or find a k8s cluster using common steps.
- [ ] Setup using cnf-config: `./cnf-testsuite cnf_setup cnf-config=sample-cnfs/sample_coredns/cnf-testsuite.yml`
- [ ] You should see coredns setup successfully
- [ ] Cleanup using cnf-path: `./cnf-testsuite cnf_cleanup cnf-path=sample-cnfs/sample_coredns/`
- [ ] You should see coredns cleanup without errors.

#### When running cnf_cleanup, both cnf-config and cnf-path should work the same to cleanup any installed cnfs:
- [ ] Create or find a k8s cluster using common steps.
- [ ] Setup using cnf-path: `./cnf-testsuite cnf_setup cnf-path=sample-cnfs/sample_coredns/`
- [ ] You should see coredns setup successfully
- [ ] Cleanup using cnf-config: `./cnf-testsuite cnf_cleanup cnf-config=sample-cnfs/sample_coredns/cnf-testsuite.yml`
- [ ] You should see coredns cleanup without errors.

- [ ] I can see screenshots of both the cnf-cleanup using cnf-config and cnf-path, successful cleanups
- [ ] I can see that the pods created for CoreDNS are terminating or terminated after cnf_cleanup

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/125342425-867e2180-e31a-11eb-908f-49d124c3d86a.png)

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/125342649-c218eb80-e31a-11eb-9600-ea1086912643.png)

**Comment by lixuna** [comment]
@agentpoyo @wavell @HashNuke what is the level of effort in points for this issue? (ex. 0,1,2,3,5,8,13,21)
