### ISSUE TITLE
[Feature] Enable Critical Error Codes 

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#650]
**Is your feature request related to a problem? Please describe.**
- Current exit codes **for the whole test suite** are pass = 0, fail = 1
- Current exit codes **for running a single test** are pass = 0, n/a = 0 , skipped = 0, fail = 1.
- All **required** tests must pass for the whole test suite to pass (return 0)

**Describe the solution you'd like**
- Update exit codes **for running a single test** are pass = 0, n/a = 0 , skipped = 0, fail = 1, critical failure = 2 for each test. 
- All **required** tests must pass
- If any tests return 2 then whole test suite is 2
- If no tests return 2 and any tests return with 1 then whole test suite returns 1
- Else whole test suite returns 0

*A critical failure is a crystal exception*

**Additional context**
- related to #645 and #707

**Comment by wavell** [comment]
acceptance test
./cnf-testsuite divide_by_zero strict
echo $? should be 2

**Comment by lixuna** [comment]
@wavell @denverwilliams This is an old issue, created one year ago. For the CNF Certification, we will not have the concept of "All required tests must pass for the whole test suite to pass (return 0)"

**Comment by wavell** [comment]
https://hackmd.io/6lp0LeL5S06FBr32PVYy1w @taylor

**Comment by taylor** [comment]
@wavell @denverwilliams please update with current status and move to todo / ready for dev

**Comment by agentpoyo** [comment]
No AC required.
