### ISSUE TITLE
[BUG] SKIPPED tests seem to still be added to overall score results

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#687]
**Describe the bug**
It seems that the SKIPPED tests are still being added in the total score results when running the CNF Test Suite.

When running a test, the total output displays a score total of 76 points but the final result states 86 points total. (see screenshot)

**To Reproduce**
1. Follow common install steps to cnf-conformance
2. Setup and use the sample-coredns-cnf `cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample_coredns_cnf/cnf-conformance.yml`
3. Then run a `workload` by doing `LOG_LEVEL=error ./cnf-conformance workload`
4. See output

**Expected behavior**
The total points for SKIPPED tests should be removed from the totals in the final results. 

These should also provide more information if SKIPPED. Perhaps 0 points of possible 10 points not counted.

**Screenshots**
![image](https://user-images.githubusercontent.com/14348948/113194728-09c1ae80-9227-11eb-884f-73547c7344c7.png)

**Device (please complete the following information):**
 - OS Linux
 - Distro Ubuntu
 - Version 18.04
 - Architecture x86

**Comment by wavell** [comment]
@sishbi

**Comment by agentpoyo** [comment]
This one kind of leans and depends on https://github.com/cncf/cnf-conformance/issues/707

**Comment by williscool** [comment]
> This one kind of leans and depends on https://github.com/cncf/cnf-conformance/issues/707

@agentpoyo just noticed this. had been working on code for the solution. have you guys talked about this in a pairing session?

@wavell @denverwilliams ?

**Comment by wavell** [comment]
https://hackmd.io/6lp0LeL5S06FBr32PVYy1w

**Comment by HashNuke** [comment]
Verified issue with result score calculation.

* Workload test says `149 of 296`
* Total points in the results yml file is 159 (`(30pts * 5) + (10pts * 2) + (-1pts * 11) = 159`)

The total score is 10 points less than what it should be. Screenshot below.
![CleanShot 2022-02-03 at 17 02 26@2x](https://user-images.githubusercontent.com/84005/152335434-9eb0c063-2c03-4c39-8bfe-eca33fee4290.png)

**Comment by HashNuke** [comment]
The screenshot below are some notes from the workload test that I was running to validate the issue.
* I made note of the tests that are failing or skipped.
* Cross-verified the output on the console with the results yaml file.

Created tickets for any issues that were found during the validation exercise.

* #1199
* #1200 
* #1201

![image](https://user-images.githubusercontent.com/84005/152395547-1e5a62a0-85b5-4b8d-ae5a-475068d0e64d.png)

**Comment by HashNuke** [comment]
Verified the points assigned to all tests and the behaviour for skipped tests. Compared the output on the console with the points assigned in the results yaml file.

* Skipped tests that are prototypes or destructive are not listed in the results yaml file. I think they should be listed appropriately and marked as zero like the other skipped tests
* ip_addresses test assigns 0 points for passing test. Will verify with the team that this is ok.

![image](https://user-images.githubusercontent.com/84005/152530708-64deab20-262d-47d5-948a-437c1a51b4c4.png)

**Comment by HashNuke** [comment]
Next: Will look into how the test score is calculated when outputting it on the console.

**Comment by HashNuke** [comment]
* Found two tests that are not defined in the points.yml file: `insecure_capabilities` and `dangerous_capabilities`
* This accounts for the 149->159 difference.

**Comment by HashNuke** [comment]
Found 7 skipped tests amounting to 40 points being included in the total maximum score.

```
non_root_user: 5
secrets_used: 5
prometheus_traffic: 10
open_metrics: 5
routed_logs: 5
tracing: 5
node_drain: 5
```

<img width="1055" alt="CleanShot 2022-02-09 at 17 07 54@2x" src="https://user-images.githubusercontent.com/84005/153193464-dcef3f11-a606-4860-90ec-f98ccced7f53.png">

**Comment by agentpoyo** [comment]
Acceptance Criteria:

- [ ] when running `workload`, I should see skipped tests not adding the overall points for categories.
- [ ] I can see an example output here of skipped tests not adding to points total.
