### ISSUE TITLE
[Feature] an optional acceptance criteria section aka "How will this be tested" for github repo

### ISSUE THREAD

**Issue by williscool** [cncf/cnf-testsuite#703]
**Is your feature request related to a problem? Please describe.**

We need an optional acceptance criteria section aka "How will this be tested" for bugs and features and maybe other things.

**Describe the solution you'd like**

PR to templates with "How will this be tested" section. Will not always be necessary i.e. for spelling or documentation changes so will be optional probably communicated via a (in needed) in parens

**Describe alternatives you've considered**

trying to guess each time

**Additional context**

an issue that did not have A/C that needed pretty elaborate A/C

https://github.com/cncf/cnf-conformance/issues/682#issuecomment-815883889

**Comment by lixuna** [comment]
@williscool if this issue is ready for peer review, please move it to the "Needs Peer Review" column

**Comment by lixuna** [comment]
@agentpoyo has the typo in the bug report template been fixed?

**Comment by agentpoyo** [comment]
> @agentpoyo has the typo in the bug report template been fixed?

It's fixed now in PR https://github.com/cncf/cnf-testsuite/pull/770 Please review and merge.
