### ISSUE TITLE
[BUG] Workload shows extra messaging (for chaos mesh) in error mode

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#714]
**Describe the bug**
Workload shows extra messaging (for chaos mesh) in error mode

**To Reproduce**
1. `LOG_LEVEL=error ./cnf-conformance workload`
2. See error
Note: the cnf used to test this was sample_coredns, on the dev box

**Expected behavior**
I expect extra messaging to show only when running in info or debug modes.

**Screenshots**
<img width="1260" alt="Screen Shot 2021-04-19 at 2 40 01 PM" src="https://user-images.githubusercontent.com/29548/115293668-375e9100-a11d-11eb-8594-794f309a0e61.png">

**Comment by taylor** [comment]
@wavell I'm not seeing these messages. Was it fixed in another commit/ticket?

**Comment by agentpoyo** [comment]
LGTM, we're not seeing these extra messages any longer.
