### ISSUE TITLE
[BUG] Spelling mistake in secret volumes test 

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#717]
**Describe the bug**
 Spelling mistake in secret volumes test 

**To Reproduce**
1. Go to `./cnf-conformance workload`
2. See misspelling

**Expected behavior**
There should be no misspellings.

**Screenshots**
<img width="782" alt="Screen Shot 2021-04-19 at 4 24 34 PM" src="https://user-images.githubusercontent.com/29548/115305444-f02bcc80-a12b-11eb-98da-5fb741d360b4.png">

**Comment by agentpoyo** [comment]
No need for full AC as you can see in the PR the file has been modified to remove the extra S in address.

https://github.com/cncf/cnf-testsuite/pull/719/files
