### ISSUE TITLE
Dup: #1302 [Feature] helm arguments should have a separate key (from the helm_chart) in the cnf-conformance.yml

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#718]
**Is your feature request related to a problem? Please describe.**
 helm arguments should have a separate key (from the helm_chart) in the cnf-conformance.yml

**Describe the solution you'd like**
 helm arguments should have a separate key (from the helm_chart) in the cnf-conformance.yml

**Comment by agentpoyo** [comment]
Closing this as it's a duplicate. This is "In Progress" and the peer review results will be found in https://github.com/cncf/cnf-testsuite/issues/1302
