### ISSUE TITLE
[Feature] Update links in documentation to replace absolute paths to relative 

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#724]
**Is your feature request related to a problem? Please describe.**
- The CNF Test Suite repo was recently renamed from `CNF Conformance`
- This caused many broken links in the documentation that are pointing to absolute paths using the old repo url `https://github.com/cncf/cnf-conformance`

**Describe the solution you'd like**
- Update links in documentation to replace absolute paths to relative 

**Example tasks:**
- Change all links in https://github.com/cncf/cnf-testsuite/blob/130c50caf83d4b6c804e9f933a06b8a1116472df/USAGE.md
- ie. from `https://github.com/cncf/cnf-conformance/blob/main/USAGE.md#overview` to  `USAGE.md#overview`
- ie. from `https://github.com/cncf/cnf-conformance/blob/main/USAGE.md#syntax-for-running-any-of-the-tests` to `USAGE.md#syntax-for-running-any-of-the-tests`

**Describe alternatives you've considered**
- update all dead links from `https://github.com/cncf/cnf-conformance/...` to `https://github.com/cncf/cnf-testsuite/...`

**Additional context**
- Inspired by CNF WG [issue 108](https://github.com/cncf/cnf-wg/issues/108)

**How will this be tested?**
1. search for "https://github.com/cncf/cnf-conformance" 
2. click on `markdown files`
2. I should see 0 code results in markdown files

**Comment by himanshu007-creator** [comment]
hi, I would like to work on this issue. Please assign me this issue.

**Comment by lixuna** [comment]
Thank you, @himanshu007-creator 

Welcome to the CNF Test Suite! Here is the link to the [Contributing Guide](CONTRIBUTING.md). (There are several links in this file that will need to be updated from `cnf-conformance` to relative URLs.) 

If you have any questions, please feel free to tag @lixuna @taylor @wavell @denverwilliams @agentpoyo and/or @williscool.

**Comment by himanshu007-creator** [comment]
hi @lixuna, i have updated all links in <a href="https://github.com/cncf/cnf-testsuite/blob/130c50caf83d4b6c804e9f933a06b8a1116472df/USAGE.md">USAGE.md</a> as mentioned in issue description. Do i also need to update all links to relative links in <a href="https://github.com/cncf/cnf-testsuite/blob/main/CONTRIBUTING.md">CONTRIBUTING.md</a> as well ?
I am not sure after reading <a href="https://github.com/cncf/cnf-testsuite/issues/724#issuecomment-826893045">this</a>

**Comment by lixuna** [comment]
Thank you for your help with updating the USAGE guide, @himanshu007-creator! 

If you would like to update the links in the contributing guide, that would be much appreciated. If not, that's ok, too!

The end goal will be to replace all mentions of "https://github.com/cncf/cnf-conformance..." with relative links throughout this cncf/cnf-testsuite repo. 

For example, today when I search for "https://github.com/cncf/cnf-conformance" and look at markdown files, I can see [24 code results](https://github.com/cncf/cnf-testsuite/search?l=Markdown&q=https%3A%2F%2Fgithub.com%2Fcncf%2Fcnf-conformance)

<img width="985" alt="Screen Shot 2021-04-27 at 10 13 20 AM" src="https://user-images.githubusercontent.com/11701267/116266587-3e028f00-a741-11eb-8d96-c57ea0c8a67d.png">

How will this be tested? 
1. search for "https://github.com/cncf/cnf-conformance" 
2. I should see 0 code results in markdown files

**Comment by himanshu007-creator** [comment]
I have made a PR, please review it , if some changes are needed,  will fix them✔

**Comment by agentpoyo** [comment]
LGTM :+1:
