### ISSUE TITLE
[Feature] Update USAGE guide to list platform tests by test categories

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#729]
**Is your feature request related to a problem? Please describe.**
- Currently, all platform tests are grouped together under https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#platform-tests
- It's difficult to see which platform tests have been implemented per each test category

**Describe the solution you'd like**
- Expand the platform test documentation to show all test categories with the platform tests assigned under each category

**Describe alternatives you've considered**
- N/A

**Additional context**
- The CNF Test Suite's primary focus is on workload (application) testing, however the CNF Test Suite supports adding platform (infrastructure) tests in the future. Currently there are several proofs of concepts available for platform tests.

**Comment by agentpoyo** [comment]
Doc updates requires no Acceptance Criteria.

**Comment by lixuna** [comment]
@wavell @agentpoyo what was the level of effort in pts to make this change? (0,1,2,3,5,8,13,21)

Maybe a 1?

**Comment by agentpoyo** [comment]
1pt
