### ISSUE TITLE
[BUG] document and markdown files should skip the binary tests in gh actions

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#734]
**Describe the bug**
Document updates and changes to markdown files skip the spec tests but the binary tests still run, causing longer running github action tests. Need to skip the binary tests for documentation changes in markdown files.

**Comment by denverwilliams** [comment]
@agentpoyo Skips now working https://github.com/cncf/cnf-testsuite/actions/runs/775841150

**Comment by agentpoyo** [comment]
LGTM :+1:

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/115810731-0c419f00-a3b4-11eb-8e98-dbc6f94eaa36.png)

**Comment by lixuna** [comment]
@wavell @agentpoyo @denverwilliams what was the level of effort in pts to make this change? (0,1,2,3,5,8,13,21)

**Comment by agentpoyo** [comment]
2pts
