### ISSUE TITLE
[BUG] Rename cnf-conformance binary & tarball to cnf-testsuite

### ISSUE THREAD

**Issue by denverwilliams** [cncf/cnf-testsuite#739]
**Describe the bug**
Rename cnf-conformance binary & tarball to cnf-testsuite.
..
**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - OS [e.g. Linux, iOS, Windows, Android]
 - Distro [e.g. Ubuntu]
 - Version [e.g. 18.04]
 - Architecture [e.g. x86, arm]

**How will this be tested? aka Acceptance Criteria (optional)**

(optional: unncesasray for things like spelling errors and such)

Once this issue is address how will the fix be verified?

**Additional context**

---

NOTE: you can enable higher logging level output via the command line or env var. to help with debugging

```
# cmd line
./cnf-conformance -l debug test

# make sure to use -- if running from source
crystal src/cnf-conformance.cr -- -l debug test 

# env var
LOGLEVEL=DEBUG ./cnf-conformance test
```

Also setting the verbose option for many tasks will add extra output to help with debugging

```
crystal src/cnf-conformance.cr test_name verbose
```

Check [usage documentation](https://github.com/cncf/cnf-conformance/blob/master/USAGE.md) for more info about invoking commands and loggin

**Comment by agentpoyo** [comment]
Acceptance Criteria:

 - [ ] Follow the curl binary installation
 - [ ] Verify the tarball downloaded is called/named `cnf-testsuite` and not `cnf-conformance`
 - [ ] Verify that `cnf-testsuite` is in your PATH as the executable binary used to run the test suite
 - [ ] I can see a screenshot that the executable is `cnf-testsuite` by running `cnf-testsuite version`

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/116451750-847bea80-a822-11eb-89f1-7a071a705050.png)
