### ISSUE TITLE
[Feature] Rename "statelessness" test category name to "State" in YAML and Crystal files

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#744]
**Is your feature request related to a problem? Please describe.**
- Update code in response to "State" Test Category name change in #264 

**Describe the solution you'd like**
- Update YAML and Crystal files to change "statelessness" to "state" [per CNF WG's best practices](https://github.com/cncf/cnf-wg/blob/main/doc/best_cnf_dev.md#60-state)
- Search for "statelessness" in repo
- Filter to view YAML files
- As of April 28, 2021, there are 2 YAML files that contain the phrase "statelessness"
- Update YAML files to rename "statelessness" to "state"
- Filter to view Crystal files
- As of April 28, 2021, there are 5 Crystal files that contain the phrase "statelessness"
- Update Crystal files to rename "statelessness" to "state"

**How will this be tested?**
- Search for "statelessness" in repo
- Filter to view YAML files
- After the documentation is updated in this issue, there should be 0 results for "statelessness" in YAML files
- Filter to view Crystal files
- After the documentation is updated in this issue, there should be 0 results for "statelessness" in Crystal files

**Additional context**
#264

**Comment by HashNuke** [comment]
Attempted as a part of #838. Would love for someone to pick it up for review and share any feedback.
I haven't marked the checklist on this issue because I am not sure if the PR is good yet.

**Comment by agentpoyo** [comment]
Acceptance Criteria:

- [ ] run `cnf-testsuite state`
- [ ] I should see no crystal errors and PASSED on tests
- [ ] I can see a screenshot of the test using `state` instead of statelessness

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/124797831-57317400-df18-11eb-9909-41b8d6fa10f3.png)
