### ISSUE TITLE
[Feature] cnf-testsuite prerequisites should check kubectl versions

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#761]
**Is your feature request related to a problem? Please describe.**
Yes, discovered my kubectl client version was 1.14 while the server version was 1.20. This caused issues when cnf-testsuite was running kubectl apply commands.

**Describe the solution you'd like**
Prerequisites should check that kubectl is no more than 3 versions behind between the client and the server versions.

**Additional context**
![image](https://user-images.githubusercontent.com/14348948/117353279-8cb4d500-ae75-11eb-8854-4317a219863e.png)

**Comment by HashNuke** [comment]
@agentpoyo @wavell Would the following behaviour be alright when comparing?

For examples in the following scenarios, let us say kubectl version is `a.b.c` and server version is `x.y.z`

1. Print error and exit if major versions are different. Example: `a != x` then error.
2. Print error and exit if minor versions are 3 versions behind/ahead. Example: `(y - b) > 3` then error.

**Comment by agentpoyo** [comment]
This new issue is likely related: https://github.com/cncf/cnf-testsuite/issues/824

This can either be quick to support MicroK8s and their changing of the `minor` version or could turn into more. If we add the support to handle the minor version with `+`, we can test against MicroK8s.

**Comment by agentpoyo** [comment]
Acceptance Criteria:

- [ ] Create or find a k8s cluster that is 3 minor versions older than our kubectl client: `kind create cluster --name kind --kubeconfig kind.conf  --image=kindest/node:​v1.18.0`
- [ ] `./cnf-testsuite setup`
- [ ] You should see setup check the server version that it's 3 or more versions older than client
- [ ] I can see a screenshot of the `setup` output

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/124168651-0bd81b00-da6b-11eb-9a0d-7d709d1247cd.png)

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/124169442-ded83800-da6b-11eb-9058-ee2c98724726.png)

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/124173346-8a838700-da70-11eb-8560-ff90082b1c2a.png)

**Comment by agentpoyo** [comment]
Taken from the k8s docs: https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/

```
You must use a kubectl version that is within one minor version difference of your cluster. For example, a v1.21 client can communicate with v1.20, v1.21, and v1.22 control planes. Using the latest version of kubectl helps avoid unforeseen issues.
```

We might want to refactor our warnings to match what they state as a +-1 minor version difference between client and cluster.

**Comment by agentpoyo** [comment]
@HashNuke 

Looks like the client behind the server passes but if the server is 3 version behind the client, it doesn't warn.

Also, I couldn't or didn't see any hints when using any arguments with `offline` about the cluster or server may not be reachable, etc.

But look at my previous comment after looking at k8s docs: https://github.com/cncf/cnf-testsuite/issues/761#issuecomment-872470576 about their recommendation now of versions should only be + or - 1 minor version difference.

@wavell @taylor @denverwilliams

**Comment by agentpoyo** [comment]
Also, we should only display the WARNING during normal setup output. 

> Global kubectl client is not more than 3 minor versions behind server version

**Comment by agentpoyo** [comment]
LGTM, same results pointed out in https://github.com/cncf/cnf-testsuite/pull/840 PR screenshots.

**Comment by lixuna** [comment]
@agentpoyo @wavell @HashNuke what is the level of effort in points for this issue? (ex. 0,1,2,3,5,8,13,21)

**Comment by agentpoyo** [comment]
@lixuna 3pts is what I would have said prior to the work.
