### ISSUE TITLE
[Feature] Make a tool that tarballs the containerized tools used by the testsuite.

### ISSUE THREAD

**Issue by denverwilliams** [cncf/cnf-testsuite#763]
Make a tarball tool that tarballs containerized tools that we maintain or are maintained upstream(dockerd images). 

https://hackmd.io/qCAvHzzDS9aXU2q4lxNzYQ?view

**How will this be tested? aka Acceptance Criteria (optional) **

(optional: unnecessary for things like some version bumps etc.)

Once this issue is addressed how will the fix be verified?

**Additional context**
Related to #585

**Comment by wavell** [comment]
Acceptance criteria

[ ] - run `./cnf-testsuite setup --offline=./airgapped.tar.gz`
[ ] - I should see a tarball named airgapped.tar.gz
[ ] - untar airgapped.tar.gz
[ ] - I should see an image

**Comment by taylor** [comment]
The overview in https://hackmd.io/qCAvHzzDS9aXU2q4lxNzYQ?view looks good. +1 for breaking it down into smaller chunks. Handling the test suite before supporting items like copying the image to the K8s repo etc sounds good too.

**Comment by agentpoyo** [comment]
This fails, it was wanting a tmp/ directory in the `pwd`, so after creating, it still complains with the following DEBUG output:

![image](https://user-images.githubusercontent.com/14348948/117888748-231f3700-b278-11eb-8261-ff7b3de25a4d.png)

@wavell @denverwilliams

**Comment by taylor** [comment]
@agentpoyo @denverwilliams @wavell what is the estimate in points for this?

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/118047812-eff4aa80-b340-11eb-82b4-40d77a89ff64.png)

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/118047892-0ac71f00-b341-11eb-8d91-602ec1ca199e.png)

**Comment by lixuna** [comment]
@denverwilliams @agentpoyo @wavell what was the level of effort in points to add this feature? (ex. 0,1,2,3,5,8,13,21)

**Comment by agentpoyo** [comment]
I'd say 5pts before work was started and completed. @watson and @denverwilliams might want to chime in with their pts estimates. @lixuna

**Comment by lixuna** [comment]
denver agreed with 5
