### ISSUE TITLE
[EPIC Feature] Make an image deployment tool that makes the images available to the private cluster

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#773]
Make an image deployment tool that makes the images available to the private cluster

 - bootstrapping phase
    - docker cli tools need to be installed onto the cluster.
    - option 1
    - load dockerd containter into private registry so it's available for us to deploy to the cluster.
    - option 2
    - Spawn a registry process in the test suite and use it to make the docker cli tools needed avaliabe to be installed onto the cluster.
- image copy phase
    - option 1
       - use kubectl command to copy images to k8s node
       - use kubectl command to call dockerd tool to load images on node
       - use kubectl command to call dockerd tool to retag images with the proper full path on node
    - option 2
      - Use docker tools to load docker images into local docker client from offline tarball and push to the private registry.
      - Use docker cli tools installed on the cluster to pull down images from the private registry and re-tag with the appropriate image name / tag.

https://hackmd.io/qCAvHzzDS9aXU2q4lxNzYQ?view

Split into two tickets:
    - [[Feature] Bootstrap a cluster #782](https://github.com/cncf/cnf-testsuite/issues/782)
    - [[Feature] Publish tarball #780](https://github.com/cncf/cnf-testsuite/issues/780)

**How will this be tested? aka Acceptance Criteria (optional) **

(optional: unnecessary for things like some version bumps etc.)

Once this issue is addressed how will the fix be verified?

**Additional context**
Related to #585

**Comment by taylor** [comment]
@agentpoyo @denverwilliams @wavell what is the estimate in points for this?

**Comment by taylor** [comment]
This was implemented in 2 tickets:
    - [[Feature] Bootstrap a cluster #782](https://github.com/cncf/cnf-testsuite/issues/782)
    - [[Feature] Publish tarball #780](https://github.com/cncf/cnf-testsuite/issues/780)
