### ISSUE TITLE
[BUG] cnf_setup command try to remove a non existent file 

### ISSUE THREAD

**Issue by williscool** [cncf/cnf-testsuite#776]
**Describe the bug**

`cnf_setup`  command try to remove a non existent file 

**To Reproduce**
```
taylor@cnfdev03:~/workspace/taylor$ cnf-testsuite cnf_setup cnf-config=./cnf-testsuite.yml
Successfully created directories for cnf-testsuite
Successfully setup coredns
rm: cannot remove '/home/taylor/workspace/taylor/cnfs/coredns/configmap_test.yml': No such file  or directory
```
**Expected behavior**

binary should not attempt to remove this file if it does not exist or if this is unimportant this message should be supressed

**Screenshots**

example around the 3:36 mark of this video
https://asciinema.org/a/rHjHOFFVL5jW8B0R6umYzcFyl

**Device (please complete the following information):**

- OS [e.g. Linux, iOS, Windows, Android]
- Distro [e.g. Ubuntu]
- Version [e.g. 18.04]
- Architecture [e.g. x86, arm]

**How will this be tested? aka Acceptance Criteria (optional)**

(optional: unnecessary for things like spelling errors and such)

Once this issue is address how will the fix be verified?

**Additional context**

---

NOTE: you can enable higher logging level output via the command line or env var. to help with debugging

```
# cmd line
./cnf-testsuite -l debug test

# make sure to use -- if running from source
crystal src/cnf-testsuite.cr -- -l debug test

# env var
LOGLEVEL=DEBUG ./cnf-testsuite test
```

Also setting the verbose option for many tasks will add extra output to help with debugging

```
crystal src/cnf-testsuite.cr test_name verbose
```

Check [usage documentation](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) for more info about invoking commands and logging

**Comment by agentpoyo** [comment]
Acceptance Criteria: 
---

Note: CNF configuration may or may not change in this ticket. Update docs accordingly.

###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster

### Run `cnf_setup` to the new example cnf for coredns from INSTALL.md docs:
- [ ] Follow common steps and use your existing binary v0.11.1 installation from the curl binary install steps.
- [ ] Pull down the new `cnf-testsuite.yml` from `example-cnfs/coredns/` with curl or wget: `wget -O cnf-testsuite.yml https://raw.githubusercontent.com/cncf/cnf-testsuite/main/example-cnfs/coredns/cnf-testsuite.yml` from MAIN branch if already merged or from the `bug/#776_fix_non_existent_file` branch with: `wget -O cnf-testsuite.yml https://raw.githubusercontent.com/cncf/cnf-testsuite/bug/%23776_fix_non_existent_file/example-cnfs/coredns/cnf-testsuite.yml`
- [ ] You should not see the error: `rm: cannot remove '/myuser/cnfs/coredns/configmap_test.yml': No such file  or directory`
- [ ] You should see Success on creation of directories and setup of coredns.
- [ ] Run `cnf-testsuite workload`
- [ ] You should not see pod_network_latency and disk_fill_chaos FAILURE and PASSED messages.

### Screenshots of tests runs with results in the comments
- [ ]  I can see a screenshot of a successful cnf_setup
- [ ]  I can see a screenshot of successful workload output.

**Comment by agentpoyo** [comment]
The error seems to have come back after another test suppressed this message:

![image](https://user-images.githubusercontent.com/14348948/118326823-1d6d5f80-b4cb-11eb-8148-c8c2f2880951.png)

**Comment by williscool** [comment]
LGTM

https://asciinema.org/a/pKIE0itd2JlxX0WtZsdZNIY1S
