### ISSUE TITLE
[Feature] Publish tarball

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#780]
Make an image deployment tool that a tarball and pushes the tarball to a previously bootstrapped and air-gapped cluster.

- image copy phase
    - option 1
       - use kubectl command to copy images to k8s node
       - use kubectl command to call dockerd tool to load images on node

https://hackmd.io/qCAvHzzDS9aXU2q4lxNzYQ?view

**How will this be tested? aka Acceptance Criteria (optional) **

(optional: unnecessary for things like some version bumps etc.)

Once this issue is addressed how will the fix be verified?

**Additional context**
Related to #585 #773

**Comment by agentpoyo** [comment]
See https://github.com/cncf/cnf-testsuite/issues/585#issuecomment-849926890 for AC on entire Airgapped Peer Review
