### ISSUE TITLE
[Feature] Bootstrap a cluster

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#782]
Make an bootstrap cluster tool that puts cri-tools on a air-gapped cluster

 - bootstrapping phase
    - docker cli tools need to be installed onto the cluster.
    - option 1
    - load dockerd container into private registry so it's available for us to deploy to the cluster.
    - option 2
    - Reuse an existing container that is on the cluster and has shell and tar commands available
    - option 3
    - Spawn a registry process in the test suite and use it to make the docker cli tools needed available to be installed onto the cluster.

https://hackmd.io/qCAvHzzDS9aXU2q4lxNzYQ?view

**How will this be tested? aka Acceptance Criteria (optional) **

(optional: unnecessary for things like some version bumps etc.)

Once this issue is addressed how will the fix be verified?

**Additional context**
Related to #585 #773

**Comment by agentpoyo** [comment]
### Acceptance Criteria for peer review
---
### Documentation is updated:
- [ ] cnf-conformance.yml documentation update 

###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]   As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]  I expect to see PASSED for the test

### Update Prerequisite checker
- [ ] N/A

### Update yml validator, if needed
- [ ] N/A

### Needs to be filled out with AC
- [ ]  Follow common steps above
- [ ]  Next steps here....

### Screenshots of publish tarball test:
- [ ] I can see a screenshots of SUCCESS of the publish tarball.
