### ISSUE TITLE
[Feature] Add support for bootstrapping using the tar binary from the host.

### ISSUE THREAD

**Issue by denverwilliams** [cncf/cnf-testsuite#785]
**Is your feature request related to a problem? Please describe.**

Add support for bootstrapping using the tar binary from the host. 
For clusters where only pods with /bin/sh are available we will need to use Tar on the host file system in order to finish bootstrapping.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**How will this be tested? aka Acceptance Criteria (optional) **

(optional: unnecessary for things like some version bumps etc.)

Once this issue is addressed how will the fix be verified?

**Additional context**

**Comment by agentpoyo** [comment]
### Acceptance Criteria for peer review
---
### Documentation is updated:
- [ ] cnf-conformance.yml documentation update 

###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]   As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]  I expect to see PASSED for the test

### Update Prerequisite checker
- [ ] N/A

### Update yml validator, if needed
- [ ] N/A

### Needs to be filled out with AC
- [ ]  Follow common steps above
- [ ]  Next steps here....

### Screenshots of publish tarball test:
- [ ] I can see a screenshots of SUCCESS of the

**Comment by agentpoyo** [comment]
See https://github.com/cncf/cnf-testsuite/issues/585#issuecomment-849926890 for AC on entire Airgapped Peer Review

**Comment by lixuna** [comment]
@denverwilliams @agentpoyo @wavell what was the level of effort in points to add this feature? (ex. 0,1,2,3,5,8,13,21)

**Comment by agentpoyo** [comment]
5pts
