### ISSUE TITLE
[Feature] Tar and upload helm directories, and manifest files

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#789]
Use the tarball tool to tarball (and untar) the following tools:

1) tools that use manifest files
2) tools that use a custom helm directory

https://hackmd.io/qCAvHzzDS9aXU2q4lxNzYQ?view

**How will this be tested? aka Acceptance Criteria (optional) **

(optional: unnecessary for things like some version bumps etc.)

Once this issue is addressed how will the fix be verified?

**Additional context**
Related to #585

**Comment by agentpoyo** [comment]
See https://github.com/cncf/cnf-testsuite/issues/585#issuecomment-849926890 for AC on entire Airgapped Peer Review

**Comment by lixuna** [comment]
@denverwilliams @agentpoyo @wavell what was the level of effort in points to add this feature? (ex. 0,1,2,3,5,8,13,21)

**Comment by agentpoyo** [comment]
5pts
