### ISSUE TITLE
[Feature] Create an environment for the automated test of #585 

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#794]
**Is your feature request related to a problem? Please describe.**
[Feature] Create an environment for the automated test of #585 

**Describe the solution you'd like**
[Feature] Create an environment for the automated test of #585

**Comment by agentpoyo** [comment]
No Acceptance Criteria required, this was activity to setup GH Actions to run automated tests which are passing.

**Comment by lixuna** [comment]
@denverwilliams @agentpoyo @wavell what was the level of effort in points to add this feature? (ex. 0,1,2,3,5,8,13,21)
