### ISSUE TITLE
[Feature] cnf_setup airgapped mode

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#795]
**Is your feature request related to a problem? Please describe.**
cnf_setup should install cnfs that use a remote helm chart in airgapped mode

**Describe the solution you'd like**
cnf_setup should install cnfs that use a remote helm chart in airgapped mode

**Comment by agentpoyo** [comment]
Todo: Add AC for peer review.

**Comment by wavell** [comment]
- [ ] use a kubeconfig for a airgapped kind cluster (see github actions)
- [ ] `./cnf-testsuite cnf_setup cnf-config=example-cnfs/coredns/cnf-testsuite.yml airgapped=./tmp/airgapped.tar.gz`
- [ ]`./cnf-testsuite cnf_setup cnf-config=example-cnfs/coredns/cnf-testsuite.yml input-file=./tmp/airgapped.tar.gz`
- [ ] I should see the airgapped installation of the coredns cnf

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/123322958-83053080-d4fa-11eb-9b01-413f8d7b993f.png)

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/123323918-ce6c0e80-d4fb-11eb-92f9-2863868e8388.png)
