### ISSUE TITLE
[Documentation] Create a Contribution Ladder for the CNF Test Suite project

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testsuite#797]
### Discussed in https://github.com/cncf/cnf-testsuite/discussions/790

<div type='discussions-op-text'>

<sup>Originally posted by **taylor** May 26, 2021</sup>
Create a contribution ladder to make it easier for people to know how to engage and what the different roles mean.

Reference:
- https://github.com/cncf/project-template/blob/main/CONTRIBUTOR_LADDER.md
- https://github.com/getporter/porter/blob/main/CONTRIBUTION_LADDER.md
- https://github.com/openservicemesh/osm/blob/main/CONTRIBUTOR_LADDER.md

Overview of potential contributors capabilities:

- Have issues and pull requests assigned to them
- Apply labels, milestones and projects
- Mark issues as duplicates
- Close, reopen, and assign issues and pull requests
- They must agree to and follow this Contributing Guide.
</div>

**Comment by agentpoyo** [comment]
- [ ] When I browse to the cnf-testsuite repo, I can find the CONTRIBUTION_LADDER.md as a valid markdown document in the `main` branch that explains contributing levels for the test suite.
