### ISSUE TITLE
[Workload]  Microservice Test: Does the CNF use a proper init system?

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testsuite#8]
## Title: [Workload] Microservices test: specialized_init_system

Description of problem

There are proper init systems and sophisticated supervisors that can be run inside of a container.  Both of these systems properly reap and pass signals.  Sophisticated supervisors are considered overkill because they take up too many resources and are sometimes too complicated.  Some examples of sophisticated supervisors are: supervisord, monit, and runit.  Proper init systems are smaller than sophisticated supervisors and therefore suitable for containers.  Some of the proper container init systems are tini, dumb-init, and s6-overlay.

Description of solution

The test should fails if PID 1 is supervisord, monit, or runit, and passes if PID 1 is tini, dumb-init, or s6-overlay
The test should fail if PID 1 is anything else.

https://cloud.google.com/architecture/best-practices-for-building-containers 

Acceptance Criteria:
---

### Microservice Test:  Microservices test: specialized_init_system

EPIC: CNF Conformance Test Suite

Release: vN.N.N

Test Category: Configuration

Type of test (static or runtime) = ?

- [ ]  example code: N/A

---

**Environment set up tasks:**

**Upstream tool set up tasks: (conformance suite + upstream tools)**
- N/A

**CNF setup Tasks** 

**Sample CNF tasks:**

**Code implementation tasks:**
- [ ] 

**Documentation tasks:**
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-conformance/blob/master/TEST-CATEGORIES.md) if needed 
- [ ] Update [Pseudo Code md](https://github.com/cncf/cnf-conformance/blob/master/PSEUDO-CODE.md) if needed
- [ ] Update [USAGE md](https://github.com/cncf/cnf-conformance/blob/master/USAGE.md) if needed 
- [ ] Update [installation instructions](https://github.com/cncf/cnf-conformance#installation)  if needed 

**QA tasks**

Dev Review: 
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

---

### Reference: 
Tools:
- Falco 
-  sysdig-inspect

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Find or build a k8s cluster for testing
- [ ] Checkout the `feature/init-systems` branch to build the cnf-testsuite binary from source install (follow source install directions)
- [ ] Setup a CNF that tests the init_system test
- [ ] I should see FAIL and PASS depending on the CNF used for testing with or without an init systems installed on the CNF
- [ ] I can see screenshots of the output here.

**Comment by agentpoyo** [comment]
Expected failed output when no init system found:

![1733_failed_output](https://user-images.githubusercontent.com/14348948/217332021-2bde5810-7cc1-4e6a-ae94-edffcf020c26.jpg)
