### ISSUE TITLE
[Feature] Speed up the github actions automated tests and spec tests

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#805]
**Is your feature request related to a problem? Please describe.**
Github actions are almost 20 minutes long to run.

**Describe the solution you'd like**
We need to speed up github actions tests as they eat up a lot of resources and time when doing tests.

**Describe alternatives you've considered**
Removal of some long running tests; splitting up tests.

**How will this be tested? aka Acceptance Criteria (optional) **
Github Actions will be faster.

**Comment by lixuna** [comment]
@denverwilliams @agentpoyo @wavell what is the status of this issue?

**Comment by agentpoyo** [comment]
GH Actions run in or around 7-8 minutes now if nothing causes them to fail, etc.

![image](https://user-images.githubusercontent.com/14348948/124621125-a22b8880-de3f-11eb-99f7-40a1ea6ebc7d.png)
