### ISSUE TITLE
[Feature] cnf_setup should install cnfs that use a local helm directory in airgapped mode

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#807]
Is your feature request related to a problem? Please describe.
cnf_setup should install cnfs that use a local helm directory in airgapped mode

Describe the solution you'd like
cnf_setup should install cnfs that use a local helm directory in airgapped mode

**Comment by wavell** [comment]
- [ ] use a kubeconfig for a airgapped kind cluster (see github actions)
- [ ] `./cnf-testsuite cnf_setup cnf-config=sample-cnfs/sample_coredns/cnf-testsuite.yml airgapped=./tmp/airgapped.tar.gz`
- [ ] `./cnf-testsuite cnf_setup cnf-config=sample-cnfs/sample_coredns/cnf-testsuite.yml input-file=./tmp/airgapped.tar.gz`
- [ ] I should see the airgapped installation of the sample_coredns cnf

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/123336654-c87e2980-d50b-11eb-8f39-52a357290d9b.png)

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/123337924-8f46b900-d50d-11eb-8fdf-8bee0ab1ed62.png)
