### ISSUE TITLE
[Feature] cnf_setup should install cnfs that use a manifest directory in airgapped mode

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#808]
Is your feature request related to a problem? Please describe.
cnf_setup should install cnfs that use a manifest directory in airgapped mode

Describe the solution you'd like
cnf_setup should install cnfs that use a manifest directory in airgapped mode

**Comment by wavell** [comment]
- [ ] Use a kubeconfig for an airgapped kind cluster (see github actions)
- [ ] `./cnf-testsuite cnf_setup cnf-config=sample-cnfs/k8s-non-helm/cnf-testsuite.yml airgapped=./tmp/airgapped.tar.gz`
- [ ] `./cnf-testsuite cnf_setup cnf-config=sample-cnfs/k8s-non-helm/cnf-testsuite.yml input-file=./tmp/airgapped.tar.gz`
- [ ] I should see k8s-non-helm installed in an airgapped cluster

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/123494111-5c232900-d5e4-11eb-99bb-418c2245ccd5.png)

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/123494133-6e04cc00-d5e4-11eb-94a5-cd4f3c43befd.png)

**Comment by agentpoyo** [comment]
While in airgapped mode (no internet):

```
[drew@hercules cnf-testsuite]$ ./cnf-testsuite cnf_setup cnf-config=sample-cnfs/k8s-non-helm/cnf-testsuite.yml input-file=/tmp/airgapped.tar.gz
Successfully created directories for cnf-testsuite
cnf setup airgapped mode
The connection to the server localhost:8080 was refused - did you specify the right host or port?
../../../../usr/share/crystal/src/json/parser.cr:125:5 in 'parse_exception'
../../../../usr/share/crystal/src/json/parser.cr:121:5 in 'unexpected_token'
../../../../usr/share/crystal/src/json/parser.cr:37:7 in 'parse_value'
../../../../usr/share/crystal/src/json/parser.cr:13:12 in 'parse'
../../../../usr/share/crystal/src/json.cr:131:5 in 'parse'
src/tasks/utils/kubectl_client.cr:187:7 in 'nodes'
src/tasks/utils/kubectl_client.cr:272:52 in 'schedulable_nodes_list'
src/tasks/utils/airgap.cr:353:12 in 'pods_with_tar'
src/tasks/utils/airgap.cr:188:5 in 'bootstrap_cluster'
src/tasks/utils/airgap.cr:165:5 in 'cache_images'
src/tasks/cnf_setup.cr:21:5 in '->'
../../../../usr/share/crystal/src/primitives.cr:255:3 in 'call'
lib/sam/src/sam/execution.cr:20:7 in 'invoke'
lib/sam/src/sam.cr:35:5 in 'invoke'
lib/sam/src/sam.cr:53:7 in 'process_tasks'
src/cnf-testsuite.cr:104:3 in '__crystal_main'
../../../../usr/share/crystal/src/crystal/main.cr:105:5 in 'main_user_code'
../../../../usr/share/crystal/src/crystal/main.cr:91:7 in 'main'
../../../../usr/share/crystal/src/crystal/main.cr:114:3 in 'main'
__libc_start_main
_start
???
unexpected token '<EOF>' at 1:1
```

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/123855103-1bc5f280-d8e5-11eb-81dd-473a20f0dc01.png)

**Comment by agentpoyo** [comment]
In airgapped mode (no internet), kind cluster was still accessible:

![image](https://user-images.githubusercontent.com/14348948/123855240-4a43cd80-d8e5-11eb-9e05-557e0aaddea5.png)

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/124963320-4569d280-dfe5-11eb-811a-8436c6f957c9.png)

**Comment by agentpoyo** [comment]
I think something is still not working right. While running (disconnected with no internet), I saw this pop up after a few minutes but the screenshot in prior comment says it was setup successfully. It's the dreaded ErrImagePull

![image](https://user-images.githubusercontent.com/14348948/124963377-59adcf80-dfe5-11eb-997b-264050e8708b.png)

**Comment by agentpoyo** [comment]
file listing of my /tmp/images:

![image](https://user-images.githubusercontent.com/14348948/124963592-a1ccf200-dfe5-11eb-88c8-0a53c9a014df.png)

**Comment by agentpoyo** [comment]
After I turned on networking, I noticed my nginx-webapp pods were able to then pull their images:

![image](https://user-images.githubusercontent.com/14348948/124963808-de98e900-dfe5-11eb-982b-dc1c1f02ad2b.png)

**Comment by agentpoyo** [comment]
![container_creating](https://user-images.githubusercontent.com/14348948/124968289-076fad00-dfeb-11eb-972c-2d5f734782fe.png)

**Comment by agentpoyo** [comment]
All is good, the previous errors were due to some local DNS issues I was encountering and not getting latest main checkout pull:

![image](https://user-images.githubusercontent.com/14348948/124975828-1313a180-dff4-11eb-8147-08156b16b7c8.png)

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/124975949-3c343200-dff4-11eb-80e7-43204817d8e4.png)
