### ISSUE TITLE
[Feature] Separate the tar module into its own library

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#810]
**Is your feature request related to a problem? Please describe.**
Separate the tar module into its own library

**Describe the solution you'd like**
Separate the tar module into its own library

**Comment by wavell** [comment]
- [ ] `grep --exclude-dir={node_modules,_build,priv,deps,graphdoc,lib} --exclude={*.sql,cnf-conformance} -rnw '.' -e '.*require.*tar.*'` should not show any full path references under the ./src or ./spec directories (under the ./utils directory is fine).

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/128414426-d88274dd-2ce4-4607-b358-21d2b935e538.png)
