### ISSUE TITLE
[Feature] Separate the docker module into its own library

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#811]
**Is your feature request related to a problem? Please describe.**
Separate the docker module into its own library

**Describe the solution you'd like**
Separate the docker module into its own library

**Comment by wavell** [comment]
- [ ] `grep --exclude-dir={node_modules,_build,priv,deps,graphdoc,lib} --exclude={*.sql,cnf-conformance} -rnw '.' -e '.*require.*docker.*'` should not show any full path references under the ./src or ./spec directories (under the ./utils directory is fine).

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/128415519-4e0d82f4-a52b-46fe-a723-0477e67933e2.png)
