### ISSUE TITLE
[Feature] Separate the kubectl module into its own library

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#812]
**Is your feature request related to a problem? Please describe.**
Separate the kubectl module into its own library

**Describe the solution you'd like**
Separate the kubectl module into its own library

**Comment by agentpoyo** [comment]
Acceptance Criteria:

- [ ] `grep --exclude-dir={node_modules,_build,priv,deps,graphdoc,lib} --exclude={*.sql,cnf-conformance} -rnw '.' -e '.*require.*kubectl.*'` should not show any full path references under the ./src or ./spec directories (under the ./utils directory is fine).

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/128755808-81ff5321-29d0-4697-bbad-15a1ceabff17.png)
