### ISSUE TITLE
[Feature] CNF setup should install all images referenced in the cnf-testsuite.yml

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#815]
**Is your feature request related to a problem? Please describe.**
CNF setup should install all images referenced in the cnf-testsuite.yml in airgap mode

**Describe the solution you'd like**
CNF setup should install all images referenced in the cnf-testsuite.yml in airgap mode

**Comment by wavell** [comment]
- [ ] use a kubeconfig for a airgapped kind cluster (see github actions)
- [ ] `./cnf-testsuite cnf_setup cnf-config=example-cnfs/coredns/cnf-testsuite.yml airgapped=./tmp/airgapped.tar.gz`
- [ ] `./cnf-testsuite cnf_setup cnf-config=example-cnfs/coredns/cnf-testsuite.yml input-file=./tmp/airgapped.tar.gz`
- [ ] `ls /tmp/images/` should have the images included in the cnf-testuite.yml container names array

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/123819723-9bd96180-d8bf-11eb-80ef-a4391bc99ae9.png)

**Comment by lixuna** [comment]
@agentpoyo @wavell  what is the level of effort in points? (ex. 0,1,2,3,5,8,13,21)
