### ISSUE TITLE
[Feature] cnf_setup should install only the images that are referenced in its helm charts/manifests.

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#820]
**Is your feature request related to a problem? Please describe.**
cnf_setup is installing the bootstrap images and upstream tool images along with those that are referenced in its helm charts/manifests.

**Describe the solution you'd like**
cnf_setup should install only the images that are referenced in its helm charts/manifests and not the bootstrapping images or upstream tools

**Comment by wavell** [comment]
- [ ] `ls /tmp/bootstrap_images/' should have a list of tar files that are used for tools
- [ ] `ls /tmp/images/` should either not exist or not have those previous bootstrap images

**Comment by agentpoyo** [comment]
Screenshot of /tmp files during `./cnf-testsuite cnf_setup cnf-config=example-cnfs/coredns/cnf-testsuite.yml airgapped=./tmp/airgapped.tar.gz` command:

![image](https://user-images.githubusercontent.com/14348948/123826002-fe812c00-d8c4-11eb-8f5c-7a968af319e6.png)

**Comment by agentpoyo** [comment]
Screenshot of /tmp files after: ` ./cnf-testsuite cnf_setup cnf-config=example-cnfs/coredns/cnf-testsuite.yml input-file=./tmp/airgapped.tar.gz` command:

![image](https://user-images.githubusercontent.com/14348948/123826170-240e3580-d8c5-11eb-94e5-25915140ee22.png)

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/123826321-4738e500-d8c5-11eb-873f-0d812fa1f150.png)

**Comment by lixuna** [comment]
@agentpoyo @denverwilliams what is the level of effort in points to fix this bug? (ex. 0,1,2,3,5,8,13,21)
