### ISSUE TITLE
[FEATURE] Add support to run cnf_testsuite on Ubuntu Microk8s

### ISSUE THREAD

**Issue by mmiklus** [cncf/cnf-testsuite#824]
### [FEATURE] Add support to run cnf_testsuite on Ubuntu Microk8s #824

**Original title: [FEATURE] Unable to run cnf_testsuite on Ubuntu Microk8s**

**Describe the bug**
Canonical Microk8s distribution does not follow semantic versioning, thus the check in cnf_manager.cr fails. 

**To Reproduce**

```
sudo snap install microk8s --classic
sudo snap alias microk8s.kubectl kubectl
vagrant@ubuntu-hirsute:~/cnf-testsuite$ cnf-testsuite cnf_setup cnf-config=./example-cnfs/envoy/cnf-testsuite.yml
Successfully created directories for cnf-testsuite
mv: cannot move '/home/vagrant/cnf-testsuite/cnfs/envoy/exported_chart/envoy/templates' to '/home/vagrant/cnf-testsuite/cnfs/envoy/exported_chart/templates': Directory not empty
Successfully setup envoy
../../../usr/share/crystal/src/regex/match_data.cr:149:7 in 'parse'
../../../workspace/src/tasks/utils/utils.cr:314:8 in 'version_less_than'
../../../workspace/src/tasks/utils/cnf_manager.cr:610:8 in 'sample_setup'
../../../workspace/lib/sam/src/sam/execution.cr:20:7 in '__crystal_main'
../../../usr/share/crystal/src/crystal/main.cr:105:5 in 'main'
src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
Not a semantic version: "1.20+.0"

vagrant@ubuntu-hirsute:~/cnf-testsuite$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-34+984a1cd176537e", GitCommit:"984a1cd176537e2d36d7db36e49e787e1c42a0aa", GitTreeState:"clean", BuildDate:"2021-06-11T05:07:09Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-34+984a1cd176537e", GitCommit:"984a1cd176537e2d36d7db36e49e787e1c42a0aa", GitTreeState:"clean", BuildDate:"2021-06-11T05:08:05Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
```

**Device (please complete the following information):**
Vagrantfile:
```
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/hirsute64"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.10.10",
    virtualbox__intnet: "intnet"
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
  end
end
```
- OS [Linux]
- Distro [Ubuntu]
- Version [21.04]

**Comment by agentpoyo** [comment]
I was able to reproduce this error. This seems more like a FEATURE request rather than bug as we've never fully vetted microk8s as a supported platform.

Using the native kubectl seems to work but our `cnf_setup` still compares the server version as well:

```
vagrant@ubuntu-hirsute:~$ cnf-testsuite cnf_setup cnf-config=./cnf-testsuite.yml
Successfully created directories for cnf-testsuite
Successfully setup coredns
../../usr/share/crystal/src/regex/match_data.cr:149:7 in 'parse'
../../workspace/src/tasks/utils/utils.cr:314:8 in 'version_less_than'
../../workspace/src/tasks/utils/cnf_manager.cr:610:8 in 'sample_setup'
../../workspace/lib/sam/src/sam/execution.cr:20:7 in '__crystal_main'
../../usr/share/crystal/src/crystal/main.cr:105:5 in 'main'
src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
Not a semantic version: "1.20+.0"
```

```
vagrant@ubuntu-hirsute:~$ microk8s kubectl version
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.1-3+ba118484dd39df", GitCommit:"ba118484dd39df570e55e47f082e523cda7583e5", GitTreeState:"clean", BuildDate:"2021-06-11T05:09:28Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.1-3+ba118484dd39df", GitCommit:"ba118484dd39df570e55e47f082e523cda7583e5", GitTreeState:"clean", BuildDate:"2021-06-11T05:06:35Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
vagrant@ubuntu-hirsute:~$ cnf-testsuite cnf_cleanup cnf-config=./cnf-testsuite.yml
Successfully cleaned up coredns
vagrant@ubuntu-hirsute:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.1-3+ba118484dd39df", GitCommit:"ba118484dd39df570e55e47f082e523cda7583e5", GitTreeState:"clean", BuildDate:"2021-06-11T05:06:35Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by agentpoyo** [comment]
Acceptance Criteria

#### I can run a `workload` using microk8s.kubectl bundled version with the test suite:
- [ ] Setup or find a microk8s cluster to use (https://snapcraft.io/install/microk8s)
- [ ] Verify connection to microk8s cluster by using the `microk8s.kubectl`
- [ ] You'll need to setup an alias for kubectl or cnf-testsuite will complain on `setup` or `pre-reqs` checks. If using snap, simply run the following to create an alias: `sudo snap alias microk8s.kubectl kubectl`
- [ ] I can see the microk8s version when running `kubectl version`
- [ ] I can run `./cnf-testsuite setup` and not see errors about kubectl version
- [ ] I can run `./cnf-testsuite cnf_setup cnf-config=sample-cnfs/sample_coredns/cnf-testsuite.yml` 
- [ ] I can run `./cnf-testsuite workload` successfully without any connection or kubectl/helm errors against microk8s cluster.

#### I can run a `workload` using native kubectl version with microk8s server version:
- [ ] Setup or find a microk8s cluster to use (https://snapcraft.io/install/microk8s)
- [ ] Verify connection to microk8s cluster by using the `kubectl cluster-info`
- [ ] I can see the kubectl version when running `kubectl version` and the server version that should be microk8s version.
- [ ] I can run `./cnf-testsuite setup` and not see errors about kubectl versions
- [ ] I can run `./cnf-testsuite cnf_setup cnf-config=sample-cnfs/sample_coredns/cnf-testsuite.yml` 
- [ ] I can run `./cnf-testsuite workload` successfully without any connection or kubectl/helm errors against microk8s cluster.

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/125857341-6ee3fa65-d0af-4385-938b-3966ff5705d8.png)

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/125858204-7830e734-66c9-4863-958d-519a177d263f.png)

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/125858355-b1aef76e-adcc-4660-a2ff-f62b2e1bd846.png)

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/125861300-88dd931a-97ad-476a-b02b-50ca3412729b.png)

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/125861490-03256190-1d1f-43db-8370-d56d8b72c72b.png)

**Comment by taylor** [comment]
Hi, @mmiklus. Support has been merged into the `main` branch and will be in the v0.13.1 binary release on July 29th.  It can be used prior to v0.13.1 by using the source or pre-release binaries.

**Comment by lixuna** [comment]
@agentpoyo @denverwilliams @wavell @HashNuke what is the level of effort in points for this issue? (ex. 0,1,2,3,5,8,13,21)

**Comment by agentpoyo** [comment]
3pts @lixuna
