### ISSUE TITLE
[BUG] cnf_setup manifest should  populate the exported_chart directory and export a temp_template file

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#827]
Is your feature request related to a problem? Please describe.
[BUG] cnf_setup manifest should  populate the exported_chart directory and export a temp_template.yml file

Describe the solution you'd like
[BUG] cnf_setup manifest should  populate the exported_chart directory and export a temp_template.yml file

**Comment by wavell** [comment]
- [ ] ./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/k8s-non-helm/cnf-testsuite.yml
- [ ] ./cnf-testsuite security 
- [ ] The above should pass the security test

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/124176958-3d55e400-da75-11eb-8445-cc90a3c70e9a.png)
