### ISSUE TITLE
[Feature] Images that have no image pull policy setting in their manifests should have a descriptive error message with an exit code 1

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#836]
**Is your feature request related to a problem? Please describe.**
Images that have no image pull policy setting in their manifests should have a descriptive error message with an exit code 1

**Describe the solution you'd like**
Images that have no image pull policy setting in their manifests should have a descriptive error message with an exit code 1

**Comment by wavell** [comment]
Acceptance criteria

- [ ] Pull down cnf-test suite source
- [ ] `./cnf-testsuite cnf_setup cnf-config=sample-cnfs/k8s-non-helm-no-image-policy/cnf-testsuite.yml airgapped=./tmp/airgapped.tar.gz`
- [ ] `docker run --network none --privileged -v $(pwd):/cnf-testsuite -v /tmp/airgapped.tar.gz:/airgapped/airgapped.tar.gz -t conformance/offline:latest /bin/bash -c "LOG_LEVEL=debug crystal src/cnf-testsuite.cr cnf_setup cnf-config=./sample-cnfs/k8s-non-helm-no-image-policy/cnf-testsuite.yml input-file=/airgapped/airgapped.tar.gz"`
- [ ] I should see a red error message that says image pull policies were missing from some containers

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/126213835-3fb14b56-0998-4a86-a189-f47344b70b86.png)

**Comment by lixuna** [comment]
@agentpoyo @denverwilliams @wavell what is the level of effort in points for this issue? (ex. 0,1,2,3,5,8,13,21)

**Comment by agentpoyo** [comment]
5pts @lixuna
