### ISSUE TITLE
Present the CNF Test Suite @ Crystal Conference

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testsuite#843]
Present the CNF Test Suite at [Crystal Conference](https://crystal-lang.org/conference/)

- [x] Document story
- [x] Create slide deck
- [x] Give talk
- [x] Share pdf of presentation

Goal:
- celebrate wins with crystal
- contributors for test suite
- improve crystal support for networking and kubernetes apps

**Comment by taylor** [comment]
What to cover for background

- What is cloud native computing 
- Telecommunication and networking community
- How does cloud native benefit?
- What is different about telecommunication and  networking software
- How does the test suite benefit its end-users

**Comment by taylor** [comment]
Going with Crystal - Why we chose Crystal over other languages (ie. Go in CNCF ecosystem)

- Difficulties with networking applications, wrapping tools, json apis and where crystal helps
- Default / common choices in K8s and where crystal helps
- We have had success with this project in Telco space… and crystal helps
- An end-user became a contributor and created their first PR in under 2 weeks
- Example of Go vs Crystal error messaging.  See meeting notes from previous sessions

**Comment by taylor** [comment]
Wins and obstacles with crystalizing CNF Test Suite
- Live demo or walk-through broken into parts highlighting where Crystal helped
- Crystal feature set in use on CNF Test Suite
- Experience w/ upgrading process
- Multi-platform support: Linux, WSL, MacOS (source)
- How to Use the CNF Test Suite

**Comment by taylor** [comment]
[[Crystal 1.0] Crystal in the Cloud_ CNF Test Suite.pdf](https://github.com/cncf/cnf-testsuite/files/6785788/Crystal.1.0.Crystal.in.the.Cloud_.CNF.Test.Suite.pdf)

**Comment by lixuna** [comment]
PDF of slides shared at https://forum.crystal-lang.org/t/cnf-test-suite-talk-title-crystal-in-the-cloud-a-cloud-native-journey/3479

**Comment by williscool** [comment]
definitely an 8 @lixuna

**Comment by taylor** [comment]
8
