### ISSUE TITLE
[Documentation] Add slides and recordings of CNF Test Suite demo/presentations/talks to repo

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#848]
### Short description: 

- to help end users and contributors learn more about the CNF Test Suite, add slide decks and recordings from past events to the README or a new file
- to share where the CNF Test Suite will be featured next, add "Upcoming Events" section to README or a new file
- similar to https://github.com/cncf/telecom-user-group#upcoming-events and https://github.com/cncf/telecom-user-group#past-events

Tasks:
- [x] Add slides/recording from Crystal Conf #843 
- [x] N/A Add slides/recording from KubeCon EU 
- [x] Add slides/recording from common demo presentation
- [x] N/A more tbd/in planning

**Comment by taylor** [comment]
[SHARED-COMMON CNF Test Suite Demo and CNF initiatives overview 2021-06-29.pdf](https://github.com/cncf/cnf-testsuite/files/6857515/SHARED-COMMON.CNF.Test.Suite.Demo.and.CNF.initiatives.overview.2021-06-29.pdf)

The version given @ Crystal Conference is in ticket #843

**Comment by lixuna** [comment]
2 most recent presentations have been added to https://github.com/cncf/cnf-testsuite#presentations
