### ISSUE TITLE
[Feature] Container Process List

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#865]
**Is your feature request related to a problem? Please describe.**
Some CNF tests need introspection for processes

**Describe the solution you'd like**
A tool that lists the processes in a container

https://hackmd.io/iRvwSvuKTj2VOx1zWXzUCw?both

**Comment by wavell** [comment]
It seems the best way (with the least dependencies) to handle this would be to do a kubectl exec ls of the proc directory and the proc/pid/status directories

**Comment by wavell** [comment]
- [ ] `crystal spec spec/utils/kernel_introspection_spec.cr`
- [ ] I should see a passing test

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/127069398-7ef47242-fa72-4a90-8e1d-33f6131805a7.png)

This failed. Seems like a potential bug in which container it's using to run the sleep command to test with the expected output.

**Comment by agentpoyo** [comment]
This is now fixed:

![image](https://user-images.githubusercontent.com/14348948/127570616-516a5c68-719f-435f-a3ae-a8103225579b.png)
