### ISSUE TITLE
[Maintenance] Update version of Crystal lang in Q4 2021

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#867]
### [Q4 2021 Maintenance] Update version of Crystal lang 

**Describe the maintenance item**
- Crystal's v1.1.0 release has been available since July 16, 2021 https://crystal-lang.org/2021/07/16/1.1.0-released.html
- v1.1.1 release has been available since July 26, 2021 https://github.com/crystal-lang/crystal/releases/tag/1.1.1
- in Q4 2021, check for latest release of Crystal
- check compatibility with dependencies
- update CNF Test Suite with one minor release behind the latest

**Expected behavior**
- the CNF Test Suite will function as expected after updating Crystal

**How will this be tested? aka Acceptance Criteria (optional)**

- [ ] All documentation is updated to mention the updated Crystal version
- [ ] Install works as expected
- [ ] Running all tests works as expected
- [ ] Running workload-only works as expected
- [ ] Running platform-only works as expected
- [ ] Running individual test categories works as expected
- [ ] Running individual tests works as expected
- [ ] tbd, add more expectations as needed

**Additional context**
- in #771 the test suite was updated for crystal v1.0.0

**Comment by lixuna** [comment]
Blocked by #771

**Comment by lixuna** [comment]
https://crystal-lang.org/2021/11/10/1.2.2-released.html

**Comment by lixuna** [comment]
Good day, @HashNuke @wavell @denverwilliams @agentpoyo 

Can this issue be added to this sprint for the next release?

**Comment by lixuna** [comment]
Checking in - 

Good day, @HashNuke @wavell @denverwilliams @agentpoyo

Can this issue be added to this sprint for the next release?

**Comment by HashNuke** [comment]
Identified #1180 when attempting this ticket. Fixed 1180 too as a part of the PR for this ticket.

**Comment by agentpoyo** [comment]
Todo: Writeup AC steps.

**Comment by agentpoyo** [comment]
###  Acceptance Criteria 
---
###  Common steps
- [x] Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-testsuite/blob/main/KIND-INSTALL.md) will work as well
- [x]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [x]  As a peer reviewer, check that PR passes in GitHub Actions
     - [x] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [x]  As a peer reviewer, Pull down latest version of CNF conformance test code from `main` branch
- [x]  Run `shards install`

### Update Prerequisite checker
- [ ] NA

### Added to overall points:
- [ ]  I see the test in the embedded points.yml as valid test score

### Update my crystal version from 1.x to 1.1.1
- [ ] I can see I'm running the latest 1.1.1 version of crystal from `crystal --version` output.

### When I run `crystal build src/cnf-testsuite.cr` I should not see errors during binary compile:
- [ ] I can see successful ouput from `crystal build src/cnf-testsuite.cr`
- [ ] I can see screenshot of the output.

### When I run `cnf_setup` against a valid working CNF, I can see it installs without errors or issues:
- [ ] Run `./cnf-testsuite cnf_setup cnf-config=sample-cnfs/sample-coredns-cn/cnf-testsuite.yml`
- [ ] I can see screenshot of the output and it's successful without errors.

### When I run `workload` tests against a valid working CNF, I can see cnf-testsuite results without errors related to crystal:
- [ ] Run `./cnf-testsuite workload`
- [ ] I can see screenshot of the output and it's successful without errors.

**Comment by agentpoyo** [comment]
![867_output1](https://user-images.githubusercontent.com/14348948/153064695-b7493f59-f526-4567-8eb1-f9ddc6aa9543.png)

**Comment by agentpoyo** [comment]
![867_output2](https://user-images.githubusercontent.com/14348948/153065884-c9de32d6-3013-4c8a-a85e-004880fc1fea.png)

**Comment by agentpoyo** [comment]
![867_output3](https://user-images.githubusercontent.com/14348948/153075292-740b644b-6ccb-4f13-a379-9e73997495cf.png)

**Comment by agentpoyo** [comment]
Seeing crystal code error "index out of bounds" when it runs the security tests.

**Comment by agentpoyo** [comment]
Crystal code error was due to bad cluster and CNF installed.
