### ISSUE TITLE
[Feature] Reorganize the test results to make them more human-readable

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#876]
**Is your feature request related to a problem? Please describe.**
- The test results are somewhat hard to read

**Describe the solution you'd like**
- Two ways to make them more human-readable would be to add a section header above each Test Category and to indent the test results by 2 spaces

**Describe alternatives you've considered**
- N/A, other suggestions to make the results more human-readable are welcome

**How will this be tested? aka Acceptance Criteria (optional)**
Workload: 
- Run workload tests, using instructions at https://github.com/cncf/cnf-testsuite/blob/main/README.md#installation-and-usage
- I should see the test results reorganized and more human-readable

Platform:
- Run platform tests, using instructions at https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#platform-tests
- I should see the test results reorganized and more human-readable

**Additional context**
- A recording of the test results is available at https://asciinema.org/a/DUI1XgA45N4OJ8sKZQ2hinCfn
- Mocks to provide a rough outline of the idea, and applied to every test category section

<img width="752" alt="Screen Shot 2021-07-21 at 10 59 56 AM" src="https://user-images.githubusercontent.com/11701267/126521189-e8fe6749-1ac4-4f5c-9280-0312f78051e8.png">
<img width="754" alt="Screen Shot 2021-07-21 at 11 00 03 AM" src="https://user-images.githubusercontent.com/11701267/126521192-8337e97d-f238-49e4-a8b0-6940f1441402.png">
<img width="749" alt="Screen Shot 2021-07-21 at 11 00 12 AM" src="https://user-images.githubusercontent.com/11701267/126521193-b523d88e-4f6d-4b92-b110-956a48340fd5.png">

**Comment by lixuna** [comment]
mocks in progress, this issue will be updated with more details shortly

**Comment by lixuna** [comment]
@agentpoyo The description of this issue is ready for your review. Does this reflect the improvements that you would like to see in the test results?

**Comment by agentpoyo** [comment]
@lixuna Yeah, looks good to me.

**Comment by agentpoyo** [comment]
One thing also, should we also include a sub task in this issue to make the PASSED :heavy_check_mark: , FAILED :x: and SKIPPED ⏭️  emoji's consistent? I think there's some tests that when SKIPPED don't have the ⏭️  emoji. I can open a new issue as well if we want it to be separate. @lixuna

**Comment by lixuna** [comment]
@agentpoyo good catch. Please create a new issue to add the SKIPPED ⏭️ emoji to tests that are missing it.

**Comment by lixuna** [comment]
Note: this will need to be updated based on the test category name refactoring in #1088

**Comment by agentpoyo** [comment]
These improvements have been made for `cert` command when using the cn-testsuite. We can readdress or validate later if we feel `workload` or other top level multiple tests should be refactored with the headers we've done for `cert`. #1088 was already reviewed and merged. No AC required for this one.
