### ISSUE TITLE
[Feature] Sysbench tool for logging

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#885]
**Is your feature request related to a problem? Please describe.**
A remote system that runs the cnf-testsuite can have issues related to performance, but the system in question is a black box

**Describe the solution you'd like**
Install and make a wrapper for the sysbench tool  for debug level logging and output to log files

**Comment by wavell** [comment]
`sysbench --test=cpu --num-threads=4 --cpu-max-prime=9999 run `

**Comment by wavell** [comment]
- [ ] K8sInstrumentation.disk_speed should be a valid function in the src/utils/k8s_instrumentation.cr file

**Comment by lixuna** [comment]
@agentpoyo has this issue passed the A/C?

**Comment by agentpoyo** [comment]
> @agentpoyo has this issue passed the A/C?

@lixuna This really can't be tested, it was essentially tested since it was used for the reasonable_startup_time #860 which had A/C.
