### ISSUE TITLE
[Feature] Separate Find into its own library

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#906]
Is your feature request related to a problem? Please describe.
Separate the find module into its own library

Describe the solution you'd like
Separate the find module into its own library

**Comment by wavell** [comment]
grep --exclude-dir={node_modules,_build,priv,deps,graphdoc,lib} --exclude={*.sql,cnf-conformance} -rnw '.' -e '.*require.*find.*'

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/129256163-f345f761-38b6-4c1e-a9f9-948ac29ae836.png)

**Comment by lixuna** [comment]
Hi @agentpoyo and @wavell what was the level of effort for this issue (ie. 0,1,2,3,5,8,13,21)?

**Comment by agentpoyo** [comment]
@lixuna 3pts
