### ISSUE TITLE
[Enhancement] improve remediation steps for test called, `increase_decrease_capacity`

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#907]
### [Enhancement] improve remediation steps for test called, `increase_decrease_capacity`
- Child ticket of: #895 
- Related issue: #632 

**Is your feature request related to a problem? Please describe.**
- Add more suggestions on how to demonstrate a CNF's ability to follow cloud native best practices 
- Make suggestions more user friendly and useful for test called, `increase_decrease_capacity`

**User Story:**
**Given** that I am a CNF Developer running the CNF Test Suite, 
**When** my CNF fails the test called, `increase_decrease_capacity`
**Then** I would like to see where to find remediation steps to pass the test 

What we see now:
- Go to USAGE.md (no hyperlinks, no direct link to the failed test)

Would like to see: 
- Use a url shortner for links in the CLI output
- Add shortened links to go directly to the test remediation steps
- Add information/test remediation steps in the USAGE.md doc
- Update how remediation steps are displayed in the USAGE.md (ie. Remediation collapsable bullet, Or put under details)
- tbd, issue is still in planning

 

**Describe alternatives you've considered**
- update the report log
- add to debug log
- update the test categories or usage documentation in this repo
- link to external github repo
- link to existing external documentation
- create new external documentation

**Initial ideas:**
- Add a remediation (collapsable) section on USAGE doc for the increase decrease capacity test
   - Paragraph on what to check for remediation when this test fails
   - Links to K8s docs specific to addressing the increase/decrease capacity test
   - Links to  other relevant docs for additional information
- Show message on console output for remediation (link or paragraph)
  - Add link to the new remediation documentation in USAGE.md in output
- Show message in results yaml file for remediation (link or paragraph)
  - Add link to the new remediation documentation in USAGE.md in results file

**Comment by taylor** [comment]
MVP improvements for remediation of this test
- Add remediation information (eg. link, short message, whatever) to specific tests in the yaml results output
- Update how remediation steps are displayed in the USAGE.md
- Keep information/test remediation steps in the USAGE doc
- Add shortened links to go directly to the test remediation steps
- Use a url shortner for links in the CLI output
- Remediation information on the CLI should come after the test FAIL or SKIPPED message

**Comment by lixuna** [comment]
In planning: 
- needs Acceptance Criteria
- level of effort in points (0.1.2.3.5.8.13.21)

**Comment by agentpoyo** [comment]
Acceptance Criteria:

#### When I run `increase_decrease_capacity`, I should see 
- [ ] Find a k8s cluster (kind or other) with cnf-testsuite installed (binary or source, following the INSTALL directions)
- [ ] Verify k8s connection via `kubectl cluster-info` command.
- [ ] Setup a CNF that is designed to fail, using `sample-fragile-state` as good working sample from sample-cnfs/sample-fragile-state/: `./cnf-testsuite cnf_setup cnf-config=sample-cnfs/sample-fragile-state/cnf-testsuite.yml`
- [ ] Run `./cnf-testsuite increase_decrease_capacity`
- [ ] I should see the test FAIL with output that has:
  - [ ] Brief paragraph or statement about the FAILED state.
  - [ ] A URL link (shortened) that takes me to Remediation Steps Documentation
  - [ ] The link tells me steps (In the USAGE.md) to remediate FAILED status for `increase_decrease_capacity` best practices.

**Comment by lixuna** [comment]
### Level of effort in pts: 0,1,2,3,5,8,13,21: 

TBD

**Comment by agentpoyo** [comment]
@williscool @lixuna @taylor 

Do we have a preferred URL shortner? I know we mentioned bitly.com but that requires a login/account for the most part.

I found https://git.io as promising and sort of sticks with github with it's git.io domain. Can create shortend URLS using curl from command line as well:

![image](https://user-images.githubusercontent.com/14348948/130095677-f097ac7e-5fc4-4b0e-9f6b-521ac1451460.png)

**Comment by taylor** [comment]
Bit.ly and we have an account

**Comment by taylor** [comment]
@lixuna my estimate on effort for this issue 5pts

Cc: @williscool @agentpoyo

**Comment by agentpoyo** [comment]
I'll say 5pts too.

If you wanna share bit.ly account or I can use my own (I have my own as well).

**Comment by lixuna** [comment]
Suggestion: 
- short url could be named something short and human readable like `https://bit.ly/cnf-capacity`

**Comment by agentpoyo** [comment]
Yeah, the customization of bit.ly wins me over too. I only brought up git.io as it could be used elsewhere for github only links. I do like that you can create on the fly from command line.

bitly it is though.

**Comment by taylor** [comment]
I recommend creating separate bitly urls for the link shown on the yml file and for the link shown in the console so we can known how end users are accessing the remediation, and what is most useful for them.

**Comment by agentpoyo** [comment]
> I recommend creating separate bitly urls for the link shown on the yml file and for the link shown in the console so we can known how end users are accessing the remediation, and what is most useful for them.

We can make sure to tag them as "console" or "YML" to easy identification of where they're used at.

**Comment by williscool** [comment]
> @lixuna my estimate on effort for this issue 5pts
> 
> Cc: @williscool @agentpoyo

5 pts

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/130242075-d3e227e7-a987-434c-8861-9ed146b4279a.png)

**Comment by taylor** [comment]
See how it looks with a short generated url

**Comment by agentpoyo** [comment]
> See how it looks with a short generated url

Something like `bit.ly/inc_dec_rem`  perhaps?

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/130245453-8228ac00-e4c7-48c6-88b0-d61ba1551413.png)

@taylor

**Comment by taylor** [comment]
@agentpoyo it seems like it will become difficult to have custom URLs. I suggest seeing how it looks with the randomly generated ones.  Or do something like cnf0001, cnf0002

**Comment by agentpoyo** [comment]
> @agentpoyo it seems like it will become difficult to have custom URLs. I suggest seeing how it looks with the randomly generated ones. Or do something like cnf0001, cnf0002

Maybe, depending on the type of link we're linking to but we can always abbreviate or shorten ourselves when we deem necessary. I think the random generated short URLs are ugly. At least with the custom it at least gives the reader a clue on where the link is taking them. @taylor

**Comment by lixuna** [comment]
I agree with using a short, custom url that is human readable and tells the user where they are going, like https://bit.ly/cnf-capacity

**Comment by lixuna** [comment]
or https://bit.ly/capacity-remedy

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/130264083-3062e1cc-67d2-4d45-a239-9bed6b83d46e.png)

@lixuna @taylor @williscool 

I like capacity_remedy as the link.

**Comment by lixuna** [comment]
for other tests, my hope is that we can find one word to describe the test and use the same format, like https://bit.ly/[test]_remedy

**Comment by agentpoyo** [comment]
> for other tests, my hope is that we can find one word to describe the test and use the same format, like [https://bit.ly/[test]_remedy](https://bit.ly/%5Btest%5D_remedy)

I agree. I think we can do it. We might just have to get creative when naming any that might be deemed too long.

Perhaps we come up with our own character limit for the bit.ly URL's to keep them uniform?

@taylor @lixuna @williscool

**Comment by taylor** [comment]
Any unique URL bringing the user to the specific section where they can get help for a failed test will be an improvement. 

As we add more tests it may be difficult to come up with a human readable short URL.  If you can do it I'm all for it though.

Prefix ideas:
- cnf_, cnf-
- cnftest_, cnftest-
- test_, test-

**Comment by taylor** [comment]
The next important item is improving the document itself https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-test-the-increasing-and-decreasing-of-capacity. Formatting, phrasing, etc.  More details similar to what is in the resilience litmus tests

**Comment by agentpoyo** [comment]
> The next important item is improving the document itself https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-test-the-increasing-and-decreasing-of-capacity. Formatting, phrasing, etc. More details similar to what is in the resilience litmus tests

Well, that is the USAGE doc on how to use cnf-testsuite. If we start getting into documentation that is more indepth troubleshooting beyond the quick links to existing docs that help (like we have now with increase_capacity), then I think that needs to be an entirely new document.

Now the description of the actual test is ideal but I would leave the descriptions to what they are, a description of what the test is and does.

**Comment by williscool** [comment]
One comment on the url shortenr

we could also look into a custom domain 

https://support.bitly.com/hc/en-us/articles/230558107-What-is-a-custom-domain-

https://github.com/cncf/cnf-testsuite/pull/938/files#r694067506

**Comment by agentpoyo** [comment]
> One comment on the url shortenr
> 
> we could also look into a custom domain
> 
> https://support.bitly.com/hc/en-us/articles/230558107-What-is-a-custom-domain-

I think @taylor mentioned the custom domain. Not sure if it was through bit.ly which is paid account or using our own perhaps.

@williscool @lixuna

**Comment by taylor** [comment]
Custom domains in another iteration on this. 

First steps, in the CLI results (and results yaml file)
- add "any" shortened URL as a way for the end user to find existing remediation steps when they have a failure
- add remediation content (links, instructions, etc) for every test implemented and w/shortened URLs

**Comment by williscool** [comment]
Followed https://github.com/cncf/cnf-testsuite/issues/907#issuecomment-892824290

everything looks good!

![image](https://user-images.githubusercontent.com/394931/131376527-2eebe50f-b4a5-4578-a8da-8be2cc990698.png)
