### ISSUE TITLE
[Feature] CNF setup pre-pull image

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#908]
**Is your feature request related to a problem? Please describe.**
reasonable startup time includes pull down time when calculating the startup time

**Describe the solution you'd like**
pre-cache cnf setup image before calculating startup time

**Comment by agentpoyo** [comment]
Acceptance Criteria:

- [ ] Setup a k8s cluster without cached images already available.
- [ ] Run `./cnf-testsuite cnf_setup cnf-config=sample-cnfs/sample_coredns/cnf-testsuite.yml`
- [ ] I should see the images for CoreDNS already pulled down and available.

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/128277037-153d0961-7412-469b-b5a2-efd0f3ec3676.png)
