### ISSUE TITLE
[BUG] Unify CRI-Tools Pod & Daemonset install functions.

### ISSUE THREAD

**Issue by denverwilliams** [cncf/cnf-testsuite#910]
**Describe the bug**
We currently use the two functions for install the CRI-Tools Pod as a single Pod or Daemonset. These should be unified into a single function using Daemonsets.

**To Reproduce**.

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

- OS [e.g. Linux, iOS, Windows, Android]
- Distro [e.g. Ubuntu]
- Version [e.g. 18.04]
- Architecture [e.g. x86, arm]

**How will this be tested? aka Acceptance Criteria (optional)**

(optional: unnecessary for things like spelling errors and such)

Once this issue is address how will the fix be verified?

**Additional context**

---

NOTE: you can enable higher logging level output via the command line or env var. to help with debugging

```
# cmd line
./cnf-testsuite -l debug test

# make sure to use -- if running from source
crystal src/cnf-testsuite.cr -- -l debug test

# env var
LOGLEVEL=DEBUG ./cnf-testsuite test
```

Also setting the verbose option for many tasks will add extra output to help with debugging

```
crystal src/cnf-testsuite.cr test_name verbose
```

Check [usage documentation](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) for more info about invoking commands and logging

**Comment by agentpoyo** [comment]
###  Acceptance Criteria 
---
###  Common steps
- [ ] Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-testsuite/blob/main/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]  As a peer reviewer, Pull down latest version of CNF conformance test code from `main` branch
- [ ]  Run `shards install`

### Update Prerequisite checker
- [ ] NA

### Added to overall points:
- [ ]  I see the test in the embedded points.yml as valid test score

### When I run `install_cluster_tools`, I should see cluster-tools pods creating or running in ready state:
- [ ] Run `./cnf-testsuite install_cluster_tools`
- [ ] I can see cluster-tools running as a pod from `kubectl get pods`
- [ ] I can see a screenshot of the cluster tools pods.

### When I run `uninstall_cluster_tools`, I should see cluster-tools pods terminating or no longer runniing:
- [ ] Run `./cnf-testsuite uninstall_cluster_tools`
- [ ] I can see cluster-tools running as a pod from `kubectl get pods`
- [ ] I can see a screenshot of no cluster-tools running or in terminating state.

**Comment by agentpoyo** [comment]
![cluster_tools_install](https://user-images.githubusercontent.com/14348948/144166689-ac2894a2-26dd-416d-9b30-fc77da72605d.png)

![cluster_tools_uninstall](https://user-images.githubusercontent.com/14348948/144166781-46714925-744c-4c51-9ed5-90bceb0116ee.png)
