### ISSUE TITLE
[Documentation] update docs to reflect Crystal v1.0.0

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#912]
### [Documentation] update docs to reflect Crystal v1.0.0

Short description: 
- the CNF Test Suite used to use cystal-lang v0.35.1 
- in #771, the CNF Test Suite uses v1.0.0

Tasks:

- [ ] find all mentions of cystal-lang v.x.y
- [ ] update all mentions to cystal-lang v1.0.0 
- [ ] for example: in https://github.com/cncf/cnf-testsuite/blob/main/SOURCE_INSTALL.md, "0.35.1" is mentioned 3 times
- [ ] there appears to be other places in the repo that will need this update, see a quick search, https://github.com/cncf/cnf-testsuite/search?q=0.35.1

**Comment by agentpoyo** [comment]
Acceptance Criteria:

#### When I view the INSTALL.md documentation:
- [ ] I see that the supported crystal version references 1.0.0 in the INSTALL.md requirements

#### When I view the SOURCE_INSTALL.md documentation:
- [ ] I see that the supported crystal version references 1.0.0 in the SOURCE_INSTALL.md requirements
