### ISSUE TITLE
[BUG] Litmus Spec tests failing.

### ISSUE THREAD

**Issue by denverwilliams** [cncf/cnf-testsuite#918]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

- OS [e.g. Linux, iOS, Windows, Android]
- Distro [e.g. Ubuntu]
- Version [e.g. 18.04]
- Architecture [e.g. x86, arm]

**How will this be tested? aka Acceptance Criteria (optional)**

(optional: unnecessary for things like spelling errors and such)

Once this issue is address how will the fix be verified?

**Additional context**

---

NOTE: you can enable higher logging level output via the command line or env var. to help with debugging

```
# cmd line
./cnf-testsuite -l debug test

# make sure to use -- if running from source
crystal src/cnf-testsuite.cr -- -l debug test

# env var
LOGLEVEL=DEBUG ./cnf-testsuite test
```

Also setting the verbose option for many tasks will add extra output to help with debugging

```
crystal src/cnf-testsuite.cr test_name verbose
```

Check [usage documentation](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) for more info about invoking commands and logging

**Comment by agentpoyo** [comment]
## [Acceptance Criteria]

- [ ] Create or find k8s cluster
- [ ] Follow common INSTALL steps (binary or source) install to setup cnf-testsuite
- [ ] Run `cnf-testsuite cnf_setup cnf-config=sample-cnfs/sample_coredns/cnf-testsuite.yml`
- [ ] Run `cnf-testsuite workload`
- [ ] I should see PASS for the litmus chaos tests.
- [ ] I can see a screenshot of the output from the test.

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/129405823-32a83621-83c8-46dd-95e5-d97e1feb7d9e.png)
