### ISSUE TITLE
[BUG] Fix docker-ratelimt issue when doing authenticated pulls.

### ISSUE THREAD

**Issue by denverwilliams** [cncf/cnf-testsuite#927]
**Describe the bug**
DockerHub is currently rate-limiting us when we do authenticated image pulls. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

- OS [e.g. Linux, iOS, Windows, Android]
- Distro [e.g. Ubuntu]
- Version [e.g. 18.04]
- Architecture [e.g. x86, arm]

**How will this be tested? aka Acceptance Criteria (optional)**

(optional: unnecessary for things like spelling errors and such)

Once this issue is address how will the fix be verified?

**Additional context**

---

NOTE: you can enable higher logging level output via the command line or env var. to help with debugging

```
# cmd line
./cnf-testsuite -l debug test

# make sure to use -- if running from source
crystal src/cnf-testsuite.cr -- -l debug test

# env var
LOGLEVEL=DEBUG ./cnf-testsuite test
```

Also setting the verbose option for many tasks will add extra output to help with debugging

```
crystal src/cnf-testsuite.cr test_name verbose
```

Check [usage documentation](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) for more info about invoking commands and logging

**Comment by lixuna** [comment]
What is the level of effort in pts for this issue? (ie. 0,1,2,3,5,8,13,21)

Please add a comment with your estimates, @HashNuke @wavell @denverwilliams @taylor @agentpoyo

**Comment by taylor** [comment]
3

**Comment by agentpoyo** [comment]
This has been implemented and now rotates between 3 accounts to bump up number of pulls in 6 hour window.

Caught issues implemented: Password on an account docker didn't like special characters used.
