### ISSUE TITLE
[Feature] Separate Git Client module into its own library

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#933]
**Is your feature request related to a problem? Please describe.**
Separate Git Client module into its own library

**Describe the solution you'd like**
Separate Git Client module into its own library

**Comment by agentpoyo** [comment]
Acceptance Criteria:

- [x] `grep --exclude-dir={node_modules,_build,priv,deps,graphdoc,lib} --exclude={*.sql,cnf-conformance} -rnw '.' -e '.*require.*git.*'` should not show any full path references under the ./src or ./spec directories (under the ./utils directory is fine).

**Comment by agentpoyo** [comment]
![git_module_library](https://user-images.githubusercontent.com/14348948/134532494-24e4ce22-aa95-441a-909b-f2ece9b35508.png)

**Comment by lixuna** [comment]
@wavell @denverwilliams @agentpoyo What is the level of effort in pts on this item? (ie. 0,1,2,3,5,8,13,21)

**Comment by HashNuke** [comment]
@lixuna I would say 3pts. I'll wait for other folks to respond.
