### ISSUE TITLE
[BUG] Make cnf_cleanup deduce if the installation was a manifest installation

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#935]
**Describe the bug**
make cnf_cleanup deduce if the installation was a manifest installation

**Actual Problem**
It doesn't work now.

**Comment by wavell** [comment]
- [ ] `./cnf-testsuite cnf_setup cnf-config=sample-cnfs/sample_nonroot/cnf-testsuite.yml`
- [ ] `kubectl get pods`
- [ ]  Should see nginx
- [ ] `./cnf-testsuite cnf_cleanup cnf-config=sample-cnfs/sample_nonroot/cnf-testsuite.yml`
- [ ] `kubectl get pods`
- [ ] Should not see nginx

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/131412158-1c7ffd32-0489-4ab9-8fb5-709758e8ee56.png)

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/131412244-d78b1e84-98d8-434f-b048-53f01c3ac2c3.png)
