### ISSUE TITLE
[Documentation] Blog/Paper on Chaos testing in networking

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#936]
**Is your feature request related to a problem? Please describe.**
Blog/Paper on Chaos testing in networking

**Describe the solution you'd like**
Blog/Paper on Chaos testing in networking

**Comment by wavell** [comment]
@uditgaurav

**Comment by wavell** [comment]
ask me for the link

**Comment by wavell** [comment]
https://vmblog.com/archive/2021/09/15/cloud-native-chaos-and-telcos-enforcing-reliability-and-availability-for-telcos.aspx#.YUI_TNNKi3I

**Comment by agentpoyo** [comment]
LGTM
