### ISSUE TITLE
[Documentation] add test command and test details for `increase_decrease_capacity` to the USAGE.md

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#939]
### [Enhancement] add test command and test details for increase_decrease_capacity 
- Related issues: #632, #907

**Is your feature request related to a problem? Please describe.**
- the test command is missing from the USAGE.md
- Add reasons why this test was created
- See litmus chaos experiment documentation as reference, ex https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-test-if-the-cnf-crashes-when-disk-fill-occurs

**User Story:**
**Given** that I am a CNF Developer running the CNF Test Suite, 
**When** I read the USAGE.md docs for `increase_decrease_capacity`
**Then** I would like to learn why this test was included in the CNF Test Suite and how to run the test (test command)

What we see now:
- https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-test-the-increasing-and-decreasing-of-capacity
- no command to run this test
- no details on why this test was created

Would like to see: 
- Test command for this workload test, ex. ./cnf-testsuite ip_addresses
- Purpose of this test
 

**Describe alternatives you've considered**
- link to external github repo
- link to existing external documentation
- create new external documentation

**Initial ideas:**
- Add a test details (collapsable) section on USAGE doc for the increase decrease capacity test
   - Paragraph on the purpose of this test
   - Links to K8s docs specific to addressing the increase/decrease capacity test
   - Links to  other relevant docs for additional information

**Comment by agentpoyo** [comment]
Acceptance Criteria:

- [ ] When I view the USAGE.md doc and scroll to `increase_decrease_capacity`, I can see there is a Details drop down with a description of the test and remediation steps and links.
