### ISSUE TITLE
[BUG] Falco non_root_user test is intermittently detecting the creation of root containers. 

### ISSUE THREAD

**Issue by denverwilliams** [cncf/cnf-testsuite#953]
**Describe the bug**
Pods can have a root user both inside the container(the user the runs the container processes) and outside the container(i.e the user that controls the container-runtime and is responsible for starting/creating containers).

The Falco non_root_user test should only care about root users that are running inside the container, the user running the container processes, but it's intermittently seeing the 'root' user responsible for running the container-runtime which leads to false-negative test results.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

- OS [e.g. Linux, iOS, Windows, Android]
- Distro [e.g. Ubuntu]
- Version [e.g. 18.04]
- Architecture [e.g. x86, arm]

**How will this be tested? aka Acceptance Criteria (optional)**

(optional: unnecessary for things like spelling errors and such)

Once this issue is address how will the fix be verified?

**Additional context**

---

NOTE: you can enable higher logging level output via the command line or env var. to help with debugging

```
# cmd line
./cnf-testsuite -l debug test

# make sure to use -- if running from source
crystal src/cnf-testsuite.cr -- -l debug test

# env var
LOGLEVEL=DEBUG ./cnf-testsuite test
```

Also setting the verbose option for many tasks will add extra output to help with debugging

```
crystal src/cnf-testsuite.cr test_name verbose
```

Check [usage documentation](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) for more info about invoking commands and logging

**Comment by lixuna** [comment]
What is the level of effort in pts for this issue? (ie. 0,1,2,3,5,8,13,21)

Please add a comment with your estimates, @HashNuke @wavell @denverwilliams @taylor @agentpoyo

**Comment by agentpoyo** [comment]
This was an intermittent bug, no real way to test with acceptance criteria as it's passing manual tests and github actions.

**Comment by agentpoyo** [comment]
13 pts

**Comment by taylor** [comment]
8pts
