### ISSUE TITLE
[BUG] Airgap mode for chaos testing should run in a separate vm on github actions

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#962]
**Describe the bug**
Airgap mode for chaos testing should run in a separate vm on github actions

**To Reproduce**
Airgap mode for chaos testing should run in a separate vm on github actions

**Comment by agentpoyo** [comment]
Acceptance Criteria:

- [ ] When viewing Github Actions,  I can see the chaos tests are running in separate VMs outside of the spec and other binary actions.
- [ ] I can see a screenshot of Chaos Tests PASSING state.

![image](https://user-images.githubusercontent.com/14348948/132904353-8438d953-e1b0-48af-9342-eac1f14515a6.png)
