### ISSUE TITLE
[BUG] chaos tests offline mode address issues

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#968]
**Describe the bug**
The chaos and litmus tests for offline airgap have bugs, not pulling down proper configs, etc. Need to address these.

**To Reproduce**

**Comment by lixuna** [comment]
What your estimate for the level of effort in pts for this issue? (ie. 0,1,2,3,5,8,13,21)

Please add a comment with your estimates, @HashNuke @wavell @denverwilliams @taylor @agentpoyo

**Comment by agentpoyo** [comment]
No Acceptance Criteria required, this was to address the bugs accociated with running the airgap tests for litmus and chaos for the CI. You can view github actions logs to see that these are now running and passing tests.

@lixuna 5 pts
