### ISSUE TITLE
[BUG] cluster_api_setup crashes upon run

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#987]
> Found this issue when making changes for #307.

## Describe the bug
`cluster_api_setup` task is crashing when it is run.

```
$ crystal build src/cnf-testsuite.cr && ./cnf-testsuite cluster_api_setup
current_branch during compile: "main"
current_tag during compile: "v0.17.0"
/home/pair/.crenv/versions/1.0.0/share/crystal/src/crystal/system/unix/file.cr:11:7 in 'open'
/home/pair/.crenv/versions/1.0.0/share/crystal/src/file.cr:111:5 in 'new'
/home/pair/.crenv/versions/1.0.0/share/crystal/src/file.cr:627:12 in '__crystal_main'
/home/pair/.crenv/versions/1.0.0/share/crystal/src/crystal/main.cr:110:5 in 'main_user_code'
/home/pair/.crenv/versions/1.0.0/share/crystal/src/crystal/main.cr:96:7 in 'main'
/home/pair/.crenv/versions/1.0.0/share/crystal/src/crystal/main.cr:119:3 in 'main'
__libc_start_main
_start
???
Error opening file with mode 'r': 'results/cnf-testsuite-results-20210927-071936-832.yml': No such file or directory
```

![BD52FC9A-47EE-44CD-89B3-5B20AD8B937C](https://user-images.githubusercontent.com/84005/134880978-27765e23-dbdf-4d73-abc1-f41936809ffb.png)

## To Reproduce

`./cnf-testsuite cluster_api_setup`

## Expected behavior
The task should successfully setup cluster API and exit.

**Comment by agentpoyo** [comment]
###  Acceptance Criteria 
---
### Documentation is updated:
- [ ] USAGE.md documentation updated
   - [ ] how to run
   - [ ] Description and details 
       - [ ] what the best practice is
       - [ ] why are we testing this
- [ ] CATEGORIES updated

###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-testsuite/blob/main/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]   As a peer reviewer, Pull down latest version of CNF conformance test code from `main` branch
- [ ]  Run `shards install`

### Update Prerequisite checker
- [ ] NA

### Update yml validator, if needed
- [ ]  update if needed

### I expect no errors when running `cluster_api_setup`:
- [ ] Run `./cnf-testsuite cluster_api_setup`
- [ ] I should see that `cluster_api_setup` succeeds.

### Screenshots of output:
- [ ] I can see a screenshots of expected output.

**Comment by agentpoyo** [comment]
![987_bug](https://user-images.githubusercontent.com/14348948/135624045-4dcd0dfa-f576-439b-a77d-38fe13d19722.png)

**Comment by lixuna** [comment]
Thank you for working on this, @HashNuke and @agentpoyo 

What is your estimate in points for this issue? (0,1,2,3,5,8,13,21)
