### ISSUE TITLE
[Feature] Add support for kubescape in airgap mode

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#994]
**Describe the solution you'd like**
Need to add airgap support for kubescape tests.

Ref: #963

**Comment by wavell** [comment]
@Ben Hirschberg, we are having issues trying to use kubescape in an airgapped environment.  We are using ./tools/kubescape/kubescape download framework nsa --output /tools/kubescape/nsa.json to get the library local and then the command framework nsa --use-from ./tools/kubescape/nsa.json in an airgapped environment after and staging the json, but kubescape seems to be doing a call for https://api.github.com/repos/armosec/kubescape/releases/latest on startup.  Is there any way to use kubescape in an airgapped environment?

**Comment by lixuna** [comment]
cc @slashben

TIA!

**Comment by slashben** [comment]
We have ran tests and (with some delay) it worked in the latest version. We will debug it later together.
